import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { DB_URL, bailIfDbUnreachable } from "./dbSuiteHelpers";
import { parseDeclaredColumnOrder } from "./declaredColumnOrder";

/**
 * Standing guard: every `create table` block in supabase/schemas/01_tables.sql
 * lists its columns in the same order the database physically has them
 * (`pg_attribute.attnum`).
 *
 * This is the guard the Epic-5 blocker needed and did not have. `alter table
 * add column` always appends to the tail and `drop column` leaves a hole, so a
 * story that removes a column from mid-table and adds new ones puts the
 * declarative file out of step with the database. `migra` — the engine behind
 * `supabase db diff` — compares columns by ordinal position, decides the table
 * changed, and, unable to express a reorder in SQL, emits only the collateral:
 * `drop view` + `create view` for every dependent view. That output is
 * non-convergent (committing it does not change the column order, so the next
 * diff reproduces it) and each generated `create view` silently drops
 * `security_invoker = on` and the 06_grants.sql grants. Story 5.2 hit exactly
 * this and misdiagnosed it as unavoidable `db diff` noise; see the COLUMN-ORDER
 * TRAP header in 01_tables.sql.
 *
 * Cheap by construction: one catalog query plus a text scan, no fixtures, no
 * role switching, nothing written. It fails the moment the two orders diverge,
 * which is the moment the fix is still a one-line move in a schema file rather
 * than a blocked deploy.
 *
 * The parser tests below run anywhere. The catalog comparison needs
 * `make start` (or `supabase start`); when the database is unreachable it
 * reports a single skipped test rather than failing the whole run.
 */

const TABLES_SQL = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "schemas",
  "01_tables.sql",
);

type PhysicalOrder = Record<string, string[]>;

function readPhysicalOrder(): { order?: PhysicalOrder; error?: string } {
  const query = `
    select coalesce(json_object_agg(t.relname, t.cols), '{}'::json)
    from (
      select c.relname,
             json_agg(a.attname order by a.attnum) as cols
      from pg_class c
        join pg_namespace n on n.oid = c.relnamespace
        join pg_attribute a on a.attrelid = c.oid
      where n.nspname = 'public'
        and c.relkind = 'r'
        and a.attnum > 0
        and not a.attisdropped
      group by c.relname
    ) t;
  `;

  try {
    const stdout = execFileSync(
      "psql",
      [DB_URL, "-X", "-q", "-A", "-t", "-c", query],
      { encoding: "utf8", stdio: ["pipe", "pipe", "pipe"], timeout: 120_000 },
    );
    return { order: JSON.parse(stdout.trim()) as PhysicalOrder };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return { error: message };
  }
}

const declared = parseDeclaredColumnOrder(readFileSync(TABLES_SQL, "utf8"));

describe("declarative column order parser", () => {
  it("reads a table's columns in declaration order and skips constraints", () => {
    // Arrange
    const sql = `
      create table public.demo (
          id bigint generated by default as identity primary key,
          -- a comment mentioning constraint, check and unique
          channels text[] not null default array['a', 'b']::text[],
          label text not null default 'x, y',
          constraint demo_label_check check (label in ('x, y', 'z')),
          unique (id, label)
      );
    `;

    // Act
    const result = parseDeclaredColumnOrder(sql);

    // Assert
    expect(result.get("demo")).toEqual(["id", "channels", "label"]);
  });

  it("keys quoted and schema-qualified table names by their bare name", () => {
    // Arrange
    const sql = `create table public."references" (id bigint, name_en text);`;

    // Act
    const result = parseDeclaredColumnOrder(sql);

    // Assert
    expect([...result.keys()]).toEqual(["references"]);
    expect(result.get("references")).toEqual(["id", "name_en"]);
  });

  it("finds every create table block in the real schema file", () => {
    // Assert — 01_tables.sql declares the whole public schema; a scanner that
    // silently matched nothing would make every assertion below vacuous.
    expect(declared.size).toBeGreaterThanOrEqual(20);
    expect(declared.get("shidduchim")?.[0]).toBe("id");
  });
});

const { order, error } = readPhysicalOrder();

describe("declared column order matches the database (database)", () => {
  if (bailIfDbUnreachable(error)) return;

  const physical = order ?? {};

  it("checks every table declared in 01_tables.sql", () => {
    expect(declared.size).toBeGreaterThanOrEqual(20);
  });

  for (const [table, declaredColumns] of declared) {
    it(`column order matches pg_attribute: public.${table}`, () => {
      const physicalColumns = physical[table];

      expect(
        physicalColumns,
        `public.${table} is declared in 01_tables.sql but does not exist in the database`,
      ).toBeDefined();

      // toEqual on the arrays, not on sorted sets: order IS the assertion.
      // A mismatch prints both orders, which is the fix — move the columns in
      // 01_tables.sql to the order shown on the "received" side. Never write a
      // migration for this.
      expect(physicalColumns).toEqual(declaredColumns);
    });
  }
});
