import { describe, expect, it } from "vitest";

/**
 * AC 5(b): a `?raw` schema-shape guard, the same `import.meta.glob` idiom
 * `entity360/pendingDbWidenings.test.ts` and
 * `references/entitlementGate.guard.test.ts` use, asserting the
 * `create table public.entity_files` block in `01_tables.sql` declares NO
 * column named `url` or ending in `_url`. AC 5 requires signed URLs be
 * minted per click and never persisted — a `url`/`*_url` column on the row
 * would be exactly that mistake, silently, at the schema layer.
 */

const sqlSources = import.meta.glob(
  "../../../../../supabase/schemas/01_tables.sql",
  { query: "?raw", import: "default", eager: true },
) as Record<string, string>;

const TABLES_SQL = Object.values(sqlSources)[0];

/**
 * Extracts the balanced `(...)` body of `create table public.entity_files (`
 * from raw SQL source text. Bracket-matched (not a naive first-`)` regex)
 * because the block itself contains nested parens (`check (...)`).
 */
export function extractEntityFilesTableBody(sql: string): string | undefined {
  const marker = "create table public.entity_files (";
  const start = sql.indexOf(marker);
  if (start === -1) return undefined;

  const openParenIndex = start + marker.length - 1;
  let depth = 0;
  let end = -1;
  for (let i = openParenIndex; i < sql.length; i++) {
    if (sql[i] === "(") depth += 1;
    if (sql[i] === ")") {
      depth -= 1;
      if (depth === 0) {
        end = i;
        break;
      }
    }
  }
  if (end === -1) return undefined;
  return sql.slice(openParenIndex + 1, end);
}

/** Splits a comma-separated column/constraint list at TOP LEVEL only —
 * commas inside a nested `(...)` (e.g. a `check (target_type in (...))`)
 * do not split. */
function splitTopLevel(body: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let current = "";
  for (const char of body) {
    if (char === "(") depth += 1;
    if (char === ")") depth -= 1;
    if (char === "," && depth === 0) {
      parts.push(current);
      current = "";
    } else {
      current += char;
    }
  }
  if (current.trim() !== "") parts.push(current);
  return parts;
}

/** True when the table body declares a column literally named `url` or
 * whose name ends in `_url`. Constraint entries (which do not name a
 * column) are skipped. */
export function hasUrlColumn(tableBody: string): boolean {
  return splitTopLevel(tableBody).some((entry) => {
    const trimmed = entry.trim();
    if (/^constraint\b/i.test(trimmed)) return false;
    const match = /^"?(\w+)"?\s/.exec(trimmed);
    if (!match) return false;
    const columnName = match[1].toLowerCase();
    return columnName === "url" || columnName.endsWith("_url");
  });
}

describe("entity_files has no url column (AC 5b)", () => {
  it("is shown red first: a scratch block carrying a url text column is flagged", () => {
    // Arrange — contract §13 rule 2's "prove it red first", a deliberately
    // broken fixture standing in for the mistake AC 5 forbids.
    const scratchBlock = `
        id bigint generated by default as identity primary key,
        account_id bigint not null,
        target_type text not null,
        target_id bigint not null,
        storage_path text not null,
        file_name text not null,
        url text,
        mime_type text not null,
        size_bytes bigint not null
    `;

    // Act / Assert
    expect(hasUrlColumn(scratchBlock)).toBe(true);
  });

  it("is also red for a column merely ending in _url, not only the bare name", () => {
    // Arrange
    const scratchBlock = `
        id bigint generated by default as identity primary key,
        signed_url text
    `;

    // Act / Assert
    expect(hasUrlColumn(scratchBlock)).toBe(true);
  });

  it("is green: the real entity_files table declares no url / *_url column", () => {
    // Arrange
    const body = extractEntityFilesTableBody(TABLES_SQL);

    // Act / Assert
    expect(body).toBeDefined();
    expect(hasUrlColumn(body!)).toBe(false);
  });
});

/**
 * Task 5's regression tripwire, deliberately NOT counted as coverage
 * (contract §13 rule 2 / the story's own instruction): `getPublicUrl` has
 * zero occurrences repo-wide today, so this assertion cannot fail right now
 * — it exists only so a future reintroduction (e.g. someone "simplifying"
 * `signEntityFileUrl` back onto a public URL) is caught immediately.
 */
const atomicCrmSources = import.meta.glob("../../**/*.{ts,tsx}", {
  query: "?raw",
  import: "default",
  eager: true,
}) as Record<string, string>;

describe("getPublicUrl regression tripwire — not coverage", () => {
  it("still has zero occurrences across src/components/atomic-crm", () => {
    // Arrange
    const offenders = Object.entries(atomicCrmSources)
      .filter(([path]) => !path.includes(".test."))
      .filter(([, content]) => /getPublicUrl/.test(content))
      .map(([path]) => path);

    // Assert
    expect(offenders).toEqual([]);
  });
});
