--
-- Tables
-- This file declares all tables in the public schema.
--
-- ===========================================================================
-- COLUMN-ORDER TRAP — read this before adding or moving a column
-- ===========================================================================
-- Every `create table` block below must list its columns in the *physical*
-- order the migrated database has them (`pg_attribute.attnum`), not in a tidy
-- logical order. This is not cosmetic:
--
--   `supabase db diff` builds a shadow database from THIS file and diffs it
--   against the migrated database with `migra`. migra compares a table's
--   columns by ordinal position as well as by name. If the two orders differ
--   it classifies the table as changed — but it has no way to express
--   "reorder columns" in SQL, so it emits NO `alter table` at all. What it
--   does emit is the collateral: every view that depends on that table gets a
--   `drop view` + `create or replace view`, verbatim and pointlessly.
--
--   That output is NON-CONVERGENT. Committing it as a migration does not fix
--   the column order, so the very next `db diff` reproduces the identical
--   drops, forever, on a tree with no pending edit. Worse, `create view`
--   carries forward neither `with (security_invoker = on)` nor the grants in
--   06_grants.sql, so every one of those generated migrations is a live RLS
--   bypass and a lockout waiting to be applied unnoticed.
--
-- HOW IT HAPPENS: `alter table ... add column` always appends to the tail, and
-- `alter table ... drop column` leaves a hole. So a story that drops a column
-- from mid-table and adds new ones will leave the database in an order this
-- file no longer matches, however sensible this file reads.
--
-- WHAT TO DO after generating a migration that adds or drops columns: check
--   select attnum, attname from pg_attribute
--   where attrelid = 'public.<table>'::regclass and attnum > 0 and not attisdropped
--   order by attnum;
-- and reorder the `create table` block here to match. That is a change to this
-- file only — never a migration. Then re-run `db diff` TWICE: once to see it
-- clean, once to prove it converges. `supabase/tests/column_order.test.ts`
-- (`npm run test:unit:db -- column_order`) automates the comparison for every
-- table in this file against a running stack, and names the ones that drifted.
--
-- HISTORY: Story 5.2's migration 20260730011428_shidduch_overview_fields.sql
-- dropped `parents_en`/`parents_he` from the middle of `public.shidduchim` and
-- appended eight columns to its tail without reordering this file. That
-- migration and 20260730094101_shadchan_stats_overview.sql both explain the
-- resulting four view drops as "`db diff`'s own dependency-tracking artifact
-- on this repo's view graph", i.e. as unavoidable. **That explanation is
-- wrong** — migrations are append-only history so those comments stand, but do
-- not believe them. The same view graph diffs perfectly clean at the Epic-4
-- baseline (a8c5e3d), and reordering `shidduchim` here — nothing else, no
-- migration — made `db diff` report "No schema changes found" again. The cause
-- is always this file disagreeing with `pg_attribute`, and it is always
-- fixable here.
--
-- `public.tasks`, `public.shidduchim` and `public.resumes` below all carry
-- tail-ordered columns that exist only for this reason. `resumes` is the
-- cautionary case: Story 5.8 appended `single_id` and nothing complained,
-- because no view depends on `resumes` — migra had no dependent to drop, so it
-- stayed silent while the drift accumulated. `db diff` being quiet is not
-- evidence that the orders agree; only the guard below is.
-- ===========================================================================

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";
create extension if not exists "pgjwt" with schema "extensions";

-- Private schema (created by a historical RLS-cleanup migration; currently unused, kept to avoid a spurious drop)
create schema if not exists "private";

create table public.members (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__members__user_id on public.members using btree (user_id);

-- Tasks/reminders. Uses the AD-13 polymorphic shape (target_type/target_id) so a
-- reminder can hang off a shadchan, a shidduch, a single or a reference without
-- forking a parallel table per entity. delivery_channels is in_app+email by
-- default — deliberately no SMS channel (FR44-46).
create table public.tasks (
    id bigint generated by default as identity primary key,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    member_id bigint,
    -- Column order here deliberately matches the order `supabase db diff` appends
    -- them (alphabetical), so the declared schema and a migrated database agree
    -- and `db diff` stays quiet. See COLUMN-ORDER TRAP at the top of this file.
    account_id bigint not null,
    delivery_channels text[] not null default array['in_app', 'email']::text[],
    target_id bigint not null,
    target_type text not null default 'shidduch',
    -- Story 8.5 (Task 8, contract §8 rule 4): 'connection' joins the widened
    -- ENTITY_TARGET_TYPES union — R1 (3.14) already lifted `tasks` out of
    -- household-only scope, so a shadchan holding a task about one of their
    -- connections needs no further trigger change, only this value. Review
    -- fix (F2): the comment here used to claim connections rows are never
    -- hard-deleted, so no purge trigger was needed — false (accounts' own
    -- FOR ALL delete policy plus connections' two ON DELETE CASCADE parent
    -- FKs mean deleting either party's account hard-deletes the connections
    -- row). purge_connection_dependents() (02_functions.sql), before delete
    -- on public.connections (04_triggers.sql), purges the tasks this value
    -- would otherwise orphan.
    constraint tasks_target_type_check check (
        target_type in ('shadchan', 'shidduch', 'reference', 'single', 'connection')
    ),
    constraint tasks_delivery_channels_check check (
        delivery_channels <@ array['in_app', 'email', 'push']::text[]
    )
);

-- tasks.member_id points at public.members (the user/profile table) — NOT at
-- public.account_members like singles.member_id / shidduchim.owner_member_id /
-- interactions.actor_member_id do. The two `member_id` names collide on
-- purpose-free vocabulary but not on referent; resolving the collision is
-- Epic 2 (AD-19), not this story.
comment on column public.tasks.member_id is 'FK-less reference to public.members(id) — the assignee/reminder-owner user. NOT public.account_members, unlike other *_member_id columns in this schema.';

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

--
-- Foreign keys
--

alter table public.members
    add constraint members_user_id_fkey foreign key (user_id) references auth.users(id);

--
-- =====================================================================
-- MyShadchan — Shidduchim pipeline domain (AD-1, AD-4, AD-12)
-- =====================================================================
-- The central object is a `shidduch` (plural `shidduchim`): a proposed
-- match/single a shadchan redts. Every row carries a non-null account_id
-- (tenant isolation, AD-1) and is RLS-scoped by account. Bilingual
-- identity fields store both scripts (`_en`/`_he`, AD-12).
--
-- Account-scoping now resolves through current_context_id() and the
-- server-held member_state.active_account_id (Story 2.1, AD-19) rather than
-- an arbitrary first membership. anon-grant revocation and invite binding
-- landed alongside it; FORCE ROW LEVEL SECURITY remained an unassigned gap
-- for this domain until Story 7.1, which shipped it on the four new
-- Communication tables below (connections/threads/thread_participants/
-- messages) — see that story's Task 5 for the pg_roles.rolbypassrls
-- evidence. None of the tables in THIS section carry it.
--

-- The one canonical pipeline state (AD-4): exactly 7 values, decision
-- states (yes/unsure/no) reachable only from look_into. Gut
-- `for_sure_not` is deliberately distinct from post-investigation `no`.
-- There is NO separate decision_substate — everything is this enum (D4).
create type public.pipeline_state as enum (
    'new',
    'look_into',
    'not_sure',
    'for_sure_not',
    'yes',
    'unsure',
    'no'
);

-- Tenant root. Also carries billing state (AD-16) — billing columns are
-- schema-ready but unused in this build.
create table public.accounts (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null default 'My Account',
    transparency_level text not null default 'shared',
    data_region text,
    -- Billing (AD-16) — legacy schema-readiness columns, UNUSED. They MUST
    -- NEVER feed an entitlement decision: the sole entitlement authority is the
    -- `subscription` table via public.ai_entitlement(). They look identical to
    -- the real thing, so client writes to them are revoked in 06_grants.sql
    -- (a mislabeled `accounts.plan = 'ai'` would be an instant paywall bypass
    -- the day any code read it).
    stripe_customer_id text,
    subscription_status text,
    plan text,
    current_period_end timestamp with time zone,
    trial_end timestamp with time zone,
    -- Onboarding demo-data flag (Stage A). Set once, to true, by seed_demo's
    -- final write. Cleared back to false ONLY as an opt-in side effect of
    -- clear_demo (its `releaseDemoFlag` request param, default false/absent
    -- -- see clear_demo/index.ts's module docstring): the customer's own
    -- "clear it & start fresh" action passes true, meaning "I'm permanently
    -- done with demo mode"; a reseed refresh (admin_reseed_demo_accounts)
    -- never does, because that account must REMAIN demo-flagged to stay in
    -- the reseed pool. An unconditional flip-to-false on every clear is NOT
    -- this column's contract and must not come back — it previously
    -- deadlocked clear_demo's own demo===true guard against a seed_demo run
    -- that failed partway through. Drives the demo banner and (together
    -- with my_personas()/my_contexts()) the onboarding re-arm condition in
    -- OnboardingGate.tsx.
    demo boolean not null default false,
    -- Story 2.2 (AC-1, AD-2): a context is typed household or shadchanus.
    -- Every account created before this column existed becomes 'household'
    -- (correct — no shadchanus context exists in this codebase before this
    -- story's own add_persona() provisions the first one). enforce_household_scope()
    -- (02_functions.sql) is what makes the household/shadchanus split more than
    -- a label: a shadchanus-kind account can never hold a household domain row.
    kind text not null default 'household',
    -- Story 7.2 (AC-1, AC-2): a household's own default posture for a new
    -- thread's visibility (AD-22; FR96/FR99) — resolved by create_thread()
    -- when p_visibility is omitted (02_functions.sql), never a ceiling or a
    -- floor on an explicit argument. A GENUINELY NEW column, not a reuse of
    -- `transparency_level` above: that column is a different, still-dormant
    -- AD-3 concern with a three-value vocabulary (ShidduchVisibility) that
    -- does not match a thread's two (Dev Notes, "Do not reuse
    -- transparency_level"). Appended at the physical TAIL, after `kind` —
    -- see the COLUMN-ORDER TRAP note at the top of this file; declaring it
    -- anywhere else would put this file out of step with pg_attribute and
    -- make `db diff` emit a permanent, non-convergent set of view drops.
    default_thread_visibility text not null default 'open',
    constraint accounts_kind_check check (kind in ('household', 'shadchanus')),
    constraint accounts_default_thread_visibility_check check (
        default_thread_visibility in ('open', 'private')
    )
);

-- One membership+role model (AD-2). The `shadchan` role is reserved in
-- the check from day one but granted nothing in v1 RLS (deny posture).
-- Distinct from public.members (the user/profile table): account_members
-- carries per-account role and status, members carries the login's own
-- profile fields.
create table public.account_members (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    user_id uuid,
    role text not null default 'parent_admin',
    status text not null default 'active',
    invited_by bigint,
    -- Story 2.2 (AC-2): `single` — "a single with their own login"
    -- (personas-and-contexts.md shape 5) — joins the five-role vocabulary
    -- AD-2 specifies. enforce_membership_role_matches_context() (AC-5) further
    -- restricts `shadchan` to shadchanus-kind accounts and every other role,
    -- including this one, to household-kind accounts.
    constraint account_members_role_check check (
        role in ('parent_admin', 'single', 'helper', 'self_manager', 'shadchan')
    ),
    -- Story 2.5 (AC-6): 'archived' is the one lifecycle transition
    -- remove_persona() ever writes to this column — never a delete. Safe to
    -- add now: the only literal comparison anywhere in the schema is
    -- current_context_id()'s `and am.status = 'active'`, and every existing
    -- write site already writes 'active'.
    constraint account_members_status_check check (
        status in ('active', 'archived')
    )
);

-- The server-held active-context pointer (AD-19). One row per user;
-- active_account_id NULL means "no active context" — the fail-closed case
-- current_context_id() relies on. Written by exactly one code path:
-- activate_context_for(), the private SECURITY DEFINER helper shared by
-- set_active_context() and the activate_first_context trigger — never by a
-- raw client write (05_policies.sql grants authenticated no insert/update/
-- delete policy on this table at all).
create table public.member_state (
    user_id uuid not null primary key,
    active_account_id bigint,
    updated_at timestamp with time zone not null default now()
);

-- Story 2.7 (AC-1, FR119): the one table every invite -- genesis or
-- otherwise -- lives in. Every write goes through create_invite() (AC-3,
-- sets invited_by from the caller's own membership), revoke_invite()
-- (Story 2.8), handle_new_user()'s binding step (a definer trigger), or a
-- service_role genesis seed (invited_by null, the platform-ops runbook
-- action that gets the very first household its very first member) -- there
-- is no insert/update policy for authenticated at all (05_policies.sql), so
-- those checks are the entire write gate. `self_manager` is deliberately
-- excluded from the role check: it is a role a person ARRIVES at
-- (add_persona('single') finding no existing household), never one a second
-- person is invited into (see create_invite()'s comment, 02_functions.sql).
create table public.invites (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    token uuid not null default gen_random_uuid() unique,
    email text not null,
    account_id bigint not null,
    role text not null,
    invited_by bigint,
    status text not null default 'pending',
    expires_at timestamp with time zone not null default (now() + interval '14 days'),
    accepted_at timestamp with time zone,
    -- Story 6.1: the single a `role = 'single'` invite links at acceptance.
    -- Appended at the tail (COLUMN-ORDER TRAP above) rather than placed
    -- logically near `role` — this table already has migrated rows, so its
    -- physical column order must match `db diff`'s shadow database exactly.
    target_single_id bigint,
    constraint invites_role_check check (
        role in ('parent_admin', 'helper', 'single', 'shadchan')
    ),
    constraint invites_status_check check (
        status in ('pending', 'accepted', 'revoked', 'expired')
    )
);

-- The single being suggested FOR (one isolated pipeline each).
create table public.singles (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    first_name_en text,
    first_name_he text,
    last_name_en text,
    last_name_he text,
    gender text,
    dob date,
    community text,
    status text not null default 'active',
    member_id bigint
);

-- Matchmakers. "via {shadchan}" provenance lives here (FR18).
create table public.shadchanim (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    name text not null,
    name_he text,
    location text,
    contacts jsonb,
    responsiveness text,
    -- Story 8.2 (AC-1): appended at the physical TAIL (COLUMN-ORDER TRAP,
    -- header comment above) — this table already carries rows. Links this
    -- book entry to the connections row the household's consent created;
    -- populated only by accept_connection_invite() (02_functions.sql) —
    -- never client-writable (06_grants.sql narrows this table's
    -- insert/update grants to a column list that omits it). UNIQUE, not a
    -- plain index: one connection can only ever back one book entry.
    connection_id bigint unique
);

-- Reusable references — a first-class main entity. A reference is reusable
-- within an account and links across many shidduchim via reference_links.
-- The *_norm columns are the match keys feeding matchIdentity() (AD-5): they are
-- computed server-side by the ONE shared normalize function via the
-- set_reference_norms trigger, never client-supplied and never normalized in the
-- SPA. NOTE: `references` is a reserved SQL keyword, so the table name is always
-- double-quoted in raw SQL (public."references"). PostgREST exposes it as the
-- `references` resource; the frontend never sees the quoting.
create table public."references" (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    name_en text,
    name_he text,
    relationship text,
    phone text,
    school text,
    grad_year integer,
    -- Trigger-set match keys (AD-5/AD-12). Not user-editable.
    name_norm_en text,
    name_norm_he text,
    phone_norm text
);

-- The central object (AD-4). One single, one canonical pipeline_state.
-- Sole INSERT path = public.create_shidduch(); sole state writer =
-- public.transition_shidduch(). See 02_functions.sql.
create table public.shidduchim (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    single_id bigint not null,
    shadchan_id bigint,
    -- Single's identity (bilingual, AD-12)
    name_en text,
    name_he text,
    -- COLUMN ORDER IS LOAD-BEARING — see COLUMN-ORDER TRAP at the top of this
    -- file before moving, inserting or grouping anything below.
    -- Name-bearing context fields, bilingual where they carry a name.
    seminary_en text,
    seminary_he text,
    shul_en text,
    shul_he text,
    location_en text,
    location_he text,
    -- Informational only — NEVER matching signals (FR11)
    age integer,
    height text,
    -- The one canonical state (AD-4); NO decision_substate (D4)
    pipeline_state public.pipeline_state not null default 'new',
    -- Provenance (FR13): first shadchan to redt + when
    first_suggested_by bigint,
    first_suggested_at timestamp with time zone not null default now(),
    -- Board-visible "Redt {date}"
    redt_date date not null default current_date,
    -- Set when entering a terminal state. THE ONE COLUMN IN THIS SCHEMA THAT
    -- `authenticated` MAY NOT SELECT: candid decision rationale, which Story
    -- 6.3's AC-4 requires to read NULL for a `single`. RLS is row-scoped and
    -- cannot narrow a column, so 06_grants.sql grants SELECT on this table
    -- COLUMN BY COLUMN and simply omits this one, and the sole read path is
    -- public.shidduch_close_reason() (02_functions.sql). Two consequences for
    -- anyone editing this table: a NEW COLUMN must be added to that grant or
    -- it is unreadable, and `select *` on public.shidduchim is an error for
    -- every logged-in caller.
    close_reason text,
    -- 'channel' | 'manual' | 'shadchan' (shadchan reserved for Phase-2)
    origin text not null default 'manual',
    -- Visibility (AD-3) — columns locked NOW so Epic 6's single login needs
    -- no breaking migration. owner_member_id is the visibility owner.
    owner_member_id bigint,
    visibility text not null default 'shared',
    -- Per-column ordering on the board.
    index smallint not null default 0,
    -- ---------------------------------------------------------------------
    -- Story 5.2 additions. They sit at the END, out of any reading order,
    -- because that is where `ALTER TABLE ADD COLUMN` physically put them in
    -- 20260730011428_shidduch_overview_fields.sql, and this file must mirror
    -- the database's physical column order, not a tidy logical one. Grouping
    -- `father_*`/`mother_*` back up with the other name-bearing fields, or
    -- `dob` next to `age`, re-breaks `supabase db diff` — see COLUMN-ORDER
    -- TRAP at the top of this file.
    -- ---------------------------------------------------------------------
    -- Prose/free text, single script, not bilingual — not identity signals
    -- (AD-12 does not apply; see Story 5.2's under-specification table).
    background text,
    dob date,
    -- The SUGGESTED PERSON's own prior children — a shidduch fact, not the
    -- retired `children` resource (now `singles`, AD-23). Exempted in
    -- scripts/retired-names.json, not renamed — see Story 5.2's ruling.
    existing_children_note text,
    -- Story 5.2: father/mother replace the single combined `parents_*` pair
    -- (dropped outright — demo/test data only, NFR-14 forbids a shim).
    -- Name-bearing and bilingual, despite sitting down here.
    father_en text,
    father_he text,
    marital_status text,
    mother_en text,
    mother_he text,
    constraint shidduchim_origin_check check (origin in ('channel', 'manual', 'shadchan')),
    constraint shidduchim_visibility_check check (
        visibility in ('shared', 'private_parent', 'private_single')
    )
);

-- 1:1 with a shidduch, OR 1:1 with a single (Story 5.8): the single's OWN
-- resume — "the one I send out to shadchanim" — lives here too, in the same
-- table and the same Resume/Photo tabs, rather than a second, parallel
-- resume feature (AD-24 — a single sees the same screens as a parent, never
-- a forked surface). Exactly one of `shidduchim_id`/`single_id` is set,
-- enforced by `resumes_owner_check` below; each is unique (partial index,
-- since either may be null) so at most one resume per shidduch and at most
-- one per single.
create table public.resumes (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    shidduchim_id bigint,
    files jsonb,
    extracted jsonb,
    sections jsonb,
    -- Story 5.8 appended this, so it sits at the tail rather than next to
    -- `shidduchim_id` where it belongs logically. Physical order is what
    -- `db diff` compares — see COLUMN-ORDER TRAP at the top of this file.
    -- Nothing flagged it at the time only because no view depends on
    -- `resumes`, so migra had no dependent to drop and stayed silent.
    single_id bigint,
    constraint resumes_owner_check check ((shidduchim_id is not null) <> (single_id is not null))
);

-- Photo tab (Story 5.4): one row per uploaded photo of the suggested
-- person, replacing `resumes.photos jsonb` above (dropped in this story —
-- its sole consumer, `Resume.photos?: unknown` in types.ts, and its sole
-- definition here, both go in the same diff; no view, edge function or
-- FakeRest generator ever read it). RLS enforces at ROW granularity, so
-- per-photo visibility (AC-3) requires per-photo rows, not an element
-- inside a whole-row-visible jsonb blob (AD-1). `visibility` reuses
-- shidduchim_visibility_check's vocabulary above, narrowed (the
-- entity_files_visibility_target_check precedent, below) to the two values
-- that mean something for a photo of the suggested person —
-- 'private_single' would hide it from the uploader, who IS the process
-- manager, which is nonsense here. `hidden_at` is a soft-hide (AC-2): a
-- hidden photo is excluded by a plain `hidden_at is null` filter, never
-- deleted (no DELETE code path exists against this table).
create table public.resume_photos (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    resume_id bigint not null,
    -- `{account_id}/photos/{visibility}/{shidduchim_id}/{uuid}-{filename}` —
    -- the visibility lives in the object key itself (AC-4), because storage
    -- policies can only reason about storage.foldername(name), never about
    -- this row. Consequence: changing visibility after upload is not
    -- supported (hide + re-upload) — there is deliberately no UPDATE policy
    -- to move the object (AC-6).
    path text not null,
    uploaded_at timestamp with time zone not null default now(),
    visibility text not null default 'shared',
    hidden_at timestamp with time zone,
    constraint resume_photos_visibility_check check (
        visibility in ('shared', 'private_parent')
    ),
    -- The two-phase upload's consistency guarantee (entity_files_storage_
    -- path_scope_check precedent, below): account_id is trigger-assigned
    -- from current_context_id(), so if the caller switched context between
    -- the storage PUT and this INSERT, the row is rejected instead of being
    -- written with a path into another account's folder.
    constraint resume_photos_storage_path_scope_check check (
        path like account_id::text || '/%'
    )
);

-- Deliberately absent from account_has_domain_data() (02_functions.sql) and
-- its FakeRest mirror (accountDomainData.ts): resume_photos FKs to resumes,
-- which both already check, so a photo cannot exist without a resumes row
-- and the predicate is already true without a redundant exists() arm.
comment on table public.resume_photos is 'Deliberately not in account_has_domain_data()''s table list: it FKs to resumes, which that function already checks, so a photo cannot exist without a resumes row and the predicate is already true.';

-- Medical tab (Story 5.5, the sensitive tier). One row per medical note
-- attached to a shidduch, readable and writable only by a `parent_admin` or
-- `self_manager` (05_policies.sql) — never funnelled through `interactions`,
-- whose own RLS is deliberately content-blind (AD-3) rather than role-aware.
-- A dedicated table with a dedicated, narrow policy is the AD-1 single-owner
-- rule applied to the epic's own stated sensitivity tier.
create table public.medical_notes (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    shidduchim_id bigint not null,
    author_member_id bigint,
    body text not null,
    created_at timestamp with time zone not null default now()
);

-- Deliberately absent from account_has_domain_data() (02_functions.sql) and
-- its FakeRest mirror (accountDomainData.ts): medical_notes FKs to
-- shidduchim, which both already check, so a medical note cannot exist
-- without a shidduchim row and the predicate is already true.
comment on table public.medical_notes is 'Deliberately not in account_has_domain_data()''s table list: it FKs to shidduchim, which that function already checks, so a medical note cannot exist without a shidduchim row and the predicate is already true.';

-- The capture inbox (Epic 2 "front door"). Un-triaged items that arrived by
-- PWA share, inbound email, or manual upload and need ONE calm confirmation
-- step (which single, which shadchan) before becoming a shidduch. Distinct from
-- `resumes`, which is a resume already attached to a resolved shidduch.
-- account_id is auto-set by set_account_id_default (AD-1); the inbound-email
-- webhook writes as service_role. For email, `sender` holds the recovered
-- original sender when one can be confidently extracted from the forwarded
-- message's headers; `sender_needs_confirmation` is set when forwarding is
-- detected but the original sender is ambiguous or missing. Captured
-- `raw_text`/`attachments` are stored verbatim and never auto-parsed at the DB
-- layer (parsing is a gated follow-up).
create table public.inbox_items (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    source text not null default 'upload',
    raw_text text,
    subject text,
    sender text,
    attachments jsonb,
    status text not null default 'unresolved',
    single_id bigint,
    shadchan_id bigint,
    resolved_shidduchim_id bigint,
    -- Story 8.3 (Task 1): appended at the physical TAIL (COLUMN-ORDER TRAP,
    -- header comment above) — this table already carries rows. Set only by
    -- redt_via_connection() (02_functions.sql), a SECURITY DEFINER function
    -- — a shadchan holds no table-level access to a household's inbox_items
    -- at all ("Inbox items scoped to account" below keys strictly on
    -- account_id = current_context_id()). A provenance foreign key, NOT a
    -- second RLS scoping axis (AD-1's "exactly one axis" is about which
    -- column RLS keys on, not about whether a row may carry an unrelated FK
    -- for attribution) — inbox_items stays scoped by account_id alone,
    -- exactly as shidduchim.shadchan_id already references another
    -- account-scoped table without being a second scope.
    connection_id bigint,
    -- Story 10.2: appended at the physical TAIL (COLUMN-ORDER TRAP) — the
    -- migration adds it after connection_id. `sender` holds the recovered
    -- original sender for email; this flag is set when forwarding is detected
    -- but the original sender is ambiguous or missing.
    sender_needs_confirmation boolean not null default false,
    -- Story 10.5: idempotency token for the resolve window, appended at the
    -- physical TAIL (COLUMN-ORDER TRAP). `resolution_input` stashes the
    -- inputs so a retry can complete a partially-failed resolve without
    -- re-running domain mutations.
    resolution_attempt_id text,
    resolution_input jsonb,
    constraint inbox_items_source_check check (source in ('whatsapp', 'sms', 'email', 'photo', 'upload', 'shadchan')),
    constraint inbox_items_status_check check (status in ('unresolved', 'resolving', 'resolved', 'dismissed')),
    -- Story 8.3 review fix (non-blocking observation, judged real): the
    -- widened source check above permits `source = 'shadchan'` with a NULL
    -- connection_id — unreachable through redt_via_connection() (always
    -- sets both together) but directly reachable via a raw
    -- `POST /inbox_items` (authenticated holds a plain table-level INSERT
    -- grant here, 06_grants.sql, gated only by account scope — nothing
    -- restricts source/connection_id shape). Measured effect:
    -- InboxResolveDialog.tsx's linked-shadchan lookup is `enabled:
    -- isShadchanSourced && item.connection_id != null` — false for such a
    -- row, so the query never runs and TanStack Query v5 leaves a disabled,
    -- uncached query's `isPending` permanently true, which renders the
    -- dialog's "Loading…" branch forever (the Dismiss button lives inside
    -- the Form the loading branch replaces, so the item is not even
    -- dismissable). Closed at the data layer rather than the UI: a
    -- shadchan-sourced item must always carry its provenance.
    constraint inbox_items_shadchan_source_requires_connection
        check (source <> 'shadchan' or connection_id is not null)
);

-- Join references <-> shidduchim/resumes. Carries candid diligence content
-- (call_status/what_they_said/conversation_log) that is single-invisible
-- (AD-3, F3): it has NO own visibility column — any future RLS derives
-- visibility by joining back to the parent shidduch, never independently.
-- `relationship_override` exists because one person genuinely wears different
-- hats per family — the same reference is "the shul rabbi" for one shidduch and
-- "a family friend" for another. Null means fall back to references.relationship.
create table public.reference_links (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    reference_id bigint not null,
    shidduchim_id bigint,
    resume_id bigint,
    call_status text,
    what_they_said text,
    conversation_log jsonb,
    relationship_override text,
    constraint reference_links_call_status_check check (
        call_status is null
        or call_status in ('not_started', 'answered', 'no_answer', 'call_back', 'they_will_call_back')
    )
);

-- Dating history (powers dedupe later, Epic-4). Person identity fields are
-- present for a future account-scoped matchIdentity(); no logic is built now.
create table public.date_records (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    single_id bigint,
    person_name_en text,
    person_name_he text,
    person_parents text,
    person_seminary text,
    person_location text,
    date_on date,
    outcome text,
    notes text
);

-- Redt history: a shidduch can be redt (proposed) many times, by the same
-- shadchan or different ones, on different dates (FR13 refinement). Each row is
-- one redt event. shidduchim.redt_date (= the LAST redt), shidduchim.shadchan_id
-- (= the latest redt's shadchan, the card "via"), and first_suggested_by/at
-- (= the earliest redt) are DERIVED from this table by the
-- refresh_shidduch_redt_summary() trigger — never hand-set as the source of truth.
create table public.redts (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    shidduchim_id bigint not null,
    shadchan_id bigint,
    redt_date date not null default current_date,
    note text
);

-- Education history: a single can have attended several institutions — a
-- seminary (girl) or yeshiva (boy), plus schools/college — each with optional
-- years. shidduchim.seminary_en/_he stays the card "headline"; this table holds
-- the full list. `kind` distinguishes seminary vs yeshiva vs school.
create table public.shidduch_schools (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    shidduchim_id bigint not null,
    kind text not null default 'seminary',
    name_en text,
    name_he text,
    start_year integer,
    end_year integer,
    constraint shidduch_schools_kind_check check (
        kind in ('seminary', 'yeshiva', 'school', 'college', 'other')
    )
);

-- Story 5.6: a bookmark to an external profile (a shidduch site, a social
-- profile) with no file behind it — deliberately not polymorphic (YAGNI),
-- scoped to shidduchim only, structurally identical to shidduch_schools
-- above (same account-scoped, shidduch-child shape, no sensitivity tier).
create table public.shidduchim_external_links (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    shidduchim_id bigint not null,
    url text not null,
    label text
);

-- Polymorphic interaction timeline (AD-13 target_type/target_id pattern, reused
-- rather than forked). ONE surface serves both "notes" and "timeline": a note is
-- kind='note'; the timeline is this table ordered by created_at.
--
-- AD-3/F3 visibility: this table has NO own visibility column. When an
-- interaction concerns a specific shidduch-scoped conversation it carries
-- reference_link_id, and RLS derives visibility by walking
-- reference_links -> shidduchim.visibility. Interactions with no shidduch context
-- (e.g. "updated phone number") are account-scoped only. `kind` is a closed
-- enumeration precisely so a coarse aggregate ("N of M references contacted",
-- FR68) can be computed WITHOUT reading candid row content.
create table public.interactions (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    target_type text not null,
    target_id bigint not null,
    -- Which parent this row derives its visibility from. NOT a visibility column
    -- (AD-3 forbids those): it stores no visibility decision, it declares which
    -- parent the answer is derived FROM, and the constraint below makes the two
    -- cases total and mutually exclusive.
    --
    --   'shidduch' -> reference_link_id is required; visibility derives by
    --                 joining reference_links -> shidduchim.
    --   'account'  -> no shidduch parent exists, so there is no shidduch whose
    --                 visibility could ever make this row single-visible. This
    --                 is the only legal bucket for a shadchan- or
    --                 single-targeted row (neither has one shidduch parent to
    --                 derive visibility from — a single belongs to many
    --                 shidduchim, a shadchan to more still), and it is the
    --                 bucket the future single policy denies wholesale.
    --
    -- Without this discriminator a row with a null reference_link_id silently
    -- fell through BOTH branches, which is how a free-text note would have
    -- leaked to a single regardless of the parent's pipeline state.
    scope text not null default 'account',
    reference_link_id bigint,
    actor_member_id bigint,
    kind text not null default 'note',
    body text,
    metadata jsonb,
    -- Soft-delete (Story 3.5 owns this column and its read filter; Story 3.6
    -- owns the write path, its moderation policy and its UI). Nullable, no
    -- default: a live row simply never sets it.
    deleted_at timestamp with time zone,
    -- Story 8.5 (Task 8, contract §8 rule 4): 'connection' joins the widened
    -- ENTITY_TARGET_TYPES union. Review fix (F2): see
    -- tasks_target_type_check's comment above — connections rows CAN be
    -- hard-deleted (an accounts cascade), and purge_connection_dependents()
    -- now purges the interactions this value would otherwise orphan.
    constraint interactions_target_type_check check (
        target_type in ('reference', 'shidduch', 'shadchan', 'single', 'connection')
    ),
    constraint interactions_kind_check check (
        kind in ('note', 'call_logged', 'status_change', 'merge', 'link_created', 'link_removed', 'single_input')
    ),
    constraint interactions_scope_check check (scope in ('shidduch', 'account')),
    -- The structural half of AD-3, enumerated exhaustively. scope = 'shidduch'
    -- means "visibility derives from a parent shidduch", and which shidduch
    -- depends on what the row is about:
    --   target_type = 'reference' -> via reference_link_id -> the link's shidduch
    --   target_type = 'shidduch'  -> target_id IS the shidduch, so no link
    -- scope = 'account' means there is no shidduch parent at all. It is the
    -- only legal scope for a reference row with no conversation context AND
    -- the only legal scope, unconditionally, for a shadchan- or
    -- single-targeted row: neither entity has one shidduch parent from which
    -- visibility could derive (a single belongs to many shidduchim, a
    -- shadchan to more still), so there is no shidduch whose visibility could
    -- ever gate the row. An interaction ABOUT a shidduch always has that
    -- shidduch as its parent, so it can never be account-scoped.
    -- Story 8.5: 'connection' joins the 'account'-scope arm alongside
    -- 'shadchan'/'single' — a connection has no shidduch parent either
    -- (it is a third scope, AD-20), same reasoning as those two.
    constraint interactions_scope_link_check check (
        (scope = 'shidduch' and target_type = 'reference' and reference_link_id is not null)
        or (scope = 'shidduch' and target_type = 'shidduch' and reference_link_id is null)
        or (scope = 'account' and target_type = 'reference' and reference_link_id is null)
        or (scope = 'account' and target_type in ('shadchan', 'single', 'connection') and reference_link_id is null)
    )
);

-- The account-scoped identity match store (AD-5). ONE row per matchable entity,
-- written only by the shared normalize trigger — never by the client. Signals are
-- name(_en/_he) + parents + seminary/yeshiva + shul + location + phone;
-- deliberately NOT age/height (FR11). matchIdentity() reads only this table, so
-- reference dedupe, shidduch-suggestion dedupe and date-record dedupe share one
-- implementation instead of three bespoke matchers.
create table public.identity_signals (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    target_type text not null,
    target_id bigint not null,
    name_en_norm text,
    name_he_norm text,
    -- Variant-folded consonant skeletons: what makes Hebrew/English
    -- transliteration variants (Chaim/Haim, Yitzchak/Itzhak) compare equal.
    name_en_key text,
    name_he_key text,
    phone_norm text,
    parents_norm text,
    seminary_norm text,
    shul_norm text,
    location_norm text,
    constraint identity_signals_target_type_check check (
        target_type in ('reference', 'shidduch', 'date_record')
    )
);

-- Transitions-as-data (AD-4, invariant 2): the legal pipeline_state edges,
-- enforced by public.transition_shidduch() and the enforce_pipeline_transition
-- trigger — never scattered ifs. Rows are seeded by the migration.
create table public.pipeline_transitions (
    from_state public.pipeline_state not null,
    to_state public.pipeline_state not null,
    constraint pipeline_transitions_pkey primary key (from_state, to_state)
);

-- Billing + AI entitlement (E4). AI (research assistant, future resume
-- auto-parse) is the ONLY paid surface; everything else stays free forever.
--
-- One subscription row per account. The DEFAULT posture is UNENTITLED: no row,
-- or a row that is not exactly (plan='ai', status='active'), locks the AI
-- features. The client may only SELECT this table (05_policies.sql /
-- 06_grants.sql) — there is deliberately NO client-callable path that flips
-- `plan` to 'ai' or `status` to 'active', because that would be exactly the
-- billing bypass the old client-side entitlement placeholder warned about.
-- Every write is service_role (payment webhook / admin), which bypasses RLS.
create table public.subscription (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    -- 'free' = the free-forever tier; 'ai' = the paid AI tier ($2/mo · $24/yr).
    plan text not null default 'free',
    -- 'active' = entitled and paid; 'lapsed' = was paid, now expired (AI
    -- auto-fill pauses, the free manual path stays); 'none' = never subscribed.
    status text not null default 'none',
    current_period_end timestamp with time zone,
    constraint subscription_plan_check check (plan in ('free', 'ai')),
    constraint subscription_status_check check (status in ('active', 'lapsed', 'none'))
);

-- AI usage meter (E4). One row per account per calendar month. resumes_parsed
-- backs the calm "34 / 100 resumes" meter in Billing. It is incremented
-- server-side by the (future) AI edge functions under service_role, right after
-- they confirm entitlement via ai_entitlement(); the client only ever SELECTs.
create table public.ai_usage (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    -- Month key in 'YYYY-MM' form, e.g. '2026-07'.
    period text not null,
    resumes_parsed integer not null default 0,
    constraint ai_usage_resumes_parsed_nonneg check (resumes_parsed >= 0)
);

-- Story 2.2 (AC-4): deliberately excluded from enforce_household_scope()'s
-- 11 household-only tables (interactions/tasks dropped out of that set in
-- Story 3.14 — see 04_triggers.sql — but subscription/ai_usage were never in
-- it either way). No source restricts a shadchanus context from holding
-- billing/entitlement rows; left scoped generically by current_context_id()
-- until a future story states a rule either way.
comment on table public.subscription is 'Deliberately excluded from enforce_household_scope() (Story 2.2 AC-4): no source restricts a shadchanus context from holding billing/entitlement rows; scoped generically by current_context_id() until a story states a rule.';
comment on table public.ai_usage is 'Deliberately excluded from enforce_household_scope() (Story 2.2 AC-4): same open question as public.subscription — no source restricts entitlement usage-metering to household contexts.';

-- Files tab (Story 3.7): a polymorphic catalog row per uploaded object,
-- backing the private `entity-files` storage bucket (07_storage.sql). Full
-- four-value target-type parity FROM CREATION (contract §8 rule 1/§10) —
-- unlike tasks/interactions, this table was never behind ENTITY_TARGET_TYPES
-- (entity360/pendingDbWidenings.ts).
create table public.entity_files (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    target_type text not null,
    target_id bigint not null,
    -- `{account_id}/{target_type}/{target_id}/{uuid}{ext}` — no user-supplied
    -- segment. The original file name lives in file_name below and is
    -- re-attached at download time (createSignedUrl's `download` option),
    -- never placed in the key.
    storage_path text not null,
    file_name text not null,
    mime_type text not null,
    size_bytes bigint not null,
    -- The domain's one AD-3 visibility vocabulary (shidduchim_visibility_check
    -- above), not a second one. Settable after upload (AC 2b) — Epic 6's
    -- single-access work is what ENFORCES it; this table stores and exposes
    -- the value from day one.
    visibility text not null default 'shared',
    uploaded_by_member_id bigint,
    -- Story 8.5 (Task 8, contract §8 rule 4): 'connection' joins for
    -- TS/DB-union parity with ENTITY_TARGET_TYPES — legal here though no
    -- story wires a connection Files tab, exactly as 'shadchan' was already
    -- legal before shadchanim ever grew one. Review fix (F2):
    -- purge_connection_dependents() (02_functions.sql) purges a
    -- connection-targeted entity_files CATALOG row too, for parity with the
    -- other three purge_* callers — see tasks_target_type_check's comment
    -- above for why connections rows are not, in fact, un-deletable.
    constraint entity_files_target_type_check check (
        target_type in ('reference', 'shidduch', 'shadchan', 'single', 'connection')
    ),
    constraint entity_files_visibility_check check (
        visibility in ('shared', 'private_parent', 'private_single')
    ),
    -- A non-'shared' value is a statement about who in a household may see
    -- the file. A shadchan and a reference are not household members, so the
    -- value would describe nothing. Narrows the check above; does not
    -- replace it.
    constraint entity_files_visibility_target_check check (
        visibility = 'shared' or target_type in ('shidduch', 'single')
    ),
    -- The two-phase upload's consistency guarantee, enforced by the database
    -- rather than by a test: account_id is trigger-assigned from
    -- current_context_id() (set_entity_files_account_id, 04_triggers.sql), so
    -- if the caller switched context between the storage PUT and this
    -- INSERT, the row is rejected instead of being written with a path
    -- pointing into the other account's folder.
    constraint entity_files_storage_path_scope_check check (
        storage_path like account_id::text || '/%'
    )
);

-- entity_files is deliberately NOT attached to enforce_household_scope() —
-- see 04_triggers.sql's household-only-tables comment and AC 8(c)/(d): a
-- shadchan must be able to attach a file in their own shadchanus context from
-- day one (Epic 8.5). This is a term (contract §8 rule 5), not an oversight.
comment on table public.entity_files is 'Deliberately NOT attached to enforce_household_scope() (contract §8 rule 5, Story 3.7): a shadchanus context must be able to hold entity_files rows from day one (Epic 8.5).';

-- =====================================================================
-- MyShadchan — Communication (Epic 7: threads, AD-1, AD-20, AD-22)
-- =====================================================================
-- A connection is a THIRD scope, owned by neither the household nor the
-- shadchanus account (AD-20) — the FK target every dual-axis thread/
-- thread_participants/messages row's connection_id points at when it is
-- not account-scoped. Bare and read-only-to-`authenticated` in this story:
-- the consent workflow (propose/accept/end, AD-11/FR119) is Epic 8 Story
-- 8.2, which ALTERs this table and must NOT re-create it, its trigger or
-- its policy (Story 7.1 Dev Notes, "AD-20: the dual axis is born here").
-- `status` admits only 'accepted'/'ended' — no 'pending', because AD-20
-- says a connection exists only after acceptance.
create table public.connections (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    household_account_id bigint not null,
    shadchanus_account_id bigint not null,
    status text not null default 'accepted',
    ended_at timestamp with time zone,
    -- Story 8.2 columns — appended at the physical TAIL (COLUMN-ORDER TRAP,
    -- header comment above): this table already carries rows (the
    -- migration-data-safety fixture's production-shaped seed, plus this
    -- story's own SQL test fixtures), so `proposed_by_account_id` cannot be
    -- added NOT NULL in one step — the migration adds it nullable, backfills
    -- every pre-existing row from `household_account_id`, THEN sets NOT
    -- NULL. Never re-declare 7.4's columns above this line, its
    -- `enforce_connection_kinds()` trigger, its RLS or its grants — this
    -- story only ALTERs.
    proposed_by_account_id bigint not null,
    accepted_at timestamp with time zone,
    ended_by_account_id bigint,
    -- Story 8.5 (AC-2) — appended at the physical TAIL, same COLUMN-ORDER
    -- TRAP as 8.2's own columns above. A snapshot of the household side's
    -- `accounts.name`, taken once by `accept_connection_invite()` at the
    -- SAME moment it already snapshots the shadchanus side's name into
    -- `shadchanim.name` (02_functions.sql) — the mirror-image of that
    -- existing precedent, not a new mechanism. Necessary because
    -- `public.accounts`' own RLS ("Accounts readable to their members",
    -- 05_policies.sql) never lets a shadchanus caller read the household
    -- account row directly (AD-20): there is no live join the Connection 360
    -- identity header could use instead. This table already carries rows
    -- (the migration-data-safety fixture's seed, plus 8.2/8.4's own SQL test
    -- fixtures), so the migration adds it nullable, backfills every
    -- pre-existing row from a join to `accounts`, THEN sets NOT NULL — the
    -- same two-step shape `proposed_by_account_id` above already used.
    household_account_name text not null,
    constraint connections_status_check check (status in ('accepted', 'ended')),
    -- Story 8.2 (AC-3, "What ending does and does not do"): the two columns
    -- that answer "is this row ended" must always agree — never one flipped
    -- without the other.
    constraint connections_ended_consistency check ((status = 'ended') = (ended_at is not null))
);

-- At most one LIVE connection per pair; an ended one stays as history and
-- does not structurally forbid reconnecting later — a plain UNIQUE
-- constraint would forbid that, which AD-20's "either side may end it"
-- would make senseless. A partial index, not a table constraint, because a
-- CHECK/UNIQUE constraint cannot carry a WHERE clause.
create unique index connections_live_pair_idx on public.connections (household_account_id, shadchanus_account_id) where status = 'accepted';

-- Story 8.2 (AC-1, AC-2, Task 2): the consent workflow's proposed-not-yet-
-- accepted invite. A sibling table to Epic 2's household-membership
-- `invites` (Story 2.7), not a shared row in it — see this story's Dev
-- Notes, "Why a sibling table, not a shared one": a membership invite grants
-- a role to a person inside the inviter's OWN account, while a connection
-- invite links two already-existing, opposite-kind accounts with neither
-- becoming a member of the other.
--
-- The token itself is never stored — only `token_hash` (a SHA-256 hex
-- digest via pgcrypto's `extensions.digest()`), unlike 2.7's stored-raw-uuid
-- `invites.token`: a connection invite crosses the tenant boundary, so a
-- read of this table must never yield a usable token. The raw token is
-- returned once, from `create_connection_invite()` (02_functions.sql), and
-- never persisted in plaintext anywhere.
create table public.connection_invites (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    inviter_account_id bigint not null,
    inviter_kind text not null,
    token_hash text not null unique,
    status text not null default 'pending',
    expires_at timestamp with time zone not null,
    accepted_by_account_id bigint,
    accepted_at timestamp with time zone,
    revoked_at timestamp with time zone,
    constraint connection_invites_status_check check (status in ('pending', 'accepted', 'revoked', 'expired')),
    constraint connection_invites_inviter_kind_check check (inviter_kind in ('household', 'shadchanus'))
);

-- The three thread tables, dual-axis from day one (AD-1, AD-22 resolution
-- rule 3): every row carries a nullable account_id AND a nullable
-- connection_id, with exactly one non-null (the XOR checks below). The
-- connection axis is structural only in this story — thread_is_readable()
-- fails closed on it (02_functions.sql) and every INSERT policy below
-- requires connection_id is null — until Story 7.4 opens it. See this
-- story's Dev Notes, "What this story does not do".
create table public.threads (
    id bigint generated by default as identity primary key,
    account_id bigint,
    connection_id bigint,
    created_at timestamp with time zone not null default now(),
    subject_type text not null,
    subject_id bigint,
    visibility text not null default 'open',
    created_by_member_id bigint,
    constraint threads_subject_type_check check (subject_type in ('shidduch', 'relationship')),
    -- The paired-null rule (AC-1): a 'shidduch' thread always names its
    -- subject; a 'relationship' thread (a general conversation not tied to
    -- one shidduch) never does. Reachability of subject_id within the
    -- thread's own scope is validated by create_thread() (02_functions.sql),
    -- not by a foreign key here — subject_id is polymorphic-shaped, like
    -- interactions.target_id / tasks.target_id above, so its integrity
    -- rests on purge_polymorphic_dependents() rather than an FK.
    constraint threads_subject_id_check check (
        (subject_type = 'shidduch' and subject_id is not null)
        or (subject_type = 'relationship' and subject_id is null)
    ),
    constraint threads_visibility_check check (visibility in ('open', 'private')),
    -- The XOR (AD-1): exactly one of account_id/connection_id is non-null,
    -- written as `<>` on two booleans so it cannot be satisfied by both
    -- being true or both being false.
    constraint threads_scope_check check ((account_id is not null) <> (connection_id is not null))
);

-- Explicit participants (AC-2): who is in the conversation. Never derived
-- from "everyone in the scope" — every thread has at least one participant
-- row (its creator) from the moment it is created (create_thread()).
create table public.thread_participants (
    id bigint generated by default as identity primary key,
    account_id bigint,
    connection_id bigint,
    thread_id bigint not null,
    member_id bigint not null,
    created_at timestamp with time zone not null default now(),
    -- Story 7.5 (AC-1): unread state is DERIVED, never queued (Dev Notes,
    -- "Why in-app delivery needs no queue") — a thread is unread for this
    -- participant when a message.created_at postdates this column. NULL
    -- (not epoch zero) is the honest "never opened this thread" value;
    -- mark_thread_read() (02_functions.sql) is the only path that moves it.
    -- Appended at the physical TAIL — `alter table ... add column` always
    -- appends (COLUMN-ORDER TRAP, top of this file), and this column lands
    -- on an EXISTING table, not a fresh `create table`.
    last_read_at timestamp with time zone,
    constraint thread_participants_scope_check check ((account_id is not null) <> (connection_id is not null))
);

-- Structured, subject-scoped rows (AC-4) — never appended to the generic
-- interactions timeline. Append-only: no UPDATE/DELETE policy or grant for
-- authenticated (05_policies.sql / 06_grants.sql).
create table public.messages (
    id bigint generated by default as identity primary key,
    account_id bigint,
    connection_id bigint,
    thread_id bigint not null,
    sender_member_id bigint,
    body text not null,
    created_at timestamp with time zone not null default now(),
    constraint messages_scope_check check ((account_id is not null) <> (connection_id is not null)),
    constraint messages_body_not_blank_check check (btrim(body) <> '')
);

-- Story 7.5 (AC-3, AC-6, AC-8): an event-based delivery queue — one row per
-- (message, recipient, channel), queued by the fan_out_message_notifications()
-- trigger (02_functions.sql / 04_triggers.sql) the moment a message is
-- inserted. Distinct from Story 12.2's task_notifications, a TIME-based queue
-- ("a reminder came due"); this one is EVENT-based ("a message was inserted").
-- Carries its own account_id/connection_id copy rather than a composite FK to
-- messages — AD-1 names a trigger as an accepted alternative, and a composite
-- FK here would need a new unique key on the data-bearing messages table for
-- a queue no client can ever read (AC-8). The plain FK is below, in the
-- Foreign keys section.
create table public.message_notifications (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    account_id bigint,
    connection_id bigint,
    message_id bigint not null,
    recipient_member_id bigint not null,
    channel text not null,
    status text not null default 'pending',
    recipient_email text,
    attempts integer not null default 0,
    sent_at timestamp with time zone,
    error text,
    -- AC-6: no outbound SMS, structurally — closed to exactly the two
    -- channels this story ever delivers.
    constraint message_notifications_channel_check check (channel in ('email', 'push')),
    -- 'sending' is the claim-before-dispatch state (AC-9, `for update skip
    -- locked`); 'skipped' is AC-4's deliberate no-login-yet case, never a
    -- failure.
    constraint message_notifications_status_check check (
        status in ('pending', 'sending', 'sent', 'failed', 'skipped')
    ),
    -- AD-1's XOR, the same shape as threads_scope_check/messages_scope_check
    -- above: a notification inherits its message's scope on whichever axis
    -- produced it (AC-8).
    constraint message_notifications_scope_check check ((account_id is not null) <> (connection_id is not null))
);

-- Story 7.5 (AC-5, AC-12): a device registered for Web Push (RFC 8291/8292).
-- One row per (member, browser/device) — a member with several devices holds
-- several rows, and the fan-out trigger queues a push notification only when
-- at least one exists for the recipient (AC-5): "by push where installed",
-- with no dead letter for a member who never enabled it.
create table public.push_subscriptions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    member_id bigint not null,
    endpoint text not null,
    p256dh text not null,
    auth text not null
);

-- Story 9.1 (AD-21): the sole anon-readable relation in the product. A
-- published-listing snapshot, never a view onto a live tenant table — see
-- this story's Dev Notes "Why this exists". Both branches (`shadchan` here;
-- `single` from Story 9.2 on) share one table so `listing_type` alone tells
-- an anon reader what it is looking at; the `single_*` columns exist from
-- this first migration even though only 9.2 ever writes them, so 9.2 never
-- needs an `ALTER TABLE` (COLUMN-ORDER TRAP, header comment above). No photo
-- column of any kind — see Dev Notes "No photo on a listing" for why that is
-- a decision, not an omission.
create table public.listings (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    listing_type text not null,
    single_id bigint,
    published_by_member_id bigint references public.account_members(id) on delete set null,

    -- Shadchan fields (FR101, story 9.1). Null = not opted in.
    shadchan_name text,
    shadchan_area text,
    shadchan_contact_info text,

    -- Single fields (FR102, story 9.2). Null = not opted in. Untouched by
    -- this story — do not write to these columns here.
    single_first_name_en text,
    single_first_name_he text,
    single_age integer,
    single_height text,
    single_community text,
    single_location text,
    single_summary text,

    constraint listings_type_check check (listing_type in ('shadchan', 'single')),
    constraint listings_single_id_presence check (
        (listing_type = 'single' and single_id is not null)
        or (listing_type = 'shadchan' and single_id is null)
    ),
    constraint listings_shadchan_name_required check (
        listing_type <> 'shadchan' or shadchan_name is not null
    ),
    constraint listings_single_name_required check (
        listing_type <> 'single'
        or single_first_name_en is not null
        or single_first_name_he is not null
    )
);

-- Story 9.3 (AD-21's own dignity-floor requirement, FR104): existence of a
-- row = "locked", mirroring `listings` itself. A TABLE, not a column on
-- `singles` (Dev Notes "Why a lock table, not a column on `singles`" in
-- 9-3-single-controls-own-listing.md) — `authenticated` already holds a
-- table-level UPDATE grant on `singles` (06_grants.sql), and a column-level
-- REVOKE cannot carve a column back out of a standing table-level grant, so
-- a boolean column here would be a silent no-op the moment any
-- parent_admin's ordinary dataProvider.update("singles", ...) reached it.
-- No identity column, so no sequence exists to grant either way — the
-- primary key is the single_id itself (one lock per single, ever, at once).
create table public.listing_withdrawal_locks (
    single_id bigint primary key,
    account_id bigint not null,
    locked_at timestamp with time zone not null default now()
);

-- Story 9.5 (FR107): a revocable, expiring, per-single bearer-token share
-- link — the "sole surviving use of tokenised access" now that the child
-- portal is retired (Story 1.4). A separate mechanism from `listings`
-- (AD-21): a listing is an opt-in PUBLIC snapshot with no photo and no
-- files; a share link is a TARGETED, revocable grant that can include the
-- resume file(s) and an optional photo, served only through the `share/`
-- Worker (never a direct or signed Storage URL — AD-9). `token` is always
-- server-overwritten by `set_share_link_token_defaults()` (04_triggers.sql)
-- regardless of what a client supplies (AC-2), mirroring the deleted
-- portal's `set_child_portal_token_defaults()` exactly.
create table public.share_links (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    single_id bigint not null,
    created_by_member_id bigint references public.account_members(id) on delete set null,
    token text not null,
    include_photo boolean not null default false,
    expires_at timestamp with time zone not null,
    revoked_at timestamp with time zone
);

-- Story 9.5 (AC-5, AC-8): one row per request against a share link — every
-- profile view AND every file download, not merely "the link was opened".
-- The sole writer is the `share/` Worker using the service-role key
-- (06_grants.sql grants no `authenticated`/`anon` DML at all); `authenticated`
-- only ever reads it, scoped through `share_links`' own RLS (05_policies.sql).
-- `duration_ms` (nullable — the Worker always sets it, no CHECK forces that)
-- is the wall-clock time the request took, in milliseconds: it exists so the
-- storage decision's revisit trigger #2 ("Worker->Storage hop becomes a
-- reliability problem, p95 > 1.5s") has an actual data source instead of an
-- anecdote — free to add on a brand-new table, unlike an `alter table` on an
-- existing one (COLUMN-ORDER TRAP above).
create table public.share_access_log (
    id bigint generated by default as identity primary key,
    share_link_id bigint not null references public.share_links(id) on delete cascade,
    accessed_at timestamp with time zone not null default now(),
    resource text not null,
    ip_hash text,
    user_agent text,
    duration_ms integer
);

--
-- Foreign keys (shidduchim domain)
--
-- (account_id, id) uniqueness is what makes the composite foreign keys below
-- possible. Every FK that crosses between two tenant-owned tables carries
-- account_id, so a row can only ever reference a parent in its own account.
-- These are all ON DELETE CASCADE, which is what made the single-column version
-- dangerous: one tenant deleting their own single would have cascaded into
-- another tenant's shidduch. Without them a plain FK on shidduchim_id lets one tenant point a row
-- at another tenant's shidduch: no read leak, but it plants rows naming a
-- stranger's records and turns FK-violation-versus-success into a cross-tenant
-- id oracle. The composite FK makes crossing the boundary impossible rather
-- than merely unrewarding.
alter table public.singles
    add constraint singles_account_id_id_key unique (account_id, id);
alter table public."references"
    add constraint references_account_id_id_key unique (account_id, id);
alter table public.shidduchim
    add constraint shidduchim_account_id_id_key unique (account_id, id);
alter table public.resumes
    add constraint resumes_account_id_id_key unique (account_id, id);
alter table public.reference_links
    add constraint reference_links_account_id_id_key unique (account_id, id);

alter table public.account_members
    add constraint account_members_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.account_members
    add constraint account_members_invited_by_fkey foreign key (invited_by) references public.account_members(id) on delete set null;
alter table public.account_members
    add constraint account_members_user_id_fkey foreign key (user_id) references auth.users(id) on delete set null;

alter table public.member_state
    add constraint member_state_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade;
alter table public.member_state
    add constraint member_state_active_account_id_fkey foreign key (active_account_id) references public.accounts(id) on delete set null;

alter table public.invites
    add constraint invites_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.invites
    add constraint invites_invited_by_fkey foreign key (invited_by) references public.account_members(id) on delete set null;
-- Story 6.1 (AC-2/AC-5): the tenant boundary for target_single_id is this
-- composite FK, not an application check — a tampered invite naming another
-- household's single fails referential integrity, exactly like the
-- singles/references/shidduchim composite FKs below. Defined composite from
-- the start, never an interim single-column FK on target_single_id alone.
-- Safe to fully VALIDATE even against a production table: `target_single_id`
-- is null on every pre-existing row (the column is new), and a composite FK
-- with any null referencing column is trivially satisfied (MATCH SIMPLE).
alter table public.invites
    add constraint invites_target_single_id_fkey
    foreign key (account_id, target_single_id) references public.singles(account_id, id) on delete cascade;
-- Story 6.1 review fix (BLOCKER #2): declared NOT VALID and NEVER validated
-- — deliberately, permanently, not a "validate later" TODO. Epic 2 shipped
-- `single` as an ordinary invitable household role two epics before this
-- constraint existed (Settings' generic selector, `invitableRoles()`), so a
-- production `invites` row with `role = 'single'` and no target can already
-- exist in ANY status. Running `validate constraint` against it — which
-- `db diff` naturally emits and which passes every local gate because
-- `db reset` always starts from an EMPTY table — aborts `supabase db push`
-- against a non-empty production table (reproduced locally against a
-- rewound `invites` table; see the migration's own header comment). The
-- migration-data-safety guard (`supabase/tests/migration-data-safety/`)
-- forbids the alternative of deleting or rewriting such a row to make it
-- validate, so NOT VALID — enforced for every new INSERT/UPDATE from here
-- on, silently grandfathering only the rows that already existed — is the
-- correct, permanent state, not a transitional one. `accept_invite()`
-- (02_functions.sql) has its own explicit guard turning what would
-- otherwise be a raw constraint-violation error on such a legacy row into
-- the same friendly "invalid, expired, or already used" message every
-- other unhonourable invite gets. `revoke_invite()` needed the SAME guard
-- and shipped without it — clicking Revoke on such a row raised a bare
-- 23514 at the admin — and now has one. ANY future function that UPDATEs
-- this table needs it too: `not valid` grandfathers a row only against the
-- constraint's own validation pass, never against the next write to it.
alter table public.invites
    add constraint invites_role_target_check check (
        (role = 'single') = (target_single_id is not null)
    ) not valid;

alter table public.singles
    add constraint singles_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.singles
    add constraint singles_member_id_fkey foreign key (member_id) references public.account_members(id) on delete set null;

alter table public.shadchanim
    add constraint shadchanim_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
-- Story 8.2 (AC-1): the book entry's optional back-reference to the
-- connections row that created it, set only by accept_connection_invite().
-- No ON DELETE action: a connections row is never deleted — end_connection()
-- only flips status/ended_at (this story's Dev Notes, "What ending does and
-- does not do") — so there is no real delete path this FK needs to defend
-- against.
alter table public.shadchanim
    add constraint shadchanim_connection_id_fkey foreign key (connection_id) references public.connections(id);

-- Story 8.3 (Task 1): the redt's provenance link (see inbox_items' own
-- comment above). No ON DELETE action, matching shadchanim_connection_id_fkey
-- just above — a connections row is never deleted (end_connection() only
-- flips status/ended_at), so there is no real delete path this FK needs to
-- defend against.
alter table public.inbox_items
    add constraint inbox_items_connection_id_fkey foreign key (connection_id) references public.connections(id);

alter table public."references"
    add constraint references_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;

alter table public.shidduchim
    add constraint shidduchim_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.shidduchim
    add constraint shidduchim_single_id_fkey
    foreign key (account_id, single_id) references public.singles(account_id, id) on delete cascade;
alter table public.shidduchim
    add constraint shidduchim_shadchan_id_fkey foreign key (shadchan_id) references public.shadchanim(id) on delete set null;
alter table public.shidduchim
    add constraint shidduchim_first_suggested_by_fkey foreign key (first_suggested_by) references public.shadchanim(id) on delete set null;
alter table public.shidduchim
    add constraint shidduchim_owner_member_id_fkey foreign key (owner_member_id) references public.account_members(id) on delete set null;

alter table public.resumes
    add constraint resumes_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.resumes
    add constraint resumes_shidduchim_id_fkey
    foreign key (account_id, shidduchim_id) references public.shidduchim(account_id, id) on delete cascade;
alter table public.resumes
    add constraint resumes_single_id_fkey
    foreign key (account_id, single_id) references public.singles(account_id, id) on delete cascade;

alter table public.resume_photos
    add constraint resume_photos_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.resume_photos
    add constraint resume_photos_resume_id_fkey
    foreign key (account_id, resume_id) references public.resumes(account_id, id) on delete cascade;

alter table public.medical_notes
    add constraint medical_notes_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.medical_notes
    add constraint medical_notes_shidduchim_id_fkey
    foreign key (account_id, shidduchim_id) references public.shidduchim(account_id, id) on delete cascade;
alter table public.medical_notes
    add constraint medical_notes_author_member_id_fkey foreign key (author_member_id) references public.account_members(id) on delete set null;

alter table public.reference_links
    add constraint reference_links_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
-- Composite (account_id, ...) foreign keys: a link can only ever join records
-- inside its own account. MATCH SIMPLE means a null shidduchim_id/resume_id
-- still satisfies the constraint, which is correct — a link may legitimately
-- reference a resume but no shidduch.
alter table public.reference_links
    add constraint reference_links_reference_id_fkey
    foreign key (account_id, reference_id) references public."references"(account_id, id) on delete cascade;
alter table public.reference_links
    add constraint reference_links_shidduchim_id_fkey
    foreign key (account_id, shidduchim_id) references public.shidduchim(account_id, id) on delete cascade;
alter table public.reference_links
    add constraint reference_links_resume_id_fkey
    foreign key (account_id, resume_id) references public.resumes(account_id, id) on delete cascade;

alter table public.date_records
    add constraint date_records_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.date_records
    add constraint date_records_single_id_fkey
    foreign key (account_id, single_id) references public.singles(account_id, id) on delete cascade;

alter table public.redts
    add constraint redts_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.redts
    add constraint redts_shidduchim_id_fkey
    foreign key (account_id, shidduchim_id) references public.shidduchim(account_id, id) on delete cascade;
alter table public.redts
    add constraint redts_shadchan_id_fkey foreign key (shadchan_id) references public.shadchanim(id) on delete set null;

alter table public.shidduch_schools
    add constraint shidduch_schools_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.shidduch_schools
    add constraint shidduch_schools_shidduchim_id_fkey
    foreign key (account_id, shidduchim_id) references public.shidduchim(account_id, id) on delete cascade;

alter table public.shidduchim_external_links
    add constraint shidduchim_external_links_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.shidduchim_external_links
    add constraint shidduchim_external_links_shidduchim_id_fkey
    foreign key (account_id, shidduchim_id) references public.shidduchim(account_id, id) on delete cascade;

-- interactions/identity_signals are polymorphic: target_id carries no FK (it can
-- point at several tables), so its integrity rests on the cleanup triggers in
-- 04_triggers.sql. reference_link_id is NOT polymorphic and is enforced properly.
alter table public.interactions
    add constraint interactions_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.interactions
    add constraint interactions_reference_link_id_fkey
    foreign key (account_id, reference_link_id) references public.reference_links(account_id, id) on delete cascade;
alter table public.interactions
    add constraint interactions_actor_member_id_fkey foreign key (actor_member_id) references public.account_members(id) on delete set null;

alter table public.identity_signals
    add constraint identity_signals_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.identity_signals
    add constraint identity_signals_target_key unique (account_id, target_type, target_id);

alter table public.tasks
    add constraint tasks_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;

-- entity_files is polymorphic (target_id carries no FK, same design as
-- interactions.target_id / tasks.target_id) — its integrity rests on
-- purge_polymorphic_dependents() (02_functions.sql), not a foreign key.
alter table public.entity_files
    add constraint entity_files_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.entity_files
    add constraint entity_files_uploaded_by_member_id_fkey foreign key (uploaded_by_member_id) references public.account_members(id) on delete set null;

-- Billing (E4). One subscription row per account (unique account_id) and one
-- usage row per (account, month). Both cascade with the account.
alter table public.subscription
    add constraint subscription_account_id_key unique (account_id);
alter table public.subscription
    add constraint subscription_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;

alter table public.ai_usage
    add constraint ai_usage_account_id_period_key unique (account_id, period);
alter table public.ai_usage
    add constraint ai_usage_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;

-- Communication domain (Epic 7). Both sides of a connection FK to accounts;
-- kind-matching (household/shadchanus) is enforced by
-- enforce_connection_kinds() (02_functions.sql, 04_triggers.sql), not by
-- the FK itself.
alter table public.connections
    add constraint connections_household_account_id_fkey foreign key (household_account_id) references public.accounts(id) on delete cascade;
alter table public.connections
    add constraint connections_shadchanus_account_id_fkey foreign key (shadchanus_account_id) references public.accounts(id) on delete cascade;

-- Story 8.2: `proposed_by_account_id` is always one of the two accounts
-- above, so whichever of the two FKs above cascades first already removes
-- this row before this one could ever be violated — no ON DELETE action
-- needed (contrast the SET NULL a nullable, genuinely independent reference
-- would want). `ended_by_account_id` is nullable and independent in the same
-- way, so it gets SET NULL rather than leaving a dangling audit reference.
alter table public.connections
    add constraint connections_proposed_by_account_id_fkey foreign key (proposed_by_account_id) references public.accounts(id);
alter table public.connections
    add constraint connections_ended_by_account_id_fkey foreign key (ended_by_account_id) references public.accounts(id) on delete set null;

-- Story 8.2 (Task 2): connection_invites' two account references. No ON
-- DELETE action on either — an account is never deleted in this product
-- (AGENTS.md: "User deletion is not supported to avoid data loss"), so
-- there is no real cascade/orphan scenario either FK needs to resolve.
alter table public.connection_invites
    add constraint connection_invites_inviter_account_id_fkey foreign key (inviter_account_id) references public.accounts(id);
alter table public.connection_invites
    add constraint connection_invites_accepted_by_account_id_fkey foreign key (accepted_by_account_id) references public.accounts(id);

-- Two composite unique keys on threads — the dual-axis composite-FK trick
-- (Story 7.1 Dev Notes, "The dual-axis composite-FK trick, spelled out").
-- Each is trivially satisfied on its own (id is already the primary key);
-- their sole purpose is being an FK target for thread_participants/messages
-- below, so a child row's axis is checked against the SAME axis on its
-- parent thread.
alter table public.threads
    add constraint threads_account_id_id_key unique (account_id, id);
alter table public.threads
    add constraint threads_connection_id_id_key unique (connection_id, id);
alter table public.threads
    add constraint threads_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.threads
    add constraint threads_connection_id_fkey foreign key (connection_id) references public.connections(id) on delete cascade;
alter table public.threads
    add constraint threads_created_by_member_id_fkey foreign key (created_by_member_id) references public.account_members(id) on delete set null;

-- thread_participants/messages each carry BOTH composite FKs to threads.
-- Postgres's default MATCH SIMPLE skips a multi-column FK check when ANY
-- referencing column is null, so exactly one of the two constraints does
-- real work per row (the account-scoped one when connection_id is null,
-- the connection-scoped one when account_id is null) — both must exist for
-- "exactly one axis is real" to be enforced by the database rather than
-- merely assumed. This is the first dual-axis child pair in the schema.
alter table public.thread_participants
    add constraint thread_participants_thread_account_fkey
    foreign key (account_id, thread_id) references public.threads(account_id, id) on delete cascade;
alter table public.thread_participants
    add constraint thread_participants_thread_connection_fkey
    foreign key (connection_id, thread_id) references public.threads(connection_id, id) on delete cascade;
-- A join row has no meaning without its member — cascade, not set null,
-- unlike shidduchim_owner_member_id_fkey and friends above.
alter table public.thread_participants
    add constraint thread_participants_member_id_fkey foreign key (member_id) references public.account_members(id) on delete cascade;
alter table public.thread_participants
    add constraint thread_participants_thread_id_member_id_key unique (thread_id, member_id);

alter table public.messages
    add constraint messages_thread_account_fkey
    foreign key (account_id, thread_id) references public.threads(account_id, id) on delete cascade;
alter table public.messages
    add constraint messages_thread_connection_fkey
    foreign key (connection_id, thread_id) references public.threads(connection_id, id) on delete cascade;
alter table public.messages
    add constraint messages_sender_member_id_fkey foreign key (sender_member_id) references public.account_members(id) on delete set null;

-- Story 7.5 (AC-8): the plain, single-column FK the story's AC-8 calls for —
-- no composite FK and no new unique key added to `messages` (see the table
-- comment above).
alter table public.message_notifications
    add constraint message_notifications_message_id_fkey foreign key (message_id) references public.messages(id) on delete cascade;
alter table public.message_notifications
    add constraint message_notifications_recipient_member_id_fkey foreign key (recipient_member_id) references public.account_members(id) on delete cascade;
alter table public.message_notifications
    add constraint message_notifications_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.message_notifications
    add constraint message_notifications_connection_id_fkey foreign key (connection_id) references public.connections(id) on delete cascade;
-- The fan-out trigger's `on conflict (message_id, recipient_member_id,
-- channel) do nothing` needs this to exist — it is what makes the trigger
-- idempotent under any future re-run or retry; the cost of not having it is
-- a duplicate email or push send.
alter table public.message_notifications
    add constraint message_notifications_dedupe_key unique (message_id, recipient_member_id, channel);

alter table public.push_subscriptions
    add constraint push_subscriptions_member_id_fkey foreign key (member_id) references public.account_members(id) on delete cascade;
alter table public.push_subscriptions
    add constraint push_subscriptions_member_id_endpoint_key unique (member_id, endpoint);

-- Story 9.1: `accounts` is not boilerplate here — a `shadchan` listing has
-- `single_id` null, so without this FK an AD-15 account deletion would
-- orphan a PUBLICLY READABLE row forever (the one table in the product
-- where an orphan is a standing privacy leak, not just dead data). The
-- composite `single_id` FK follows shidduchim_single_id_fkey's precedent
-- above, not inbox_items' FK-less pattern: unlike a capture row, a listing
-- never names a single that does not exist yet. MATCH SIMPLE means a
-- `shadchan` row's null single_id is trivially satisfied, while a `single`
-- row must name a single in the SAME account — closing the cross-tenant id
-- oracle the composite-FK comment block above warns about, and guaranteeing
-- AD-15's per-single purge takes any live listing down with its subject.
alter table public.listings
    add constraint listings_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.listings
    add constraint listings_single_id_fkey
    foreign key (account_id, single_id) references public.singles(account_id, id) on delete cascade;

-- Story 9.3: the composite FK follows the same domain standard as
-- listings_single_id_fkey just above — a purged single (AD-15) takes their
-- own lock with them, so a lock row can never outlive the single it
-- protects, and a lock can never be forged onto a single in a different
-- account.
alter table public.listing_withdrawal_locks
    add constraint listing_withdrawal_locks_single_id_fkey
    foreign key (account_id, single_id) references public.singles(account_id, id)
    on delete cascade;

-- Story 9.5: `accounts` is not boilerplate here — same reasoning as
-- `listings_account_id_fkey` above, restated for a table that holds live
-- bearer tokens rather than published content. The composite `single_id`
-- FK is the load-bearing half for AD-15: a per-single purge must take every
-- outstanding share link (and, via share_access_log's own FK below, its
-- access log) down with the single — otherwise a purged person's resume
-- stays downloadable through a live link, the exact outcome a data-subject
-- removal exists to prevent.
alter table public.share_links
    add constraint share_links_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.share_links
    add constraint share_links_single_id_fkey
    foreign key (account_id, single_id) references public.singles(account_id, id) on delete cascade;

--
-- Indexes on foreign keys (shidduchim domain)
--
create index account_members_account_id_idx on public.account_members using btree (account_id);
-- A duplicate active membership in the same account is a schema error, not a
-- silent ambiguity current_context_id() has to paper over with an ORDER BY.
-- user_id is nullable, so NULL-user_id rows are not constrained here — a row
-- with no user is not a membership anyone resolves through anyway.
create unique index account_members_account_user_active_uq on public.account_members (account_id, user_id) where status = 'active';
create index invites_account_id_idx on public.invites using btree (account_id);
create index singles_account_id_idx on public.singles using btree (account_id);
create index shadchanim_account_id_idx on public.shadchanim using btree (account_id);
create index references_account_id_idx on public."references" using btree (account_id);
create index shidduchim_account_id_idx on public.shidduchim using btree (account_id);
create index shidduchim_single_id_idx on public.shidduchim using btree (single_id);
create index shidduchim_shadchan_id_idx on public.shidduchim using btree (shadchan_id);
create index resumes_account_id_idx on public.resumes using btree (account_id);
-- Story 5.8: `resumes_shidduchim_id_key unique (shidduchim_id)` becomes two
-- partial unique indexes now that either column may be null — a plain
-- UNIQUE constraint treats every null as distinct (no protection), and a
-- table CHECK/UNIQUE constraint cannot carry a WHERE clause, so this is
-- deliberately a CREATE UNIQUE INDEX, not an ALTER TABLE ... ADD CONSTRAINT.
create unique index resumes_shidduchim_id_key on public.resumes (shidduchim_id) where shidduchim_id is not null;
create unique index resumes_single_id_key on public.resumes (single_id) where single_id is not null;
create index resume_photos_account_id_idx on public.resume_photos using btree (account_id);
create index medical_notes_account_id_idx on public.medical_notes using btree (account_id);
create index reference_links_account_id_idx on public.reference_links using btree (account_id);
create index reference_links_reference_id_idx on public.reference_links using btree (reference_id);
create index reference_links_shidduchim_id_idx on public.reference_links using btree (shidduchim_id);
create index date_records_account_id_idx on public.date_records using btree (account_id);
create index date_records_single_id_idx on public.date_records using btree (single_id);
create index redts_account_id_idx on public.redts using btree (account_id);
create index redts_shidduchim_id_idx on public.redts using btree (shidduchim_id);
create index shidduch_schools_account_id_idx on public.shidduch_schools using btree (account_id);
create index shidduch_schools_shidduchim_id_idx on public.shidduch_schools using btree (shidduchim_id);
create index shidduchim_external_links_account_id_idx on public.shidduchim_external_links using btree (account_id);
create index shidduchim_external_links_shidduchim_id_idx on public.shidduchim_external_links using btree (shidduchim_id);
create index interactions_account_id_idx on public.interactions using btree (account_id);
create index interactions_target_idx on public.interactions using btree (account_id, target_type, target_id, created_at desc);
create index interactions_reference_link_id_idx on public.interactions using btree (reference_link_id);
create index identity_signals_account_id_idx on public.identity_signals using btree (account_id);
create index identity_signals_phone_idx on public.identity_signals using btree (account_id, target_type, phone_norm);
create index identity_signals_name_en_key_idx on public.identity_signals using btree (account_id, target_type, name_en_key);
create index identity_signals_name_he_key_idx on public.identity_signals using btree (account_id, target_type, name_he_key);
create index tasks_account_id_idx on public.tasks using btree (account_id);
create index tasks_target_idx on public.tasks using btree (account_id, target_type, target_id);
-- `created_at desc` tail mirrors interactions_target_idx above: the Files
-- tab lists newest-first.
create index entity_files_account_id_idx on public.entity_files using btree (account_id);
create index entity_files_target_idx on public.entity_files using btree (account_id, target_type, target_id, created_at desc);
create index references_phone_norm_idx on public."references" using btree (account_id, phone_norm);
create index subscription_account_id_idx on public.subscription using btree (account_id);
create index ai_usage_account_id_idx on public.ai_usage using btree (account_id);
create index inbox_items_account_id_idx on public.inbox_items using btree (account_id);
create index inbox_items_status_idx on public.inbox_items using btree (account_id, status);
create index connections_household_account_id_idx on public.connections using btree (household_account_id);
create index connections_shadchanus_account_id_idx on public.connections using btree (shadchanus_account_id);
create index threads_account_id_idx on public.threads using btree (account_id);
create index threads_connection_id_idx on public.threads using btree (connection_id);
create index threads_subject_idx on public.threads using btree (subject_type, subject_id);
create index thread_participants_account_id_idx on public.thread_participants using btree (account_id);
create index thread_participants_connection_id_idx on public.thread_participants using btree (connection_id);
create index thread_participants_member_id_idx on public.thread_participants using btree (member_id);
create index messages_account_id_idx on public.messages using btree (account_id);
create index messages_connection_id_idx on public.messages using btree (connection_id);
create index messages_thread_id_idx on public.messages using btree (thread_id, created_at);
create index message_notifications_account_id_idx on public.message_notifications using btree (account_id);
create index message_notifications_connection_id_idx on public.message_notifications using btree (connection_id);
create index message_notifications_message_id_idx on public.message_notifications using btree (message_id);
create index message_notifications_recipient_member_id_idx on public.message_notifications using btree (recipient_member_id);
-- The claim query filters status = 'pending' ordered by created_at (AC-9).
create index message_notifications_pending_idx on public.message_notifications using btree (status, created_at);
create index push_subscriptions_member_id_idx on public.push_subscriptions using btree (member_id);

-- Story 9.1 (AC-3): the two partial unique indexes are what makes "exactly
-- one live listing per subject" real, for both branches, declared together
-- now even though only the `shadchan` one is exercised until 9.2 — a single
-- table where only one migration ever spoke for the invariant.
create index listings_account_id_idx on public.listings using btree (account_id);
create unique index listings_shadchan_account_id_key on public.listings (account_id)
    where listing_type = 'shadchan';
create unique index listings_single_id_key on public.listings (single_id)
    where listing_type = 'single';

-- Story 9.3: matches every other account_id-scoped table's own index — the
-- lock table's one RLS policy filters on account_id.
create index listing_withdrawal_locks_account_id_idx on public.listing_withdrawal_locks using btree (account_id);

-- Story 9.5: the manager-scoped RLS policy filters on account_id; the token
-- lookup (the Worker's ONLY unscoped read, before the account is known) is a
-- point lookup by token, so it gets its own unique index rather than riding
-- the account_id one.
create index share_links_account_id_idx on public.share_links using btree (account_id);
create unique index share_links_token_key on public.share_links (token);
create index share_access_log_share_link_id_idx on public.share_access_log using btree (share_link_id);
