--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";
create extension if not exists "pgjwt" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

-- Tasks/reminders. Originally contacts-only; widened in the References epic to
-- the AD-13 polymorphic shape (target_type/target_id) so a reminder can hang off
-- a shadchan, a shidduch or a reference without forking a parallel table.
-- `contact_id` is retained (now nullable) so the legacy contacts UI, which
-- filters on contact_id, keeps working unchanged; sync_task_target() keeps it in
-- lockstep with target_type/target_id. delivery_channels is in_app+email by
-- default — deliberately no SMS channel (FR44-46).
create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint,
    -- Column order here deliberately matches the order `supabase db diff` appends
    -- them (alphabetical), so the declared schema and a migrated database agree
    -- and `db diff` stays quiet.
    account_id bigint not null,
    delivery_channels text[] not null default array['in_app', 'email']::text[],
    target_id bigint not null,
    target_type text not null default 'contact',
    constraint tasks_target_type_check check (
        target_type in ('contact', 'shadchan', 'shidduch', 'reference')
    ),
    constraint tasks_delivery_channels_check check (
        delivery_channels <@ array['in_app', 'email', 'push']::text[]
    )
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);

--
-- =====================================================================
-- MyShadchan — Shidduchim pipeline domain (AD-1, AD-4, AD-12)
-- =====================================================================
-- The central object is a `shidduch` (plural `shidduchim`): a proposed
-- match/single a shadchan redts. Every row carries a non-null account_id
-- (tenant isolation, AD-1) and is RLS-scoped by account. Bilingual
-- identity fields store both scripts (`_en`/`_he`, AD-12).
--
-- Full RLS enforcement (FORCE + multi-account current_account_ids +
-- anon-grant revocation + invite binding) is Epic-1 and DEFERRED; this
-- build ships the account_id columns, account-scoped policies, and no
-- anon grants, so RLS can be hardened later WITHOUT a schema change.
--

-- The one canonical pipeline state (AD-4): exactly 7 values, decision
-- states (yes/unsure/no) reachable only from look_into. Gut
-- `for_sure_not` is deliberately distinct from post-investigation `no`.
-- There is NO separate decision_substate — everything is this enum (D4).
create type public.pipeline_state as enum (
    'new',
    'look_into',
    'not_sure',
    'for_sure_not',
    'yes',
    'unsure',
    'no'
);

-- Tenant root. Also carries billing state (AD-16) — billing columns are
-- schema-ready but unused in this build.
create table public.accounts (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null default 'My Account',
    transparency_level text not null default 'shared',
    data_region text,
    -- Billing (AD-16) — present for schema-readiness, wired in a later epic.
    stripe_customer_id text,
    subscription_status text,
    plan text,
    current_period_end timestamp with time zone,
    trial_end timestamp with time zone,
    -- Onboarding demo-data flag (Stage A). True while the account holds the
    -- seeded demo dataset; cleared by clear_demo. Drives the future demo banner.
    demo boolean not null default false
);

-- One membership+role model (AD-2). The `shadchan` role is reserved in
-- the check from day one but granted nothing in v1 RLS (deny posture).
-- Replaces the fork's `sales` concept for the shidduchim domain; `sales`
-- itself is left in place for the legacy CRM resources.
create table public.account_members (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    user_id uuid,
    role text not null default 'parent_admin',
    status text not null default 'active',
    invited_by bigint,
    constraint account_members_role_check check (
        role in ('parent_admin', 'helper', 'self_manager', 'shadchan')
    )
);

-- The "child"/single being suggested FOR (one isolated pipeline each).
create table public.children (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    first_name_en text,
    first_name_he text,
    last_name_en text,
    last_name_he text,
    gender text,
    dob date,
    community text,
    status text not null default 'active',
    member_id bigint
);

-- Matchmakers. "via {shadchan}" provenance lives here (FR18).
create table public.shadchanim (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    name text not null,
    name_he text,
    location text,
    contacts jsonb,
    notes text,
    responsiveness text
);

-- Reusable references — a first-class main entity. A reference is reusable
-- within an account and links across many shidduchim via reference_links.
-- The *_norm columns are the match keys feeding matchIdentity() (AD-5): they are
-- computed server-side by the ONE shared normalize function via the
-- set_reference_norms trigger, never client-supplied and never normalized in the
-- SPA. NOTE: `references` is a reserved SQL keyword, so the table name is always
-- double-quoted in raw SQL (public."references"). PostgREST exposes it as the
-- `references` resource; the frontend never sees the quoting.
create table public."references" (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    name_en text,
    name_he text,
    relationship text,
    phone text,
    school text,
    grad_year integer,
    -- Trigger-set match keys (AD-5/AD-12). Not user-editable.
    name_norm_en text,
    name_norm_he text,
    phone_norm text
);

-- The central object (AD-4). One child, one canonical pipeline_state.
-- Sole INSERT path = public.create_shidduch(); sole state writer =
-- public.transition_shidduch(). See 02_functions.sql.
create table public.shidduchim (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    child_id bigint not null,
    shadchan_id bigint,
    -- Single's identity (bilingual, AD-12)
    name_en text,
    name_he text,
    -- Name-bearing context fields, bilingual where they carry a name
    parents_en text,
    parents_he text,
    seminary_en text,
    seminary_he text,
    shul_en text,
    shul_he text,
    location_en text,
    location_he text,
    -- Informational only — NEVER matching signals (FR11)
    age integer,
    height text,
    -- The one canonical state (AD-4); NO decision_substate (D4)
    pipeline_state public.pipeline_state not null default 'new',
    -- Provenance (FR13): first shadchan to redt + when
    first_suggested_by bigint,
    first_suggested_at timestamp with time zone not null default now(),
    -- Board-visible "Redt {date}"
    redt_date date not null default current_date,
    -- Set when entering a terminal state
    close_reason text,
    -- 'channel' | 'manual' | 'shadchan' (shadchan reserved for Phase-2)
    origin text not null default 'manual',
    -- Visibility (AD-3) — columns locked NOW so the deferred child portal
    -- needs no breaking migration. owner_member_id is the visibility owner.
    owner_member_id bigint,
    visibility text not null default 'shared',
    -- Per-column ordering on the board (mirrors deals.index)
    index smallint not null default 0,
    constraint shidduchim_origin_check check (origin in ('channel', 'manual', 'shadchan')),
    constraint shidduchim_visibility_check check (
        visibility in ('shared', 'private_parent', 'private_child')
    )
);

-- 1:1 with a shidduch (resume detail is Epic-3; the table is shaped now).
create table public.resumes (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    shidduchim_id bigint not null,
    files jsonb,
    photos jsonb,
    extracted jsonb,
    sections jsonb
);

-- Join references <-> shidduchim/resumes. Carries candid diligence content
-- (call_status/what_they_said/conversation_log) that is child-invisible
-- (AD-3, F3): it has NO own visibility column — any future RLS derives
-- visibility by joining back to the parent shidduch, never independently.
-- `relationship_override` exists because one person genuinely wears different
-- hats per family — the same reference is "the shul rabbi" for one shidduch and
-- "a family friend" for another. Null means fall back to references.relationship.
create table public.reference_links (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    reference_id bigint not null,
    shidduchim_id bigint,
    resume_id bigint,
    call_status text,
    what_they_said text,
    conversation_log jsonb,
    relationship_override text,
    constraint reference_links_call_status_check check (
        call_status is null
        or call_status in ('not_started', 'answered', 'no_answer', 'call_back', 'they_will_call_back')
    )
);

-- Dating history (powers dedupe later, Epic-4). Person identity fields are
-- present for a future account-scoped matchIdentity(); no logic is built now.
create table public.date_records (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    child_id bigint,
    person_name_en text,
    person_name_he text,
    person_parents text,
    person_seminary text,
    person_location text,
    date_on date,
    outcome text,
    notes text
);

-- Redt history: a shidduch can be redt (proposed) many times, by the same
-- shadchan or different ones, on different dates (FR13 refinement). Each row is
-- one redt event. shidduchim.redt_date (= the LAST redt), shidduchim.shadchan_id
-- (= the latest redt's shadchan, the card "via"), and first_suggested_by/at
-- (= the earliest redt) are DERIVED from this table by the
-- refresh_shidduch_redt_summary() trigger — never hand-set as the source of truth.
create table public.redts (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    shidduchim_id bigint not null,
    shadchan_id bigint,
    redt_date date not null default current_date,
    note text
);

-- Education history: a single can have attended several institutions — a
-- seminary (girl) or yeshiva (boy), plus schools/college — each with optional
-- years. shidduchim.seminary_en/_he stays the card "headline"; this table holds
-- the full list. `kind` distinguishes seminary vs yeshiva vs school.
create table public.shidduch_schools (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    shidduchim_id bigint not null,
    kind text not null default 'seminary',
    name_en text,
    name_he text,
    start_year integer,
    end_year integer,
    constraint shidduch_schools_kind_check check (
        kind in ('seminary', 'yeshiva', 'school', 'college', 'other')
    )
);

-- Polymorphic interaction timeline (AD-13 target_type/target_id pattern, reused
-- rather than forked). ONE surface serves both "notes" and "timeline": a note is
-- kind='note'; the timeline is this table ordered by created_at.
--
-- AD-3/F3 visibility: this table has NO own visibility column. When an
-- interaction concerns a specific shidduch-scoped conversation it carries
-- reference_link_id, and RLS derives visibility by walking
-- reference_links -> shidduchim.visibility. Interactions with no shidduch context
-- (e.g. "updated phone number") are account-scoped only. `kind` is a closed
-- enumeration precisely so a coarse aggregate ("N of M references contacted",
-- FR68) can be computed WITHOUT reading candid row content.
create table public.interactions (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    target_type text not null,
    target_id bigint not null,
    -- Which parent this row derives its visibility from. NOT a visibility column
    -- (AD-3 forbids those): it stores no visibility decision, it declares which
    -- parent the answer is derived FROM, and the constraint below makes the two
    -- cases total and mutually exclusive.
    --
    --   'shidduch' -> reference_link_id is required; visibility derives by
    --                 joining reference_links -> shidduchim.
    --   'account'  -> no shidduch parent exists, so there is no shidduch whose
    --                 visibility could ever make this row child-visible. The
    --                 future child policy denies this bucket wholesale.
    --
    -- Without this discriminator a row with a null reference_link_id silently
    -- fell through BOTH branches, which is how a free-text note would have
    -- leaked to a candidate regardless of the parent's pipeline state.
    scope text not null default 'account',
    reference_link_id bigint,
    actor_member_id bigint,
    kind text not null default 'note',
    body text,
    metadata jsonb,
    constraint interactions_target_type_check check (
        target_type in ('reference', 'shidduch')
    ),
    constraint interactions_kind_check check (
        kind in ('note', 'call_logged', 'status_change', 'merge', 'link_created', 'link_removed')
    ),
    constraint interactions_scope_check check (scope in ('shidduch', 'account')),
    -- The structural half of AD-3, enumerated exhaustively. scope = 'shidduch'
    -- means "visibility derives from a parent shidduch", and which shidduch
    -- depends on what the row is about:
    --   target_type = 'reference' -> via reference_link_id -> the link's shidduch
    --   target_type = 'shidduch'  -> target_id IS the shidduch, so no link
    -- scope = 'account' means there is no shidduch parent at all, and is only
    -- legal for reference-targeted rows: an interaction ABOUT a shidduch always
    -- has that shidduch as its parent, so it can never be account-scoped.
    constraint interactions_scope_link_check check (
        (scope = 'shidduch' and target_type = 'reference' and reference_link_id is not null)
        or (scope = 'shidduch' and target_type = 'shidduch' and reference_link_id is null)
        or (scope = 'account' and target_type = 'reference' and reference_link_id is null)
    )
);

-- The account-scoped identity match store (AD-5). ONE row per matchable entity,
-- written only by the shared normalize trigger — never by the client. Signals are
-- name(_en/_he) + parents + seminary/yeshiva + shul + location + phone;
-- deliberately NOT age/height (FR11). matchIdentity() reads only this table, so
-- reference dedupe, shidduch-suggestion dedupe and date-record dedupe share one
-- implementation instead of three bespoke matchers.
create table public.identity_signals (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    target_type text not null,
    target_id bigint not null,
    name_en_norm text,
    name_he_norm text,
    -- Variant-folded consonant skeletons: what makes Hebrew/English
    -- transliteration variants (Chaim/Haim, Yitzchak/Itzhak) compare equal.
    name_en_key text,
    name_he_key text,
    phone_norm text,
    parents_norm text,
    seminary_norm text,
    shul_norm text,
    location_norm text,
    constraint identity_signals_target_type_check check (
        target_type in ('reference', 'shidduch', 'date_record')
    )
);

-- Transitions-as-data (AD-4, invariant 2): the legal pipeline_state edges,
-- enforced by public.transition_shidduch() and the enforce_pipeline_transition
-- trigger — never scattered ifs. Rows are seeded by the migration.
create table public.pipeline_transitions (
    from_state public.pipeline_state not null,
    to_state public.pipeline_state not null,
    constraint pipeline_transitions_pkey primary key (from_state, to_state)
);

-- Billing + AI entitlement (E4). AI (research assistant, future resume
-- auto-parse) is the ONLY paid surface; everything else stays free forever.
--
-- One subscription row per account. The DEFAULT posture is UNENTITLED: no row,
-- or a row that is not exactly (plan='ai', status='active'), locks the AI
-- features. The client may only SELECT this table (05_policies.sql /
-- 06_grants.sql) — there is deliberately NO client-callable path that flips
-- `plan` to 'ai' or `status` to 'active', because that would be exactly the
-- billing bypass the old client-side entitlement placeholder warned about.
-- Every write is service_role (payment webhook / admin), which bypasses RLS.
create table public.subscription (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    -- 'free' = the free-forever tier; 'ai' = the paid AI tier ($2/mo · $24/yr).
    plan text not null default 'free',
    -- 'active' = entitled and paid; 'lapsed' = was paid, now expired (AI
    -- auto-fill pauses, the free manual path stays); 'none' = never subscribed.
    status text not null default 'none',
    current_period_end timestamp with time zone,
    constraint subscription_plan_check check (plan in ('free', 'ai')),
    constraint subscription_status_check check (status in ('active', 'lapsed', 'none'))
);

-- AI usage meter (E4). One row per account per calendar month. resumes_parsed
-- backs the calm "34 / 100 resumes" meter in Billing. It is incremented
-- server-side by the (future) AI edge functions under service_role, right after
-- they confirm entitlement via ai_entitlement(); the client only ever SELECTs.
create table public.ai_usage (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    -- Month key in 'YYYY-MM' form, e.g. '2026-07'.
    period text not null,
    resumes_parsed integer not null default 0,
    constraint ai_usage_resumes_parsed_nonneg check (resumes_parsed >= 0)
);

--
-- Foreign keys (shidduchim domain)
--
-- (account_id, id) uniqueness is what makes the composite foreign keys below
-- possible. Every FK that crosses between two tenant-owned tables carries
-- account_id, so a row can only ever reference a parent in its own account.
-- These are all ON DELETE CASCADE, which is what made the single-column version
-- dangerous: one tenant deleting their own child would have cascaded into
-- another tenant's shidduch. Without them a plain FK on shidduchim_id lets one tenant point a row
-- at another tenant's shidduch: no read leak, but it plants rows naming a
-- stranger's records and turns FK-violation-versus-success into a cross-tenant
-- id oracle. The composite FK makes crossing the boundary impossible rather
-- than merely unrewarding.
alter table public.children
    add constraint children_account_id_id_key unique (account_id, id);
alter table public."references"
    add constraint references_account_id_id_key unique (account_id, id);
alter table public.shidduchim
    add constraint shidduchim_account_id_id_key unique (account_id, id);
alter table public.resumes
    add constraint resumes_account_id_id_key unique (account_id, id);
alter table public.reference_links
    add constraint reference_links_account_id_id_key unique (account_id, id);

alter table public.account_members
    add constraint account_members_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.account_members
    add constraint account_members_invited_by_fkey foreign key (invited_by) references public.account_members(id) on delete set null;
alter table public.account_members
    add constraint account_members_user_id_fkey foreign key (user_id) references auth.users(id) on delete set null;

alter table public.children
    add constraint children_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.children
    add constraint children_member_id_fkey foreign key (member_id) references public.account_members(id) on delete set null;

alter table public.shadchanim
    add constraint shadchanim_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;

alter table public."references"
    add constraint references_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;

alter table public.shidduchim
    add constraint shidduchim_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.shidduchim
    add constraint shidduchim_child_id_fkey
    foreign key (account_id, child_id) references public.children(account_id, id) on delete cascade;
alter table public.shidduchim
    add constraint shidduchim_shadchan_id_fkey foreign key (shadchan_id) references public.shadchanim(id) on delete set null;
alter table public.shidduchim
    add constraint shidduchim_first_suggested_by_fkey foreign key (first_suggested_by) references public.shadchanim(id) on delete set null;
alter table public.shidduchim
    add constraint shidduchim_owner_member_id_fkey foreign key (owner_member_id) references public.account_members(id) on delete set null;

alter table public.resumes
    add constraint resumes_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.resumes
    add constraint resumes_shidduchim_id_fkey
    foreign key (account_id, shidduchim_id) references public.shidduchim(account_id, id) on delete cascade;
alter table public.resumes
    add constraint resumes_shidduchim_id_key unique (shidduchim_id);

alter table public.reference_links
    add constraint reference_links_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
-- Composite (account_id, ...) foreign keys: a link can only ever join records
-- inside its own account. MATCH SIMPLE means a null shidduchim_id/resume_id
-- still satisfies the constraint, which is correct — a link may legitimately
-- reference a resume but no shidduch.
alter table public.reference_links
    add constraint reference_links_reference_id_fkey
    foreign key (account_id, reference_id) references public."references"(account_id, id) on delete cascade;
alter table public.reference_links
    add constraint reference_links_shidduchim_id_fkey
    foreign key (account_id, shidduchim_id) references public.shidduchim(account_id, id) on delete cascade;
alter table public.reference_links
    add constraint reference_links_resume_id_fkey
    foreign key (account_id, resume_id) references public.resumes(account_id, id) on delete cascade;

alter table public.date_records
    add constraint date_records_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.date_records
    add constraint date_records_child_id_fkey
    foreign key (account_id, child_id) references public.children(account_id, id) on delete cascade;

alter table public.redts
    add constraint redts_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.redts
    add constraint redts_shidduchim_id_fkey
    foreign key (account_id, shidduchim_id) references public.shidduchim(account_id, id) on delete cascade;
alter table public.redts
    add constraint redts_shadchan_id_fkey foreign key (shadchan_id) references public.shadchanim(id) on delete set null;

alter table public.shidduch_schools
    add constraint shidduch_schools_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.shidduch_schools
    add constraint shidduch_schools_shidduchim_id_fkey
    foreign key (account_id, shidduchim_id) references public.shidduchim(account_id, id) on delete cascade;

-- interactions/identity_signals are polymorphic: target_id carries no FK (it can
-- point at several tables), so its integrity rests on the cleanup triggers in
-- 04_triggers.sql. reference_link_id is NOT polymorphic and is enforced properly.
alter table public.interactions
    add constraint interactions_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.interactions
    add constraint interactions_reference_link_id_fkey
    foreign key (account_id, reference_link_id) references public.reference_links(account_id, id) on delete cascade;
alter table public.interactions
    add constraint interactions_actor_member_id_fkey foreign key (actor_member_id) references public.account_members(id) on delete set null;

alter table public.identity_signals
    add constraint identity_signals_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.identity_signals
    add constraint identity_signals_target_key unique (account_id, target_type, target_id);

alter table public.tasks
    add constraint tasks_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;

-- Billing (E4). One subscription row per account (unique account_id) and one
-- usage row per (account, month). Both cascade with the account.
alter table public.subscription
    add constraint subscription_account_id_key unique (account_id);
alter table public.subscription
    add constraint subscription_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;

alter table public.ai_usage
    add constraint ai_usage_account_id_period_key unique (account_id, period);
alter table public.ai_usage
    add constraint ai_usage_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;

--
-- Indexes on foreign keys (shidduchim domain)
--
create index account_members_account_id_idx on public.account_members using btree (account_id);
create index children_account_id_idx on public.children using btree (account_id);
create index shadchanim_account_id_idx on public.shadchanim using btree (account_id);
create index references_account_id_idx on public."references" using btree (account_id);
create index shidduchim_account_id_idx on public.shidduchim using btree (account_id);
create index shidduchim_child_id_idx on public.shidduchim using btree (child_id);
create index shidduchim_shadchan_id_idx on public.shidduchim using btree (shadchan_id);
create index resumes_account_id_idx on public.resumes using btree (account_id);
create index reference_links_account_id_idx on public.reference_links using btree (account_id);
create index reference_links_reference_id_idx on public.reference_links using btree (reference_id);
create index reference_links_shidduchim_id_idx on public.reference_links using btree (shidduchim_id);
create index date_records_account_id_idx on public.date_records using btree (account_id);
create index date_records_child_id_idx on public.date_records using btree (child_id);
create index redts_account_id_idx on public.redts using btree (account_id);
create index redts_shidduchim_id_idx on public.redts using btree (shidduchim_id);
create index shidduch_schools_account_id_idx on public.shidduch_schools using btree (account_id);
create index shidduch_schools_shidduchim_id_idx on public.shidduch_schools using btree (shidduchim_id);
create index interactions_account_id_idx on public.interactions using btree (account_id);
create index interactions_target_idx on public.interactions using btree (account_id, target_type, target_id, created_at desc);
create index interactions_reference_link_id_idx on public.interactions using btree (reference_link_id);
create index identity_signals_account_id_idx on public.identity_signals using btree (account_id);
create index identity_signals_phone_idx on public.identity_signals using btree (account_id, target_type, phone_norm);
create index identity_signals_name_en_key_idx on public.identity_signals using btree (account_id, target_type, name_en_key);
create index identity_signals_name_he_key_idx on public.identity_signals using btree (account_id, target_type, name_he_key);
create index tasks_account_id_idx on public.tasks using btree (account_id);
create index tasks_target_idx on public.tasks using btree (account_id, target_type, target_id);
create index references_phone_norm_idx on public."references" using btree (account_id, phone_norm);
create index subscription_account_id_idx on public.subscription using btree (account_id);
create index ai_usage_account_id_idx on public.ai_usage using btree (account_id);
