--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";
create extension if not exists "pgjwt" with schema "extensions";

-- Private schema (created by a historical RLS-cleanup migration; currently unused, kept to avoid a spurious drop)
create schema if not exists "private";

create table public.members (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__members__user_id on public.members using btree (user_id);

-- Tasks/reminders. Uses the AD-13 polymorphic shape (target_type/target_id) so a
-- reminder can hang off a shadchan, a shidduch or a reference without forking a
-- parallel table per entity. delivery_channels is in_app+email by default —
-- deliberately no SMS channel (FR44-46).
create table public.tasks (
    id bigint generated by default as identity primary key,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    member_id bigint,
    -- Column order here deliberately matches the order `supabase db diff` appends
    -- them (alphabetical), so the declared schema and a migrated database agree
    -- and `db diff` stays quiet.
    account_id bigint not null,
    delivery_channels text[] not null default array['in_app', 'email']::text[],
    target_id bigint not null,
    target_type text not null default 'shidduch',
    constraint tasks_target_type_check check (
        target_type in ('shadchan', 'shidduch', 'reference')
    ),
    constraint tasks_delivery_channels_check check (
        delivery_channels <@ array['in_app', 'email', 'push']::text[]
    )
);

-- tasks.member_id points at public.members (the user/profile table) — NOT at
-- public.account_members like singles.member_id / shidduchim.owner_member_id /
-- interactions.actor_member_id do. The two `member_id` names collide on
-- purpose-free vocabulary but not on referent; resolving the collision is
-- Epic 2 (AD-19), not this story.
comment on column public.tasks.member_id is 'FK-less reference to public.members(id) — the assignee/reminder-owner user. NOT public.account_members, unlike other *_member_id columns in this schema.';

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

--
-- Foreign keys
--

alter table public.members
    add constraint members_user_id_fkey foreign key (user_id) references auth.users(id);

--
-- =====================================================================
-- MyShadchan — Shidduchim pipeline domain (AD-1, AD-4, AD-12)
-- =====================================================================
-- The central object is a `shidduch` (plural `shidduchim`): a proposed
-- match/single a shadchan redts. Every row carries a non-null account_id
-- (tenant isolation, AD-1) and is RLS-scoped by account. Bilingual
-- identity fields store both scripts (`_en`/`_he`, AD-12).
--
-- Account-scoping now resolves through current_context_id() and the
-- server-held member_state.active_account_id (Story 2.1, AD-19) rather than
-- an arbitrary first membership. anon-grant revocation and invite binding
-- landed alongside it; FORCE ROW LEVEL SECURITY remains a flagged gap with
-- no assigned story (see 2.1's Dev Notes).
--

-- The one canonical pipeline state (AD-4): exactly 7 values, decision
-- states (yes/unsure/no) reachable only from look_into. Gut
-- `for_sure_not` is deliberately distinct from post-investigation `no`.
-- There is NO separate decision_substate — everything is this enum (D4).
create type public.pipeline_state as enum (
    'new',
    'look_into',
    'not_sure',
    'for_sure_not',
    'yes',
    'unsure',
    'no'
);

-- Tenant root. Also carries billing state (AD-16) — billing columns are
-- schema-ready but unused in this build.
create table public.accounts (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null default 'My Account',
    transparency_level text not null default 'shared',
    data_region text,
    -- Billing (AD-16) — legacy schema-readiness columns, UNUSED. They MUST
    -- NEVER feed an entitlement decision: the sole entitlement authority is the
    -- `subscription` table via public.ai_entitlement(). They look identical to
    -- the real thing, so client writes to them are revoked in 06_grants.sql
    -- (a mislabeled `accounts.plan = 'ai'` would be an instant paywall bypass
    -- the day any code read it).
    stripe_customer_id text,
    subscription_status text,
    plan text,
    current_period_end timestamp with time zone,
    trial_end timestamp with time zone,
    -- Onboarding demo-data flag (Stage A). True while the account holds the
    -- seeded demo dataset; cleared by clear_demo. Drives the future demo banner.
    demo boolean not null default false,
    -- Story 2.2 (AC-1, AD-2): a context is typed household or shadchanus.
    -- Every account created before this column existed becomes 'household'
    -- (correct — no shadchanus context exists in this codebase before this
    -- story's own add_persona() provisions the first one). enforce_household_scope()
    -- (02_functions.sql) is what makes the household/shadchanus split more than
    -- a label: a shadchanus-kind account can never hold a household domain row.
    kind text not null default 'household',
    constraint accounts_kind_check check (kind in ('household', 'shadchanus'))
);

-- One membership+role model (AD-2). The `shadchan` role is reserved in
-- the check from day one but granted nothing in v1 RLS (deny posture).
-- Distinct from public.members (the user/profile table): account_members
-- carries per-account role and status, members carries the login's own
-- profile fields.
create table public.account_members (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    user_id uuid,
    role text not null default 'parent_admin',
    status text not null default 'active',
    invited_by bigint,
    -- Story 2.2 (AC-2): `single` — "a single with their own login"
    -- (personas-and-contexts.md shape 5) — joins the five-role vocabulary
    -- AD-2 specifies. enforce_membership_role_matches_context() (AC-5) further
    -- restricts `shadchan` to shadchanus-kind accounts and every other role,
    -- including this one, to household-kind accounts.
    constraint account_members_role_check check (
        role in ('parent_admin', 'single', 'helper', 'self_manager', 'shadchan')
    ),
    -- Story 2.5 (AC-6): 'archived' is the one lifecycle transition
    -- remove_persona() ever writes to this column — never a delete. Safe to
    -- add now: the only literal comparison anywhere in the schema is
    -- current_context_id()'s `and am.status = 'active'`, and every existing
    -- write site already writes 'active'.
    constraint account_members_status_check check (
        status in ('active', 'archived')
    )
);

-- The server-held active-context pointer (AD-19). One row per user;
-- active_account_id NULL means "no active context" — the fail-closed case
-- current_context_id() relies on. Written by exactly one code path:
-- activate_context_for(), the private SECURITY DEFINER helper shared by
-- set_active_context() and the activate_first_context trigger — never by a
-- raw client write (05_policies.sql grants authenticated no insert/update/
-- delete policy on this table at all).
create table public.member_state (
    user_id uuid not null primary key,
    active_account_id bigint,
    updated_at timestamp with time zone not null default now()
);

-- Story 2.7 (AC-1, FR119): the one table every invite -- genesis or
-- otherwise -- lives in. Every write goes through create_invite() (AC-3,
-- sets invited_by from the caller's own membership), revoke_invite()
-- (Story 2.8), handle_new_user()'s binding step (a definer trigger), or a
-- service_role genesis seed (invited_by null, the platform-ops runbook
-- action that gets the very first household its very first member) -- there
-- is no insert/update policy for authenticated at all (05_policies.sql), so
-- those checks are the entire write gate. `self_manager` is deliberately
-- excluded from the role check: it is a role a person ARRIVES at
-- (add_persona('single') finding no existing household), never one a second
-- person is invited into (see create_invite()'s comment, 02_functions.sql).
create table public.invites (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    token uuid not null default gen_random_uuid() unique,
    email text not null,
    account_id bigint not null,
    role text not null,
    invited_by bigint,
    status text not null default 'pending',
    expires_at timestamp with time zone not null default (now() + interval '14 days'),
    accepted_at timestamp with time zone,
    constraint invites_role_check check (
        role in ('parent_admin', 'helper', 'single', 'shadchan')
    ),
    constraint invites_status_check check (
        status in ('pending', 'accepted', 'revoked', 'expired')
    )
);

-- The single being suggested FOR (one isolated pipeline each).
create table public.singles (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    first_name_en text,
    first_name_he text,
    last_name_en text,
    last_name_he text,
    gender text,
    dob date,
    community text,
    status text not null default 'active',
    member_id bigint
);

-- Matchmakers. "via {shadchan}" provenance lives here (FR18).
create table public.shadchanim (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    name text not null,
    name_he text,
    location text,
    contacts jsonb,
    notes text,
    responsiveness text
);

-- Reusable references — a first-class main entity. A reference is reusable
-- within an account and links across many shidduchim via reference_links.
-- The *_norm columns are the match keys feeding matchIdentity() (AD-5): they are
-- computed server-side by the ONE shared normalize function via the
-- set_reference_norms trigger, never client-supplied and never normalized in the
-- SPA. NOTE: `references` is a reserved SQL keyword, so the table name is always
-- double-quoted in raw SQL (public."references"). PostgREST exposes it as the
-- `references` resource; the frontend never sees the quoting.
create table public."references" (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    name_en text,
    name_he text,
    relationship text,
    phone text,
    school text,
    grad_year integer,
    -- Trigger-set match keys (AD-5/AD-12). Not user-editable.
    name_norm_en text,
    name_norm_he text,
    phone_norm text
);

-- The central object (AD-4). One single, one canonical pipeline_state.
-- Sole INSERT path = public.create_shidduch(); sole state writer =
-- public.transition_shidduch(). See 02_functions.sql.
create table public.shidduchim (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    single_id bigint not null,
    shadchan_id bigint,
    -- Single's identity (bilingual, AD-12)
    name_en text,
    name_he text,
    -- Name-bearing context fields, bilingual where they carry a name
    parents_en text,
    parents_he text,
    seminary_en text,
    seminary_he text,
    shul_en text,
    shul_he text,
    location_en text,
    location_he text,
    -- Informational only — NEVER matching signals (FR11)
    age integer,
    height text,
    -- The one canonical state (AD-4); NO decision_substate (D4)
    pipeline_state public.pipeline_state not null default 'new',
    -- Provenance (FR13): first shadchan to redt + when
    first_suggested_by bigint,
    first_suggested_at timestamp with time zone not null default now(),
    -- Board-visible "Redt {date}"
    redt_date date not null default current_date,
    -- Set when entering a terminal state
    close_reason text,
    -- 'channel' | 'manual' | 'shadchan' (shadchan reserved for Phase-2)
    origin text not null default 'manual',
    -- Visibility (AD-3) — columns locked NOW so Epic 6's single login needs
    -- no breaking migration. owner_member_id is the visibility owner.
    owner_member_id bigint,
    visibility text not null default 'shared',
    -- Per-column ordering on the board.
    index smallint not null default 0,
    constraint shidduchim_origin_check check (origin in ('channel', 'manual', 'shadchan')),
    constraint shidduchim_visibility_check check (
        visibility in ('shared', 'private_parent', 'private_single')
    )
);

-- 1:1 with a shidduch (resume detail is Epic-3; the table is shaped now).
create table public.resumes (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    shidduchim_id bigint not null,
    files jsonb,
    photos jsonb,
    extracted jsonb,
    sections jsonb
);

-- The capture inbox (Epic 2 "front door"). Un-triaged items that arrived by
-- PWA share, inbound email, or manual upload and need ONE calm confirmation
-- step (which single, which shadchan) before becoming a shidduch. Distinct from
-- `resumes`, which is a resume already attached to a resolved shidduch.
-- account_id is auto-set by set_account_id_default (AD-1); the inbound-email
-- webhook writes as service_role. Captured `raw_text`/`attachments` are stored
-- verbatim and never auto-parsed at the DB layer (parsing is a gated follow-up).
create table public.inbox_items (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    source text not null default 'upload',
    raw_text text,
    subject text,
    sender text,
    attachments jsonb,
    status text not null default 'unresolved',
    single_id bigint,
    shadchan_id bigint,
    resolved_shidduchim_id bigint,
    constraint inbox_items_source_check check (source in ('whatsapp', 'sms', 'email', 'photo', 'upload')),
    constraint inbox_items_status_check check (status in ('unresolved', 'resolved', 'dismissed'))
);

-- Join references <-> shidduchim/resumes. Carries candid diligence content
-- (call_status/what_they_said/conversation_log) that is single-invisible
-- (AD-3, F3): it has NO own visibility column — any future RLS derives
-- visibility by joining back to the parent shidduch, never independently.
-- `relationship_override` exists because one person genuinely wears different
-- hats per family — the same reference is "the shul rabbi" for one shidduch and
-- "a family friend" for another. Null means fall back to references.relationship.
create table public.reference_links (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    reference_id bigint not null,
    shidduchim_id bigint,
    resume_id bigint,
    call_status text,
    what_they_said text,
    conversation_log jsonb,
    relationship_override text,
    constraint reference_links_call_status_check check (
        call_status is null
        or call_status in ('not_started', 'answered', 'no_answer', 'call_back', 'they_will_call_back')
    )
);

-- Dating history (powers dedupe later, Epic-4). Person identity fields are
-- present for a future account-scoped matchIdentity(); no logic is built now.
create table public.date_records (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    single_id bigint,
    person_name_en text,
    person_name_he text,
    person_parents text,
    person_seminary text,
    person_location text,
    date_on date,
    outcome text,
    notes text
);

-- Redt history: a shidduch can be redt (proposed) many times, by the same
-- shadchan or different ones, on different dates (FR13 refinement). Each row is
-- one redt event. shidduchim.redt_date (= the LAST redt), shidduchim.shadchan_id
-- (= the latest redt's shadchan, the card "via"), and first_suggested_by/at
-- (= the earliest redt) are DERIVED from this table by the
-- refresh_shidduch_redt_summary() trigger — never hand-set as the source of truth.
create table public.redts (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    shidduchim_id bigint not null,
    shadchan_id bigint,
    redt_date date not null default current_date,
    note text
);

-- Education history: a single can have attended several institutions — a
-- seminary (girl) or yeshiva (boy), plus schools/college — each with optional
-- years. shidduchim.seminary_en/_he stays the card "headline"; this table holds
-- the full list. `kind` distinguishes seminary vs yeshiva vs school.
create table public.shidduch_schools (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    shidduchim_id bigint not null,
    kind text not null default 'seminary',
    name_en text,
    name_he text,
    start_year integer,
    end_year integer,
    constraint shidduch_schools_kind_check check (
        kind in ('seminary', 'yeshiva', 'school', 'college', 'other')
    )
);

-- Polymorphic interaction timeline (AD-13 target_type/target_id pattern, reused
-- rather than forked). ONE surface serves both "notes" and "timeline": a note is
-- kind='note'; the timeline is this table ordered by created_at.
--
-- AD-3/F3 visibility: this table has NO own visibility column. When an
-- interaction concerns a specific shidduch-scoped conversation it carries
-- reference_link_id, and RLS derives visibility by walking
-- reference_links -> shidduchim.visibility. Interactions with no shidduch context
-- (e.g. "updated phone number") are account-scoped only. `kind` is a closed
-- enumeration precisely so a coarse aggregate ("N of M references contacted",
-- FR68) can be computed WITHOUT reading candid row content.
create table public.interactions (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    target_type text not null,
    target_id bigint not null,
    -- Which parent this row derives its visibility from. NOT a visibility column
    -- (AD-3 forbids those): it stores no visibility decision, it declares which
    -- parent the answer is derived FROM, and the constraint below makes the two
    -- cases total and mutually exclusive.
    --
    --   'shidduch' -> reference_link_id is required; visibility derives by
    --                 joining reference_links -> shidduchim.
    --   'account'  -> no shidduch parent exists, so there is no shidduch whose
    --                 visibility could ever make this row single-visible. The
    --                 future single policy denies this bucket wholesale.
    --
    -- Without this discriminator a row with a null reference_link_id silently
    -- fell through BOTH branches, which is how a free-text note would have
    -- leaked to a candidate regardless of the parent's pipeline state.
    scope text not null default 'account',
    reference_link_id bigint,
    actor_member_id bigint,
    kind text not null default 'note',
    body text,
    metadata jsonb,
    constraint interactions_target_type_check check (
        target_type in ('reference', 'shidduch')
    ),
    constraint interactions_kind_check check (
        kind in ('note', 'call_logged', 'status_change', 'merge', 'link_created', 'link_removed')
    ),
    constraint interactions_scope_check check (scope in ('shidduch', 'account')),
    -- The structural half of AD-3, enumerated exhaustively. scope = 'shidduch'
    -- means "visibility derives from a parent shidduch", and which shidduch
    -- depends on what the row is about:
    --   target_type = 'reference' -> via reference_link_id -> the link's shidduch
    --   target_type = 'shidduch'  -> target_id IS the shidduch, so no link
    -- scope = 'account' means there is no shidduch parent at all, and is only
    -- legal for reference-targeted rows: an interaction ABOUT a shidduch always
    -- has that shidduch as its parent, so it can never be account-scoped.
    constraint interactions_scope_link_check check (
        (scope = 'shidduch' and target_type = 'reference' and reference_link_id is not null)
        or (scope = 'shidduch' and target_type = 'shidduch' and reference_link_id is null)
        or (scope = 'account' and target_type = 'reference' and reference_link_id is null)
    )
);

-- The account-scoped identity match store (AD-5). ONE row per matchable entity,
-- written only by the shared normalize trigger — never by the client. Signals are
-- name(_en/_he) + parents + seminary/yeshiva + shul + location + phone;
-- deliberately NOT age/height (FR11). matchIdentity() reads only this table, so
-- reference dedupe, shidduch-suggestion dedupe and date-record dedupe share one
-- implementation instead of three bespoke matchers.
create table public.identity_signals (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    target_type text not null,
    target_id bigint not null,
    name_en_norm text,
    name_he_norm text,
    -- Variant-folded consonant skeletons: what makes Hebrew/English
    -- transliteration variants (Chaim/Haim, Yitzchak/Itzhak) compare equal.
    name_en_key text,
    name_he_key text,
    phone_norm text,
    parents_norm text,
    seminary_norm text,
    shul_norm text,
    location_norm text,
    constraint identity_signals_target_type_check check (
        target_type in ('reference', 'shidduch', 'date_record')
    )
);

-- Transitions-as-data (AD-4, invariant 2): the legal pipeline_state edges,
-- enforced by public.transition_shidduch() and the enforce_pipeline_transition
-- trigger — never scattered ifs. Rows are seeded by the migration.
create table public.pipeline_transitions (
    from_state public.pipeline_state not null,
    to_state public.pipeline_state not null,
    constraint pipeline_transitions_pkey primary key (from_state, to_state)
);

-- Billing + AI entitlement (E4). AI (research assistant, future resume
-- auto-parse) is the ONLY paid surface; everything else stays free forever.
--
-- One subscription row per account. The DEFAULT posture is UNENTITLED: no row,
-- or a row that is not exactly (plan='ai', status='active'), locks the AI
-- features. The client may only SELECT this table (05_policies.sql /
-- 06_grants.sql) — there is deliberately NO client-callable path that flips
-- `plan` to 'ai' or `status` to 'active', because that would be exactly the
-- billing bypass the old client-side entitlement placeholder warned about.
-- Every write is service_role (payment webhook / admin), which bypasses RLS.
create table public.subscription (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    -- 'free' = the free-forever tier; 'ai' = the paid AI tier ($2/mo · $24/yr).
    plan text not null default 'free',
    -- 'active' = entitled and paid; 'lapsed' = was paid, now expired (AI
    -- auto-fill pauses, the free manual path stays); 'none' = never subscribed.
    status text not null default 'none',
    current_period_end timestamp with time zone,
    constraint subscription_plan_check check (plan in ('free', 'ai')),
    constraint subscription_status_check check (status in ('active', 'lapsed', 'none'))
);

-- AI usage meter (E4). One row per account per calendar month. resumes_parsed
-- backs the calm "34 / 100 resumes" meter in Billing. It is incremented
-- server-side by the (future) AI edge functions under service_role, right after
-- they confirm entitlement via ai_entitlement(); the client only ever SELECTs.
create table public.ai_usage (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    -- Month key in 'YYYY-MM' form, e.g. '2026-07'.
    period text not null,
    resumes_parsed integer not null default 0,
    constraint ai_usage_resumes_parsed_nonneg check (resumes_parsed >= 0)
);

-- Story 2.2 (AC-4): deliberately excluded from enforce_household_scope()'s 13
-- household-only tables. No source restricts a shadchanus context from
-- holding billing/entitlement rows; left scoped generically by
-- current_context_id() until a future story states a rule either way.
comment on table public.subscription is 'Deliberately excluded from enforce_household_scope() (Story 2.2 AC-4): no source restricts a shadchanus context from holding billing/entitlement rows; scoped generically by current_context_id() until a story states a rule.';
comment on table public.ai_usage is 'Deliberately excluded from enforce_household_scope() (Story 2.2 AC-4): same open question as public.subscription — no source restricts entitlement usage-metering to household contexts.';

--
-- Foreign keys (shidduchim domain)
--
-- (account_id, id) uniqueness is what makes the composite foreign keys below
-- possible. Every FK that crosses between two tenant-owned tables carries
-- account_id, so a row can only ever reference a parent in its own account.
-- These are all ON DELETE CASCADE, which is what made the single-column version
-- dangerous: one tenant deleting their own single would have cascaded into
-- another tenant's shidduch. Without them a plain FK on shidduchim_id lets one tenant point a row
-- at another tenant's shidduch: no read leak, but it plants rows naming a
-- stranger's records and turns FK-violation-versus-success into a cross-tenant
-- id oracle. The composite FK makes crossing the boundary impossible rather
-- than merely unrewarding.
alter table public.singles
    add constraint singles_account_id_id_key unique (account_id, id);
alter table public."references"
    add constraint references_account_id_id_key unique (account_id, id);
alter table public.shidduchim
    add constraint shidduchim_account_id_id_key unique (account_id, id);
alter table public.resumes
    add constraint resumes_account_id_id_key unique (account_id, id);
alter table public.reference_links
    add constraint reference_links_account_id_id_key unique (account_id, id);

alter table public.account_members
    add constraint account_members_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.account_members
    add constraint account_members_invited_by_fkey foreign key (invited_by) references public.account_members(id) on delete set null;
alter table public.account_members
    add constraint account_members_user_id_fkey foreign key (user_id) references auth.users(id) on delete set null;

alter table public.member_state
    add constraint member_state_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade;
alter table public.member_state
    add constraint member_state_active_account_id_fkey foreign key (active_account_id) references public.accounts(id) on delete set null;

alter table public.invites
    add constraint invites_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.invites
    add constraint invites_invited_by_fkey foreign key (invited_by) references public.account_members(id) on delete set null;

alter table public.singles
    add constraint singles_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.singles
    add constraint singles_member_id_fkey foreign key (member_id) references public.account_members(id) on delete set null;

alter table public.shadchanim
    add constraint shadchanim_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;

alter table public."references"
    add constraint references_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;

alter table public.shidduchim
    add constraint shidduchim_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.shidduchim
    add constraint shidduchim_single_id_fkey
    foreign key (account_id, single_id) references public.singles(account_id, id) on delete cascade;
alter table public.shidduchim
    add constraint shidduchim_shadchan_id_fkey foreign key (shadchan_id) references public.shadchanim(id) on delete set null;
alter table public.shidduchim
    add constraint shidduchim_first_suggested_by_fkey foreign key (first_suggested_by) references public.shadchanim(id) on delete set null;
alter table public.shidduchim
    add constraint shidduchim_owner_member_id_fkey foreign key (owner_member_id) references public.account_members(id) on delete set null;

alter table public.resumes
    add constraint resumes_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.resumes
    add constraint resumes_shidduchim_id_fkey
    foreign key (account_id, shidduchim_id) references public.shidduchim(account_id, id) on delete cascade;
alter table public.resumes
    add constraint resumes_shidduchim_id_key unique (shidduchim_id);

alter table public.reference_links
    add constraint reference_links_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
-- Composite (account_id, ...) foreign keys: a link can only ever join records
-- inside its own account. MATCH SIMPLE means a null shidduchim_id/resume_id
-- still satisfies the constraint, which is correct — a link may legitimately
-- reference a resume but no shidduch.
alter table public.reference_links
    add constraint reference_links_reference_id_fkey
    foreign key (account_id, reference_id) references public."references"(account_id, id) on delete cascade;
alter table public.reference_links
    add constraint reference_links_shidduchim_id_fkey
    foreign key (account_id, shidduchim_id) references public.shidduchim(account_id, id) on delete cascade;
alter table public.reference_links
    add constraint reference_links_resume_id_fkey
    foreign key (account_id, resume_id) references public.resumes(account_id, id) on delete cascade;

alter table public.date_records
    add constraint date_records_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.date_records
    add constraint date_records_single_id_fkey
    foreign key (account_id, single_id) references public.singles(account_id, id) on delete cascade;

alter table public.redts
    add constraint redts_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.redts
    add constraint redts_shidduchim_id_fkey
    foreign key (account_id, shidduchim_id) references public.shidduchim(account_id, id) on delete cascade;
alter table public.redts
    add constraint redts_shadchan_id_fkey foreign key (shadchan_id) references public.shadchanim(id) on delete set null;

alter table public.shidduch_schools
    add constraint shidduch_schools_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.shidduch_schools
    add constraint shidduch_schools_shidduchim_id_fkey
    foreign key (account_id, shidduchim_id) references public.shidduchim(account_id, id) on delete cascade;

-- interactions/identity_signals are polymorphic: target_id carries no FK (it can
-- point at several tables), so its integrity rests on the cleanup triggers in
-- 04_triggers.sql. reference_link_id is NOT polymorphic and is enforced properly.
alter table public.interactions
    add constraint interactions_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.interactions
    add constraint interactions_reference_link_id_fkey
    foreign key (account_id, reference_link_id) references public.reference_links(account_id, id) on delete cascade;
alter table public.interactions
    add constraint interactions_actor_member_id_fkey foreign key (actor_member_id) references public.account_members(id) on delete set null;

alter table public.identity_signals
    add constraint identity_signals_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.identity_signals
    add constraint identity_signals_target_key unique (account_id, target_type, target_id);

alter table public.tasks
    add constraint tasks_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;

-- Billing (E4). One subscription row per account (unique account_id) and one
-- usage row per (account, month). Both cascade with the account.
alter table public.subscription
    add constraint subscription_account_id_key unique (account_id);
alter table public.subscription
    add constraint subscription_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;

alter table public.ai_usage
    add constraint ai_usage_account_id_period_key unique (account_id, period);
alter table public.ai_usage
    add constraint ai_usage_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;

--
-- Indexes on foreign keys (shidduchim domain)
--
create index account_members_account_id_idx on public.account_members using btree (account_id);
-- A duplicate active membership in the same account is a schema error, not a
-- silent ambiguity current_context_id() has to paper over with an ORDER BY.
-- user_id is nullable, so NULL-user_id rows are not constrained here — a row
-- with no user is not a membership anyone resolves through anyway.
create unique index account_members_account_user_active_uq on public.account_members (account_id, user_id) where status = 'active';
create index invites_account_id_idx on public.invites using btree (account_id);
create index singles_account_id_idx on public.singles using btree (account_id);
create index shadchanim_account_id_idx on public.shadchanim using btree (account_id);
create index references_account_id_idx on public."references" using btree (account_id);
create index shidduchim_account_id_idx on public.shidduchim using btree (account_id);
create index shidduchim_single_id_idx on public.shidduchim using btree (single_id);
create index shidduchim_shadchan_id_idx on public.shidduchim using btree (shadchan_id);
create index resumes_account_id_idx on public.resumes using btree (account_id);
create index reference_links_account_id_idx on public.reference_links using btree (account_id);
create index reference_links_reference_id_idx on public.reference_links using btree (reference_id);
create index reference_links_shidduchim_id_idx on public.reference_links using btree (shidduchim_id);
create index date_records_account_id_idx on public.date_records using btree (account_id);
create index date_records_single_id_idx on public.date_records using btree (single_id);
create index redts_account_id_idx on public.redts using btree (account_id);
create index redts_shidduchim_id_idx on public.redts using btree (shidduchim_id);
create index shidduch_schools_account_id_idx on public.shidduch_schools using btree (account_id);
create index shidduch_schools_shidduchim_id_idx on public.shidduch_schools using btree (shidduchim_id);
create index interactions_account_id_idx on public.interactions using btree (account_id);
create index interactions_target_idx on public.interactions using btree (account_id, target_type, target_id, created_at desc);
create index interactions_reference_link_id_idx on public.interactions using btree (reference_link_id);
create index identity_signals_account_id_idx on public.identity_signals using btree (account_id);
create index identity_signals_phone_idx on public.identity_signals using btree (account_id, target_type, phone_norm);
create index identity_signals_name_en_key_idx on public.identity_signals using btree (account_id, target_type, name_en_key);
create index identity_signals_name_he_key_idx on public.identity_signals using btree (account_id, target_type, name_he_key);
create index tasks_account_id_idx on public.tasks using btree (account_id);
create index tasks_target_idx on public.tasks using btree (account_id, target_type, target_id);
create index references_phone_norm_idx on public."references" using btree (account_id, phone_norm);
create index subscription_account_id_idx on public.subscription using btree (account_id);
create index ai_usage_account_id_idx on public.ai_usage using btree (account_id);
create index inbox_items_account_id_idx on public.inbox_items using btree (account_id);
create index inbox_items_status_idx on public.inbox_items using btree (account_id, status);
