import { z } from "zod";
import type { Hono } from "hono";
import { createWorkerApp } from "../shared/createApp";
import { requireAiEntitlement } from "../shared/aiEntitlementGate";
import type { AiEntitlementVariables } from "../shared/aiEntitlementGate";
import { ok, fail } from "../shared/envelope";
import type { BaseEnv } from "../shared/env";
import type { ReferenceLinkSummary } from "../../src/components/atomic-crm/types";
import { buildCrossReferenceSummary } from "./dossierFacts";
import {
  claudeNarrator,
  deterministicNarrative,
  type DossierNarrator,
} from "./dossierNarrator";

export type AiEnv = BaseEnv & {
  AI_GATEWAY_ACCOUNT_ID: string;
  AI_GATEWAY_ID: string;
  ANTHROPIC_API_KEY: string;
};

type AiApp = Hono<{ Bindings: AiEnv; Variables: AiEntitlementVariables }>;

const DossierBodySchema = z.object({
  shidduchim_id: z.number(),
});

const NO_DATA_NARRATIVE = deterministicNarrative({
  spokenTo: [],
  outstanding: [],
  covered: [],
  gaps: [],
  endorsements: [],
  reservations: [],
  hasContradiction: false,
});

/**
 * Build the AI worker app. The optional `narrator` parameter lets tests inject a
 * fake; production uses `claudeNarrator(env)`.
 */
export function createAiApp(narrator?: DossierNarrator): AiApp {
  // E10/E11 (AI research assistant + diligence dossier) land here — AD-8
  // (Cloudflare AI Gateway only, assistive, never judges compatibility). Every
  // non-health route is gated by `requireAiEntitlement` (Story 11.1).
  const app = createWorkerApp<AiEnv>("ai") as unknown as AiApp;
  app.use("*", requireAiEntitlement);

  // 11.3: POST /dossier — per-suggestion cross-reference summary + grounded
  // narrative. Facts are computed from rows the caller-scoped client can see;
  // the narrative is generated by Claude through the Cloudflare AI Gateway with
  // a deterministic fallback.
  app.post("/dossier", async (c) => {
    const bodyResult = DossierBodySchema.safeParse(await c.req.json());
    if (!bodyResult.success) {
      return c.json(fail("invalid request body"), 400);
    }
    const { shidduchim_id } = bodyResult.data;

    const supabase = c.get("supabaseCaller");

    const { data: links, error } = await supabase
      .from("reference_links_summary")
      .select("*")
      .eq("shidduchim_id", shidduchim_id);

    if (error) {
      return c.json(fail("failed to read reference links"), 500);
    }

    if (!links || links.length === 0) {
      return c.json(
        ok({
          spokenToCount: 0,
          outstandingCount: 0,
          endorsementCount: 0,
          reservationCount: 0,
          covered: [],
          gaps: [],
          hasContradiction: false,
          narrative: NO_DATA_NARRATIVE,
        }),
        200,
      );
    }

    const facts = buildCrossReferenceSummary(
      links as unknown as ReferenceLinkSummary[],
    );

    const compose = narrator?.compose ?? claudeNarrator(c.env).compose;
    const narrative = await compose(facts);

    return c.json(
      ok({
        spokenToCount: facts.spokenTo.length,
        outstandingCount: facts.outstanding.length,
        endorsementCount: facts.endorsements.length,
        reservationCount: facts.reservations.length,
        covered: facts.covered.map((topic) => topic.label),
        gaps: facts.gaps.map((topic) => topic.label),
        hasContradiction: facts.hasContradiction,
        narrative,
      }),
      200,
    );
  });

  return app;
}

const app = createAiApp();
export default app;
