
  create table "public"."message_notifications" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "account_id" bigint,
    "connection_id" bigint,
    "message_id" bigint not null,
    "recipient_member_id" bigint not null,
    "channel" text not null,
    "status" text not null default 'pending'::text,
    "recipient_email" text,
    "attempts" integer not null default 0,
    "sent_at" timestamp with time zone,
    "error" text
      );


alter table "public"."message_notifications" enable row level security;

-- Hand-added: `db diff` does not re-emit FORCE ROW LEVEL SECURITY (same
-- class of gap as its known blind spot for view security_invoker/grants —
-- see 05_policies.sql's Story 7.5 comment on this table, which follows 7.1's
-- pg_roles.rolbypassrls-backed decision rather than re-deciding it).
alter table "public"."message_notifications" force row level security;


  create table "public"."push_subscriptions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "member_id" bigint not null,
    "endpoint" text not null,
    "p256dh" text not null,
    "auth" text not null
      );


alter table "public"."push_subscriptions" enable row level security;

-- Hand-added: see the message_notifications FORCE statement above.
alter table "public"."push_subscriptions" force row level security;

alter table "public"."thread_participants" add column "last_read_at" timestamp with time zone;

CREATE INDEX message_notifications_account_id_idx ON public.message_notifications USING btree (account_id);

CREATE INDEX message_notifications_connection_id_idx ON public.message_notifications USING btree (connection_id);

CREATE UNIQUE INDEX message_notifications_dedupe_key ON public.message_notifications USING btree (message_id, recipient_member_id, channel);

CREATE INDEX message_notifications_message_id_idx ON public.message_notifications USING btree (message_id);

CREATE INDEX message_notifications_pending_idx ON public.message_notifications USING btree (status, created_at);

CREATE UNIQUE INDEX message_notifications_pkey ON public.message_notifications USING btree (id);

CREATE INDEX message_notifications_recipient_member_id_idx ON public.message_notifications USING btree (recipient_member_id);

CREATE UNIQUE INDEX push_subscriptions_member_id_endpoint_key ON public.push_subscriptions USING btree (member_id, endpoint);

CREATE INDEX push_subscriptions_member_id_idx ON public.push_subscriptions USING btree (member_id);

CREATE UNIQUE INDEX push_subscriptions_pkey ON public.push_subscriptions USING btree (id);

alter table "public"."message_notifications" add constraint "message_notifications_pkey" PRIMARY KEY using index "message_notifications_pkey";

alter table "public"."push_subscriptions" add constraint "push_subscriptions_pkey" PRIMARY KEY using index "push_subscriptions_pkey";

alter table "public"."message_notifications" add constraint "message_notifications_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."message_notifications" validate constraint "message_notifications_account_id_fkey";

alter table "public"."message_notifications" add constraint "message_notifications_channel_check" CHECK ((channel = ANY (ARRAY['email'::text, 'push'::text]))) not valid;

alter table "public"."message_notifications" validate constraint "message_notifications_channel_check";

alter table "public"."message_notifications" add constraint "message_notifications_connection_id_fkey" FOREIGN KEY (connection_id) REFERENCES public.connections(id) ON DELETE CASCADE not valid;

alter table "public"."message_notifications" validate constraint "message_notifications_connection_id_fkey";

alter table "public"."message_notifications" add constraint "message_notifications_dedupe_key" UNIQUE using index "message_notifications_dedupe_key";

alter table "public"."message_notifications" add constraint "message_notifications_message_id_fkey" FOREIGN KEY (message_id) REFERENCES public.messages(id) ON DELETE CASCADE not valid;

alter table "public"."message_notifications" validate constraint "message_notifications_message_id_fkey";

alter table "public"."message_notifications" add constraint "message_notifications_recipient_member_id_fkey" FOREIGN KEY (recipient_member_id) REFERENCES public.account_members(id) ON DELETE CASCADE not valid;

alter table "public"."message_notifications" validate constraint "message_notifications_recipient_member_id_fkey";

alter table "public"."message_notifications" add constraint "message_notifications_scope_check" CHECK (((account_id IS NOT NULL) <> (connection_id IS NOT NULL))) not valid;

alter table "public"."message_notifications" validate constraint "message_notifications_scope_check";

alter table "public"."message_notifications" add constraint "message_notifications_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'sending'::text, 'sent'::text, 'failed'::text, 'skipped'::text]))) not valid;

alter table "public"."message_notifications" validate constraint "message_notifications_status_check";

alter table "public"."push_subscriptions" add constraint "push_subscriptions_member_id_endpoint_key" UNIQUE using index "push_subscriptions_member_id_endpoint_key";

alter table "public"."push_subscriptions" add constraint "push_subscriptions_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.account_members(id) ON DELETE CASCADE not valid;

alter table "public"."push_subscriptions" validate constraint "push_subscriptions_member_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.claim_message_notifications(p_limit integer)
 RETURNS TABLE(id bigint, channel text, recipient_member_id bigint, recipient_email text, thread_id bigint, message_body text, subject_type text, subject_id bigint)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  -- Every OUT column above (id, channel, ...) is an implicitly declared
  -- plpgsql variable in scope for the whole function body, so a BARE `id`
  -- inside the query below is ambiguous with the OUT parameter of the same
  -- name — table aliases on every reference (mn/mn2), not just on the final
  -- projection, are required here, not stylistic.
  return query
  with claimed as (
    update public.message_notifications mn
    set status = 'sending', attempts = attempts + 1
    where mn.id in (
      select mn2.id from public.message_notifications mn2
      where mn2.status = 'pending'
      order by mn2.created_at
      limit p_limit
      for update skip locked
    )
    returning mn.*
  )
  select
    claimed.id,
    claimed.channel,
    claimed.recipient_member_id,
    claimed.recipient_email,
    m.thread_id,
    m.body,
    t.subject_type,
    t.subject_id
  from claimed
  join public.messages m on m.id = claimed.message_id
  join public.threads t on t.id = m.thread_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.delete_push_subscription_by_endpoint(p_endpoint text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  delete from public.push_subscriptions where endpoint = p_endpoint;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.fan_out_message_notifications()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_participant record;
  v_user_id uuid;
  v_email text;
  v_disabled boolean;
begin
  for v_participant in
    select tp.member_id
    from public.thread_participants tp
    where tp.thread_id = new.thread_id
      and tp.member_id is distinct from new.sender_member_id
  loop
    select am.user_id into v_user_id
    from public.account_members am
    where am.id = v_participant.member_id;

    if v_user_id is null then
      insert into public.message_notifications (
        account_id, connection_id, message_id, recipient_member_id, channel, status, error
      )
      values (
        new.account_id, new.connection_id, new.id, v_participant.member_id, 'email', 'skipped',
        'recipient membership has no accepted login (account_members.user_id is null)'
      )
      on conflict (message_id, recipient_member_id, channel) do nothing;
    else
      select m.email::text, m.disabled into v_email, v_disabled
      from public.members m
      where m.user_id = v_user_id;

      if v_email is null or v_disabled then
        insert into public.message_notifications (
          account_id, connection_id, message_id, recipient_member_id, channel, status, error
        )
        values (
          new.account_id, new.connection_id, new.id, v_participant.member_id, 'email', 'failed',
          case
            when v_email is null then 'no public.members row for this login'
            else 'recipient member is disabled'
          end
        )
        on conflict (message_id, recipient_member_id, channel) do nothing;
      else
        insert into public.message_notifications (
          account_id, connection_id, message_id, recipient_member_id, channel, status, recipient_email
        )
        values (
          new.account_id, new.connection_id, new.id, v_participant.member_id, 'email', 'pending', v_email
        )
        on conflict (message_id, recipient_member_id, channel) do nothing;
      end if;
    end if;

    if exists (
      select 1 from public.push_subscriptions ps
      where ps.member_id = v_participant.member_id
    ) then
      insert into public.message_notifications (
        account_id, connection_id, message_id, recipient_member_id, channel, status
      )
      values (
        new.account_id, new.connection_id, new.id, v_participant.member_id, 'push', 'pending'
      )
      on conflict (message_id, recipient_member_id, channel) do nothing;
    end if;
  end loop;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.mark_thread_read(p_thread_id bigint)
 RETURNS public.thread_participants
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_participant public.thread_participants;
begin
  update public.thread_participants tp
  set last_read_at = now()
  where tp.member_id = public.current_member_id()
    and tp.thread_id = p_thread_id
  returning tp.* into v_participant;

  return v_participant;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.settle_message_notification(p_id bigint, p_status text, p_error text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if p_status not in ('sent', 'failed', 'skipped') then
    raise exception 'invalid message_notification status: %', p_status
      using errcode = 'invalid_parameter_value';
  end if;

  update public.message_notifications
  set status = p_status,
      error = p_error,
      sent_at = case when p_status = 'sent' then now() else sent_at end
  where id = p_id
    and status = 'sending';
end;
$function$
;

-- Hand-added: `db diff` under-emitted every one of these four function
-- grants entirely — a newly created function defaults to EXECUTE granted to
-- PUBLIC, and 06_grants.sql's revokes/grants against that default never
-- appeared in the plain generated diff (the same class of gap as the table
-- REVOKEs above, extended to functions). Without this block every one of
-- these four SECURITY DEFINER functions would still be callable by
-- `authenticated` through inherited PUBLIC execute — reproduced live: the
-- plain generated migration left `claim_message_notifications()` callable by
-- `authenticated`, which is exactly what AC-10 forbids.
revoke all on function public.mark_thread_read(bigint) from public, anon;
grant execute on function public.mark_thread_read(bigint) to authenticated;
grant execute on function public.mark_thread_read(bigint) to service_role;

revoke all on function public.claim_message_notifications(integer) from public, anon, authenticated;
grant execute on function public.claim_message_notifications(integer) to service_role;

revoke all on function public.settle_message_notification(bigint, text, text) from public, anon, authenticated;
grant execute on function public.settle_message_notification(bigint, text, text) to service_role;

revoke all on function public.delete_push_subscription_by_endpoint(text) from public, anon, authenticated;
grant execute on function public.delete_push_subscription_by_endpoint(text) to service_role;

-- Hand-added: `db diff` under-emits here exactly like its documented blind
-- spot for view security_invoker/grants — it emitted the explicit GRANTs
-- below but not the REVOKEs needed to strip the TRUNCATE/REFERENCES/TRIGGER
-- privilege Postgres's default privileges hand `authenticated` on every new
-- table `postgres` creates (06_grants.sql's own comment documents this fact;
-- a second `db diff` run after applying the plain generated file reproduced
-- these three lines as a live divergence, which is how this gap was found).
-- TRUNCATE bypasses RLS entirely — force or no force — so leaving it granted
-- on a queue AC-11 exists specifically to withhold from `authenticated`
-- reads is not a cosmetic gap.
revoke references on table "public"."message_notifications" from "authenticated";
revoke trigger on table "public"."message_notifications" from "authenticated";
revoke truncate on table "public"."message_notifications" from "authenticated";

grant delete on table "public"."message_notifications" to "service_role";

grant insert on table "public"."message_notifications" to "service_role";

grant references on table "public"."message_notifications" to "service_role";

grant select on table "public"."message_notifications" to "service_role";

grant trigger on table "public"."message_notifications" to "service_role";

grant truncate on table "public"."message_notifications" to "service_role";

grant update on table "public"."message_notifications" to "service_role";

-- Hand-added: see the message_notifications REVOKE block above — the same
-- default-privilege residue, on the same brand-new-table pattern.
revoke references on table "public"."push_subscriptions" from "authenticated";
revoke trigger on table "public"."push_subscriptions" from "authenticated";
revoke truncate on table "public"."push_subscriptions" from "authenticated";

grant delete on table "public"."push_subscriptions" to "authenticated";

grant insert on table "public"."push_subscriptions" to "authenticated";

grant select on table "public"."push_subscriptions" to "authenticated";

grant delete on table "public"."push_subscriptions" to "service_role";

grant insert on table "public"."push_subscriptions" to "service_role";

grant references on table "public"."push_subscriptions" to "service_role";

grant select on table "public"."push_subscriptions" to "service_role";

grant trigger on table "public"."push_subscriptions" to "service_role";

grant truncate on table "public"."push_subscriptions" to "service_role";

grant update on table "public"."push_subscriptions" to "service_role";


  create policy "Push subscriptions manageable by their own member"
  on "public"."push_subscriptions"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.account_members am
  WHERE ((am.id = push_subscriptions.member_id) AND (am.user_id = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM public.account_members am
  WHERE ((am.id = push_subscriptions.member_id) AND (am.user_id = auth.uid())))));


CREATE TRIGGER fan_out_message_notifications_trigger AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION public.fan_out_message_notifications();


