-- Epic 11 (inbound email capture): a private per-household inbound email
-- address on `accounts`, a new `trusted_senders` allowlist table, and a
-- `held` status on `inbox_items` for mail from a sender that is neither a
-- known member nor a trusted address. See supabase/schemas/01_tables.sql,
-- 02_functions.sql, 04_triggers.sql, 05_policies.sql, 06_grants.sql for the
-- declarative source.

-- MANUAL ADJUSTMENT (see AGENTS.md "the empty-table trap"): `db diff`
-- generated the column add and the kind-correspondence CHECK constraint back
-- to back, with no backfill in between. `accounts` already carries
-- production rows (2 accounts, both household-kind, per the pre-flight
-- brief), so validating that CHECK immediately would fail against any of
-- them — invisible locally only because `db reset` seeds against an empty
-- table. Added nullable with no default, backfilled for every existing
-- household-kind row, verified with a fail-closed assertion, and ONLY THEN
-- does the unique index and the CHECK constraint go on.
alter table "public"."accounts" add column "inbound_email_token" extensions.citext;

-- Backfill every existing household-kind account with a fresh CSPRNG token —
-- 6 bytes (48 bits) from pgcrypto, hex-encoded (12 hex chars) — the exact
-- call set_account_inbound_email_token_default() (02_functions.sql) uses for
-- every future row. Short on purpose: this address is displayed to and
-- typed by users, and entropy is not load-bearing here since mail from an
-- unrecognized sender is held for review regardless. shadchanus-kind
-- accounts are left NULL: they have no mailbox of their own.
update "public"."accounts"
set inbound_email_token = encode(extensions.gen_random_bytes(6), 'hex')
where kind = 'household' and inbound_email_token is null;

-- Fail closed rather than let a household row silently keep a NULL token: if
-- the backfill above missed any row, for any reason, abort the whole
-- migration before the unique index/CHECK constraint below ever run — a
-- wrong assumption about the data must stop the deploy, not produce a
-- household account with no inbound address.
do $$
declare
    v_missing bigint;
begin
    select count(*)
      into v_missing
      from public.accounts
     where kind = 'household' and inbound_email_token is null;

    if v_missing > 0 then
        raise exception
            'inbound_email_addresses: % household-kind account(s) still have no inbound_email_token after backfill; refusing to add the unique index/CHECK constraint',
            v_missing;
    end if;
end;
$$;

CREATE UNIQUE INDEX accounts_inbound_email_token_key ON public.accounts USING btree (inbound_email_token);

alter table "public"."accounts" add constraint "accounts_inbound_email_token_kind_check" CHECK (((kind = 'household'::text) = (inbound_email_token IS NOT NULL))) not valid;

alter table "public"."accounts" validate constraint "accounts_inbound_email_token_kind_check";

  create table "public"."trusted_senders" (
    "id" bigint generated by default as identity not null,
    "account_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "created_by_member_id" bigint,
    "email" extensions.citext not null
      );


alter table "public"."trusted_senders" enable row level security;

CREATE UNIQUE INDEX trusted_senders_account_id_email_key ON public.trusted_senders USING btree (account_id, email);

CREATE INDEX trusted_senders_account_id_idx ON public.trusted_senders USING btree (account_id);

CREATE UNIQUE INDEX trusted_senders_pkey ON public.trusted_senders USING btree (id);

alter table "public"."trusted_senders" add constraint "trusted_senders_pkey" PRIMARY KEY using index "trusted_senders_pkey";

alter table "public"."trusted_senders" add constraint "trusted_senders_account_id_email_key" UNIQUE using index "trusted_senders_account_id_email_key";

alter table "public"."trusted_senders" add constraint "trusted_senders_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."trusted_senders" validate constraint "trusted_senders_account_id_fkey";

alter table "public"."trusted_senders" add constraint "trusted_senders_created_by_member_id_fkey" FOREIGN KEY (created_by_member_id) REFERENCES public.account_members(id) ON DELETE SET NULL not valid;

alter table "public"."trusted_senders" validate constraint "trusted_senders_created_by_member_id_fkey";

alter table "public"."inbox_items" drop constraint "inbox_items_status_check";

alter table "public"."inbox_items" add constraint "inbox_items_status_check" CHECK ((status = ANY (ARRAY['unresolved'::text, 'resolving'::text, 'resolved'::text, 'dismissed'::text, 'held'::text]))) not valid;

alter table "public"."inbox_items" validate constraint "inbox_items_status_check";

set check_function_bodies = off;

-- Unconditional overwrite for a household-kind row (no `is null` guard) —
-- mirrors set_share_link_token_defaults()'s own `new.token` line exactly: a
-- client-supplied value is never honored for a bearer credential. Short
-- token (12 hex chars / 48 bits) on purpose — see 02_functions.sql for the
-- full rationale.
CREATE OR REPLACE FUNCTION public.set_account_inbound_email_token_default()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if new.kind = 'household' then
    new.inbound_email_token := encode(extensions.gen_random_bytes(6), 'hex');
  end if;
  return new;
end;
$function$
;

-- Hand-verified against 06_grants.sql (AGENTS.md / 20260803032639's own
-- precedent: `db diff` never re-emits grants correctly for a brand-new
-- table — it emitted verb-by-verb `authenticated`/`service_role` grants with
-- no `revoke` and no sequence privileges at all; replaced here with the
-- exact statements the schema file declares). `anon` never appears in any
-- grant on this table.
revoke all on table public.trusted_senders from anon, authenticated;
grant select, insert, update, delete on table public.trusted_senders to authenticated;
grant all on table public.trusted_senders to service_role;

revoke all on sequence public.trusted_senders_id_seq from anon;
grant usage, select on sequence public.trusted_senders_id_seq to authenticated;
grant all on sequence public.trusted_senders_id_seq to service_role;


  create policy "Trusted senders scoped to account"
  on "public"."trusted_senders"
  as permissive
  for all
  to authenticated
using (((account_id = public.current_context_id()) AND (public.current_member_role() <> 'single'::text)))
with check (((account_id = public.current_context_id()) AND (public.current_member_role() <> 'single'::text)));


CREATE TRIGGER set_account_inbound_email_token_default BEFORE INSERT ON public.accounts FOR EACH ROW EXECUTE FUNCTION public.set_account_inbound_email_token_default();

CREATE TRIGGER validate_trusted_senders_household_scope BEFORE INSERT OR UPDATE OF account_id ON public.trusted_senders FOR EACH ROW EXECUTE FUNCTION public.enforce_household_scope();
