-- Story 14.2: Deletion that deletes (PRV-2)
-- Track account deletion requests with cooling-off window

-- Create table to track deletion requests
create table public.account_deletion_requests (
    id bigint generated by default as identity primary key,
    account_id bigint not null references public.accounts(id) on delete cascade,
    requested_at timestamp with time zone not null default now(),
    expires_at timestamp with time zone not null,  -- requested_at + cooling-off period
    status text not null default 'pending',  -- pending, exported, deleted, cancelled
    export_completed boolean not null default false,
    export_data jsonb,  -- Optional: store export data if needed for audit
    requested_by_auth_uid uuid not null references auth.users(id),
    cancelled_at timestamp with time zone null,
    deleted_at timestamp with time zone null,
    constraint account_deletion_requests_status_check check (
        status in ('pending', 'exported', 'deleted', 'cancelled')
    )
);

-- Indexes for efficient querying
create index account_deletion_requests_account_id_idx on public.account_deletion_requests(account_id);
create index account_deletion_requests_status_idx on public.account_deletion_requests(status);
create index account_deletion_requests_expires_at_idx on public.account_deletion_requests(expires_at);
create index account_deletion_requests_requested_by_auth_uid_idx on public.account_deletion_requests(requested_by_auth_uid);

-- Enable RLS
alter table public.account_deletion_requests enable row level security;

-- Policies: Users can only see/delete their own requests
create policy "Users can view their own deletion requests"
    on public.account_deletion_requests
    for select
    to authenticated
    using (requested_by_auth_uid = auth.uid());

create policy "Users can insert their own deletion requests"
    on public.account_deletion_requests
    for insert
    to authenticated
    with check (requested_by_auth_uid = auth.uid());

create policy "Users can update their own deletion requests"
    on public.account_deletion_requests
    for update
    to authenticated
    using (requested_by_auth_uid = auth.uid())
    with check (requested_by_auth_uid = auth.uid());

create policy "Users can delete their own deletion requests"
    on public.account_deletion_requests
    for delete
    to authenticated
    using (requested_by_auth_uid = auth.uid());

-- Grants
grant select, insert, update, delete on table public.account_deletion_requests to authenticated;
grant select, insert, update, delete on table public.account_deletion_requests to service_role;