
-- The diff tool (migra) diffs schema, not data — `storage.buckets` is a data
-- table, so the bucket row this story's schema comment describes never
-- appears in the generated diff. Added by hand per the story's own
-- instruction (Task 1): verified empirically that migra omits it, so it is
-- not a duplicate of anything the diff already emits.
insert into storage.buckets (id, name, public)
values ('entity-files', 'entity-files', false)
on conflict (id) do nothing;

  create table "public"."entity_files" (
    "id" bigint generated by default as identity not null,
    "account_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "target_type" text not null,
    "target_id" bigint not null,
    "storage_path" text not null,
    "file_name" text not null,
    "mime_type" text not null,
    "size_bytes" bigint not null,
    "visibility" text not null default 'shared'::text,
    "uploaded_by_member_id" bigint
      );


alter table "public"."entity_files" enable row level security;

CREATE INDEX entity_files_account_id_idx ON public.entity_files USING btree (account_id);

CREATE UNIQUE INDEX entity_files_pkey ON public.entity_files USING btree (id);

CREATE INDEX entity_files_target_idx ON public.entity_files USING btree (account_id, target_type, target_id, created_at DESC);

alter table "public"."entity_files" add constraint "entity_files_pkey" PRIMARY KEY using index "entity_files_pkey";

alter table "public"."entity_files" add constraint "entity_files_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."entity_files" validate constraint "entity_files_account_id_fkey";

alter table "public"."entity_files" add constraint "entity_files_storage_path_scope_check" CHECK ((storage_path ~~ ((account_id)::text || '/%'::text))) not valid;

alter table "public"."entity_files" validate constraint "entity_files_storage_path_scope_check";

alter table "public"."entity_files" add constraint "entity_files_target_type_check" CHECK ((target_type = ANY (ARRAY['reference'::text, 'shidduch'::text, 'shadchan'::text, 'single'::text]))) not valid;

alter table "public"."entity_files" validate constraint "entity_files_target_type_check";

alter table "public"."entity_files" add constraint "entity_files_uploaded_by_member_id_fkey" FOREIGN KEY (uploaded_by_member_id) REFERENCES public.account_members(id) ON DELETE SET NULL not valid;

alter table "public"."entity_files" validate constraint "entity_files_uploaded_by_member_id_fkey";

alter table "public"."entity_files" add constraint "entity_files_visibility_check" CHECK ((visibility = ANY (ARRAY['shared'::text, 'private_parent'::text, 'private_single'::text]))) not valid;

alter table "public"."entity_files" validate constraint "entity_files_visibility_check";

alter table "public"."entity_files" add constraint "entity_files_visibility_target_check" CHECK (((visibility = 'shared'::text) OR (target_type = ANY (ARRAY['shidduch'::text, 'single'::text])))) not valid;

alter table "public"."entity_files" validate constraint "entity_files_visibility_target_check";

set check_function_bodies = off;

create or replace view "public"."entity_files_summary" as  SELECT ef.id,
    ef.account_id,
    ef.created_at,
    ef.target_type,
    ef.target_id,
    ef.storage_path,
    ef.file_name,
    ef.mime_type,
    ef.size_bytes,
    ef.visibility,
    ef.uploaded_by_member_id,
    NULLIF(btrim(((COALESCE(m.first_name, ''::text) || ' '::text) || COALESCE(m.last_name, ''::text))), ''::text) AS uploaded_by_name
   FROM ((public.entity_files ef
     LEFT JOIN public.account_members am ON ((am.id = ef.uploaded_by_member_id)))
     LEFT JOIN public.members m ON ((m.user_id = am.user_id)));


CREATE OR REPLACE FUNCTION public.set_entity_files_uploaded_by()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if new.uploaded_by_member_id is null then
    new.uploaded_by_member_id := public.current_member_id();
  end if;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.purge_polymorphic_dependents()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_target_type text := TG_ARGV[0];
begin
  delete from public.identity_signals
  where account_id = old.account_id and target_type = v_target_type and target_id = old.id;

  delete from public.interactions
  where account_id = old.account_id and target_type = v_target_type and target_id = old.id;

  delete from public.tasks
  where account_id = old.account_id and target_type = v_target_type and target_id = old.id;

  delete from public.entity_files
  where account_id = old.account_id and target_type = v_target_type and target_id = old.id;

  return old;
end;
$function$
;

grant delete on table "public"."entity_files" to "authenticated";

grant insert on table "public"."entity_files" to "authenticated";

grant select on table "public"."entity_files" to "authenticated";

grant delete on table "public"."entity_files" to "service_role";

grant insert on table "public"."entity_files" to "service_role";

grant references on table "public"."entity_files" to "service_role";

grant select on table "public"."entity_files" to "service_role";

grant trigger on table "public"."entity_files" to "service_role";

grant truncate on table "public"."entity_files" to "service_role";

grant update on table "public"."entity_files" to "service_role";


  create policy "Entity files scoped to account"
  on "public"."entity_files"
  as permissive
  for all
  to authenticated
using ((account_id = public.current_context_id()))
with check ((account_id = public.current_context_id()));


CREATE TRIGGER set_entity_files_account_id BEFORE INSERT ON public.entity_files FOR EACH ROW EXECUTE FUNCTION public.set_account_id_default();

CREATE TRIGGER set_entity_files_uploaded_by BEFORE INSERT ON public.entity_files FOR EACH ROW EXECUTE FUNCTION public.set_entity_files_uploaded_by();


  create policy "Entity files deletable within account"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'entity-files'::text) AND ((storage.foldername(name))[1] = (public.current_context_id())::text)));



  create policy "Entity files readable within account"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'entity-files'::text) AND ((storage.foldername(name))[1] = (public.current_context_id())::text)));



  create policy "Entity files writable within account"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'entity-files'::text) AND ((storage.foldername(name))[1] = (public.current_context_id())::text)));

-- Verified empirically (hand-check step, AGENTS.md): migra's diff, generated
-- above, does not account for this database's pre-existing
-- `alter default privileges ... grant all on tables to authenticated`
-- (an earlier migration) firing the moment `create table`/`create view`
-- above ran, nor did it emit any ACL statement at all for
-- entity_files_summary. Applying the migration as generated left
-- `entity_files` over-granted to `authenticated` (TRUNCATE bypasses RLS)
-- and left `entity_files_summary` WITHOUT the SELECT grant `authenticated`
-- needs. The statements below are copied verbatim from
-- supabase/schemas/06_grants.sql so the applied database matches the
-- declared schema exactly, regardless of the diff tool's blind spot.
revoke all on table public.entity_files from anon, authenticated;
grant select, insert, delete on table public.entity_files to authenticated;
grant all on table public.entity_files to service_role;
grant update (visibility) on table public.entity_files to authenticated;

revoke all on sequence public.entity_files_id_seq from anon;
grant usage, select on sequence public.entity_files_id_seq to authenticated;
grant all on sequence public.entity_files_id_seq to service_role;

revoke all on table public.entity_files_summary from anon, authenticated;
grant select on table public.entity_files_summary to authenticated;
grant all on table public.entity_files_summary to service_role;



