
  create table "public"."ai_usage" (
    "id" bigint generated by default as identity not null,
    "account_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "period" text not null,
    "resumes_parsed" integer not null default 0
      );


alter table "public"."ai_usage" enable row level security;


  create table "public"."subscription" (
    "id" bigint generated by default as identity not null,
    "account_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "plan" text not null default 'free'::text,
    "status" text not null default 'none'::text,
    "current_period_end" timestamp with time zone
      );


alter table "public"."subscription" enable row level security;

CREATE INDEX ai_usage_account_id_idx ON public.ai_usage USING btree (account_id);

CREATE UNIQUE INDEX ai_usage_account_id_period_key ON public.ai_usage USING btree (account_id, period);

CREATE UNIQUE INDEX ai_usage_pkey ON public.ai_usage USING btree (id);

CREATE INDEX subscription_account_id_idx ON public.subscription USING btree (account_id);

CREATE UNIQUE INDEX subscription_account_id_key ON public.subscription USING btree (account_id);

CREATE UNIQUE INDEX subscription_pkey ON public.subscription USING btree (id);

alter table "public"."ai_usage" add constraint "ai_usage_pkey" PRIMARY KEY using index "ai_usage_pkey";

alter table "public"."subscription" add constraint "subscription_pkey" PRIMARY KEY using index "subscription_pkey";

alter table "public"."ai_usage" add constraint "ai_usage_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."ai_usage" validate constraint "ai_usage_account_id_fkey";

alter table "public"."ai_usage" add constraint "ai_usage_account_id_period_key" UNIQUE using index "ai_usage_account_id_period_key";

alter table "public"."ai_usage" add constraint "ai_usage_resumes_parsed_nonneg" CHECK ((resumes_parsed >= 0)) not valid;

alter table "public"."ai_usage" validate constraint "ai_usage_resumes_parsed_nonneg";

alter table "public"."subscription" add constraint "subscription_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."subscription" validate constraint "subscription_account_id_fkey";

alter table "public"."subscription" add constraint "subscription_account_id_key" UNIQUE using index "subscription_account_id_key";

alter table "public"."subscription" add constraint "subscription_plan_check" CHECK ((plan = ANY (ARRAY['free'::text, 'ai'::text]))) not valid;

alter table "public"."subscription" validate constraint "subscription_plan_check";

alter table "public"."subscription" add constraint "subscription_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'lapsed'::text, 'none'::text]))) not valid;

alter table "public"."subscription" validate constraint "subscription_status_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.ai_entitlement()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare
  -- Monthly resume auto-parse allowance for the AI tier. Named rather than
  -- magic; the meter reads "<resumes_used> / <this>". Free tier gets 0.
  c_ai_monthly_resume_limit constant integer := 100;
  v_account_id bigint;
  v_plan text := 'free';
  v_status text := 'none';
  v_is_entitled boolean := false;
  v_resumes_limit integer := 0;
  v_resumes_used integer := 0;
  v_period text := to_char(now(), 'YYYY-MM');
begin
  v_account_id := public.current_account_id();
  if v_account_id is null then
    return jsonb_build_object(
      'is_entitled', false,
      'plan', 'free',
      'status', 'none',
      'resumes_used', 0,
      'resumes_limit', 0
    );
  end if;

  select s.plan, s.status
    into v_plan, v_status
  from public.subscription s
  where s.account_id = v_account_id;

  -- Default posture is UNENTITLED: entitlement requires EXACTLY the paid,
  -- currently-active state. 'lapsed' (was paid, now expired) is not entitled —
  -- AI auto-fill pauses, nothing is lost, the free manual path stays.
  v_plan := coalesce(v_plan, 'free');
  v_status := coalesce(v_status, 'none');
  v_is_entitled := (v_plan = 'ai' and v_status = 'active');
  v_resumes_limit := case when v_is_entitled then c_ai_monthly_resume_limit else 0 end;

  select coalesce(u.resumes_parsed, 0)
    into v_resumes_used
  from public.ai_usage u
  where u.account_id = v_account_id and u.period = v_period;

  v_resumes_used := coalesce(v_resumes_used, 0);

  return jsonb_build_object(
    'is_entitled', v_is_entitled,
    'plan', v_plan,
    'status', v_status,
    'resumes_used', v_resumes_used,
    'resumes_limit', v_resumes_limit
  );
end;
$function$
;

-- Grants (E4). `db diff` emits the positive grants but NOT the anon/authenticated
-- revokes — and the postgres-owned default privileges auto-grant TRUNCATE (which
-- BYPASSES RLS) to both roles on every new table. It also drops the function
-- EXECUTE grants entirely. All restated here explicitly, matching the rest of the
-- shidduchim domain (see references_entity migration). subscription/ai_usage are
-- SELECT-only for authenticated; every write is service_role. There is no client
-- path that flips plan/status to a paid state — the entitlement bypass the retired
-- client-side placeholder warned about is closed here.
revoke all on table "public"."subscription" from anon, authenticated;
grant select on table "public"."subscription" to authenticated;
grant all on table "public"."subscription" to service_role;

revoke all on table "public"."ai_usage" from anon, authenticated;
grant select on table "public"."ai_usage" to authenticated;
grant all on table "public"."ai_usage" to service_role;

-- Identity sequences: only service_role inserts, so authenticated never needs them.
revoke all on sequence "public"."subscription_id_seq" from anon, authenticated;
grant all on sequence "public"."subscription_id_seq" to service_role;

revoke all on sequence "public"."ai_usage_id_seq" from anon, authenticated;
grant all on sequence "public"."ai_usage_id_seq" to service_role;

-- ai_entitlement() is the single server-authoritative entitlement decision, called
-- by the SPA and (future) AI edge functions alike. anon must never run it.
revoke all on function "public"."ai_entitlement"() from public, anon;
grant execute on function "public"."ai_entitlement"() to authenticated;
grant execute on function "public"."ai_entitlement"() to service_role;


  create policy "AI usage readable within account"
  on "public"."ai_usage"
  as permissive
  for select
  to authenticated
using ((account_id = public.current_account_id()));



  create policy "Subscription readable within account"
  on "public"."subscription"
  as permissive
  for select
  to authenticated
using ((account_id = public.current_account_id()));



