
  create table "public"."inbox_items" (
    "id" bigint generated by default as identity not null,
    "account_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "source" text not null default 'upload'::text,
    "raw_text" text,
    "subject" text,
    "sender" text,
    "attachments" jsonb,
    "status" text not null default 'unresolved'::text,
    "child_id" bigint,
    "shadchan_id" bigint,
    "resolved_shidduchim_id" bigint
      );


alter table "public"."inbox_items" enable row level security;

CREATE INDEX inbox_items_account_id_idx ON public.inbox_items USING btree (account_id);

CREATE UNIQUE INDEX inbox_items_pkey ON public.inbox_items USING btree (id);

CREATE INDEX inbox_items_status_idx ON public.inbox_items USING btree (account_id, status);

alter table "public"."inbox_items" add constraint "inbox_items_pkey" PRIMARY KEY using index "inbox_items_pkey";

alter table "public"."inbox_items" add constraint "inbox_items_source_check" CHECK ((source = ANY (ARRAY['whatsapp'::text, 'sms'::text, 'email'::text, 'photo'::text, 'upload'::text]))) not valid;

alter table "public"."inbox_items" validate constraint "inbox_items_source_check";

alter table "public"."inbox_items" add constraint "inbox_items_status_check" CHECK ((status = ANY (ARRAY['unresolved'::text, 'resolved'::text, 'dismissed'::text]))) not valid;

alter table "public"."inbox_items" validate constraint "inbox_items_status_check";

-- Strip the default-ACL grants (incl. TRUNCATE, which bypasses RLS) before
-- re-granting only the DML authenticated needs. anon is denied entirely.
revoke all on table "public"."inbox_items" from anon, authenticated;

grant delete on table "public"."inbox_items" to "authenticated";

grant insert on table "public"."inbox_items" to "authenticated";

grant select on table "public"."inbox_items" to "authenticated";

grant update on table "public"."inbox_items" to "authenticated";

grant delete on table "public"."inbox_items" to "service_role";

grant insert on table "public"."inbox_items" to "service_role";

grant references on table "public"."inbox_items" to "service_role";

grant select on table "public"."inbox_items" to "service_role";

grant trigger on table "public"."inbox_items" to "service_role";

grant truncate on table "public"."inbox_items" to "service_role";

grant update on table "public"."inbox_items" to "service_role";

-- authenticated inserts its own captures (share/upload), so it needs the
-- identity sequence; anon is denied.
revoke all on sequence "public"."inbox_items_id_seq" from anon;
grant usage, select on sequence "public"."inbox_items_id_seq" to "authenticated";
grant all on sequence "public"."inbox_items_id_seq" to "service_role";


  create policy "Inbox items scoped to account"
  on "public"."inbox_items"
  as permissive
  for all
  to authenticated
using ((account_id = public.current_account_id()))
with check ((account_id = public.current_account_id()));


CREATE TRIGGER set_inbox_items_account_id BEFORE INSERT ON public.inbox_items FOR EACH ROW EXECUTE FUNCTION public.set_account_id_default();


