drop policy "Enable insert for admins" on "public"."configuration";

drop policy "Enable update for admins" on "public"."configuration";

drop view if exists "public"."init_state";

drop function if exists "public"."is_admin"();


  create table "public"."invites" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "token" uuid not null default gen_random_uuid(),
    "email" text not null,
    "account_id" bigint not null,
    "role" text not null,
    "invited_by" bigint,
    "status" text not null default 'pending'::text,
    "expires_at" timestamp with time zone not null default (now() + '14 days'::interval),
    "accepted_at" timestamp with time zone
      );


alter table "public"."invites" enable row level security;

CREATE INDEX invites_account_id_idx ON public.invites USING btree (account_id);

CREATE UNIQUE INDEX invites_pkey ON public.invites USING btree (id);

CREATE UNIQUE INDEX invites_token_key ON public.invites USING btree (token);

alter table "public"."invites" add constraint "invites_pkey" PRIMARY KEY using index "invites_pkey";

alter table "public"."invites" add constraint "invites_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."invites" validate constraint "invites_account_id_fkey";

alter table "public"."invites" add constraint "invites_invited_by_fkey" FOREIGN KEY (invited_by) REFERENCES public.account_members(id) ON DELETE SET NULL not valid;

alter table "public"."invites" validate constraint "invites_invited_by_fkey";

alter table "public"."invites" add constraint "invites_role_check" CHECK ((role = ANY (ARRAY['parent_admin'::text, 'helper'::text, 'single'::text, 'shadchan'::text]))) not valid;

alter table "public"."invites" validate constraint "invites_role_check";

alter table "public"."invites" add constraint "invites_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'revoked'::text, 'expired'::text]))) not valid;

alter table "public"."invites" validate constraint "invites_status_check";

alter table "public"."invites" add constraint "invites_token_key" UNIQUE using index "invites_token_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.check_signup_invite(event jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_email text;
  v_age_affirmed boolean;
  v_token uuid;
begin
  v_email := event -> 'user' ->> 'email';

  begin
    v_age_affirmed := (event -> 'user' -> 'user_metadata' ->> 'age_affirmed')::boolean;
  exception when others then
    v_age_affirmed := null;
  end;

  if v_age_affirmed is distinct from true then
    return jsonb_build_object('error', jsonb_build_object(
      'http_code', 403,
      'message', 'You must confirm you are 18 years of age or older to sign up.'
    ));
  end if;

  begin
    v_token := nullif(event -> 'user' -> 'user_metadata' ->> 'invite_token', '')::uuid;
  exception when others then
    v_token := null;
  end;

  if v_token is null or v_email is null or not exists (
    select 1 from public.invites i
    where i.token = v_token
      and lower(i.email) = lower(v_email)
      and i.status = 'pending'
      and i.expires_at > now()
  ) then
    return jsonb_build_object('error', jsonb_build_object(
      'http_code', 403,
      'message', 'This invite is invalid, expired, or has already been used.'
    ));
  end if;

  return '{}'::jsonb;
end;
$function$
;

revoke all on function public.check_signup_invite(jsonb) from public, anon, authenticated;

grant execute on function public.check_signup_invite(jsonb) to supabase_auth_admin;

CREATE OR REPLACE FUNCTION public.create_invite(p_email text, p_role text)
 RETURNS public.invites
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint;
  v_membership_id bigint;
  v_caller_role text;
  v_account_kind text;
  v_invite public.invites;
begin
  v_account_id := public.current_context_id();

  select am.id, am.role into v_membership_id, v_caller_role
  from public.account_members am
  where am.account_id = v_account_id
    and am.user_id = auth.uid()
    and am.status = 'active';

  if v_membership_id is null then
    raise exception 'no active membership of the current context'
      using errcode = 'insufficient_privilege';
  end if;

  if v_caller_role not in ('parent_admin', 'self_manager', 'shadchan') then
    raise exception 'role % may not send invites', v_caller_role
      using errcode = 'insufficient_privilege';
  end if;

  if public.role_authority(p_role) > public.role_authority(v_caller_role) then
    raise exception 'cannot invite role % above your own authority', p_role
      using errcode = 'insufficient_privilege';
  end if;

  select kind into v_account_kind from public.accounts where id = v_account_id;

  if v_account_kind = 'household' and p_role not in ('parent_admin', 'helper', 'single') then
    raise exception 'role % is not invitable into a household-kind account', p_role
      using errcode = 'check_violation';
  end if;

  if v_account_kind = 'shadchanus' and p_role <> 'shadchan' then
    raise exception 'role % is not invitable into a shadchanus-kind account', p_role
      using errcode = 'check_violation';
  end if;

  insert into public.invites (email, account_id, role, invited_by)
  values (p_email, v_account_id, p_role, v_membership_id)
  returning * into v_invite;

  return v_invite;
end;
$function$
;

revoke all on function public.create_invite(text, text) from public, anon;

grant execute on function public.create_invite(text, text) to authenticated;

grant execute on function public.create_invite(text, text) to service_role;

CREATE OR REPLACE FUNCTION public.get_invite_preview(p_token uuid)
 RETURNS TABLE(email text, account_name text, role text, status text, expires_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select
    i.email,
    a.name as account_name,
    i.role,
    case
      when i.status = 'pending' and i.expires_at < now() then 'expired'
      else i.status
    end as status,
    i.expires_at
  from public.invites i
  join public.accounts a on a.id = i.account_id
  where i.token = p_token;
$function$
;

revoke all on function public.get_invite_preview(uuid) from public;

grant execute on function public.get_invite_preview(uuid) to anon;

grant execute on function public.get_invite_preview(uuid) to authenticated;

grant execute on function public.get_invite_preview(uuid) to service_role;

CREATE OR REPLACE FUNCTION public.role_authority(p_role text)
 RETURNS integer
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO ''
AS $function$
  select case p_role
    when 'parent_admin' then 3
    when 'self_manager' then 2
    when 'helper' then 1
    when 'single' then 1
    when 'shadchan' then 1
    else 0
  end;
$function$
;

revoke all on function public.role_authority(text) from public, anon;

grant execute on function public.role_authority(text) to authenticated;

grant execute on function public.role_authority(text) to service_role;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  member_count int;
  v_invite public.invites;
  v_invite_token uuid;
begin
  select count(id) into member_count
  from public.members;

  insert into public.members (first_name, last_name, email, user_id, administrator)
  values (
    coalesce(
      nullif(new.raw_user_meta_data ->> 'first_name', ''),
      nullif(new.raw_user_meta_data -> 'custom_claims' ->> 'first_name', ''),
      nullif(new.raw_user_meta_data ->> 'given_name', ''),
      nullif(split_part(coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', ''), ' ', 1), ''),
      'Pending'),
    coalesce(
      nullif(new.raw_user_meta_data ->> 'last_name', ''),
      nullif(new.raw_user_meta_data -> 'custom_claims' ->> 'last_name', ''),
      nullif(new.raw_user_meta_data ->> 'family_name', ''),
      case when position(' ' in coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', '')) > 0
           then substr(coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'), position(' ' in coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name')) + 1)
      end,
      'Pending'),
    new.email,
    new.id,
    case when member_count > 0 then FALSE else TRUE end
  );

  -- Defensive cast: a malformed invite_token must never abort the whole
  -- auth.users insert (this trigger's exception would roll back the entire
  -- signup transaction). check_signup_invite() already validated the token
  -- shape before this user was allowed to be created; this guard only
  -- matters for the "hook unavailable" fallback path.
  begin
    v_invite_token := nullif(new.raw_user_meta_data ->> 'invite_token', '')::uuid;
  exception when others then
    v_invite_token := null;
  end;

  if v_invite_token is not null then
    select i.* into v_invite
    from public.invites i
    where i.token = v_invite_token
      and i.status = 'pending'
      and i.expires_at > now();

    if found then
      insert into public.account_members (account_id, user_id, role, invited_by, status)
      values (v_invite.account_id, new.id, v_invite.role, v_invite.invited_by, 'active');

      update public.invites
      set status = 'accepted', accepted_at = now()
      where id = v_invite.id;
    end if;
  end if;

  return new;
end;
$function$
;

-- Table grant (AC-2). `supabase db diff` did not emit this — the generated
-- migration only detected the narrow grants to add, not the ambient
-- default-privilege TRUNCATE/REFERENCES/TRIGGER/MAINTAIN grant `authenticated`
-- would otherwise inherit at CREATE TABLE time — so it is hand-added here,
-- matching the same fix this schema's `member_state` migration already needed
-- (Story 2.1) for the identical class of gap on FUNCTION grants. Verified by
-- applying this exact migration and checking has_table_privilege() /
-- pg_class.relacl directly: without this line, `authenticated` ends up
-- holding TRUNCATE on `invites`, which bypasses RLS entirely.
revoke all on table "public"."invites" from "anon", "authenticated";

grant select on table "public"."invites" to "authenticated";

grant delete on table "public"."invites" to "service_role";

grant insert on table "public"."invites" to "service_role";

grant references on table "public"."invites" to "service_role";

grant select on table "public"."invites" to "service_role";

grant trigger on table "public"."invites" to "service_role";

grant truncate on table "public"."invites" to "service_role";

grant update on table "public"."invites" to "service_role";

-- Sequence grant (AC-2's "no authenticated grant either" — `authenticated`
-- never inserts directly, since every write goes through create_invite() or
-- service_role). Hand-added for the same reason as the table grant above:
-- `supabase db diff` did not emit it for this brand-new sequence.
revoke all on sequence "public"."invites_id_seq" from "anon", "authenticated";

grant all on sequence "public"."invites_id_seq" to "service_role";

  create policy "Invites readable within active account"
  on "public"."invites"
  as permissive
  for select
  to authenticated
using ((account_id = public.current_context_id()));



