
  create table "public"."ai_parse_attempts" (
    "id" bigint generated by default as identity not null,
    "account_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "inbox_item_id" bigint not null,
    "attachment_path" text not null,
    "period" text not null,
    "status" text not null default 'in_progress'::text,
    "generation" bigint not null default 1,
    "started_at" timestamp with time zone not null default now(),
    "result" jsonb,
    "result_schema_version" smallint not null default 1
      );


alter table "public"."ai_parse_attempts" enable row level security;

CREATE UNIQUE INDEX ai_parse_attempts_account_item_attachment_key ON public.ai_parse_attempts USING btree (account_id, inbox_item_id, attachment_path);

CREATE UNIQUE INDEX ai_parse_attempts_pkey ON public.ai_parse_attempts USING btree (id);

alter table "public"."ai_parse_attempts" add constraint "ai_parse_attempts_pkey" PRIMARY KEY using index "ai_parse_attempts_pkey";

alter table "public"."ai_parse_attempts" add constraint "ai_parse_attempts_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."ai_parse_attempts" validate constraint "ai_parse_attempts_account_id_fkey";

alter table "public"."ai_parse_attempts" add constraint "ai_parse_attempts_inbox_item_id_fkey" FOREIGN KEY (inbox_item_id) REFERENCES public.inbox_items(id) ON DELETE CASCADE not valid;

alter table "public"."ai_parse_attempts" validate constraint "ai_parse_attempts_inbox_item_id_fkey";

alter table "public"."ai_parse_attempts" add constraint "ai_parse_attempts_account_item_attachment_key" UNIQUE using index "ai_parse_attempts_account_item_attachment_key";

alter table "public"."ai_parse_attempts" add constraint "ai_parse_attempts_status_check" CHECK ((status = ANY (ARRAY['in_progress'::text, 'completed'::text, 'failed'::text]))) not valid;

alter table "public"."ai_parse_attempts" validate constraint "ai_parse_attempts_status_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.ai_monthly_resume_limit()
 RETURNS integer
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$
  select 100;
$function$
;

CREATE OR REPLACE FUNCTION public.ai_resume_limit_for_account(p_account_id bigint)
 RETURNS integer
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare
  v_plan text;
  v_status text;
begin
  select s.plan, s.status
    into v_plan, v_status
  from public.subscription s
  where s.account_id = p_account_id;

  if coalesce(v_plan, 'free') = 'ai' and coalesce(v_status, 'none') = 'active' then
    return public.ai_monthly_resume_limit();
  end if;

  return 0;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.claim_ai_parse_attempt(p_account_id bigint, p_inbox_item_id bigint, p_attachment_path text, p_current_result_schema_version smallint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  c_stale_after constant interval := interval '5 minutes';
  -- 3x c_stale_after: comfortably outside any genuinely live request (see
  -- the function comment above), so a row this old can only be abandoned.
  c_reap_after constant interval := interval '15 minutes';
  v_period text := to_char(now(), 'YYYY-MM');
  -- Entitlement-aware, not the raw constant: an unentitled account (no
  -- subscription row, wrong plan, lapsed status) resolves to 0 here, so the
  -- `where v_limit > 0` reservation guard below refuses it outright — the
  -- SAME formula ai_entitlement() uses, never a second copy of it. Findings
  -- 6/7 are exactly about not trusting an earlier, out-of-band entitlement
  -- snapshot for enforcement; deriving it fresh, inside the same atomic
  -- operation that spends the quota, is what makes this fail-closed rather
  -- than merely relying on the Worker's own advisory pre-check.
  v_limit integer := public.ai_resume_limit_for_account(p_account_id);
  v_attempt_id bigint;
  v_generation bigint;
  v_status text;
  v_result jsonb;
  v_result_schema_version smallint;
  v_started_at timestamptz;
  v_new_count integer;
  v_is_fresh_claim boolean := false;
  v_needs_reservation boolean := false;
begin
  -- Opportunistic reaper (Finding 10 closure) — see function comment above
  -- for the full argument. Refunds only THIS account's own OTHER stuck
  -- rows; the key being claimed right now is excluded on purpose.
  with reaped as (
    update public.ai_parse_attempts
       set status = 'failed', result = null, generation = generation + 1
     where account_id = p_account_id
       and status = 'in_progress'
       and started_at < now() - c_reap_after
       and not (inbox_item_id = p_inbox_item_id and attachment_path = p_attachment_path)
    returning period
  ), reaped_counts as (
    select period, count(*) as n from reaped group by period
  )
  update public.ai_usage u
     set resumes_parsed = greatest(u.resumes_parsed - rc.n, 0)
    from reaped_counts rc
   where u.account_id = p_account_id and u.period = rc.period;

  -- Serialize on the unique constraint itself: the first INSERT for this
  -- key wins outright; a genuinely concurrent second INSERT blocks on
  -- Postgres's own conflict handling and then raises unique_violation,
  -- never silently succeeding twice.
  begin
    insert into public.ai_parse_attempts
      (account_id, inbox_item_id, attachment_path, period, status, started_at)
    values
      (p_account_id, p_inbox_item_id, p_attachment_path, v_period, 'in_progress', now())
    returning id, generation into v_attempt_id, v_generation;
    v_is_fresh_claim := true;
    v_needs_reservation := true;
  exception when unique_violation then
    select id, status, result, result_schema_version, started_at, generation
      into v_attempt_id, v_status, v_result, v_result_schema_version, v_started_at, v_generation
    from public.ai_parse_attempts
    where account_id = p_account_id
      and inbox_item_id = p_inbox_item_id
      and attachment_path = p_attachment_path
    for update;

    if v_status = 'completed' and v_result_schema_version >= p_current_result_schema_version then
      return jsonb_build_object(
        'outcome', 'replay', 'attempt_id', v_attempt_id, 'result', v_result,
        'result_schema_version', v_result_schema_version
      );
    elsif v_status = 'completed' then
      -- Stale CONTRACT, not stale time (Finding 12 closure): the cached
      -- result was written under an older response shape than the caller's
      -- own current one. Same free-reclaim treatment as an abandoned
      -- in_progress row below — the account already paid for one
      -- extraction of this document; a re-parse forced by OUR OWN contract
      -- change must not charge it again.
      update public.ai_parse_attempts
         set status = 'in_progress', started_at = now(), result = null, generation = generation + 1
       where id = v_attempt_id
      returning generation into v_generation;
      return jsonb_build_object('outcome', 'claimed', 'attempt_id', v_attempt_id, 'generation', v_generation);
    elsif v_status = 'in_progress' and v_started_at > now() - c_stale_after then
      return jsonb_build_object('outcome', 'conflict', 'attempt_id', v_attempt_id);
    elsif v_status = 'in_progress' then
      -- Stale: the original claim's reservation is still held (never
      -- released), so this resumes the SAME reservation without reserving
      -- a second unit — but it IS a new generation: bumping the fencing
      -- token here is what makes the original (now superseded) holder's
      -- later confirm/release a no-op instead of a race.
      update public.ai_parse_attempts
         set started_at = now(), generation = generation + 1
       where id = v_attempt_id
      returning generation into v_generation;
      return jsonb_build_object('outcome', 'claimed', 'attempt_id', v_attempt_id, 'generation', v_generation);
    else
      -- 'failed': its reservation was already released — needs a fresh
      -- atomic reserve-or-refuse, same as a brand-new key.
      v_needs_reservation := true;
    end if;
  end;

  if v_needs_reservation then
    -- Atomic reserve-or-refuse: the `WHERE v_limit > 0` on the INSERT's
    -- source rows gates the very-first-row-of-the-period case; the
    -- `WHERE resumes_parsed < v_limit` on the UPDATE gates every later
    -- increment. See the function comment above for the concurrency
    -- argument.
    insert into public.ai_usage as u (account_id, period, resumes_parsed)
    select p_account_id, v_period, 1
    where v_limit > 0
    on conflict (account_id, period) do update
      set resumes_parsed = u.resumes_parsed + 1
      where u.resumes_parsed < v_limit
    returning u.resumes_parsed into v_new_count;

    if not found then
      if v_is_fresh_claim then
        -- Undo the claim so this key isn't left permanently wedged by a
        -- reservation that was refused.
        delete from public.ai_parse_attempts where id = v_attempt_id;
      end if;
      -- Reclaim-from-'failed' path: leave the row as 'failed' — nothing
      -- to undo, it already reflects "no reservation held".
      return jsonb_build_object('outcome', 'cap_reached');
    end if;

    if not v_is_fresh_claim then
      -- Reclaim-from-'failed': a brand-new reservation, so — same reasoning
      -- as the stale-reclaim branch above — this is also a new generation.
      update public.ai_parse_attempts
         set status = 'in_progress', started_at = now(), result = null, period = v_period, generation = generation + 1
       where id = v_attempt_id
      returning generation into v_generation;
    end if;
  end if;

  return jsonb_build_object('outcome', 'claimed', 'attempt_id', v_attempt_id, 'generation', v_generation);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.confirm_ai_parse_attempt(p_account_id bigint, p_attempt_id bigint, p_generation bigint, p_result jsonb, p_result_schema_version smallint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_generation bigint;
  v_status text;
  v_result jsonb;
  v_result_schema_version smallint;
begin
  update public.ai_parse_attempts
     set status = 'completed', result = p_result, result_schema_version = p_result_schema_version
   where id = p_attempt_id
     and account_id = p_account_id
     and status = 'in_progress'
     and generation = p_generation;

  if found then
    return jsonb_build_object('outcome', 'applied');
  end if;

  select generation, status, result, result_schema_version
    into v_generation, v_status, v_result, v_result_schema_version
  from public.ai_parse_attempts
  where id = p_attempt_id and account_id = p_account_id;

  if not found then
    raise exception 'ai_parse_attempts % is not confirmable for account %', p_attempt_id, p_account_id;
  end if;

  if v_generation = p_generation and v_status = 'completed' then
    -- Idempotent retry of THIS SAME generation's own already-applied
    -- confirm (e.g. a lost-response network retry) — success, not merely
    -- "superseded by someone else".
    return jsonb_build_object('outcome', 'applied');
  end if;

  -- Either a newer generation already reclaimed this row (v_generation !=
  -- p_generation), or this generation's own reservation was already
  -- released through a different path (e.g. a client-side timeout) before
  -- this confirm arrived. Either way this call must not touch status,
  -- result, or ai_usage on another generation's behalf.
  if v_status = 'completed' then
    return jsonb_build_object(
      'outcome', 'superseded', 'status', v_status,
      'result', v_result, 'result_schema_version', v_result_schema_version
    );
  end if;

  return jsonb_build_object('outcome', 'superseded', 'status', v_status);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.release_ai_parse_attempt(p_account_id bigint, p_attempt_id bigint, p_generation bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_period text;
  v_generation bigint;
  v_status text;
begin
  update public.ai_parse_attempts
     set status = 'failed', result = null
   where id = p_attempt_id
     and account_id = p_account_id
     and status = 'in_progress'
     and generation = p_generation
  returning period into v_period;

  if found then
    update public.ai_usage
       set resumes_parsed = greatest(resumes_parsed - 1, 0)
     where account_id = p_account_id
       and period = v_period;
    return jsonb_build_object('outcome', 'applied');
  end if;

  select generation, status
    into v_generation, v_status
  from public.ai_parse_attempts
  where id = p_attempt_id and account_id = p_account_id;

  if not found then
    raise exception 'ai_parse_attempts % is not releasable for account %', p_attempt_id, p_account_id;
  end if;

  if v_generation = p_generation and v_status = 'failed' then
    -- Idempotent retry of THIS SAME generation's own already-applied
    -- release.
    return jsonb_build_object('outcome', 'applied');
  end if;

  return jsonb_build_object('outcome', 'superseded');
end;
$function$
;

CREATE OR REPLACE FUNCTION public.force_reclaim_ai_parse_attempt(p_account_id bigint, p_attempt_id bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_generation bigint;
begin
  update public.ai_parse_attempts
     set status = 'in_progress', started_at = now(), result = null, generation = generation + 1
   where id = p_attempt_id
     and account_id = p_account_id
     and status = 'completed'
  returning generation into v_generation;

  if found then
    return jsonb_build_object('outcome', 'reclaimed', 'generation', v_generation);
  end if;

  return jsonb_build_object('outcome', 'not_reclaimable');
end;
$function$
;

CREATE OR REPLACE FUNCTION public.sweep_expired_ai_parse_attempts()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_deleted integer;
begin
  delete from public.ai_parse_attempts
   where created_at < now() - interval '30 days';
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.ai_entitlement()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint;
  v_plan text := 'free';
  v_status text := 'none';
  v_is_entitled boolean := false;
  v_resumes_limit integer := 0;
  v_resumes_used integer := 0;
  v_period text := to_char(now(), 'YYYY-MM');
begin
  v_account_id := public.current_context_id();
  if v_account_id is null then
    return jsonb_build_object(
      'is_entitled', false,
      'plan', 'free',
      'status', 'none',
      'resumes_used', 0,
      'resumes_limit', 0
    );
  end if;

  select s.plan, s.status
    into v_plan, v_status
  from public.subscription s
  where s.account_id = v_account_id;

  -- Default posture is UNENTITLED: entitlement requires EXACTLY the paid,
  -- currently-active state. 'lapsed' (was paid, now expired) is not entitled —
  -- AI auto-fill pauses, nothing is lost, the free manual path stays.
  v_plan := coalesce(v_plan, 'free');
  v_status := coalesce(v_status, 'none');
  -- ai_resume_limit_for_account() is the one place that formula lives now
  -- (shared with claim_ai_parse_attempt()) — is_entitled is derived from its
  -- answer rather than restating "plan = 'ai' and status = 'active'" here too.
  v_resumes_limit := public.ai_resume_limit_for_account(v_account_id);
  v_is_entitled := (v_resumes_limit > 0);

  select coalesce(u.resumes_parsed, 0)
    into v_resumes_used
  from public.ai_usage u
  where u.account_id = v_account_id and u.period = v_period;

  v_resumes_used := coalesce(v_resumes_used, 0);

  return jsonb_build_object(
    'is_entitled', v_is_entitled,
    'plan', v_plan,
    'status', v_status,
    'resumes_used', v_resumes_used,
    'resumes_limit', v_resumes_limit
  );
end;
$function$
;

-- Grants (Epic 11 Findings 6/7/8 closure, C2 fencing-token follow-up). `db
-- diff` emits the positive table grants (above, left as generated) but NOT
-- the anon/authenticated revokes, and it drops the function EXECUTE grants
-- entirely — the same documented pitfall as the original billing-entitlement
-- migration (see 20260724121954_add_billing_entitlement.sql). The
-- postgres-owned default privileges (06_grants.sql lines ~64-72) auto-grant
-- TRUNCATE and full table access, and EXECUTE on every new function, to
-- `authenticated` — and EXECUTE to `public` — unless explicitly revoked
-- here. All restated explicitly to match the declarative schema.
revoke all on table "public"."ai_parse_attempts" from anon, authenticated;
grant all on table "public"."ai_parse_attempts" to service_role;

revoke all on sequence "public"."ai_parse_attempts_id_seq" from anon, authenticated;
grant all on sequence "public"."ai_parse_attempts_id_seq" to service_role;

-- ai_monthly_resume_limit() is a read-only constant lookup, safe for a
-- client JWT to invoke directly (same posture as ai_entitlement()).
revoke all on function "public"."ai_monthly_resume_limit"() from public, anon;
grant execute on function "public"."ai_monthly_resume_limit"() to authenticated;
grant execute on function "public"."ai_monthly_resume_limit"() to service_role;

-- ai_resume_limit_for_account(): reads only public.subscription, which is
-- already RLS-scoped to the caller's own account — asking about another
-- account's id from a client JWT simply resolves no row (returns 0), never
-- another tenant's data (see the function's own comment).
revoke all on function "public"."ai_resume_limit_for_account"(bigint) from public, anon;
grant execute on function "public"."ai_resume_limit_for_account"(bigint) to authenticated;
grant execute on function "public"."ai_resume_limit_for_account"(bigint) to service_role;

-- claim/confirm/release are reachable ONLY from the Worker's service-role
-- client. SECURITY DEFINER bypasses RLS entirely, so EXECUTE must never
-- reach `authenticated` or `anon` — a modified client with that privilege
-- could pass ANY p_account_id, not just its own, enabling cross-tenant
-- quota exhaustion and forged 'completed' results replayed into another
-- account's resume draft.
revoke all on function "public"."claim_ai_parse_attempt"(bigint, bigint, text, smallint) from public, anon, authenticated;
grant execute on function "public"."claim_ai_parse_attempt"(bigint, bigint, text, smallint) to service_role;

revoke all on function "public"."confirm_ai_parse_attempt"(bigint, bigint, bigint, jsonb, smallint) from public, anon, authenticated;
grant execute on function "public"."confirm_ai_parse_attempt"(bigint, bigint, bigint, jsonb, smallint) to service_role;

revoke all on function "public"."release_ai_parse_attempt"(bigint, bigint, bigint) from public, anon, authenticated;
grant execute on function "public"."release_ai_parse_attempt"(bigint, bigint, bigint) to service_role;

-- force_reclaim_ai_parse_attempt() (Finding 12 closure): same posture as
-- claim/confirm/release above — SECURITY DEFINER, reachable ONLY from the
-- Worker's service-role client.
revoke all on function "public"."force_reclaim_ai_parse_attempt"(bigint, bigint) from public, anon, authenticated;
grant execute on function "public"."force_reclaim_ai_parse_attempt"(bigint, bigint) to service_role;

-- sweep_expired_ai_parse_attempts() (Finding 11 closure): called only from
-- workers/cron's scheduled() tick via the service-role client.
revoke all on function "public"."sweep_expired_ai_parse_attempts"() from public, anon, authenticated;
grant execute on function "public"."sweep_expired_ai_parse_attempts"() to service_role;


