
  create table "public"."listings" (
    "id" bigint generated by default as identity not null,
    "account_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "listing_type" text not null,
    "single_id" bigint,
    "published_by_member_id" bigint,
    "shadchan_name" text,
    "shadchan_area" text,
    "shadchan_contact_info" text,
    "single_first_name_en" text,
    "single_first_name_he" text,
    "single_age" integer,
    "single_height" text,
    "single_community" text,
    "single_location" text,
    "single_summary" text
      );


alter table "public"."listings" enable row level security;

-- `supabase db diff` does not emit FORCE ROW LEVEL SECURITY (known gap,
-- AGENTS.md / this story's Dev Notes) — hand-added to match
-- 05_policies.sql, which declares it for this table. AD-1 requires FORCE on
-- every table without exception; it matters especially here since
-- `listings` also carries a deliberate blanket `anon` grant (AD-21).
alter table "public"."listings" force row level security;

CREATE INDEX listings_account_id_idx ON public.listings USING btree (account_id);

CREATE UNIQUE INDEX listings_pkey ON public.listings USING btree (id);

CREATE UNIQUE INDEX listings_shadchan_account_id_key ON public.listings USING btree (account_id) WHERE (listing_type = 'shadchan'::text);

CREATE UNIQUE INDEX listings_single_id_key ON public.listings USING btree (single_id) WHERE (listing_type = 'single'::text);

alter table "public"."listings" add constraint "listings_pkey" PRIMARY KEY using index "listings_pkey";

alter table "public"."listings" add constraint "listings_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."listings" validate constraint "listings_account_id_fkey";

alter table "public"."listings" add constraint "listings_published_by_member_id_fkey" FOREIGN KEY (published_by_member_id) REFERENCES public.account_members(id) ON DELETE SET NULL not valid;

alter table "public"."listings" validate constraint "listings_published_by_member_id_fkey";

alter table "public"."listings" add constraint "listings_shadchan_name_required" CHECK (((listing_type <> 'shadchan'::text) OR (shadchan_name IS NOT NULL))) not valid;

alter table "public"."listings" validate constraint "listings_shadchan_name_required";

alter table "public"."listings" add constraint "listings_single_id_fkey" FOREIGN KEY (account_id, single_id) REFERENCES public.singles(account_id, id) ON DELETE CASCADE not valid;

alter table "public"."listings" validate constraint "listings_single_id_fkey";

alter table "public"."listings" add constraint "listings_single_id_presence" CHECK ((((listing_type = 'single'::text) AND (single_id IS NOT NULL)) OR ((listing_type = 'shadchan'::text) AND (single_id IS NULL)))) not valid;

alter table "public"."listings" validate constraint "listings_single_id_presence";

alter table "public"."listings" add constraint "listings_single_name_required" CHECK (((listing_type <> 'single'::text) OR (single_first_name_en IS NOT NULL) OR (single_first_name_he IS NOT NULL))) not valid;

alter table "public"."listings" validate constraint "listings_single_name_required";

alter table "public"."listings" add constraint "listings_type_check" CHECK ((listing_type = ANY (ARRAY['shadchan'::text, 'single'::text]))) not valid;

alter table "public"."listings" validate constraint "listings_type_check";

grant select on table "public"."listings" to "anon";

grant delete on table "public"."listings" to "authenticated";

grant insert on table "public"."listings" to "authenticated";

grant references on table "public"."listings" to "authenticated";

grant select on table "public"."listings" to "authenticated";

grant trigger on table "public"."listings" to "authenticated";

grant truncate on table "public"."listings" to "authenticated";

grant update on table "public"."listings" to "authenticated";

grant delete on table "public"."listings" to "service_role";

grant insert on table "public"."listings" to "service_role";

grant references on table "public"."listings" to "service_role";

grant select on table "public"."listings" to "service_role";

grant trigger on table "public"."listings" to "service_role";

grant truncate on table "public"."listings" to "service_role";

grant update on table "public"."listings" to "service_role";


  create policy "Listings readable by anon"
  on "public"."listings"
  as permissive
  for select
  to anon
using (true);



  create policy "Listings readable by owner"
  on "public"."listings"
  as permissive
  for select
  to authenticated
using ((account_id = public.current_context_id()));



  create policy "Shadchan listings delete"
  on "public"."listings"
  as permissive
  for delete
  to authenticated
using (((listing_type = 'shadchan'::text) AND (account_id = public.current_context_id()) AND (EXISTS ( SELECT 1
   FROM public.accounts a
  WHERE ((a.id = public.current_context_id()) AND (a.kind = 'shadchanus'::text)))) AND (EXISTS ( SELECT 1
   FROM public.account_members am
  WHERE ((am.account_id = public.current_context_id()) AND (am.user_id = auth.uid()) AND (am.role = 'shadchan'::text))))));



  create policy "Shadchan listings insert"
  on "public"."listings"
  as permissive
  for insert
  to authenticated
with check (((listing_type = 'shadchan'::text) AND (account_id = public.current_context_id()) AND (EXISTS ( SELECT 1
   FROM public.accounts a
  WHERE ((a.id = public.current_context_id()) AND (a.kind = 'shadchanus'::text)))) AND (EXISTS ( SELECT 1
   FROM public.account_members am
  WHERE ((am.account_id = public.current_context_id()) AND (am.user_id = auth.uid()) AND (am.role = 'shadchan'::text))))));



  create policy "Shadchan listings update"
  on "public"."listings"
  as permissive
  for update
  to authenticated
using (((listing_type = 'shadchan'::text) AND (account_id = public.current_context_id()) AND (EXISTS ( SELECT 1
   FROM public.accounts a
  WHERE ((a.id = public.current_context_id()) AND (a.kind = 'shadchanus'::text)))) AND (EXISTS ( SELECT 1
   FROM public.account_members am
  WHERE ((am.account_id = public.current_context_id()) AND (am.user_id = auth.uid()) AND (am.role = 'shadchan'::text))))))
with check (((listing_type = 'shadchan'::text) AND (account_id = public.current_context_id()) AND (EXISTS ( SELECT 1
   FROM public.accounts a
  WHERE ((a.id = public.current_context_id()) AND (a.kind = 'shadchanus'::text)))) AND (EXISTS ( SELECT 1
   FROM public.account_members am
  WHERE ((am.account_id = public.current_context_id()) AND (am.user_id = auth.uid()) AND (am.role = 'shadchan'::text))))));


CREATE TRIGGER set_listings_account_id BEFORE INSERT ON public.listings FOR EACH ROW EXECUTE FUNCTION public.set_account_id_default();

-- `supabase db diff` never re-emits grant/ACL changes on a PRE-EXISTING,
-- otherwise-unaltered object (known gap, AGENTS.md) — hand-added here.
-- Closes a narrower, pre-existing AD-1 gap while this migration is open
-- (Epic 9 pre-flight, 2026-08-02; 06_grants.sql's own comment on this line
-- has the full story): a fork-era `grant all on sequence
-- public.members_id_seq to anon;` (06_grants.sql line 46) was never revoked
-- by the Epic 2 AD-1 sweep. Not this story's own defect and not
-- `listings`-shaped, but Epic 9 is the first epic where `anon` becomes a
-- live, reachable production role, and this story's own AC-8 ("`anon`
-- holds `select` on `listings` and nothing else") is not a true sentence
-- about the schema until this one-line revoke lands too.
revoke all on sequence public.members_id_seq from anon;


