drop function if exists "public"."check_signup_invite"(event jsonb);


  create table "public"."signup_intents" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "email" extensions.citext not null,
    "expires_at" timestamp with time zone not null default (now() + '00:10:00'::interval),
    "consumed_at" timestamp with time zone
      );


alter table "public"."signup_intents" enable row level security;

-- Hand-added: `db diff` does not re-emit FORCE ROW LEVEL SECURITY for a
-- brand-new table (same known gap `20260731181450_thread_model.sql` hand-
-- fixed for `connections`/`messages` — see that migration's own comment).
alter table "public"."signup_intents" force row level security;

CREATE INDEX signup_intents_email_idx ON public.signup_intents USING btree (email) WHERE (consumed_at IS NULL);

CREATE UNIQUE INDEX signup_intents_pkey ON public.signup_intents USING btree (id);

alter table "public"."signup_intents" add constraint "signup_intents_pkey" PRIMARY KEY using index "signup_intents_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.check_signup_age(event jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_email text;
  v_age_affirmed boolean;
begin
  v_email := event -> 'user' ->> 'email';

  begin
    v_age_affirmed := (event -> 'user' -> 'user_metadata' ->> 'age_affirmed')::boolean;
  exception when others then
    v_age_affirmed := null;
  end;

  if v_age_affirmed is distinct from true and v_email is not null then
    update public.signup_intents
    set consumed_at = now()
    where email = v_email
      and consumed_at is null
      and expires_at > now();

    if found then
      v_age_affirmed := true;
    end if;
  end if;

  delete from public.signup_intents where expires_at <= now();

  if v_age_affirmed is distinct from true then
    return jsonb_build_object('error', jsonb_build_object(
      'http_code', 403,
      'message', 'You must confirm you are 18 years of age or older to sign up.'
    ));
  end if;

  return '{}'::jsonb;
end;
$function$
;

-- MANUAL ADJUSTMENT: `db diff` emitted no function-grant DDL at all for
-- check_signup_age() — same gap `20260802130221_connection_consent.sql`
-- hand-fixed for its five new functions. `supabase_auth_admin` only, never
-- `anon`/`authenticated` directly: GoTrue is the sole caller, as the
-- before_user_created Auth Hook.
revoke all on function "public"."check_signup_age"(jsonb) from "public", "anon", "authenticated";

grant execute on function "public"."check_signup_age"(jsonb) to "supabase_auth_admin";

-- MANUAL ADJUSTMENT (see AGENTS.md): `db diff` emitted only the additive
-- grants below — never the `revoke all ... from anon, authenticated` that
-- 06_grants.sql declares first. Without it, this table's default privilege
-- (`alter default privileges ... grant all on tables to authenticated`,
-- top of 06_grants.sql) would leave `authenticated` with INSERT/UPDATE/
-- DELETE/TRUNCATE/REFERENCES/TRIGGER on a table with no client write path
-- for it at all — signup_intents is a pre-session buffer table, not a
-- product surface for a signed-in member.
revoke all on table "public"."signup_intents" from "anon", "authenticated";

grant insert on table "public"."signup_intents" to "anon";

grant delete on table "public"."signup_intents" to "service_role";

grant insert on table "public"."signup_intents" to "service_role";

grant references on table "public"."signup_intents" to "service_role";

grant select on table "public"."signup_intents" to "service_role";

grant trigger on table "public"."signup_intents" to "service_role";

grant truncate on table "public"."signup_intents" to "service_role";

grant update on table "public"."signup_intents" to "service_role";

-- MANUAL ADJUSTMENT: `db diff` emits no sequence grant/revoke DDL at all for
-- the identity column's own `signup_intents_id_seq` — same gap
-- `20260802130221_connection_consent.sql` hand-fixed for
-- `connection_invites_id_seq`. No `authenticated` grant: `authenticated` has
-- no access to signup_intents at all (06_grants.sql).
revoke all on sequence "public"."signup_intents_id_seq" from "anon", "authenticated";

grant all on sequence "public"."signup_intents_id_seq" to "service_role";


  create policy "Signup intents insertable by anon"
  on "public"."signup_intents"
  as permissive
  for insert
  to anon
with check (((email IS NOT NULL) AND (consumed_at IS NULL) AND (expires_at <= (now() + '00:10:00'::interval))));



