--
-- MyShadchan — Shidduchim pipeline (Deals Kanban -> 7-state shidduch board)
--
-- Mirrors the declarative additions to supabase/schemas/ (01_tables,
-- 02_functions, 03_views, 04_triggers, 05_policies, 06_grants). Hand-authored
-- because local Supabase/Docker was unavailable to run `supabase db diff`;
-- once Docker is up, `supabase db diff --local` MUST show no drift against
-- these schema files. Idempotent seeds at the end.
--
-- Invariants (AD-1/AD-4/AD-12): every domain row is account_id-scoped; one
-- pipeline_state enum (7 values, NO decision_substate); create_shidduch() is
-- the sole INSERT path; transition_shidduch() is the sole state writer with
-- the transition graph as data; gut `for_sure_not` != post-investigation `no`.
--

-- ---------------------------------------------------------------------------
-- Enum: the one canonical pipeline state (AD-4)
-- ---------------------------------------------------------------------------
create type public.pipeline_state as enum (
    'new',
    'look_into',
    'not_sure',
    'for_sure_not',
    'yes',
    'unsure',
    'no'
);

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
create table public.accounts (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null default 'My Account',
    transparency_level text not null default 'shared',
    data_region text,
    stripe_customer_id text,
    subscription_status text,
    plan text,
    current_period_end timestamp with time zone,
    trial_end timestamp with time zone
);

create table public.account_members (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    user_id uuid,
    role text not null default 'parent_admin',
    status text not null default 'active',
    invited_by bigint,
    constraint account_members_role_check check (
        role in ('parent_admin', 'helper', 'self_manager', 'shadchan')
    )
);

create table public.children (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    first_name_en text,
    first_name_he text,
    last_name_en text,
    last_name_he text,
    gender text,
    dob date,
    community text,
    status text not null default 'active',
    member_id bigint
);

create table public.shadchanim (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    name text not null,
    name_he text,
    location text,
    contacts jsonb,
    notes text,
    responsiveness text
);

-- `references` is a reserved SQL keyword, so quote the table name in raw SQL.
create table public."references" (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    name_en text,
    name_he text,
    relationship text,
    phone text,
    school text,
    grad_year integer
);

create table public.shidduchim (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    child_id bigint not null,
    shadchan_id bigint,
    name_en text,
    name_he text,
    parents_en text,
    parents_he text,
    seminary_en text,
    seminary_he text,
    shul_en text,
    shul_he text,
    location_en text,
    location_he text,
    age integer,
    height text,
    pipeline_state public.pipeline_state not null default 'new',
    first_suggested_by bigint,
    first_suggested_at timestamp with time zone not null default now(),
    redt_date date not null default current_date,
    close_reason text,
    origin text not null default 'manual',
    owner_member_id bigint,
    visibility text not null default 'shared',
    index smallint not null default 0,
    constraint shidduchim_origin_check check (origin in ('channel', 'manual', 'shadchan')),
    constraint shidduchim_visibility_check check (
        visibility in ('shared', 'private_parent', 'private_child')
    )
);

create table public.resumes (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    shidduchim_id bigint not null,
    files jsonb,
    photos jsonb,
    extracted jsonb,
    sections jsonb
);

create table public.reference_links (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    reference_id bigint not null,
    shidduchim_id bigint,
    resume_id bigint,
    call_status text,
    what_they_said text,
    conversation_log jsonb
);

create table public.date_records (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    child_id bigint,
    person_name_en text,
    person_name_he text,
    person_parents text,
    person_seminary text,
    person_location text,
    date_on date,
    outcome text,
    notes text
);

create table public.pipeline_transitions (
    from_state public.pipeline_state not null,
    to_state public.pipeline_state not null,
    constraint pipeline_transitions_pkey primary key (from_state, to_state)
);

-- ---------------------------------------------------------------------------
-- Foreign keys
-- ---------------------------------------------------------------------------
alter table public.account_members
    add constraint account_members_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.account_members
    add constraint account_members_invited_by_fkey foreign key (invited_by) references public.account_members(id) on delete set null;
alter table public.account_members
    add constraint account_members_user_id_fkey foreign key (user_id) references auth.users(id) on delete set null;

alter table public.children
    add constraint children_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.children
    add constraint children_member_id_fkey foreign key (member_id) references public.account_members(id) on delete set null;

alter table public.shadchanim
    add constraint shadchanim_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;

alter table public."references"
    add constraint references_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;

alter table public.shidduchim
    add constraint shidduchim_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.shidduchim
    add constraint shidduchim_child_id_fkey foreign key (child_id) references public.children(id) on delete cascade;
alter table public.shidduchim
    add constraint shidduchim_shadchan_id_fkey foreign key (shadchan_id) references public.shadchanim(id) on delete set null;
alter table public.shidduchim
    add constraint shidduchim_first_suggested_by_fkey foreign key (first_suggested_by) references public.shadchanim(id) on delete set null;
alter table public.shidduchim
    add constraint shidduchim_owner_member_id_fkey foreign key (owner_member_id) references public.account_members(id) on delete set null;

alter table public.resumes
    add constraint resumes_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.resumes
    add constraint resumes_shidduchim_id_fkey foreign key (shidduchim_id) references public.shidduchim(id) on delete cascade;
alter table public.resumes
    add constraint resumes_shidduchim_id_key unique (shidduchim_id);

alter table public.reference_links
    add constraint reference_links_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.reference_links
    add constraint reference_links_reference_id_fkey foreign key (reference_id) references public."references"(id) on delete cascade;
alter table public.reference_links
    add constraint reference_links_shidduchim_id_fkey foreign key (shidduchim_id) references public.shidduchim(id) on delete cascade;
alter table public.reference_links
    add constraint reference_links_resume_id_fkey foreign key (resume_id) references public.resumes(id) on delete cascade;

alter table public.date_records
    add constraint date_records_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.date_records
    add constraint date_records_child_id_fkey foreign key (child_id) references public.children(id) on delete cascade;

-- ---------------------------------------------------------------------------
-- Indexes on foreign keys
-- ---------------------------------------------------------------------------
create index account_members_account_id_idx on public.account_members using btree (account_id);
create index children_account_id_idx on public.children using btree (account_id);
create index shadchanim_account_id_idx on public.shadchanim using btree (account_id);
create index references_account_id_idx on public."references" using btree (account_id);
create index shidduchim_account_id_idx on public.shidduchim using btree (account_id);
create index shidduchim_child_id_idx on public.shidduchim using btree (child_id);
create index shidduchim_shadchan_id_idx on public.shidduchim using btree (shadchan_id);
create index resumes_account_id_idx on public.resumes using btree (account_id);
create index reference_links_account_id_idx on public.reference_links using btree (account_id);
create index reference_links_reference_id_idx on public.reference_links using btree (reference_id);
create index reference_links_shidduchim_id_idx on public.reference_links using btree (shidduchim_id);
create index date_records_account_id_idx on public.date_records using btree (account_id);
create index date_records_child_id_idx on public.date_records using btree (child_id);

-- ---------------------------------------------------------------------------
-- Functions
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."current_account_id"() RETURNS bigint
    LANGUAGE "plpgsql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  v_account_id bigint;
begin
  select am.account_id into v_account_id
  from public.account_members am
  where am.user_id = auth.uid()
  order by am.id
  limit 1;

  if v_account_id is null then
    select a.id into v_account_id
    from public.accounts a
    order by a.id
    limit 1;
  end if;

  return v_account_id;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."set_account_id_default"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
begin
  if new.account_id is null then
    new.account_id := public.current_account_id();
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."is_child_visible_state"("s" public.pipeline_state) RETURNS boolean
    LANGUAGE "plpgsql" IMMUTABLE
    SET "search_path" TO ''
    AS $$
begin
  case s
    when 'look_into' then return true;
    when 'yes' then return true;
    when 'unsure' then return true;
    when 'new' then return false;
    when 'not_sure' then return false;
    when 'for_sure_not' then return false;
    when 'no' then return false;
    else
      raise exception 'unclassified pipeline_state in child-visibility policy: %', s;
  end case;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."enforce_pipeline_transition"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
begin
  if new.pipeline_state is distinct from old.pipeline_state then
    if not exists (
      select 1 from public.pipeline_transitions t
      where t.from_state = old.pipeline_state
        and t.to_state = new.pipeline_state
    ) then
      raise exception 'illegal pipeline transition: % -> %', old.pipeline_state, new.pipeline_state
        using errcode = 'check_violation';
    end if;
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."enforce_shidduch_initial_state"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
begin
  if new.pipeline_state not in ('new', 'look_into', 'not_sure', 'for_sure_not') then
    raise exception 'a shidduch cannot be created in decision state % (reachable only from look_into)', new.pipeline_state
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."create_shidduch"(
    "p_child_id" bigint,
    "p_shadchan_id" bigint DEFAULT NULL,
    "p_name_en" text DEFAULT NULL,
    "p_name_he" text DEFAULT NULL,
    "p_parents_en" text DEFAULT NULL,
    "p_parents_he" text DEFAULT NULL,
    "p_seminary_en" text DEFAULT NULL,
    "p_seminary_he" text DEFAULT NULL,
    "p_shul_en" text DEFAULT NULL,
    "p_shul_he" text DEFAULT NULL,
    "p_location_en" text DEFAULT NULL,
    "p_location_he" text DEFAULT NULL,
    "p_age" integer DEFAULT NULL,
    "p_height" text DEFAULT NULL,
    "p_origin" text DEFAULT 'manual',
    "p_initial_state" public.pipeline_state DEFAULT 'new',
    "p_visibility" text DEFAULT 'shared',
    "p_redt_date" date DEFAULT NULL
) RETURNS SETOF public.shidduchim
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  v_account_id bigint;
  v_owner_member_id bigint;
begin
  v_account_id := public.current_account_id();
  if v_account_id is null then
    raise exception 'no account context for create_shidduch (no account exists)';
  end if;

  if p_initial_state not in ('new', 'look_into', 'not_sure', 'for_sure_not') then
    raise exception 'invalid initial pipeline_state: % (decision states are reachable only from look_into)', p_initial_state
      using errcode = 'check_violation';
  end if;

  if not exists (
    select 1 from public.children c
    where c.id = p_child_id and c.account_id = v_account_id
  ) then
    raise exception 'child % not found in current account', p_child_id;
  end if;

  if p_shadchan_id is not null and not exists (
    select 1 from public.shadchanim s
    where s.id = p_shadchan_id and s.account_id = v_account_id
  ) then
    raise exception 'shadchan % not found in current account', p_shadchan_id;
  end if;

  select am.id into v_owner_member_id
  from public.account_members am
  where am.user_id = auth.uid() and am.account_id = v_account_id
  order by am.id
  limit 1;

  return query
  insert into public.shidduchim (
    account_id, child_id, shadchan_id,
    name_en, name_he,
    parents_en, parents_he, seminary_en, seminary_he,
    shul_en, shul_he, location_en, location_he,
    age, height,
    pipeline_state, first_suggested_by, first_suggested_at, redt_date,
    origin, owner_member_id, visibility
  ) values (
    v_account_id, p_child_id, p_shadchan_id,
    p_name_en, p_name_he,
    p_parents_en, p_parents_he, p_seminary_en, p_seminary_he,
    p_shul_en, p_shul_he, p_location_en, p_location_he,
    p_age, p_height,
    p_initial_state, p_shadchan_id, now(), coalesce(p_redt_date, current_date),
    p_origin, v_owner_member_id, p_visibility
  )
  returning *;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."transition_shidduch"(
    "p_id" bigint,
    "p_from" public.pipeline_state,
    "p_to" public.pipeline_state,
    "p_close_reason" text DEFAULT NULL
) RETURNS SETOF public.shidduchim
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  v_current public.pipeline_state;
begin
  select pipeline_state into v_current
  from public.shidduchim
  where id = p_id
  for update;

  if not found then
    raise exception 'shidduch % not found', p_id;
  end if;

  if v_current is distinct from p_from then
    raise exception 'stale transition: shidduch % is in state %, not %', p_id, v_current, p_from
      using errcode = 'serialization_failure';
  end if;

  if p_from is not distinct from p_to then
    return query select * from public.shidduchim where id = p_id;
    return;
  end if;

  if not exists (
    select 1 from public.pipeline_transitions t
    where t.from_state = p_from and t.to_state = p_to
  ) then
    raise exception 'illegal pipeline transition: % -> %', p_from, p_to
      using errcode = 'check_violation';
  end if;

  return query
  update public.shidduchim
  set pipeline_state = p_to,
      close_reason = case
        when p_to in ('for_sure_not', 'yes', 'unsure', 'no') then coalesce(p_close_reason, close_reason)
        else null
      end
  where id = p_id
  returning *;
end;
$$;

-- ---------------------------------------------------------------------------
-- View: board read path
-- ---------------------------------------------------------------------------
create or replace view public.shidduchim_summary with (security_invoker = on) as
select
    s.id,
    s.account_id,
    s.created_at,
    s.child_id,
    s.shadchan_id,
    s.name_en,
    s.name_he,
    s.parents_en,
    s.parents_he,
    s.seminary_en,
    s.seminary_he,
    s.shul_en,
    s.shul_he,
    s.location_en,
    s.location_he,
    s.age,
    s.height,
    s.pipeline_state,
    s.first_suggested_by,
    s.first_suggested_at,
    s.redt_date,
    s.close_reason,
    s.origin,
    s.owner_member_id,
    s.visibility,
    s.index,
    sh.name as shadchan_name,
    sh.name_he as shadchan_name_he,
    c.first_name_en as child_first_name_en,
    c.first_name_he as child_first_name_he,
    c.last_name_en as child_last_name_en,
    c.last_name_he as child_last_name_he,
    count(distinct rl.id) as nb_references
from public.shidduchim s
    left join public.shadchanim sh on sh.id = s.shadchan_id
    left join public.children c on c.id = s.child_id
    left join public.reference_links rl on rl.shidduchim_id = s.id
group by s.id, sh.name, sh.name_he, c.first_name_en, c.first_name_he, c.last_name_en, c.last_name_he;

-- ---------------------------------------------------------------------------
-- Trigger: enforce the transition graph on every pipeline_state change
-- ---------------------------------------------------------------------------
create or replace trigger enforce_shidduch_transition
    before update on public.shidduchim
    for each row execute function public.enforce_pipeline_transition();

create or replace trigger set_shidduchim_account_id
    before insert on public.shidduchim
    for each row execute function public.set_account_id_default();

create or replace trigger enforce_shidduch_initial_state
    before insert on public.shidduchim
    for each row execute function public.enforce_shidduch_initial_state();

create or replace trigger set_children_account_id
    before insert on public.children
    for each row execute function public.set_account_id_default();

create or replace trigger set_shadchanim_account_id
    before insert on public.shadchanim
    for each row execute function public.set_account_id_default();

create or replace trigger set_references_account_id
    before insert on public."references"
    for each row execute function public.set_account_id_default();

create or replace trigger set_resumes_account_id
    before insert on public.resumes
    for each row execute function public.set_account_id_default();

create or replace trigger set_reference_links_account_id
    before insert on public.reference_links
    for each row execute function public.set_account_id_default();

create or replace trigger set_date_records_account_id
    before insert on public.date_records
    for each row execute function public.set_account_id_default();

-- ---------------------------------------------------------------------------
-- Row Level Security (account-scoped, deny-by-default for anon)
-- ---------------------------------------------------------------------------
alter table public.accounts enable row level security;
alter table public.account_members enable row level security;
alter table public.children enable row level security;
alter table public.shadchanim enable row level security;
alter table public."references" enable row level security;
alter table public.shidduchim enable row level security;
alter table public.resumes enable row level security;
alter table public.reference_links enable row level security;
alter table public.date_records enable row level security;
alter table public.pipeline_transitions enable row level security;

create policy "Account access scoped to member" on public.accounts
    for all to authenticated
    using (id = public.current_account_id())
    with check (id = public.current_account_id());

create policy "Account members scoped to account" on public.account_members
    for all to authenticated
    using (account_id = public.current_account_id())
    with check (account_id = public.current_account_id());

create policy "Children scoped to account" on public.children
    for all to authenticated
    using (account_id = public.current_account_id())
    with check (account_id = public.current_account_id());

create policy "Shadchanim scoped to account" on public.shadchanim
    for all to authenticated
    using (account_id = public.current_account_id())
    with check (account_id = public.current_account_id());

create policy "References scoped to account" on public."references"
    for all to authenticated
    using (account_id = public.current_account_id())
    with check (account_id = public.current_account_id());

create policy "Shidduchim scoped to account" on public.shidduchim
    for all to authenticated
    using (account_id = public.current_account_id())
    with check (account_id = public.current_account_id());

create policy "Resumes scoped to account" on public.resumes
    for all to authenticated
    using (account_id = public.current_account_id())
    with check (account_id = public.current_account_id());

create policy "Reference links scoped to account" on public.reference_links
    for all to authenticated
    using (account_id = public.current_account_id())
    with check (account_id = public.current_account_id());

create policy "Date records scoped to account" on public.date_records
    for all to authenticated
    using (account_id = public.current_account_id())
    with check (account_id = public.current_account_id());

create policy "Pipeline transitions readable" on public.pipeline_transitions
    for select to authenticated
    using (true);

-- ---------------------------------------------------------------------------
-- Grants (revoke anon, grant authenticated + service_role) — F6
-- ---------------------------------------------------------------------------
revoke all on table public.accounts from anon;
grant all on table public.accounts to authenticated;
grant all on table public.accounts to service_role;

revoke all on table public.account_members from anon;
grant all on table public.account_members to authenticated;
grant all on table public.account_members to service_role;

revoke all on table public.children from anon;
grant all on table public.children to authenticated;
grant all on table public.children to service_role;

revoke all on table public.shadchanim from anon;
grant all on table public.shadchanim to authenticated;
grant all on table public.shadchanim to service_role;

revoke all on table public."references" from anon;
grant all on table public."references" to authenticated;
grant all on table public."references" to service_role;

revoke all on table public.shidduchim from anon;
grant all on table public.shidduchim to authenticated;
grant all on table public.shidduchim to service_role;

revoke all on table public.resumes from anon;
grant all on table public.resumes to authenticated;
grant all on table public.resumes to service_role;

revoke all on table public.reference_links from anon;
grant all on table public.reference_links to authenticated;
grant all on table public.reference_links to service_role;

revoke all on table public.date_records from anon;
grant all on table public.date_records to authenticated;
grant all on table public.date_records to service_role;

revoke all on table public.pipeline_transitions from anon;
grant select on table public.pipeline_transitions to authenticated;
grant all on table public.pipeline_transitions to service_role;

revoke all on table public.shidduchim_summary from anon;
grant all on table public.shidduchim_summary to authenticated;
grant all on table public.shidduchim_summary to service_role;

revoke all on sequence public.accounts_id_seq from anon;
grant all on sequence public.accounts_id_seq to authenticated;
grant all on sequence public.accounts_id_seq to service_role;

revoke all on sequence public.account_members_id_seq from anon;
grant all on sequence public.account_members_id_seq to authenticated;
grant all on sequence public.account_members_id_seq to service_role;

revoke all on sequence public.children_id_seq from anon;
grant all on sequence public.children_id_seq to authenticated;
grant all on sequence public.children_id_seq to service_role;

revoke all on sequence public.shadchanim_id_seq from anon;
grant all on sequence public.shadchanim_id_seq to authenticated;
grant all on sequence public.shadchanim_id_seq to service_role;

revoke all on sequence public.references_id_seq from anon;
grant all on sequence public.references_id_seq to authenticated;
grant all on sequence public.references_id_seq to service_role;

revoke all on sequence public.shidduchim_id_seq from anon;
grant all on sequence public.shidduchim_id_seq to authenticated;
grant all on sequence public.shidduchim_id_seq to service_role;

revoke all on sequence public.resumes_id_seq from anon;
grant all on sequence public.resumes_id_seq to authenticated;
grant all on sequence public.resumes_id_seq to service_role;

revoke all on sequence public.reference_links_id_seq from anon;
grant all on sequence public.reference_links_id_seq to authenticated;
grant all on sequence public.reference_links_id_seq to service_role;

revoke all on sequence public.date_records_id_seq from anon;
grant all on sequence public.date_records_id_seq to authenticated;
grant all on sequence public.date_records_id_seq to service_role;

revoke all on function public.current_account_id() from anon;
grant execute on function public.current_account_id() to authenticated;
grant execute on function public.current_account_id() to service_role;

revoke all on function public.is_child_visible_state(public.pipeline_state) from anon;
grant execute on function public.is_child_visible_state(public.pipeline_state) to authenticated;
grant execute on function public.is_child_visible_state(public.pipeline_state) to service_role;

revoke all on function public.enforce_pipeline_transition() from anon;
grant execute on function public.enforce_pipeline_transition() to authenticated;
grant execute on function public.enforce_pipeline_transition() to service_role;

revoke all on function public.set_account_id_default() from anon;
grant execute on function public.set_account_id_default() to authenticated;
grant execute on function public.set_account_id_default() to service_role;

revoke all on function public.enforce_shidduch_initial_state() from anon;
grant execute on function public.enforce_shidduch_initial_state() to authenticated;
grant execute on function public.enforce_shidduch_initial_state() to service_role;

revoke all on function public.create_shidduch(bigint, bigint, text, text, text, text, text, text, text, text, text, text, integer, text, text, public.pipeline_state, text, date) from anon;
grant execute on function public.create_shidduch(bigint, bigint, text, text, text, text, text, text, text, text, text, text, integer, text, text, public.pipeline_state, text, date) to authenticated;
grant execute on function public.create_shidduch(bigint, bigint, text, text, text, text, text, text, text, text, text, text, integer, text, text, public.pipeline_state, text, date) to service_role;

revoke all on function public.transition_shidduch(bigint, public.pipeline_state, public.pipeline_state, text) from anon;
grant execute on function public.transition_shidduch(bigint, public.pipeline_state, public.pipeline_state, text) to authenticated;
grant execute on function public.transition_shidduch(bigint, public.pipeline_state, public.pipeline_state, text) to service_role;

-- ---------------------------------------------------------------------------
-- Seed: default account (v1 tenant) + the transition graph (as data)
-- ---------------------------------------------------------------------------
insert into public.accounts (name)
select 'Default Account'
where not exists (select 1 from public.accounts);

insert into public.pipeline_transitions (from_state, to_state) values
    ('new', 'look_into'),
    ('new', 'not_sure'),
    ('new', 'for_sure_not'),
    ('not_sure', 'look_into'),
    ('not_sure', 'for_sure_not'),
    ('look_into', 'yes'),
    ('look_into', 'unsure'),
    ('look_into', 'no')
on conflict do nothing;
