revoke insert on table "public"."shadchanim" from "authenticated";

revoke update on table "public"."shadchanim" from "authenticated";

-- MANUAL ADJUSTMENT (see AGENTS.md). `db diff` cannot express a column-list
-- grant — it only ever emits the table-level revoke above. Story 8.2:
-- shadchanim.connection_id is set ONLY by accept_connection_invite()
-- (SECURITY DEFINER) — never client-writable. `id`/`created_at` need no
-- INSERT grant (both have defaults).
grant insert (account_id, name, name_he, location, contacts, responsiveness)
  on "public"."shadchanim" to "authenticated";

grant update (name, name_he, location, contacts, responsiveness)
  on "public"."shadchanim" to "authenticated";


  create table "public"."connection_invites" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "inviter_account_id" bigint not null,
    "inviter_kind" text not null,
    "token_hash" text not null,
    "status" text not null default 'pending'::text,
    "expires_at" timestamp with time zone not null,
    "accepted_by_account_id" bigint,
    "accepted_at" timestamp with time zone,
    "revoked_at" timestamp with time zone
      );


alter table "public"."connection_invites" enable row level security;

-- MANUAL ADJUSTMENT: `db diff` emitted ENABLE but not FORCE. Story 7.1's
-- FORCE decision (05_policies.sql's own header on that story's block)
-- applies here too — a brand-new table, no legacy caller relying on
-- owner-bypass.
alter table "public"."connection_invites" force row level security;

-- MANUAL ADJUSTMENT (see AGENTS.md / COLUMN-ORDER TRAP, 01_tables.sql):
-- `db diff` emitted these three new `connections` columns in alphabetical
-- order (accepted_at, ended_by_account_id, proposed_by_account_id) instead
-- of 01_tables.sql's declared physical order. Reordered here so this
-- migration's ADD COLUMNs — which always append to the physical tail —
-- produce the exact attnum order the schema file declares; otherwise the
-- very next `db diff` sees a mismatched column order and emits spurious
-- view drops forever (01_tables.sql's own COLUMN-ORDER TRAP header).
--
-- `proposed_by_account_id` also cannot go straight to NOT NULL in one
-- statement: this table already carries rows on a production-shaped
-- database (the migration-data-safety fixture's own seed, and this repo's
-- pre-existing SQL test suites) — added nullable, backfilled from
-- `household_account_id` (the best available default for a row that
-- predates this column; the real write path, accept_connection_invite(),
-- always supplies the true proposer explicitly and never relies on this
-- default), and only THEN set NOT NULL. Rehearsed against a
-- production-shaped non-empty database via `make check-migration-safety`.
alter table "public"."connections" add column "proposed_by_account_id" bigint;

alter table "public"."connections" add column "accepted_at" timestamp with time zone;

alter table "public"."connections" add column "ended_by_account_id" bigint;

update "public"."connections"
   set "proposed_by_account_id" = "household_account_id"
 where "proposed_by_account_id" is null;

alter table "public"."connections" alter column "proposed_by_account_id" set not null;

alter table "public"."shadchanim" add column "connection_id" bigint;

CREATE UNIQUE INDEX connection_invites_pkey ON public.connection_invites USING btree (id);

CREATE UNIQUE INDEX connection_invites_token_hash_key ON public.connection_invites USING btree (token_hash);

CREATE UNIQUE INDEX shadchanim_connection_id_key ON public.shadchanim USING btree (connection_id);

alter table "public"."connection_invites" add constraint "connection_invites_pkey" PRIMARY KEY using index "connection_invites_pkey";

alter table "public"."connection_invites" add constraint "connection_invites_accepted_by_account_id_fkey" FOREIGN KEY (accepted_by_account_id) REFERENCES public.accounts(id) not valid;

alter table "public"."connection_invites" validate constraint "connection_invites_accepted_by_account_id_fkey";

alter table "public"."connection_invites" add constraint "connection_invites_inviter_account_id_fkey" FOREIGN KEY (inviter_account_id) REFERENCES public.accounts(id) not valid;

alter table "public"."connection_invites" validate constraint "connection_invites_inviter_account_id_fkey";

alter table "public"."connection_invites" add constraint "connection_invites_inviter_kind_check" CHECK ((inviter_kind = ANY (ARRAY['household'::text, 'shadchanus'::text]))) not valid;

alter table "public"."connection_invites" validate constraint "connection_invites_inviter_kind_check";

alter table "public"."connection_invites" add constraint "connection_invites_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'revoked'::text, 'expired'::text]))) not valid;

alter table "public"."connection_invites" validate constraint "connection_invites_status_check";

alter table "public"."connection_invites" add constraint "connection_invites_token_hash_key" UNIQUE using index "connection_invites_token_hash_key";

alter table "public"."connections" add constraint "connections_ended_by_account_id_fkey" FOREIGN KEY (ended_by_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL not valid;

alter table "public"."connections" validate constraint "connections_ended_by_account_id_fkey";

alter table "public"."connections" add constraint "connections_ended_consistency" CHECK (((status = 'ended'::text) = (ended_at IS NOT NULL))) not valid;

alter table "public"."connections" validate constraint "connections_ended_consistency";

alter table "public"."connections" add constraint "connections_proposed_by_account_id_fkey" FOREIGN KEY (proposed_by_account_id) REFERENCES public.accounts(id) not valid;

alter table "public"."connections" validate constraint "connections_proposed_by_account_id_fkey";

alter table "public"."shadchanim" add constraint "shadchanim_connection_id_fkey" FOREIGN KEY (connection_id) REFERENCES public.connections(id) not valid;

alter table "public"."shadchanim" validate constraint "shadchanim_connection_id_fkey";

alter table "public"."shadchanim" add constraint "shadchanim_connection_id_key" UNIQUE using index "shadchanim_connection_id_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.accept_connection_invite(p_token text)
 RETURNS public.connections
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_invite public.connection_invites;
  v_acceptor_account_id bigint := public.current_context_id();
  v_acceptor_kind text;
  v_household_account_id bigint;
  v_shadchanus_account_id bigint;
  v_shadchanus_name text;
  v_connection public.connections;
begin
  select * into v_invite
  from public.connection_invites
  where token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
  for update;

  if not found or v_invite.status <> 'pending' or v_invite.expires_at <= now() then
    raise exception 'This connection invite is invalid, expired, or has already been used.'
      using errcode = 'check_violation';
  end if;

  if v_acceptor_account_id is null or not exists (
    select 1 from public.account_members am
    where am.account_id = v_acceptor_account_id and am.user_id = auth.uid() and am.status = 'active'
  ) then
    raise exception 'accept_connection_invite requires an active membership of the current context'
      using errcode = 'insufficient_privilege';
  end if;

  select kind into v_acceptor_kind from public.accounts where id = v_acceptor_account_id;

  if v_acceptor_kind = v_invite.inviter_kind then
    raise exception 'a connection links a household and a shadchanus context, not two of the same kind'
      using errcode = 'check_violation';
  end if;

  if v_acceptor_kind = 'household' then
    v_household_account_id := v_acceptor_account_id;
    v_shadchanus_account_id := v_invite.inviter_account_id;
  else
    v_household_account_id := v_invite.inviter_account_id;
    v_shadchanus_account_id := v_acceptor_account_id;
  end if;

  insert into public.connections (
    household_account_id, shadchanus_account_id, status,
    proposed_by_account_id, accepted_at
  ) values (
    v_household_account_id, v_shadchanus_account_id, 'accepted',
    v_invite.inviter_account_id, now()
  )
  returning * into v_connection;

  select name into v_shadchanus_name from public.accounts where id = v_shadchanus_account_id;

  insert into public.shadchanim (account_id, name, connection_id)
  values (v_household_account_id, v_shadchanus_name, v_connection.id);

  update public.connection_invites
  set status = 'accepted', accepted_by_account_id = v_acceptor_account_id, accepted_at = now()
  where id = v_invite.id;

  return v_connection;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.create_connection_invite()
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint := public.current_context_id();
  v_kind text;
  v_token text;
begin
  if v_account_id is null or not exists (
    select 1 from public.account_members am
    where am.account_id = v_account_id and am.user_id = auth.uid() and am.status = 'active'
  ) then
    raise exception 'create_connection_invite requires an active membership of the current context'
      using errcode = 'insufficient_privilege';
  end if;

  select kind into v_kind from public.accounts where id = v_account_id;
  v_token := encode(extensions.gen_random_bytes(32), 'hex');

  insert into public.connection_invites (
    inviter_account_id, inviter_kind, token_hash, expires_at
  ) values (
    v_account_id, v_kind,
    encode(extensions.digest(v_token, 'sha256'), 'hex'),
    now() + interval '7 days'
  );

  return v_token;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.end_connection(p_connection_id bigint)
 RETURNS public.connections
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_connection public.connections;
begin
  select * into v_connection from public.connections where id = p_connection_id;

  if not found or not exists (
    select 1 from public.account_members am
    where am.user_id = auth.uid()
      and am.status = 'active'
      and am.account_id in (v_connection.household_account_id, v_connection.shadchanus_account_id)
  ) then
    raise exception 'connection % not found', p_connection_id;
  end if;

  if v_connection.status = 'ended' then
    raise exception 'connection % has already ended', p_connection_id
      using errcode = 'check_violation';
  end if;

  update public.connections
  set status = 'ended', ended_at = now(), ended_by_account_id = public.current_context_id()
  where id = p_connection_id
  returning * into v_connection;

  return v_connection;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.preview_connection_invite(p_token text)
 RETURNS TABLE(inviter_name text, inviter_kind text, status text, expires_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select a.name, ci.inviter_kind, ci.status, ci.expires_at
  from public.connection_invites ci
  join public.accounts a on a.id = ci.inviter_account_id
  where ci.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and ci.status = 'pending'
    and ci.expires_at > now();
$function$
;

CREATE OR REPLACE FUNCTION public.revoke_connection_invite(p_invite_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_invite public.connection_invites;
begin
  select * into v_invite from public.connection_invites where id = p_invite_id;

  if not found or not exists (
    select 1 from public.account_members am
    where am.account_id = v_invite.inviter_account_id and am.user_id = auth.uid() and am.status = 'active'
  ) then
    raise exception 'connection invite % not found', p_invite_id;
  end if;

  if v_invite.status <> 'pending' then
    raise exception 'connection invite % is not pending (status %)', p_invite_id, v_invite.status
      using errcode = 'check_violation';
  end if;

  update public.connection_invites
  set status = 'revoked', revoked_at = now()
  where id = p_invite_id;
end;
$function$
;

-- MANUAL ADJUSTMENT (see AGENTS.md): `db diff` emitted only the additive
-- grants below — never the `revoke all ... from anon, authenticated` that
-- 06_grants.sql declares first. Without it, this table's default privilege
-- (`alter default privileges ... grant all on tables to authenticated`,
-- top of 06_grants.sql) would leave `authenticated` with INSERT/UPDATE/
-- DELETE/TRUNCATE/REFERENCES/TRIGGER on a table this story's Task 2
-- deliberately gives no client write path at all — the same no-client-write
-- posture 7.4 set for `connections`.
revoke all on table "public"."connection_invites" from "anon", "authenticated";

grant select on table "public"."connection_invites" to "authenticated";

grant delete on table "public"."connection_invites" to "service_role";

grant insert on table "public"."connection_invites" to "service_role";

grant references on table "public"."connection_invites" to "service_role";

grant select on table "public"."connection_invites" to "service_role";

grant trigger on table "public"."connection_invites" to "service_role";

grant truncate on table "public"."connection_invites" to "service_role";

grant update on table "public"."connection_invites" to "service_role";

-- MANUAL ADJUSTMENT: `db diff` emitted no sequence grant/revoke at all for
-- the identity column's own `connection_invites_id_seq` — mirrors
-- `connections_id_seq`'s own hand-added block in 20260731181450_thread_model.sql.
-- No `authenticated` grant — `authenticated` cannot insert into
-- connection_invites at all (no INSERT policy, no INSERT grant above).
revoke all on sequence "public"."connection_invites_id_seq" from "anon", "authenticated";

grant all on sequence "public"."connection_invites_id_seq" to "service_role";

-- MANUAL ADJUSTMENT: `db diff` emitted no function-grant DDL at all for any
-- of the five new functions — same gap `20260731181450_thread_model.sql`
-- hand-fixed for `thread_is_readable`/`create_thread`. `authenticated` only,
-- never `anon` (AD-1): accepting requires already being logged in with the
-- opposite-kind context active.
revoke all on function "public"."create_connection_invite"() from "public", "anon";

grant execute on function "public"."create_connection_invite"() to "authenticated";

grant execute on function "public"."create_connection_invite"() to "service_role";

revoke all on function "public"."revoke_connection_invite"(bigint) from "public", "anon";

grant execute on function "public"."revoke_connection_invite"(bigint) to "authenticated";

grant execute on function "public"."revoke_connection_invite"(bigint) to "service_role";

revoke all on function "public"."preview_connection_invite"(text) from "public", "anon";

grant execute on function "public"."preview_connection_invite"(text) to "authenticated";

grant execute on function "public"."preview_connection_invite"(text) to "service_role";

revoke all on function "public"."accept_connection_invite"(text) from "public", "anon";

grant execute on function "public"."accept_connection_invite"(text) to "authenticated";

grant execute on function "public"."accept_connection_invite"(text) to "service_role";

revoke all on function "public"."end_connection"(bigint) from "public", "anon";

grant execute on function "public"."end_connection"(bigint) to "authenticated";

grant execute on function "public"."end_connection"(bigint) to "service_role";


  create policy "Connection invites visible to their issuer"
  on "public"."connection_invites"
  as permissive
  for select
  to authenticated
using ((inviter_account_id = public.current_context_id()));
