
  create table "public"."share_access_log" (
    "id" bigint generated by default as identity not null,
    "share_link_id" bigint not null,
    "accessed_at" timestamp with time zone not null default now(),
    "resource" text not null,
    "ip_hash" text,
    "user_agent" text,
    "duration_ms" integer
      );


alter table "public"."share_access_log" enable row level security;

alter table "public"."share_access_log" force row level security;


  create table "public"."share_links" (
    "id" bigint generated by default as identity not null,
    "account_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "single_id" bigint not null,
    "created_by_member_id" bigint,
    "token" text not null,
    "include_photo" boolean not null default false,
    "expires_at" timestamp with time zone not null,
    "revoked_at" timestamp with time zone
      );


alter table "public"."share_links" enable row level security;

alter table "public"."share_links" force row level security;

CREATE UNIQUE INDEX share_access_log_pkey ON public.share_access_log USING btree (id);

CREATE INDEX share_access_log_share_link_id_idx ON public.share_access_log USING btree (share_link_id);

CREATE INDEX share_links_account_id_idx ON public.share_links USING btree (account_id);

CREATE UNIQUE INDEX share_links_pkey ON public.share_links USING btree (id);

CREATE UNIQUE INDEX share_links_token_key ON public.share_links USING btree (token);

alter table "public"."share_access_log" add constraint "share_access_log_pkey" PRIMARY KEY using index "share_access_log_pkey";

alter table "public"."share_links" add constraint "share_links_pkey" PRIMARY KEY using index "share_links_pkey";

alter table "public"."share_access_log" add constraint "share_access_log_share_link_id_fkey" FOREIGN KEY (share_link_id) REFERENCES public.share_links(id) ON DELETE CASCADE not valid;

alter table "public"."share_access_log" validate constraint "share_access_log_share_link_id_fkey";

alter table "public"."share_links" add constraint "share_links_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."share_links" validate constraint "share_links_account_id_fkey";

alter table "public"."share_links" add constraint "share_links_created_by_member_id_fkey" FOREIGN KEY (created_by_member_id) REFERENCES public.account_members(id) ON DELETE SET NULL not valid;

alter table "public"."share_links" validate constraint "share_links_created_by_member_id_fkey";

alter table "public"."share_links" add constraint "share_links_single_id_fkey" FOREIGN KEY (account_id, single_id) REFERENCES public.singles(account_id, id) ON DELETE CASCADE not valid;

alter table "public"."share_links" validate constraint "share_links_single_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.enforce_share_link_revoke_once()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if old.revoked_at is not null
     and new.revoked_at is distinct from old.revoked_at then
    raise exception 'a revoked share link cannot be un-revoked';
  end if;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_share_link_token_defaults()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if new.account_id is null then
    new.account_id := public.current_context_id();
  end if;
  new.token := encode(extensions.gen_random_bytes(24), 'hex');
  return new;
end;
$function$
;

-- Hand-verified against 06_grants.sql (AGENTS.md: `db diff` never re-emits
-- grants correctly for this kind of narrowing — it emitted verb-by-verb
-- `authenticated`/`service_role` grants above with no `revoke`, no
-- column-level `update`, and no sequence privileges at all; replaced here
-- with the exact statements the schema file declares). AC-10: `anon` never
-- appears in any grant on either table.
revoke all on table public.share_links from anon, authenticated;
grant select, insert on table public.share_links to authenticated;
grant update (revoked_at) on table public.share_links to authenticated;
grant all on table public.share_links to service_role;

revoke all on sequence public.share_links_id_seq from anon;
grant usage, select on sequence public.share_links_id_seq to authenticated;
grant all on sequence public.share_links_id_seq to service_role;

revoke all on table public.share_access_log from anon, authenticated;
grant select on table public.share_access_log to authenticated;
grant all on table public.share_access_log to service_role;

revoke all on sequence public.share_access_log_id_seq from anon;
grant all on sequence public.share_access_log_id_seq to service_role;


  create policy "Share access log readable by link owner"
  on "public"."share_access_log"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.share_links sl
  WHERE ((sl.id = share_access_log.share_link_id) AND (sl.account_id = public.current_context_id())))));



  create policy "Share links manager scoped"
  on "public"."share_links"
  as permissive
  for all
  to authenticated
using (((account_id = public.current_context_id()) AND ((EXISTS ( SELECT 1
   FROM public.account_members am
  WHERE ((am.account_id = public.current_context_id()) AND (am.user_id = auth.uid()) AND (am.role = 'parent_admin'::text)))) OR (EXISTS ( SELECT 1
   FROM (public.account_members am
     JOIN public.singles s ON ((s.member_id = am.id)))
  WHERE ((am.account_id = public.current_context_id()) AND (am.user_id = auth.uid()) AND (am.role = 'self_manager'::text) AND (s.id = share_links.single_id)))))))
with check (((account_id = public.current_context_id()) AND ((EXISTS ( SELECT 1
   FROM public.account_members am
  WHERE ((am.account_id = public.current_context_id()) AND (am.user_id = auth.uid()) AND (am.role = 'parent_admin'::text)))) OR (EXISTS ( SELECT 1
   FROM (public.account_members am
     JOIN public.singles s ON ((s.member_id = am.id)))
  WHERE ((am.account_id = public.current_context_id()) AND (am.user_id = auth.uid()) AND (am.role = 'self_manager'::text) AND (s.id = share_links.single_id)))))));


CREATE TRIGGER enforce_share_link_revoke_once BEFORE UPDATE ON public.share_links FOR EACH ROW EXECUTE FUNCTION public.enforce_share_link_revoke_once();

CREATE TRIGGER set_share_link_token_defaults BEFORE INSERT ON public.share_links FOR EACH ROW EXECUTE FUNCTION public.set_share_link_token_defaults();


