-- R16 lifecycle fences: empty-account coverage, storage TOCTOU protection,
-- and durable inbound-ingest claims.

create table public.demo_run_ingest_claims (
    id bigint generated by default as identity primary key,
    run_id bigint,
    account_id bigint not null,
    claim_token_hash text not null,
    state text not null default 'active',
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    expires_at timestamp with time zone not null,
    released_at timestamp with time zone,
    constraint demo_run_ingest_claims_state_check check (state in ('active', 'released', 'expired')),
    constraint demo_run_ingest_claims_token_key unique (account_id, claim_token_hash),
    constraint demo_run_ingest_claims_run_id_fkey
      foreign key (run_id) references public.demo_runs(id) on delete cascade,
    constraint demo_run_ingest_claims_account_id_fkey
      foreign key (account_id) references public.accounts(id) on delete cascade
);

create index demo_run_ingest_claims_run_idx
    on public.demo_run_ingest_claims (run_id, state, expires_at);
create index demo_run_ingest_claims_account_idx
    on public.demo_run_ingest_claims (account_id, state, expires_at);

alter table public.demo_run_ingest_claims enable row level security;
alter table public.demo_run_ingest_claims force row level security;

create or replace function public.demo_assert_empty_account(p_account_id bigint)
returns void
language plpgsql security definer
set search_path to ''
as $$
begin
  if not exists (
    select 1 from public.accounts
    where id = p_account_id and kind = 'household'
  ) then
    raise exception 'demo root account % must be a household context', p_account_id
      using errcode = 'check_violation';
  end if;

  if exists (select 1 from public.singles where account_id = p_account_id)
     or exists (select 1 from public.single_preferences where account_id = p_account_id)
     or exists (select 1 from public.single_notes where account_id = p_account_id)
     or exists (select 1 from public.shadchanim where account_id = p_account_id)
     or exists (select 1 from public.references where account_id = p_account_id)
     or exists (select 1 from public.shidduchim where account_id = p_account_id)
     or exists (select 1 from public.inbox_items where account_id = p_account_id)
     or exists (select 1 from public.message_notifications where account_id = p_account_id)
     or exists (select 1 from public.task_notifications where account_id = p_account_id)
     or exists (select 1 from public.messages where account_id = p_account_id)
     or exists (select 1 from public.threads where account_id = p_account_id)
     or exists (select 1 from public.thread_participants where account_id = p_account_id)
     or exists (select 1 from public.tasks where account_id = p_account_id)
     or exists (select 1 from public.reference_links where account_id = p_account_id)
     or exists (select 1 from public.redts where account_id = p_account_id)
     or exists (select 1 from public.shidduch_education where account_id = p_account_id)
     or exists (select 1 from public.resume_photos where account_id = p_account_id)
     or exists (select 1 from public.resumes where account_id = p_account_id)
     or exists (select 1 from public.entity_files where account_id = p_account_id)
     or exists (select 1 from public.medical_notes where account_id = p_account_id)
     or exists (select 1 from public.shidduchim_external_links where account_id = p_account_id)
     or exists (select 1 from public.date_records where account_id = p_account_id)
     or exists (select 1 from public.interactions where account_id = p_account_id)
     or exists (select 1 from public.identity_signals where account_id = p_account_id)
     or exists (select 1 from public.listing_withdrawal_locks where account_id = p_account_id)
     or exists (select 1 from public.listings where account_id = p_account_id)
     or exists (select 1 from public.invites where account_id = p_account_id)
     or exists (select 1 from public.analytics_events where account_id = p_account_id)
     or exists (select 1 from public.trusted_senders where account_id = p_account_id)
     or exists (select 1 from public.share_links where account_id = p_account_id)
     or exists (
       select 1 from public.connections
       where household_account_id = p_account_id
          or shadchanus_account_id = p_account_id
     )
     or exists (
       select 1 from public.connection_invites
       where inviter_account_id = p_account_id
          or accepted_by_account_id = p_account_id
     )
     or exists (
       select 1 from public.child_grants
       where proposer_account_id = p_account_id
          or grantee_account_id = p_account_id
     )
     or exists (
       select 1 from public.messages m
       join public.connections c on c.id = m.connection_id
       where c.household_account_id = p_account_id
          or c.shadchanus_account_id = p_account_id
     )
     or exists (
       select 1 from public.threads t
       join public.connections c on c.id = t.connection_id
       where c.household_account_id = p_account_id
          or c.shadchanus_account_id = p_account_id
     )
     or exists (
       select 1 from public.thread_participants tp
       join public.connections c on c.id = tp.connection_id
       where c.household_account_id = p_account_id
          or c.shadchanus_account_id = p_account_id
     )
     or exists (
       select 1 from public.message_notifications mn
       join public.connections c on c.id = mn.connection_id
       where c.household_account_id = p_account_id
          or c.shadchanus_account_id = p_account_id
     )
     or exists (
       select 1
       from storage.objects
       where bucket_id in ('documents', 'entity-files', 'attachments')
         and (name = p_account_id::text or name like p_account_id::text || '/%')
     ) then
    raise exception 'demo root account % is not empty', p_account_id
      using errcode = 'check_violation';
  end if;
end;
$$;

create or replace function public.demo_storage_write_fence(p_account_id bigint)
returns boolean
language plpgsql volatile security definer
set search_path to ''
as $$
declare
  v_account_id bigint;
begin
  select id into v_account_id
  from public.accounts
  where id = p_account_id
  for key share;
  if v_account_id is null then
    return false;
  end if;
  return public.demo_seed_service_authorized(p_account_id)
    or not exists (
      select 1 from public.demo_run_accounts dra
      join public.demo_runs dr on dr.id = dra.run_id
      where dra.account_id = p_account_id
        and dr.status in ('seeding', 'active', 'clearing', 'failed')
    )
    or exists (
      select 1 from public.demo_run_accounts dra
      join public.demo_runs dr on dr.id = dra.run_id
      where dra.account_id = p_account_id and dr.status = 'active'
    );
end;
$$;

create or replace function public.demo_storage_write_allowed(p_account_id bigint)
returns boolean
language sql volatile security definer
set search_path to ''
as $$
  select public.demo_storage_write_fence(p_account_id);
$$;

create or replace function public.claim_demo_ingest(
    p_account_id bigint,
    p_claim_token text,
    p_ttl_seconds integer default 300
) returns jsonb
language plpgsql volatile security definer
set search_path to ''
as $$
declare
  v_account_id bigint;
  v_run_id bigint;
  v_status text;
  v_hash text;
  v_expires_at timestamp with time zone;
  v_ttl integer := greatest(30, least(coalesce(p_ttl_seconds, 300), 900));
begin
  if p_claim_token is null or length(p_claim_token) < 16 or length(p_claim_token) > 256 then
    raise exception 'invalid demo ingest claim token' using errcode = '22023';
  end if;
  select id into v_account_id
  from public.accounts
  where id = p_account_id
  for key share;
  if v_account_id is null then
    raise exception 'demo ingest account does not exist' using errcode = 'foreign_key_violation';
  end if;
  select dr.id, dr.status
    into v_run_id, v_status
  from public.demo_run_accounts dra
  join public.demo_runs dr on dr.id = dra.run_id
  where dra.account_id = p_account_id
    and dr.status in ('seeding', 'active', 'clearing', 'failed')
  order by dr.id desc
  limit 1;
  if v_run_id is not null then
    return jsonb_build_object('outcome', 'blocked');
  end if;
  v_hash := encode(extensions.digest(p_claim_token, 'sha256'), 'hex');
  v_expires_at := clock_timestamp() + make_interval(secs => v_ttl);
  insert into public.demo_run_ingest_claims (
    run_id, account_id, claim_token_hash, state, updated_at, expires_at, released_at
  ) values (
    null, p_account_id, v_hash, 'active', clock_timestamp(), v_expires_at, null
  )
  on conflict (account_id, claim_token_hash) do update
    set account_id = excluded.account_id,
        state = 'active',
        updated_at = excluded.updated_at,
        expires_at = excluded.expires_at,
        released_at = null;
  return jsonb_build_object('outcome', 'claimed', 'run_id', null, 'expires_at', v_expires_at);
end;
$$;

create or replace function public.heartbeat_demo_ingest_claim(
    p_account_id bigint,
    p_claim_token text,
    p_ttl_seconds integer default 300
) returns boolean
language plpgsql volatile security definer
set search_path to ''
as $$
declare
  v_hash text;
  v_ttl integer := greatest(30, least(coalesce(p_ttl_seconds, 300), 900));
begin
  if p_claim_token is null or length(p_claim_token) < 16 or length(p_claim_token) > 256 then
    return false;
  end if;
  v_hash := encode(extensions.digest(p_claim_token, 'sha256'), 'hex');
  update public.demo_run_ingest_claims
  set updated_at = clock_timestamp(), expires_at = clock_timestamp() + make_interval(secs => v_ttl)
  where account_id = p_account_id and claim_token_hash = v_hash
    and state = 'active' and expires_at > clock_timestamp();
  return found;
end;
$$;

create or replace function public.release_demo_ingest_claim(
    p_account_id bigint,
    p_claim_token text
) returns boolean
language plpgsql volatile security definer
set search_path to ''
as $$
declare
  v_hash text;
begin
  if p_claim_token is null or length(p_claim_token) < 16 or length(p_claim_token) > 256 then
    return false;
  end if;
  v_hash := encode(extensions.digest(p_claim_token, 'sha256'), 'hex');
  delete from public.demo_run_ingest_claims
  where account_id = p_account_id and claim_token_hash = v_hash;
  if found then
    return true;
  end if;
  return true;
end;
$$;

create or replace function public.wait_for_demo_ingest_claims(
    p_run_id bigint,
    p_lease_token text,
    p_timeout_seconds integer default 30
) returns boolean
language plpgsql volatile security definer
set search_path to ''
as $$
declare
  v_deadline timestamp with time zone := clock_timestamp()
    + make_interval(secs => greatest(1, least(coalesce(p_timeout_seconds, 30), 120)));
  v_active integer;
begin
  loop
    if not public.demo_run_lease_is_current(p_run_id, p_lease_token, 'clear') then
      raise exception 'demo ingest wait lost the clear lease' using errcode = '55000';
    end if;
    if exists (
      select 1 from public.demo_run_ingest_claims
      where state = 'active' and expires_at <= clock_timestamp()
        and (run_id = p_run_id or account_id in (
          select account_id from public.demo_run_accounts where run_id = p_run_id
        ))
    ) then
      raise exception 'stale demo ingest claim blocks clear' using errcode = '55P03';
    end if;
    select count(*)::integer into v_active
    from public.demo_run_ingest_claims
    where state = 'active' and (run_id = p_run_id or account_id in (
      select account_id from public.demo_run_accounts where run_id = p_run_id
    ));
    delete from public.demo_run_ingest_claims
    where state in ('released', 'expired')
      and (run_id = p_run_id or account_id in (
        select account_id from public.demo_run_accounts where run_id = p_run_id
      ));
    if v_active = 0 then return true; end if;
    if clock_timestamp() >= v_deadline then
      raise exception 'demo ingest claims are still active' using errcode = '55P03';
    end if;
    perform pg_sleep(0.05);
  end loop;
end;
$$;

create or replace function public.wait_for_demo_ingest_account_claims(
    p_account_id bigint,
    p_timeout_seconds integer default 30
) returns boolean
language plpgsql volatile security definer
set search_path to ''
as $$
declare
  v_deadline timestamp with time zone := clock_timestamp()
    + make_interval(secs => greatest(1, least(coalesce(p_timeout_seconds, 30), 120)));
  v_active integer;
begin
  loop
    if exists (
      select 1 from public.demo_run_ingest_claims
      where account_id = p_account_id and state = 'active'
        and expires_at <= clock_timestamp()
    ) then
      raise exception 'stale ordinary ingest claim blocks demo seed' using errcode = '55P03';
    end if;
    delete from public.demo_run_ingest_claims
    where account_id = p_account_id and state in ('released', 'expired');
    select count(*)::integer into v_active
    from public.demo_run_ingest_claims
    where account_id = p_account_id and state = 'active';
    if v_active = 0 then return true; end if;
    if clock_timestamp() >= v_deadline then
      raise exception 'ordinary ingest claims are still active' using errcode = '55P03';
    end if;
    perform pg_sleep(0.05);
  end loop;
end;
$$;

revoke all on table public.demo_run_ingest_claims from anon, authenticated;
grant all on table public.demo_run_ingest_claims to service_role;
grant all on sequence public.demo_run_ingest_claims_id_seq to service_role;
revoke all on function public.demo_storage_write_fence(bigint) from public, anon, authenticated;
grant execute on function public.demo_storage_write_fence(bigint) to service_role;
revoke all on function public.claim_demo_ingest(bigint, text, integer) from public, anon, authenticated;
grant execute on function public.claim_demo_ingest(bigint, text, integer) to service_role;
revoke all on function public.heartbeat_demo_ingest_claim(bigint, text, integer) from public, anon, authenticated;
grant execute on function public.heartbeat_demo_ingest_claim(bigint, text, integer) to service_role;
revoke all on function public.release_demo_ingest_claim(bigint, text) from public, anon, authenticated;
grant execute on function public.release_demo_ingest_claim(bigint, text) to service_role;
revoke all on function public.wait_for_demo_ingest_claims(bigint, text, integer) from public, anon, authenticated;
grant execute on function public.wait_for_demo_ingest_claims(bigint, text, integer) to service_role;
revoke all on function public.wait_for_demo_ingest_account_claims(bigint, integer) from public, anon, authenticated;
grant execute on function public.wait_for_demo_ingest_account_claims(bigint, integer) to service_role;

create or replace function public.begin_demo_seed(
    p_root_account_id bigint,
    p_lease_token text default null
) returns jsonb
language plpgsql security definer
set search_path to ''
as $$
declare
  v_account public.accounts;
  v_run public.demo_runs;
  v_token text;
begin
  perform public.demo_lock_account_axes(array[p_root_account_id], 'update');
  perform public.wait_for_demo_ingest_account_claims(p_root_account_id, 30);
  select * into v_account from public.accounts where id = p_root_account_id;
  if not found then
    raise exception 'demo root account % not found', p_root_account_id
      using errcode = 'foreign_key_violation';
  end if;
  perform public.demo_assert_empty_account(p_root_account_id);
  if exists (
    select 1 from public.demo_runs
    where root_account_id = p_root_account_id
      and status in ('seeding', 'active', 'clearing', 'failed')
  ) then
    raise exception 'demo run already exists for root account %', p_root_account_id
      using errcode = 'unique_violation';
  end if;
  v_token := coalesce(nullif(p_lease_token, ''), gen_random_uuid()::text);
  insert into public.demo_runs (
    root_account_id, status, lease_token, lease_epoch, operation,
    lease_expires_at, original_root_name
  ) values (
    p_root_account_id, 'seeding', v_token, 1, 'seed',
    now() + interval '15 minutes', v_account.name
  ) returning * into v_run;
  insert into public.demo_run_accounts (
    run_id, account_id, context_key, context_kind, is_root
  ) values (
    v_run.id, p_root_account_id, 'primary-household', 'household', true
  );
  insert into public.demo_run_member_state (
    run_id, user_id, original_active_account_id, original_updated_at
  )
  select distinct on (am.user_id)
    v_run.id, am.user_id, ms.active_account_id, ms.updated_at
  from public.account_members am
  left join public.member_state ms on ms.user_id = am.user_id
  where am.account_id = p_root_account_id
    and am.status = 'active'
    and am.user_id is not null
  order by am.user_id, am.id;
  return jsonb_build_object(
    'run_id', v_run.id, 'lease_token', v_token,
    'lease_epoch', v_run.lease_epoch, 'original_root_name', v_account.name
  );
end;
$$;
