-- Story 14.4: The data subject's purge request (PRV-11)
-- Track purge requests from non-users (singles who never consented)
CREATE TABLE IF NOT EXISTS public.purge_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    single_name text NOT NULL,
    single_email text,
    status text NOT NULL DEFAULT 'pending', -- pending, verified, processed, rejected
    verification_token text,
    requested_at timestamp with time zone NOT NULL DEFAULT now(),
    verified_at timestamp with time zone,
    processed_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL DEFAULT (now() + interval '7 days'),
    matched_singles_count integer DEFAULT 0,
    matched_shidduchim_count integer DEFAULT 0,
    notified_accounts jsonb DEFAULT '[]'::jsonb,
    result jsonb DEFAULT '{}'::jsonb
);

-- Indexes for efficient querying
CREATE INDEX purge_requests_status_idx ON public.purge_requests(status);
CREATE INDEX purge_requests_verification_token_idx ON public.purge_requests(verification_token);
CREATE INDEX purge_requests_expires_at_idx ON public.purge_requests(expires_at);

-- Enable row level security
ALTER TABLE public.purge_requests ENABLE ROW LEVEL SECURITY;

-- Policies: service_role can do everything, anon can only insert (create requests)
CREATE POLICY "Service role has full access" ON public.purge_requests
    FOR ALL
    USING (current_user = 'postgres')
    WITH CHECK (current_user = 'postgres');

CREATE POLICY "Anon can create purge requests" ON public.purge_requests
    FOR INSERT
    WITH CHECK (true);