drop policy "Enable insert for authenticated users only" on "public"."tasks";

drop policy "Enable read access for authenticated users" on "public"."tasks";

drop policy "Task Delete Policy" on "public"."tasks";

drop policy "Task Update Policy" on "public"."tasks";

revoke references on table "public"."account_members" from "authenticated";

revoke trigger on table "public"."account_members" from "authenticated";

revoke truncate on table "public"."account_members" from "authenticated";

revoke references on table "public"."accounts" from "authenticated";

revoke trigger on table "public"."accounts" from "authenticated";

revoke truncate on table "public"."accounts" from "authenticated";

revoke references on table "public"."children" from "authenticated";

revoke trigger on table "public"."children" from "authenticated";

revoke truncate on table "public"."children" from "authenticated";

revoke references on table "public"."date_records" from "authenticated";

revoke trigger on table "public"."date_records" from "authenticated";

revoke truncate on table "public"."date_records" from "authenticated";

revoke references on table "public"."pipeline_transitions" from "authenticated";

revoke trigger on table "public"."pipeline_transitions" from "authenticated";

revoke truncate on table "public"."pipeline_transitions" from "authenticated";

revoke references on table "public"."redts" from "authenticated";

revoke trigger on table "public"."redts" from "authenticated";

revoke truncate on table "public"."redts" from "authenticated";

revoke references on table "public"."reference_links" from "authenticated";

revoke trigger on table "public"."reference_links" from "authenticated";

revoke truncate on table "public"."reference_links" from "authenticated";

revoke references on table "public"."references" from "authenticated";

revoke trigger on table "public"."references" from "authenticated";

revoke truncate on table "public"."references" from "authenticated";

revoke references on table "public"."resumes" from "authenticated";

revoke trigger on table "public"."resumes" from "authenticated";

revoke truncate on table "public"."resumes" from "authenticated";

revoke references on table "public"."shadchanim" from "authenticated";

revoke trigger on table "public"."shadchanim" from "authenticated";

revoke truncate on table "public"."shadchanim" from "authenticated";

revoke references on table "public"."shidduch_schools" from "authenticated";

revoke trigger on table "public"."shidduch_schools" from "authenticated";

revoke truncate on table "public"."shidduch_schools" from "authenticated";

revoke references on table "public"."shidduchim" from "authenticated";

revoke trigger on table "public"."shidduchim" from "authenticated";

revoke truncate on table "public"."shidduchim" from "authenticated";

revoke references on table "public"."tasks" from "anon";

revoke trigger on table "public"."tasks" from "anon";

revoke truncate on table "public"."tasks" from "anon";

revoke references on table "public"."tasks" from "authenticated";

revoke trigger on table "public"."tasks" from "authenticated";

revoke truncate on table "public"."tasks" from "authenticated";

alter table "public"."date_records" drop constraint "date_records_child_id_fkey";

alter table "public"."redts" drop constraint "redts_shidduchim_id_fkey";

alter table "public"."reference_links" drop constraint "reference_links_reference_id_fkey";

alter table "public"."reference_links" drop constraint "reference_links_resume_id_fkey";

alter table "public"."reference_links" drop constraint "reference_links_shidduchim_id_fkey";

alter table "public"."resumes" drop constraint "resumes_shidduchim_id_fkey";

alter table "public"."shidduch_schools" drop constraint "shidduch_schools_shidduchim_id_fkey";

alter table "public"."shidduchim" drop constraint "shidduchim_child_id_fkey";


  create table "public"."identity_signals" (
    "id" bigint generated by default as identity not null,
    "account_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "target_type" text not null,
    "target_id" bigint not null,
    "name_en_norm" text,
    "name_he_norm" text,
    "name_en_key" text,
    "name_he_key" text,
    "phone_norm" text,
    "parents_norm" text,
    "seminary_norm" text,
    "shul_norm" text,
    "location_norm" text
      );


alter table "public"."identity_signals" enable row level security;


  create table "public"."interactions" (
    "id" bigint generated by default as identity not null,
    "account_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "target_type" text not null,
    "target_id" bigint not null,
    "scope" text not null default 'account'::text,
    "reference_link_id" bigint,
    "actor_member_id" bigint,
    "kind" text not null default 'note'::text,
    "body" text,
    "metadata" jsonb
      );


alter table "public"."interactions" enable row level security;

alter table "public"."reference_links" add column "relationship_override" text;

alter table "public"."references" add column "name_norm_en" text;

alter table "public"."references" add column "name_norm_he" text;

alter table "public"."references" add column "phone_norm" text;

-- MANUAL ADJUSTMENT (see AGENTS.md): `supabase db diff` emits account_id and
-- target_id as `add column ... not null`, which aborts on any table that already
-- holds rows. Split into add-nullable -> backfill -> set not null.
alter table "public"."tasks" add column "account_id" bigint;

alter table "public"."tasks" add column "delivery_channels" text[] not null default ARRAY['in_app'::text, 'email'::text];

alter table "public"."tasks" add column "target_id" bigint;

alter table "public"."tasks" add column "target_type" text not null default 'contact'::text;

alter table "public"."tasks" alter column "contact_id" drop not null;

-- Every pre-existing task is contacts-scoped and predates accounts: its target
-- IS its contact, and it belongs to the default (first) account.
update public.tasks set target_id = contact_id where target_id is null;
update public.tasks set account_id = (select min(a.id) from public.accounts a) where account_id is null;

alter table "public"."tasks" alter column "target_id" set not null;

alter table "public"."tasks" alter column "account_id" set not null;

CREATE UNIQUE INDEX children_account_id_id_key ON public.children USING btree (account_id, id);

CREATE INDEX identity_signals_account_id_idx ON public.identity_signals USING btree (account_id);

CREATE INDEX identity_signals_name_en_key_idx ON public.identity_signals USING btree (account_id, target_type, name_en_key);

CREATE INDEX identity_signals_name_he_key_idx ON public.identity_signals USING btree (account_id, target_type, name_he_key);

CREATE INDEX identity_signals_phone_idx ON public.identity_signals USING btree (account_id, target_type, phone_norm);

CREATE UNIQUE INDEX identity_signals_pkey ON public.identity_signals USING btree (id);

CREATE UNIQUE INDEX identity_signals_target_key ON public.identity_signals USING btree (account_id, target_type, target_id);

CREATE INDEX interactions_account_id_idx ON public.interactions USING btree (account_id);

CREATE UNIQUE INDEX interactions_pkey ON public.interactions USING btree (id);

CREATE INDEX interactions_reference_link_id_idx ON public.interactions USING btree (reference_link_id);

CREATE INDEX interactions_target_idx ON public.interactions USING btree (account_id, target_type, target_id, created_at DESC);

CREATE UNIQUE INDEX reference_links_account_id_id_key ON public.reference_links USING btree (account_id, id);

CREATE UNIQUE INDEX references_account_id_id_key ON public."references" USING btree (account_id, id);

CREATE INDEX references_phone_norm_idx ON public."references" USING btree (account_id, phone_norm);

CREATE UNIQUE INDEX resumes_account_id_id_key ON public.resumes USING btree (account_id, id);

CREATE UNIQUE INDEX shidduchim_account_id_id_key ON public.shidduchim USING btree (account_id, id);

CREATE INDEX tasks_account_id_idx ON public.tasks USING btree (account_id);

CREATE INDEX tasks_target_idx ON public.tasks USING btree (account_id, target_type, target_id);

alter table "public"."identity_signals" add constraint "identity_signals_pkey" PRIMARY KEY using index "identity_signals_pkey";

alter table "public"."interactions" add constraint "interactions_pkey" PRIMARY KEY using index "interactions_pkey";

alter table "public"."children" add constraint "children_account_id_id_key" UNIQUE using index "children_account_id_id_key";

alter table "public"."identity_signals" add constraint "identity_signals_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."identity_signals" validate constraint "identity_signals_account_id_fkey";

alter table "public"."identity_signals" add constraint "identity_signals_target_key" UNIQUE using index "identity_signals_target_key";

alter table "public"."identity_signals" add constraint "identity_signals_target_type_check" CHECK ((target_type = ANY (ARRAY['reference'::text, 'shidduch'::text, 'date_record'::text]))) not valid;

alter table "public"."identity_signals" validate constraint "identity_signals_target_type_check";

alter table "public"."interactions" add constraint "interactions_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."interactions" validate constraint "interactions_account_id_fkey";

alter table "public"."interactions" add constraint "interactions_actor_member_id_fkey" FOREIGN KEY (actor_member_id) REFERENCES public.account_members(id) ON DELETE SET NULL not valid;

alter table "public"."interactions" validate constraint "interactions_actor_member_id_fkey";

alter table "public"."interactions" add constraint "interactions_kind_check" CHECK ((kind = ANY (ARRAY['note'::text, 'call_logged'::text, 'status_change'::text, 'merge'::text, 'link_created'::text, 'link_removed'::text]))) not valid;

alter table "public"."interactions" validate constraint "interactions_kind_check";

alter table "public"."interactions" add constraint "interactions_reference_link_id_fkey" FOREIGN KEY (account_id, reference_link_id) REFERENCES public.reference_links(account_id, id) ON DELETE CASCADE not valid;

alter table "public"."interactions" validate constraint "interactions_reference_link_id_fkey";

alter table "public"."interactions" add constraint "interactions_scope_check" CHECK ((scope = ANY (ARRAY['shidduch'::text, 'account'::text]))) not valid;

alter table "public"."interactions" validate constraint "interactions_scope_check";

alter table "public"."interactions" add constraint "interactions_scope_link_check" CHECK ((((scope = 'shidduch'::text) AND (target_type = 'reference'::text) AND (reference_link_id IS NOT NULL)) OR ((scope = 'shidduch'::text) AND (target_type = 'shidduch'::text) AND (reference_link_id IS NULL)) OR ((scope = 'account'::text) AND (target_type = 'reference'::text) AND (reference_link_id IS NULL)))) not valid;

alter table "public"."interactions" validate constraint "interactions_scope_link_check";

alter table "public"."interactions" add constraint "interactions_target_type_check" CHECK ((target_type = ANY (ARRAY['reference'::text, 'shidduch'::text]))) not valid;

alter table "public"."interactions" validate constraint "interactions_target_type_check";

alter table "public"."reference_links" add constraint "reference_links_account_id_id_key" UNIQUE using index "reference_links_account_id_id_key";

alter table "public"."reference_links" add constraint "reference_links_call_status_check" CHECK (((call_status IS NULL) OR (call_status = ANY (ARRAY['not_started'::text, 'answered'::text, 'no_answer'::text, 'call_back'::text, 'they_will_call_back'::text])))) not valid;

alter table "public"."reference_links" validate constraint "reference_links_call_status_check";

alter table "public"."references" add constraint "references_account_id_id_key" UNIQUE using index "references_account_id_id_key";

alter table "public"."resumes" add constraint "resumes_account_id_id_key" UNIQUE using index "resumes_account_id_id_key";

alter table "public"."shidduchim" add constraint "shidduchim_account_id_id_key" UNIQUE using index "shidduchim_account_id_id_key";

alter table "public"."tasks" add constraint "tasks_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."tasks" validate constraint "tasks_account_id_fkey";

alter table "public"."tasks" add constraint "tasks_delivery_channels_check" CHECK ((delivery_channels <@ ARRAY['in_app'::text, 'email'::text, 'push'::text])) not valid;

alter table "public"."tasks" validate constraint "tasks_delivery_channels_check";

alter table "public"."tasks" add constraint "tasks_target_type_check" CHECK ((target_type = ANY (ARRAY['contact'::text, 'shadchan'::text, 'shidduch'::text, 'reference'::text]))) not valid;

alter table "public"."tasks" validate constraint "tasks_target_type_check";

alter table "public"."date_records" add constraint "date_records_child_id_fkey" FOREIGN KEY (account_id, child_id) REFERENCES public.children(account_id, id) ON DELETE CASCADE not valid;

alter table "public"."date_records" validate constraint "date_records_child_id_fkey";

alter table "public"."redts" add constraint "redts_shidduchim_id_fkey" FOREIGN KEY (account_id, shidduchim_id) REFERENCES public.shidduchim(account_id, id) ON DELETE CASCADE not valid;

alter table "public"."redts" validate constraint "redts_shidduchim_id_fkey";

alter table "public"."reference_links" add constraint "reference_links_reference_id_fkey" FOREIGN KEY (account_id, reference_id) REFERENCES public."references"(account_id, id) ON DELETE CASCADE not valid;

alter table "public"."reference_links" validate constraint "reference_links_reference_id_fkey";

alter table "public"."reference_links" add constraint "reference_links_resume_id_fkey" FOREIGN KEY (account_id, resume_id) REFERENCES public.resumes(account_id, id) ON DELETE CASCADE not valid;

alter table "public"."reference_links" validate constraint "reference_links_resume_id_fkey";

alter table "public"."reference_links" add constraint "reference_links_shidduchim_id_fkey" FOREIGN KEY (account_id, shidduchim_id) REFERENCES public.shidduchim(account_id, id) ON DELETE CASCADE not valid;

alter table "public"."reference_links" validate constraint "reference_links_shidduchim_id_fkey";

alter table "public"."resumes" add constraint "resumes_shidduchim_id_fkey" FOREIGN KEY (account_id, shidduchim_id) REFERENCES public.shidduchim(account_id, id) ON DELETE CASCADE not valid;

alter table "public"."resumes" validate constraint "resumes_shidduchim_id_fkey";

alter table "public"."shidduch_schools" add constraint "shidduch_schools_shidduchim_id_fkey" FOREIGN KEY (account_id, shidduchim_id) REFERENCES public.shidduchim(account_id, id) ON DELETE CASCADE not valid;

alter table "public"."shidduch_schools" validate constraint "shidduch_schools_shidduchim_id_fkey";

alter table "public"."shidduchim" add constraint "shidduchim_child_id_fkey" FOREIGN KEY (account_id, child_id) REFERENCES public.children(account_id, id) ON DELETE CASCADE not valid;

alter table "public"."shidduchim" validate constraint "shidduchim_child_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.identity_name_key(p_input text)
 RETURNS text
 LANGUAGE plpgsql
 IMMUTABLE
 SET search_path TO ''
AS $function$
declare
  v_norm text;
  v_token text;
  v_out text[] := array[]::text[];
begin
  v_norm := public.normalize_identity_text(p_input);
  if v_norm is null then
    return null;
  end if;

  -- Hebrew final forms fold to their medial forms.
  v_norm := translate(v_norm, 'ךםןףץ', 'כמנפצ');

  foreach v_token in array string_to_array(v_norm, ' ') loop
    if v_token = '' then
      continue;
    end if;

    -- Honorifics are dropped from the KEY only. "Rabbi Chaim Cohen" and
    -- "Haim Cohen" are the same person, but their exact normalized names still
    -- differ — which is right, because the key is the fuzzy signal and
    -- name_*_norm stays the strict one.
    if v_token in (
      'rabbi', 'rav', 'harav', 'reb', 'rebbetzin', 'rebbitzen', 'rebetzin',
      'rabanit', 'harabanit', 'morah', 'mr', 'mrs', 'ms', 'miss', 'dr', 'prof',
      'הרב', 'רב', 'רבי', 'מרת', 'הרבנית'
    ) then
      continue;
    end if;

    v_token := case v_token
      when 'moishe' then 'moshe' when 'moses' then 'moshe' when 'moshy' then 'moshe'
      when 'yakov' then 'yaakov' when 'yankel' then 'yaakov' when 'jacob' then 'yaakov'
      when 'kobi' then 'yaakov'
      when 'haim' then 'chaim' when 'hyman' then 'chaim'
      when 'yitzchok' then 'yitzchak' when 'itzhak' then 'yitzchak' when 'itzik' then 'yitzchak'
      when 'isaac' then 'yitzchak' when 'yitz' then 'yitzchak'
      when 'abraham' then 'avraham' when 'avrohom' then 'avraham' when 'avi' then 'avraham'
      when 'abe' then 'avraham'
      when 'yossi' then 'yosef' when 'joseph' then 'yosef' when 'yoseph' then 'yosef'
      when 'shloime' then 'shlomo' when 'solomon' then 'shlomo' when 'shloimy' then 'shlomo'
      when 'dovid' then 'david' when 'dovi' then 'david' when 'duvid' then 'david'
      when 'shmuly' then 'shmuel' when 'samuel' then 'shmuel'
      when 'mendy' then 'menachem' when 'mendel' then 'menachem'
      when 'motty' then 'mordechai' when 'mordche' then 'mordechai' when 'motti' then 'mordechai'
      when 'benjamin' then 'binyamin' when 'binyomin' then 'binyamin' when 'benny' then 'binyamin'
      when 'ephraim' then 'efraim' when 'efrayim' then 'efraim'
      when 'zvi' then 'tzvi' when 'hershel' then 'tzvi' when 'hirsch' then 'tzvi'
      when 'rivky' then 'rivka' when 'rebecca' then 'rivka' when 'rifka' then 'rivka'
      when 'sara' then 'sarah' when 'suri' then 'sarah' when 'sori' then 'sarah'
      when 'estee' then 'esther' when 'esti' then 'esther' when 'ester' then 'esther'
      when 'hana' then 'chana' when 'hannah' then 'chana' when 'chani' then 'chana'
      when 'lea' then 'leah' when 'leiah' then 'leah'
      when 'miri' then 'miriam' when 'mimi' then 'miriam'
      when 'rochel' then 'rachel' when 'ruchi' then 'rachel' when 'ruchy' then 'rachel'
      when 'debbie' then 'devorah' when 'dvora' then 'devorah' when 'devora' then 'devorah'
      when 'malky' then 'malka' when 'malkie' then 'malka'
      when 'shaindy' then 'shaindel' when 'shaindi' then 'shaindel'
      else v_token
    end;

    -- Transliteration digraph folding (order matters: digraphs before letters).
    v_token := replace(v_token, 'tz', 'z');
    v_token := replace(v_token, 'ts', 'z');
    v_token := replace(v_token, 'ch', 'h');
    v_token := replace(v_token, 'kh', 'h');
    v_token := replace(v_token, 'ph', 'f');
    v_token := replace(v_token, 'ck', 'k');
    v_token := replace(v_token, 'q', 'k');
    v_token := replace(v_token, 'c', 'k');
    v_token := replace(v_token, 'w', 'v');
    v_token := replace(v_token, 'x', 'ks');

    -- Drop non-initial vowels, then collapse repeated letters.
    v_token := left(v_token, 1) || regexp_replace(substr(v_token, 2), '[aeiouy]', '', 'g');
    v_token := regexp_replace(v_token, '(.)\1+', '\1', 'g');

    if v_token <> '' then
      v_out := v_out || v_token;
    end if;
  end loop;

  if array_length(v_out, 1) is null then
    return null;
  end if;

  return array_to_string(v_out, ' ');
end;
$function$
;

CREATE OR REPLACE FUNCTION public.link_reference_to_shidduch(p_reference_id bigint, p_shidduchim_id bigint, p_relationship_override text DEFAULT NULL::text)
 RETURNS SETOF public.reference_links
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint;
  v_existing_id bigint;
  v_new_id bigint;
begin
  v_account_id := public.current_account_id();

  if not exists (
    select 1 from public."references" r
    where r.id = p_reference_id and r.account_id = v_account_id
  ) then
    raise exception 'reference % not found in current account', p_reference_id;
  end if;

  if not exists (
    select 1 from public.shidduchim s
    where s.id = p_shidduchim_id and s.account_id = v_account_id
  ) then
    raise exception 'shidduch % not found in current account', p_shidduchim_id;
  end if;

  select rl.id into v_existing_id
  from public.reference_links rl
  where rl.reference_id = p_reference_id
    and rl.shidduchim_id = p_shidduchim_id
    and rl.account_id = v_account_id
  limit 1;

  if v_existing_id is not null then
    return query select * from public.reference_links where id = v_existing_id;
    return;
  end if;

  insert into public.reference_links (
    account_id, reference_id, shidduchim_id, call_status, relationship_override
  ) values (
    v_account_id, p_reference_id, p_shidduchim_id, 'not_started', p_relationship_override
  )
  returning id into v_new_id;

  insert into public.interactions (
    account_id, target_type, target_id, scope, reference_link_id, kind, body, metadata
  ) values (
    v_account_id, 'reference', p_reference_id, 'shidduch', v_new_id, 'link_created',
    null, jsonb_build_object('shidduchim_id', p_shidduchim_id)
  );

  return query select * from public.reference_links where id = v_new_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.log_reference_call(p_reference_link_id bigint, p_call_status text DEFAULT NULL::text, p_what_they_said text DEFAULT NULL::text, p_source text DEFAULT 'manual'::text)
 RETURNS SETOF public.reference_links
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint;
  v_link public.reference_links;
  v_member_id bigint;
  v_entry jsonb;
begin
  v_account_id := public.current_account_id();

  select * into v_link
  from public.reference_links rl
  where rl.id = p_reference_link_id and rl.account_id = v_account_id;

  if not found then
    raise exception 'reference link % not found in current account', p_reference_link_id;
  end if;

  if p_call_status is not null and p_call_status not in
    ('not_started', 'answered', 'no_answer', 'call_back', 'they_will_call_back') then
    raise exception 'invalid call status: %', p_call_status using errcode = 'check_violation';
  end if;

  if p_source not in ('manual', 'assistant') then
    raise exception 'invalid call log source: %', p_source using errcode = 'check_violation';
  end if;

  -- The log is append-only and lives in a jsonb column, so an unbounded note
  -- grows the row without limit on every call. 20k characters is far more than
  -- anyone types mid-call and keeps a single link's log bounded.
  if length(coalesce(p_what_they_said, '')) > 20000 then
    raise exception 'call note is too long (% characters, limit 20000)', length(p_what_they_said)
      using errcode = 'check_violation';
  end if;

  select am.id into v_member_id
  from public.account_members am
  where am.user_id = auth.uid() and am.account_id = v_account_id
  order by am.id
  limit 1;

  v_entry := jsonb_build_object(
    'at', to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
    'call_status', coalesce(p_call_status, v_link.call_status),
    'text', p_what_they_said,
    'source', p_source,
    'member_id', v_member_id
  );

  update public.reference_links rl
  set call_status = coalesce(p_call_status, rl.call_status),
      what_they_said = coalesce(nullif(p_what_they_said, ''), rl.what_they_said),
      conversation_log = coalesce(rl.conversation_log, '[]'::jsonb) || jsonb_build_array(v_entry)
  where rl.id = p_reference_link_id;

  insert into public.interactions (
    account_id, target_type, target_id, scope, reference_link_id, actor_member_id, kind, body, metadata
  ) values (
    v_account_id, 'reference', v_link.reference_id, 'shidduch', p_reference_link_id, v_member_id,
    'call_logged', nullif(p_what_they_said, ''),
    jsonb_build_object(
      'call_status', coalesce(p_call_status, v_link.call_status),
      'shidduchim_id', v_link.shidduchim_id,
      'source', p_source
    )
  );

  return query select * from public.reference_links where id = p_reference_link_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.match_identity(p_target_type text, p_name_en text DEFAULT NULL::text, p_name_he text DEFAULT NULL::text, p_phone text DEFAULT NULL::text, p_parents text DEFAULT NULL::text, p_seminary text DEFAULT NULL::text, p_shul text DEFAULT NULL::text, p_location text DEFAULT NULL::text, p_exclude_target_id bigint DEFAULT NULL::bigint)
 RETURNS TABLE(target_id bigint, confidence numeric, deciding_facts jsonb)
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint;
  v_name_en_norm text;
  v_name_he_norm text;
  v_name_en_key text;
  v_name_he_key text;
  v_phone_norm text;
  v_parents_norm text;
  v_seminary_norm text;
  v_shul_norm text;
  v_location_norm text;
begin
  if p_target_type not in ('reference', 'shidduch', 'date_record') then
    raise exception 'unknown identity target_type: %', p_target_type
      using errcode = 'check_violation';
  end if;

  v_account_id := public.current_account_id();
  if v_account_id is null then
    return;
  end if;

  v_name_en_norm := public.normalize_identity_text(p_name_en);
  v_name_he_norm := public.normalize_identity_text(p_name_he);
  v_name_en_key := public.identity_name_key(p_name_en);
  v_name_he_key := public.identity_name_key(p_name_he);
  v_phone_norm := public.normalize_phone(p_phone);
  v_parents_norm := public.normalize_identity_text(p_parents);
  v_seminary_norm := public.normalize_identity_text(p_seminary);
  v_shul_norm := public.normalize_identity_text(p_shul);
  v_location_norm := public.normalize_identity_text(p_location);

  -- Nothing identifying was supplied: no candidates, no guessing.
  if v_phone_norm is null and v_name_en_norm is null and v_name_he_norm is null then
    return;
  end if;

  return query
  with scored as (
    select
      s.target_id as sig_target_id,
      (v_phone_norm is not null and s.phone_norm = v_phone_norm) as phone_hit,
      (
        (v_name_en_norm is not null and s.name_en_norm = v_name_en_norm)
        or (v_name_he_norm is not null and s.name_he_norm = v_name_he_norm)
      ) as name_exact,
      (
        (v_name_en_key is not null and s.name_en_key = v_name_en_key)
        or (v_name_he_key is not null and s.name_he_key = v_name_he_key)
      ) as name_variant,
      (v_parents_norm is not null and s.parents_norm = v_parents_norm) as parents_hit,
      (v_seminary_norm is not null and s.seminary_norm = v_seminary_norm) as seminary_hit,
      (v_shul_norm is not null and s.shul_norm = v_shul_norm) as shul_hit,
      (v_location_norm is not null and s.location_norm = v_location_norm) as location_hit
    from public.identity_signals s
    where s.account_id = v_account_id
      and s.target_type = p_target_type
      and (p_exclude_target_id is null or s.target_id <> p_exclude_target_id)
  ),
  weighted as (
    select
      sc.*,
      (sc.parents_hit::int + sc.seminary_hit::int + sc.shul_hit::int + sc.location_hit::int) as corroborators
    from scored sc
  )
  select
    w.sig_target_id,
    case
      when w.phone_hit and (w.name_exact or w.name_variant) then 0.98
      when w.phone_hit then 0.90
      when w.name_exact and w.corroborators >= 2 then 0.85
      when w.name_exact and w.corroborators = 1 then 0.75
      when w.name_variant and w.corroborators >= 2 then 0.70
      when w.name_variant and w.corroborators = 1 then 0.60
    end::numeric,
    (
      select coalesce(jsonb_agg(f.fact), '[]'::jsonb)
      from (
        select jsonb_build_object('signal', 'phone', 'detail', 'phone number matches exactly') as fact
          where w.phone_hit
        union all
        select jsonb_build_object('signal', 'name', 'detail', 'name matches exactly')
          where w.name_exact
        union all
        select jsonb_build_object('signal', 'name', 'detail', 'name matches as a Hebrew/English spelling variant')
          where w.name_variant and not w.name_exact
        union all
        select jsonb_build_object('signal', 'parents', 'detail', 'same parents')
          where w.parents_hit
        union all
        select jsonb_build_object('signal', 'school', 'detail', 'same school or seminary')
          where w.seminary_hit
        union all
        select jsonb_build_object('signal', 'shul', 'detail', 'same shul')
          where w.shul_hit
        union all
        select jsonb_build_object('signal', 'location', 'detail', 'same location')
          where w.location_hit
      ) f
    )
  from weighted w
  where w.phone_hit
     or ((w.name_exact or w.name_variant) and w.corroborators >= 1)
  order by 2 desc, 1 asc
  limit 10;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.match_reference_on_entry(p_name_en text DEFAULT NULL::text, p_name_he text DEFAULT NULL::text, p_phone text DEFAULT NULL::text, p_school text DEFAULT NULL::text, p_exclude_id bigint DEFAULT NULL::bigint)
 RETURNS TABLE(reference_id bigint, confidence numeric, deciding_facts jsonb, name_en text, name_he text, phone text, relationship text, school text, grad_year integer, linked_shidduchim_count bigint)
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$
  select
    m.target_id,
    m.confidence,
    m.deciding_facts,
    r.name_en,
    r.name_he,
    r.phone,
    r.relationship,
    r.school,
    r.grad_year,
    (
      select count(distinct rl.shidduchim_id)
      from public.reference_links rl
      where rl.reference_id = r.id and rl.shidduchim_id is not null
    )
  from public.match_identity(
    'reference', p_name_en, p_name_he, p_phone, null, p_school, null, null, p_exclude_id
  ) m
  join public."references" r on r.id = m.target_id
  order by m.confidence desc, r.id asc;
$function$
;

CREATE OR REPLACE FUNCTION public.merge_references(p_loser_id bigint, p_winner_id bigint, p_resolutions jsonb DEFAULT '{}'::jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint;
  v_collision record;
  v_resolution text;
  v_member_id bigint;
begin
  if p_loser_id = p_winner_id then
    raise exception 'cannot merge a reference into itself' using errcode = 'check_violation';
  end if;

  v_account_id := public.current_account_id();

  if not exists (
    select 1 from public."references" r
    where r.id = p_loser_id and r.account_id = v_account_id
  ) then
    raise exception 'reference % not found in current account', p_loser_id;
  end if;

  if not exists (
    select 1 from public."references" r
    where r.id = p_winner_id and r.account_id = v_account_id
  ) then
    raise exception 'reference % not found in current account', p_winner_id;
  end if;

  select am.id into v_member_id
  from public.account_members am
  where am.user_id = auth.uid() and am.account_id = v_account_id
  order by am.id
  limit 1;

  for v_collision in
    select
      l.id as loser_link_id,
      w.id as winner_link_id,
      l.shidduchim_id,
      l.call_status as loser_call_status,
      l.what_they_said as loser_what_they_said,
      l.conversation_log as loser_conversation_log,
      w.call_status as winner_call_status,
      w.what_they_said as winner_what_they_said
    from public.reference_links l
      join public.reference_links w
        on w.reference_id = p_winner_id
       and w.shidduchim_id = l.shidduchim_id
       and w.account_id = v_account_id
    where l.reference_id = p_loser_id
      and l.account_id = v_account_id
      and l.shidduchim_id is not null
  loop
    v_resolution := p_resolutions ->> v_collision.shidduchim_id::text;

    if v_resolution is null then
      raise exception
        'unresolved merge conflict: both references are linked to shidduch %. Choose which call log to keep before merging.',
        v_collision.shidduchim_id
        using errcode = 'check_violation';
    end if;

    if v_resolution not in ('winner', 'loser', 'both') then
      raise exception 'invalid merge resolution % for shidduch %', v_resolution, v_collision.shidduchim_id
        using errcode = 'check_violation';
    end if;

    -- Whatever is not kept as the live call log is preserved as an interaction.
    if v_resolution = 'winner' then
      insert into public.interactions (
        account_id, target_type, target_id, scope, reference_link_id, actor_member_id, kind, body, metadata
      ) values (
        v_account_id, 'reference', p_winner_id, 'shidduch', v_collision.winner_link_id, v_member_id, 'merge',
        v_collision.loser_what_they_said,
        jsonb_build_object(
          'reason', 'duplicate reference merged; superseded call log preserved',
          'shidduchim_id', v_collision.shidduchim_id,
          'call_status', v_collision.loser_call_status,
          'conversation_log', coalesce(v_collision.loser_conversation_log, '[]'::jsonb)
        )
      );

    elsif v_resolution = 'loser' then
      insert into public.interactions (
        account_id, target_type, target_id, scope, reference_link_id, actor_member_id, kind, body, metadata
      ) values (
        v_account_id, 'reference', p_winner_id, 'shidduch', v_collision.winner_link_id, v_member_id, 'merge',
        v_collision.winner_what_they_said,
        jsonb_build_object(
          'reason', 'duplicate reference merged; superseded call log preserved',
          'shidduchim_id', v_collision.shidduchim_id,
          'call_status', v_collision.winner_call_status
        )
      );

      update public.reference_links w
      set call_status = v_collision.loser_call_status,
          what_they_said = v_collision.loser_what_they_said,
          conversation_log = coalesce(w.conversation_log, '[]'::jsonb)
            || coalesce(v_collision.loser_conversation_log, '[]'::jsonb)
      where w.id = v_collision.winner_link_id;

    else
      update public.reference_links w
      set conversation_log = coalesce(w.conversation_log, '[]'::jsonb)
            || coalesce(v_collision.loser_conversation_log, '[]'::jsonb),
          what_they_said = concat_ws(
            E'\n\n', nullif(w.what_they_said, ''), nullif(v_collision.loser_what_they_said, '')
          )
      where w.id = v_collision.winner_link_id;

      insert into public.interactions (
        account_id, target_type, target_id, scope, reference_link_id, actor_member_id, kind, body, metadata
      ) values (
        v_account_id, 'reference', p_winner_id, 'shidduch', v_collision.winner_link_id, v_member_id, 'merge',
        v_collision.loser_what_they_said,
        jsonb_build_object(
          'reason', 'duplicate reference merged; both call logs kept',
          'shidduchim_id', v_collision.shidduchim_id,
          'call_status', v_collision.loser_call_status
        )
      );
    end if;

    -- Re-home the losing link's interactions, then drop the duplicate link.
    perform public.rehome_reference_link_interactions(
      v_collision.loser_link_id, v_collision.winner_link_id
    );

    delete from public.reference_links where id = v_collision.loser_link_id;
  end loop;

  -- Non-colliding links, the whole timeline, and every reminder move across.
  update public.reference_links rl
  set reference_id = p_winner_id
  where rl.reference_id = p_loser_id and rl.account_id = v_account_id;

  perform public.rehome_reference_interactions(p_loser_id, p_winner_id);

  update public.tasks t
  set target_id = p_winner_id
  where t.target_type = 'reference' and t.target_id = p_loser_id and t.account_id = v_account_id;

  -- The loser's identity_signals row is removed by purge_polymorphic_dependents
  -- when the row below is deleted, so the matcher never points at a dead id.
  -- Account-scoped: it names no shidduch and carries no candid content, only the
  -- fact that two records became one.
  insert into public.interactions (
    account_id, target_type, target_id, scope, actor_member_id, kind, body, metadata
  ) values (
    v_account_id, 'reference', p_winner_id, 'account', v_member_id, 'merge', null,
    jsonb_build_object('merged_from_reference_id', p_loser_id)
  );

  delete from public."references" where id = p_loser_id and account_id = v_account_id;

  return p_winner_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.normalize_identity_text(p_input text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO ''
AS $function$
  select nullif(
    trim(
      regexp_replace(
        regexp_replace(
          translate(
            lower(regexp_replace(coalesce(p_input, ''), '[֑-ׇ]', '', 'g')),
            'áàâäãåéèêëíìîïóòôöõúùûüñçýÿœæ',
            'aaaaaaeeeeiiiiooooouuuuncyyoa'
          ),
          '[^a-z0-9א-ת ]', ' ', 'g'
        ),
        '\s+', ' ', 'g'
      )
    ),
    ''
  );
$function$
;

CREATE OR REPLACE FUNCTION public.normalize_phone(p_input text)
 RETURNS text
 LANGUAGE plpgsql
 IMMUTABLE
 SET search_path TO ''
AS $function$
declare
  v_digits text;
begin
  v_digits := regexp_replace(coalesce(p_input, ''), '[^0-9]', '', 'g');
  if v_digits = '' then
    return null;
  end if;

  if left(v_digits, 2) = '00' then
    v_digits := substr(v_digits, 3);
  end if;

  if left(v_digits, 3) = '972' then
    v_digits := substr(v_digits, 4);
  elsif length(v_digits) = 11 and left(v_digits, 1) = '1' then
    v_digits := substr(v_digits, 2);
  elsif left(v_digits, 2) = '44' and length(v_digits) > 10 then
    v_digits := substr(v_digits, 3);
  end if;

  v_digits := regexp_replace(v_digits, '^0+', '');

  if length(v_digits) < 7 then
    return null;
  end if;

  return v_digits;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.preview_reference_merge(p_loser_id bigint, p_winner_id bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint;
  v_loser public."references";
  v_winner public."references";
begin
  v_account_id := public.current_account_id();

  select * into v_loser from public."references" r
  where r.id = p_loser_id and r.account_id = v_account_id;
  if not found then
    raise exception 'reference % not found in current account', p_loser_id;
  end if;

  select * into v_winner from public."references" r
  where r.id = p_winner_id and r.account_id = v_account_id;
  if not found then
    raise exception 'reference % not found in current account', p_winner_id;
  end if;

  return jsonb_build_object(
    'loser', to_jsonb(v_loser),
    'winner', to_jsonb(v_winner),
    'reference_links_count', (
      select count(*) from public.reference_links rl where rl.reference_id = p_loser_id
    ),
    'interactions_count', (
      select count(*) from public.interactions i
      where i.target_type = 'reference' and i.target_id = p_loser_id
    ),
    'open_tasks_count', (
      select count(*) from public.tasks t
      where t.target_type = 'reference' and t.target_id = p_loser_id and t.done_date is null
    ),
    'collisions', (
      select coalesce(jsonb_agg(
        jsonb_build_object(
          'shidduchim_id', l.shidduchim_id,
          'shidduch_name_en', s.name_en,
          'shidduch_name_he', s.name_he,
          'loser_link', jsonb_build_object(
            'id', l.id,
            'call_status', l.call_status,
            'what_they_said', l.what_they_said,
            'conversation_log_count', coalesce(jsonb_array_length(l.conversation_log), 0)
          ),
          'winner_link', jsonb_build_object(
            'id', w.id,
            'call_status', w.call_status,
            'what_they_said', w.what_they_said,
            'conversation_log_count', coalesce(jsonb_array_length(w.conversation_log), 0)
          )
        )
      ), '[]'::jsonb)
      from public.reference_links l
        join public.reference_links w
          on w.reference_id = p_winner_id
         and w.shidduchim_id = l.shidduchim_id
         and w.account_id = v_account_id
        left join public.shidduchim s on s.id = l.shidduchim_id
      where l.reference_id = p_loser_id
        and l.account_id = v_account_id
        and l.shidduchim_id is not null
    )
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.purge_polymorphic_dependents()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_target_type text := TG_ARGV[0];
begin
  delete from public.identity_signals
  where account_id = old.account_id and target_type = v_target_type and target_id = old.id;

  delete from public.interactions
  where account_id = old.account_id and target_type = v_target_type and target_id = old.id;

  delete from public.tasks
  where account_id = old.account_id and target_type = v_target_type and target_id = old.id;

  return old;
end;
$function$
;

create or replace view "public"."reference_links_summary" as  SELECT rl.id,
    rl.account_id,
    rl.created_at,
    rl.reference_id,
    rl.shidduchim_id,
    rl.resume_id,
    rl.call_status,
    rl.what_they_said,
    rl.conversation_log,
    rl.relationship_override,
    COALESCE(rl.relationship_override, r.relationship) AS effective_relationship,
    COALESCE(jsonb_array_length(rl.conversation_log), 0) AS conversation_log_count,
    r.name_en AS reference_name_en,
    r.name_he AS reference_name_he,
    r.phone AS reference_phone,
    s.name_en AS shidduch_name_en,
    s.name_he AS shidduch_name_he,
    s.pipeline_state AS shidduch_pipeline_state,
    s.visibility AS shidduch_visibility,
    s.child_id,
    c.first_name_en AS child_first_name_en,
    c.first_name_he AS child_first_name_he
   FROM (((public.reference_links rl
     LEFT JOIN public."references" r ON ((r.id = rl.reference_id)))
     LEFT JOIN public.shidduchim s ON ((s.id = rl.shidduchim_id)))
     LEFT JOIN public.children c ON ((c.id = s.child_id)));


create or replace view "public"."references_summary" as  SELECT r.id,
    r.account_id,
    r.created_at,
    r.name_en,
    r.name_he,
    r.relationship,
    r.phone,
    r.school,
    r.grad_year,
    r.name_norm_en,
    r.name_norm_he,
    r.phone_norm,
    count(DISTINCT rl.shidduchim_id) AS linked_shidduchim_count,
    count(DISTINCT rl.id) FILTER (WHERE (rl.call_status = ANY (ARRAY['answered'::text, 'they_will_call_back'::text]))) AS contacted_count,
    max(i.created_at) FILTER (WHERE (i.kind = 'call_logged'::text)) AS last_conversation_at,
    count(DISTINCT t.id) FILTER (WHERE (t.done_date IS NULL)) AS open_task_count
   FROM (((public."references" r
     LEFT JOIN public.reference_links rl ON ((rl.reference_id = r.id)))
     LEFT JOIN public.interactions i ON (((i.target_type = 'reference'::text) AND (i.target_id = r.id))))
     LEFT JOIN public.tasks t ON (((t.target_type = 'reference'::text) AND (t.target_id = r.id))))
  GROUP BY r.id;


CREATE OR REPLACE FUNCTION public.rehome_reference_interactions(p_from_reference_id bigint, p_to_reference_id bigint)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint;
  v_moved integer;
begin
  v_account_id := public.current_account_id();
  if v_account_id is null then
    raise exception 'no account context';
  end if;

  if not exists (
    select 1 from public."references" r
    where r.id = p_from_reference_id and r.account_id = v_account_id
  ) or not exists (
    select 1 from public."references" r
    where r.id = p_to_reference_id and r.account_id = v_account_id
  ) then
    raise exception 'reference not found in current account';
  end if;

  update public.interactions i
  set target_id = p_to_reference_id
  where i.target_type = 'reference'
    and i.target_id = p_from_reference_id
    and i.account_id = v_account_id;

  get diagnostics v_moved = row_count;
  return v_moved;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.rehome_reference_link_interactions(p_from_link_id bigint, p_to_link_id bigint)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint;
  v_moved integer;
begin
  v_account_id := public.current_account_id();
  if v_account_id is null then
    raise exception 'no account context';
  end if;

  -- Both links must belong to the caller AND concern the SAME shidduch. The
  -- second half matters: without it this function would hand back exactly the
  -- capability the column-level UPDATE revoke removed — moving a candid note
  -- onto a different shidduch, and so changing whose visibility it inherits.
  -- The only caller, merge_references, only ever re-homes between two links for
  -- the same shidduch, so nothing legitimate needs more than this.
  if not exists (
    select 1
    from public.reference_links l
      join public.reference_links w
        on w.id = p_to_link_id
       and w.account_id = v_account_id
       and w.shidduchim_id is not distinct from l.shidduchim_id
    where l.id = p_from_link_id
      and l.account_id = v_account_id
  ) then
    raise exception 'reference links not found in current account, or not for the same shidduch';
  end if;

  update public.interactions i
  set reference_link_id = p_to_link_id
  where i.reference_link_id = p_from_link_id
    and i.account_id = v_account_id;

  get diagnostics v_moved = row_count;
  return v_moved;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_reference_norms()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  new.name_norm_en := public.normalize_identity_text(new.name_en);
  new.name_norm_he := public.normalize_identity_text(new.name_he);
  new.phone_norm := public.normalize_phone(new.phone);
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.sync_reference_identity_signals()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.identity_signals (
    account_id, target_type, target_id,
    name_en_norm, name_he_norm, name_en_key, name_he_key,
    phone_norm, seminary_norm
  ) values (
    new.account_id, 'reference', new.id,
    public.normalize_identity_text(new.name_en),
    public.normalize_identity_text(new.name_he),
    public.identity_name_key(new.name_en),
    public.identity_name_key(new.name_he),
    public.normalize_phone(new.phone),
    public.normalize_identity_text(new.school)
  )
  on conflict (account_id, target_type, target_id) do update
  set name_en_norm = excluded.name_en_norm,
      name_he_norm = excluded.name_he_norm,
      name_en_key = excluded.name_en_key,
      name_he_key = excluded.name_he_key,
      phone_norm = excluded.phone_norm,
      seminary_norm = excluded.seminary_norm;

  return null;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.sync_shidduch_identity_signals()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.identity_signals (
    account_id, target_type, target_id,
    name_en_norm, name_he_norm, name_en_key, name_he_key,
    parents_norm, seminary_norm, shul_norm, location_norm
  ) values (
    new.account_id, 'shidduch', new.id,
    public.normalize_identity_text(new.name_en),
    public.normalize_identity_text(new.name_he),
    public.identity_name_key(new.name_en),
    public.identity_name_key(new.name_he),
    public.normalize_identity_text(coalesce(new.parents_en, new.parents_he)),
    public.normalize_identity_text(coalesce(new.seminary_en, new.seminary_he)),
    public.normalize_identity_text(coalesce(new.shul_en, new.shul_he)),
    public.normalize_identity_text(coalesce(new.location_en, new.location_he))
  )
  on conflict (account_id, target_type, target_id) do update
  set name_en_norm = excluded.name_en_norm,
      name_he_norm = excluded.name_he_norm,
      name_en_key = excluded.name_en_key,
      name_he_key = excluded.name_he_key,
      parents_norm = excluded.parents_norm,
      seminary_norm = excluded.seminary_norm,
      shul_norm = excluded.shul_norm,
      location_norm = excluded.location_norm;

  return null;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.sync_task_target()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if coalesce(new.target_type, 'contact') = 'contact' then
    new.target_type := 'contact';
    new.target_id := coalesce(new.target_id, new.contact_id);
    new.contact_id := coalesce(new.contact_id, new.target_id);
  else
    new.contact_id := null;
  end if;

  if new.target_id is null then
    raise exception 'a task needs a target: set contact_id, or target_type + target_id'
      using errcode = 'not_null_violation';
  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.current_account_id()
 RETURNS bigint
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint;
begin
  select am.account_id into v_account_id
  from public.account_members am
  where am.user_id = auth.uid()
    and am.status = 'active'
  order by am.id
  limit 1;

  return v_account_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  sales_count int;
  v_account_id bigint;
begin
  select count(id) into sales_count
  from public.sales;

  insert into public.sales (first_name, last_name, email, user_id, administrator)
  values (
    coalesce(new.raw_user_meta_data ->> 'first_name', new.raw_user_meta_data -> 'custom_claims' ->> 'first_name', 'Pending'),
    coalesce(new.raw_user_meta_data ->> 'last_name', new.raw_user_meta_data -> 'custom_claims' ->> 'last_name', 'Pending'),
    new.email,
    new.id,
    case when sales_count > 0 then FALSE else TRUE end
  );

  if not exists (select 1 from public.account_members) then
    select a.id into v_account_id
    from public.accounts a
    order by a.id
    limit 1;

    if v_account_id is null then
      insert into public.accounts (name) values ('My Account')
      returning id into v_account_id;
    end if;

    insert into public.account_members (account_id, user_id, role, status)
    values (v_account_id, new.id, 'parent_admin', 'active');
  end if;

  return new;
end;
$function$
;

grant select on table "public"."identity_signals" to "authenticated";

grant delete on table "public"."identity_signals" to "service_role";

grant insert on table "public"."identity_signals" to "service_role";

grant references on table "public"."identity_signals" to "service_role";

grant select on table "public"."identity_signals" to "service_role";

grant trigger on table "public"."identity_signals" to "service_role";

grant truncate on table "public"."identity_signals" to "service_role";

grant update on table "public"."identity_signals" to "service_role";

grant insert on table "public"."interactions" to "authenticated";

grant select on table "public"."interactions" to "authenticated";

grant delete on table "public"."interactions" to "service_role";

grant insert on table "public"."interactions" to "service_role";

grant references on table "public"."interactions" to "service_role";

grant select on table "public"."interactions" to "service_role";

grant trigger on table "public"."interactions" to "service_role";

grant truncate on table "public"."interactions" to "service_role";

grant update on table "public"."interactions" to "service_role";


  create policy "Identity signals readable within account"
  on "public"."identity_signals"
  as permissive
  for select
  to authenticated
using ((account_id = public.current_account_id()));



  create policy "Interactions scoped to account and parent visibility"
  on "public"."interactions"
  as permissive
  for all
  to authenticated
using (((account_id = public.current_account_id()) AND ((scope = 'account'::text) OR ((target_type = 'reference'::text) AND (EXISTS ( SELECT 1
   FROM (public.reference_links rl
     JOIN public.shidduchim s ON ((s.id = rl.shidduchim_id)))
  WHERE ((rl.id = interactions.reference_link_id) AND (rl.account_id = public.current_account_id()) AND (s.account_id = public.current_account_id()))))) OR ((target_type = 'shidduch'::text) AND (EXISTS ( SELECT 1
   FROM public.shidduchim s
  WHERE ((s.id = interactions.target_id) AND (s.account_id = public.current_account_id()))))))))
with check (((account_id = public.current_account_id()) AND ((scope = 'account'::text) OR ((target_type = 'reference'::text) AND (EXISTS ( SELECT 1
   FROM (public.reference_links rl
     JOIN public.shidduchim s ON ((s.id = rl.shidduchim_id)))
  WHERE ((rl.id = interactions.reference_link_id) AND (rl.account_id = public.current_account_id()) AND (s.account_id = public.current_account_id()))))) OR ((target_type = 'shidduch'::text) AND (EXISTS ( SELECT 1
   FROM public.shidduchim s
  WHERE ((s.id = interactions.target_id) AND (s.account_id = public.current_account_id()))))))));



  create policy "Tasks scoped to account"
  on "public"."tasks"
  as permissive
  for all
  to authenticated
using ((account_id = public.current_account_id()))
with check ((account_id = public.current_account_id()));


CREATE TRIGGER set_identity_signals_account_id BEFORE INSERT ON public.identity_signals FOR EACH ROW EXECUTE FUNCTION public.set_account_id_default();

CREATE TRIGGER set_interactions_account_id BEFORE INSERT ON public.interactions FOR EACH ROW EXECUTE FUNCTION public.set_account_id_default();

CREATE TRIGGER purge_reference_dependents BEFORE DELETE ON public."references" FOR EACH ROW EXECUTE FUNCTION public.purge_polymorphic_dependents('reference');

CREATE TRIGGER set_reference_norms_trigger BEFORE INSERT OR UPDATE ON public."references" FOR EACH ROW EXECUTE FUNCTION public.set_reference_norms();

CREATE TRIGGER sync_reference_signals AFTER INSERT OR UPDATE ON public."references" FOR EACH ROW EXECUTE FUNCTION public.sync_reference_identity_signals();

CREATE TRIGGER purge_shidduch_dependents BEFORE DELETE ON public.shidduchim FOR EACH ROW EXECUTE FUNCTION public.purge_polymorphic_dependents('shidduch');

CREATE TRIGGER sync_shidduch_signals AFTER INSERT OR UPDATE ON public.shidduchim FOR EACH ROW EXECUTE FUNCTION public.sync_shidduch_identity_signals();

CREATE TRIGGER set_tasks_account_id BEFORE INSERT ON public.tasks FOR EACH ROW EXECUTE FUNCTION public.set_account_id_default();

CREATE TRIGGER sync_task_target_trigger BEFORE INSERT OR UPDATE ON public.tasks FOR EACH ROW EXECUTE FUNCTION public.sync_task_target();

-- ---------------------------------------------------------------------------
-- MANUAL ADJUSTMENTS (see AGENTS.md). `supabase db diff` emits none of the
-- following, and none of it is cosmetic.
--
-- 1. It drops WITH (security_invoker = on) when it writes a view. Without it
--    these views execute as their owner and RLS never runs.
alter view "public"."references_summary" set (security_invoker = on);
alter view "public"."reference_links_summary" set (security_invoker = on);

-- 2. It does not diff view privileges at all, so a new view keeps only the
--    schema default privileges — which do NOT include SELECT.
revoke all on table "public"."references_summary" from "anon", "authenticated";
grant select on table "public"."references_summary" to "authenticated";
grant all on table "public"."references_summary" to "service_role";

revoke all on table "public"."reference_links_summary" from "anon", "authenticated";
grant select on table "public"."reference_links_summary" to "authenticated";
grant all on table "public"."reference_links_summary" to "service_role";

-- 3. It emits no table/function/sequence grants, and cannot see MAINTAIN or
--    column-level privileges at all. Revoke-all-then-regrant is deliberate:
--    naming individual privileges misses whichever ones a future Postgres adds.

revoke all on sequence public.interactions_id_seq from anon;
grant all on sequence public.interactions_id_seq to authenticated;
grant all on sequence public.interactions_id_seq to service_role;

revoke all on sequence public.identity_signals_id_seq from anon, authenticated;
grant all on sequence public.identity_signals_id_seq to service_role;

revoke all on sequence public.tasks_id_seq from anon;
grant all on sequence public.tasks_id_seq to authenticated;
grant all on sequence public.tasks_id_seq to service_role;

-- Identity/normalization functions.
revoke all on function public.normalize_identity_text(text) from public, anon;
grant execute on function public.normalize_identity_text(text) to authenticated;
grant execute on function public.normalize_identity_text(text) to service_role;

revoke all on function public.normalize_phone(text) from public, anon;
grant execute on function public.normalize_phone(text) to authenticated;
grant execute on function public.normalize_phone(text) to service_role;

revoke all on function public.identity_name_key(text) from public, anon;
grant execute on function public.identity_name_key(text) to authenticated;
grant execute on function public.identity_name_key(text) to service_role;

revoke all on function public.match_identity(text, text, text, text, text, text, text, text, bigint) from public, anon;
grant execute on function public.match_identity(text, text, text, text, text, text, text, text, bigint) to authenticated;
grant execute on function public.match_identity(text, text, text, text, text, text, text, text, bigint) to service_role;

revoke all on function public.match_reference_on_entry(text, text, text, text, bigint) from public, anon;
grant execute on function public.match_reference_on_entry(text, text, text, text, bigint) to authenticated;
grant execute on function public.match_reference_on_entry(text, text, text, text, bigint) to service_role;

-- Trigger functions: never executable by anon.
revoke all on function public.set_reference_norms() from public, anon;
grant execute on function public.set_reference_norms() to authenticated;
grant execute on function public.set_reference_norms() to service_role;

revoke all on function public.sync_reference_identity_signals() from public, anon;
grant execute on function public.sync_reference_identity_signals() to authenticated;
grant execute on function public.sync_reference_identity_signals() to service_role;

revoke all on function public.sync_shidduch_identity_signals() from public, anon;
grant execute on function public.sync_shidduch_identity_signals() to authenticated;
grant execute on function public.sync_shidduch_identity_signals() to service_role;

revoke all on function public.purge_polymorphic_dependents() from public, anon;
grant execute on function public.purge_polymorphic_dependents() to authenticated;
grant execute on function public.purge_polymorphic_dependents() to service_role;

revoke all on function public.sync_task_target() from public, anon;
grant execute on function public.sync_task_target() to authenticated;
grant execute on function public.sync_task_target() to service_role;

-- Reference write paths.
revoke all on function public.link_reference_to_shidduch(bigint, bigint, text) from public, anon;
grant execute on function public.link_reference_to_shidduch(bigint, bigint, text) to authenticated;
grant execute on function public.link_reference_to_shidduch(bigint, bigint, text) to service_role;

revoke all on function public.log_reference_call(bigint, text, text, text) from public, anon;
grant execute on function public.log_reference_call(bigint, text, text, text) to authenticated;
grant execute on function public.log_reference_call(bigint, text, text, text) to service_role;

revoke all on function public.preview_reference_merge(bigint, bigint) from public, anon;
grant execute on function public.preview_reference_merge(bigint, bigint) to authenticated;
grant execute on function public.preview_reference_merge(bigint, bigint) to service_role;

revoke all on function public.merge_references(bigint, bigint, jsonb) from public, anon;
grant execute on function public.merge_references(bigint, bigint, jsonb) to authenticated;
grant execute on function public.merge_references(bigint, bigint, jsonb) to service_role;

-- ---------------------------------------------------------------------------
-- TRUNCATE/MAINTAIN hardening across the shidduchim domain.
--
-- The fork's default privileges grant every new table's full privilege set to
-- anon and authenticated, and the pipeline epic's `grant all` re-added it. That
-- leaves TRUNCATE, which BYPASSES ROW LEVEL SECURITY: one statement from any
-- authenticated session empties a table for every tenant at once. `db diff`
-- cannot see MAINTAIN at all, so this drift is invisible to the migration
-- generator and has to be stated explicitly.
--
-- Revoke-all-then-regrant is deliberate: naming individual privileges misses
-- whichever ones a future Postgres adds.
-- ---------------------------------------------------------------------------
revoke all on table public.accounts from anon, authenticated;
grant select, insert, update, delete on table public.accounts to authenticated;

revoke all on table public.account_members from anon, authenticated;
grant select, insert, update, delete on table public.account_members to authenticated;

revoke all on table public.children from anon, authenticated;
grant select, insert, update, delete on table public.children to authenticated;

revoke all on table public.shadchanim from anon, authenticated;
grant select, insert, update, delete on table public.shadchanim to authenticated;

revoke all on table public."references" from anon, authenticated;
grant select, insert, update, delete on table public."references" to authenticated;

revoke all on table public.shidduchim from anon, authenticated;
grant select, insert, update, delete on table public.shidduchim to authenticated;

revoke all on table public.resumes from anon, authenticated;
grant select, insert, update, delete on table public.resumes to authenticated;

revoke all on table public.reference_links from anon, authenticated;
grant select, insert, update, delete on table public.reference_links to authenticated;

revoke all on table public.date_records from anon, authenticated;
grant select, insert, update, delete on table public.date_records to authenticated;

revoke all on table public.redts from anon, authenticated;
grant select, insert, update, delete on table public.redts to authenticated;

revoke all on table public.shidduch_schools from anon, authenticated;
grant select, insert, update, delete on table public.shidduch_schools to authenticated;

-- The three tables this epic added, restated here so the whole hardening rule
-- reads in one place. interactions withholds DELETE as well (audit trail).
revoke all on table public.interactions from anon, authenticated;
grant select, insert, update on table public.interactions to authenticated;

revoke all on table public.identity_signals from anon, authenticated;
grant select on table public.identity_signals to authenticated;

revoke all on table public.tasks from anon, authenticated;
grant select, insert, update, delete on table public.tasks to authenticated;

-- pipeline_transitions is static reference data (the legal state graph), read-only
-- to clients. It was missed by the sweep above: TRUNCATE survived, and emptying it
-- makes enforce_pipeline_transition() reject every state change for every tenant.
revoke all on table public.pipeline_transitions from anon, authenticated;
grant select on table public.pipeline_transitions to authenticated;

-- The structural columns of `interactions` are not client-writable. A client
-- that could rewrite scope/reference_link_id/target_* could move a candid note
-- onto a different parent and change whose visibility it inherits. Editing what
-- a note SAYS stays allowed; moving where it HANGS does not.
revoke update on table public.interactions from authenticated;
grant update (body, metadata) on table public.interactions to authenticated;

revoke all on function public.rehome_reference_link_interactions(bigint, bigint) from public, anon;
grant execute on function public.rehome_reference_link_interactions(bigint, bigint) to authenticated;
grant execute on function public.rehome_reference_link_interactions(bigint, bigint) to service_role;

revoke all on function public.rehome_reference_interactions(bigint, bigint) from public, anon;
grant execute on function public.rehome_reference_interactions(bigint, bigint) to authenticated;
grant execute on function public.rehome_reference_interactions(bigint, bigint) to service_role;
