drop policy "Listings readable by owner" on "public"."listings";

drop policy "Listings readable via accepted grant" on "public"."listings";


  create table "public"."demo_run_actor_intents" (
    "id" bigint generated by default as identity not null,
    "run_id" bigint not null,
    "actor_key" text not null,
    "expected_email" extensions.citext not null,
    "auth_user_id" uuid,
    "state" text not null default 'pending'::text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."demo_run_actor_intents" enable row level security;


  create table "public"."demo_run_member_state" (
    "id" bigint generated by default as identity not null,
    "run_id" bigint not null,
    "user_id" uuid not null,
    "original_active_account_id" bigint,
    "original_updated_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."demo_run_member_state" enable row level security;


  create table "public"."demo_run_resources" (
    "id" bigint generated by default as identity not null,
    "run_id" bigint not null,
    "resource_type" text not null,
    "resource_id" bigint not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."demo_run_resources" enable row level security;

alter table "public"."demo_runs" add column "lease_epoch" bigint not null default 0;

alter table "public"."demo_runs" add column "lease_expires_at" timestamp with time zone;

alter table "public"."demo_runs" add column "lease_token" text;

alter table "public"."demo_runs" add column "operation" text;

alter table "public"."demo_runs" add column "original_root_name" text;

CREATE UNIQUE INDEX demo_run_accounts_account_key ON public.demo_run_accounts USING btree (account_id);

CREATE UNIQUE INDEX demo_run_actor_intents_email_key ON public.demo_run_actor_intents USING btree (run_id, expected_email);

CREATE UNIQUE INDEX demo_run_actor_intents_key ON public.demo_run_actor_intents USING btree (run_id, actor_key);

CREATE UNIQUE INDEX demo_run_actor_intents_pkey ON public.demo_run_actor_intents USING btree (id);

CREATE INDEX demo_run_actor_intents_run_idx ON public.demo_run_actor_intents USING btree (run_id);

CREATE UNIQUE INDEX demo_run_member_state_pkey ON public.demo_run_member_state USING btree (id);

CREATE INDEX demo_run_member_state_run_idx ON public.demo_run_member_state USING btree (run_id);

CREATE UNIQUE INDEX demo_run_member_state_user_key ON public.demo_run_member_state USING btree (run_id, user_id);

CREATE UNIQUE INDEX demo_run_resources_key ON public.demo_run_resources USING btree (run_id, resource_type, resource_id);

CREATE UNIQUE INDEX demo_run_resources_pkey ON public.demo_run_resources USING btree (id);

CREATE INDEX demo_run_resources_run_idx ON public.demo_run_resources USING btree (run_id);

alter table "public"."demo_run_actor_intents" add constraint "demo_run_actor_intents_pkey" PRIMARY KEY using index "demo_run_actor_intents_pkey";

alter table "public"."demo_run_member_state" add constraint "demo_run_member_state_pkey" PRIMARY KEY using index "demo_run_member_state_pkey";

alter table "public"."demo_run_resources" add constraint "demo_run_resources_pkey" PRIMARY KEY using index "demo_run_resources_pkey";

alter table "public"."demo_run_accounts" add constraint "demo_run_accounts_account_key" UNIQUE using index "demo_run_accounts_account_key";

alter table "public"."demo_run_actor_intents" add constraint "demo_run_actor_intents_email_key" UNIQUE using index "demo_run_actor_intents_email_key";

alter table "public"."demo_run_actor_intents" add constraint "demo_run_actor_intents_key" UNIQUE using index "demo_run_actor_intents_key";

alter table "public"."demo_run_actor_intents" add constraint "demo_run_actor_intents_run_id_fkey" FOREIGN KEY (run_id) REFERENCES public.demo_runs(id) ON DELETE CASCADE not valid;

alter table "public"."demo_run_actor_intents" validate constraint "demo_run_actor_intents_run_id_fkey";

alter table "public"."demo_run_actor_intents" add constraint "demo_run_actor_intents_state_check" CHECK ((state = ANY (ARRAY['pending'::text, 'reconciled'::text]))) not valid;

alter table "public"."demo_run_actor_intents" validate constraint "demo_run_actor_intents_state_check";

alter table "public"."demo_run_actor_intents" add constraint "demo_run_actor_intents_user_id_fkey" FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."demo_run_actor_intents" validate constraint "demo_run_actor_intents_user_id_fkey";

alter table "public"."demo_run_member_state" add constraint "demo_run_member_state_account_id_fkey" FOREIGN KEY (original_active_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL not valid;

alter table "public"."demo_run_member_state" validate constraint "demo_run_member_state_account_id_fkey";

alter table "public"."demo_run_member_state" add constraint "demo_run_member_state_run_id_fkey" FOREIGN KEY (run_id) REFERENCES public.demo_runs(id) ON DELETE CASCADE not valid;

alter table "public"."demo_run_member_state" validate constraint "demo_run_member_state_run_id_fkey";

alter table "public"."demo_run_member_state" add constraint "demo_run_member_state_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."demo_run_member_state" validate constraint "demo_run_member_state_user_id_fkey";

alter table "public"."demo_run_member_state" add constraint "demo_run_member_state_user_key" UNIQUE using index "demo_run_member_state_user_key";

alter table "public"."demo_run_resources" add constraint "demo_run_resources_key" UNIQUE using index "demo_run_resources_key";

alter table "public"."demo_run_resources" add constraint "demo_run_resources_run_id_fkey" FOREIGN KEY (run_id) REFERENCES public.demo_runs(id) ON DELETE CASCADE not valid;

alter table "public"."demo_run_resources" validate constraint "demo_run_resources_run_id_fkey";

alter table "public"."demo_run_resources" add constraint "demo_run_resources_type_check" CHECK ((resource_type = ANY (ARRAY['invite'::text, 'connection_invite'::text, 'child_grant'::text, 'connection'::text, 'thread'::text, 'message'::text, 'listing'::text, 'share_link'::text, 'task'::text, 'share_access_log'::text, 'inbox_item'::text, 'analytics_event'::text, 'message_notification'::text, 'task_notification'::text]))) not valid;

alter table "public"."demo_run_resources" validate constraint "demo_run_resources_type_check";

set check_function_bodies = off;

-- Remove obsolete lifecycle overloads before installing the current
-- lease-aware signatures. The drops are intentionally narrow: the current
-- (bigint, text) functions are replaced below, while unrelated overloads
-- remain untouched.
drop function if exists public.begin_demo_seed(bigint);
drop function if exists public.claim_demo_clear(bigint);

CREATE OR REPLACE FUNCTION public.activate_demo_run(p_run_id bigint, p_lease_token text, p_active_root_name text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_run public.demo_runs;
begin
  select * into v_run from public.demo_runs where id = p_run_id for update;
  if not found or v_run.lease_token is distinct from p_lease_token
     or v_run.operation <> 'seed' or v_run.status <> 'seeding'
     or v_run.lease_expires_at <= now() then
    raise exception 'demo run % lease is stale or fenced', p_run_id
      using errcode = 'serialization_failure';
  end if;

  update public.accounts
  set name = p_active_root_name, demo = true
  where id = v_run.root_account_id;

  update public.demo_runs
  set status = 'active', operation = null, lease_token = null,
      lease_expires_at = null, updated_at = now()
  where id = p_run_id;

  return jsonb_build_object('run_id', p_run_id, 'status', 'active');
end;
$function$
;

CREATE OR REPLACE FUNCTION public.begin_demo_seed(p_root_account_id bigint, p_lease_token text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_account public.accounts;
  v_run public.demo_runs;
  v_token text;
begin
  select * into v_account
  from public.accounts
  where id = p_root_account_id
  for update;

  if not found then
    raise exception 'demo root account % not found', p_root_account_id
      using errcode = 'foreign_key_violation';
  end if;

  -- The account row lock makes this inventory authoritative against a
  -- concurrent insert. It intentionally mirrors the Edge preflight and
  -- requires the primary demo context to be a household.
  perform public.demo_assert_empty_account(p_root_account_id);

  if exists (
    select 1 from public.demo_runs
    where root_account_id = p_root_account_id
      and status in ('seeding', 'active', 'clearing', 'failed')
  ) then
    raise exception 'demo run already exists for root account %', p_root_account_id
      using errcode = 'unique_violation';
  end if;

  v_token := coalesce(nullif(p_lease_token, ''), gen_random_uuid()::text);
  insert into public.demo_runs (
    root_account_id, status, lease_token, lease_epoch, operation,
    lease_expires_at, original_root_name
  ) values (
    p_root_account_id, 'seeding', v_token, 1, 'seed',
    now() + interval '15 minutes', v_account.name
  ) returning * into v_run;

  insert into public.demo_run_accounts (
    run_id, account_id, context_key, context_kind, is_root
  ) values (
    v_run.id, p_root_account_id, 'primary-household', 'household', true
  );

  insert into public.demo_run_member_state (
    run_id, user_id, original_active_account_id, original_updated_at
  )
  select distinct on (am.user_id)
    v_run.id, am.user_id, ms.active_account_id, ms.updated_at
  from public.account_members am
  left join public.member_state ms on ms.user_id = am.user_id
  where am.account_id = p_root_account_id
    and am.status = 'active'
    and am.user_id is not null
  order by am.user_id, am.id;

  return jsonb_build_object(
    'run_id', v_run.id,
    'lease_token', v_token,
    'lease_epoch', v_run.lease_epoch,
    'original_root_name', v_account.name
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.claim_demo_clear(p_root_account_id bigint, p_lease_token text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_run public.demo_runs;
  v_token text;
begin
  select * into v_run
  from public.demo_runs
  where root_account_id = p_root_account_id
    and status in ('seeding', 'active', 'clearing', 'failed')
  order by id desc
  limit 1
  for update;

  if not found then
    return jsonb_build_object('outcome', 'no_run');
  end if;

  if v_run.status in ('seeding', 'clearing')
     and v_run.lease_expires_at > now() then
    raise exception 'demo run % is busy', v_run.id
      using errcode = 'lock_not_available';
  end if;

  v_token := coalesce(nullif(p_lease_token, ''), gen_random_uuid()::text);
  update public.demo_runs
  set status = 'clearing', operation = 'clear', lease_token = v_token,
      lease_epoch = lease_epoch + 1,
      lease_expires_at = now() + interval '15 minutes',
      cleanup_started_at = coalesce(cleanup_started_at, now()),
      updated_at = now()
  where id = v_run.id
  returning * into v_run;

  return jsonb_build_object(
    'outcome', 'claimed',
    'run_id', v_run.id,
    'lease_token', v_token,
    'lease_epoch', v_run.lease_epoch,
    'root_account_id', v_run.root_account_id,
    'original_root_name', v_run.original_root_name,
    'status', v_run.status
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.create_demo_actor_intent(p_run_id bigint, p_lease_token text, p_actor_key text, p_expected_email text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_intent public.demo_run_actor_intents;
begin
  if not public.demo_run_lease_is_current(p_run_id, p_lease_token, 'seed') then
    raise exception 'demo run % lease is stale or fenced', p_run_id
      using errcode = 'serialization_failure';
  end if;

  insert into public.demo_run_actor_intents (
    run_id, actor_key, expected_email, state
  ) values (p_run_id, p_actor_key, p_expected_email, 'pending')
  on conflict (run_id, actor_key) do update
    set expected_email = excluded.expected_email,
        updated_at = now()
    where public.demo_run_actor_intents.state = 'pending'
  returning * into v_intent;

  if not found then
    select * into v_intent
    from public.demo_run_actor_intents
    where run_id = p_run_id and actor_key = p_actor_key;
  end if;

  return jsonb_build_object(
    'intent_id', v_intent.id,
    'actor_key', v_intent.actor_key,
    'expected_email', v_intent.expected_email,
    'state', v_intent.state,
    'auth_user_id', v_intent.auth_user_id
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.create_demo_companion_context(p_run_id bigint, p_lease_token text, p_context_key text, p_name text, p_kind text)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_run public.demo_runs;
  v_account_id bigint;
begin
  select * into v_run from public.demo_runs where id = p_run_id for update;
  if not found or v_run.lease_token is distinct from p_lease_token
     or v_run.operation <> 'seed' or v_run.status <> 'seeding'
     or v_run.lease_expires_at <= now() then
    raise exception 'demo run % lease is stale or fenced', p_run_id
      using errcode = 'serialization_failure';
  end if;

  select account_id into v_account_id
  from public.demo_run_accounts
  where run_id = p_run_id and context_key = p_context_key;
  if found then
    return v_account_id;
  end if;

  if p_kind not in ('household', 'shadchanus') then
    raise exception 'invalid demo companion kind %', p_kind
      using errcode = 'check_violation';
  end if;

  insert into public.accounts (name, kind)
  values (p_name, p_kind)
  returning id into v_account_id;

  insert into public.demo_run_accounts (
    run_id, account_id, context_key, context_kind, is_root
  ) values (
    p_run_id, v_account_id, p_context_key, p_kind, false
  );
  return v_account_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.current_demo_preview_accounts()
 RETURNS TABLE(account_id bigint)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  with caller_run as (
    select dra.run_id
    from public.demo_run_accounts dra
    join public.demo_runs dr on dr.id = dra.run_id
    where dra.account_id = public.current_context_id()
      and dr.status = 'active'
    order by dra.run_id desc
    limit 1
  )
  select distinct dra.account_id
  from public.demo_run_accounts dra
  join caller_run cr on cr.run_id = dra.run_id
  join public.demo_runs dr on dr.id = dra.run_id
  where dr.status = 'active';
$function$
;

CREATE OR REPLACE FUNCTION public.demo_assert_empty_account(p_account_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if not exists (
    select 1 from public.accounts
    where id = p_account_id and kind = 'household'
  ) then
    raise exception 'demo root account % must be a household context', p_account_id
      using errcode = 'check_violation';
  end if;

  if exists (select 1 from public.singles where account_id = p_account_id)
     or exists (select 1 from public.shadchanim where account_id = p_account_id)
     or exists (select 1 from public.references where account_id = p_account_id)
     or exists (select 1 from public.shidduchim where account_id = p_account_id)
     or exists (select 1 from public.inbox_items where account_id = p_account_id)
     or exists (select 1 from public.message_notifications where account_id = p_account_id)
     or exists (select 1 from public.task_notifications where account_id = p_account_id)
     or exists (select 1 from public.messages where account_id = p_account_id)
     or exists (select 1 from public.threads where account_id = p_account_id)
     or exists (select 1 from public.thread_participants where account_id = p_account_id)
     or exists (select 1 from public.tasks where account_id = p_account_id)
     or exists (select 1 from public.reference_links where account_id = p_account_id)
     or exists (select 1 from public.redts where account_id = p_account_id)
     or exists (select 1 from public.shidduch_education where account_id = p_account_id)
     or exists (select 1 from public.resume_photos where account_id = p_account_id)
     or exists (select 1 from public.resumes where account_id = p_account_id)
     or exists (select 1 from public.entity_files where account_id = p_account_id)
     or exists (select 1 from public.medical_notes where account_id = p_account_id)
     or exists (select 1 from public.shidduchim_external_links where account_id = p_account_id)
     or exists (select 1 from public.date_records where account_id = p_account_id)
     or exists (select 1 from public.listing_withdrawal_locks where account_id = p_account_id)
     or exists (select 1 from public.listings where account_id = p_account_id)
     or exists (select 1 from public.invites where account_id = p_account_id)
     or exists (select 1 from public.analytics_events where account_id = p_account_id)
     or exists (select 1 from public.share_links where account_id = p_account_id)
     or exists (
       select 1 from public.connections
       where household_account_id = p_account_id
          or shadchanus_account_id = p_account_id
     )
     or exists (
       select 1 from public.connection_invites
       where inviter_account_id = p_account_id
          or accepted_by_account_id = p_account_id
     )
     or exists (
       select 1 from public.child_grants
       where proposer_account_id = p_account_id
          or grantee_account_id = p_account_id
     )
     or exists (
       select 1
       from public.messages m
       join public.connections c on c.id = m.connection_id
       where c.household_account_id = p_account_id
          or c.shadchanus_account_id = p_account_id
     )
     or exists (
       select 1
       from public.threads t
       join public.connections c on c.id = t.connection_id
       where c.household_account_id = p_account_id
          or c.shadchanus_account_id = p_account_id
     )
     or exists (
       select 1
       from public.thread_participants tp
       join public.connections c on c.id = tp.connection_id
       where c.household_account_id = p_account_id
          or c.shadchanus_account_id = p_account_id
     )
     or exists (
       select 1
       from public.message_notifications mn
       join public.connections c on c.id = mn.connection_id
       where c.household_account_id = p_account_id
          or c.shadchanus_account_id = p_account_id
     )
     or exists (
       select 1
       from storage.objects
       where bucket_id in ('documents', 'entity-files', 'attachments')
         and (name = p_account_id::text or name like p_account_id::text || '/%')
     ) then
    raise exception 'demo root account % is not empty', p_account_id
      using errcode = 'check_violation';
  end if;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.demo_assert_registered_actor(p_account_id bigint, p_user_id uuid, p_action text DEFAULT 'operation'::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_run_id bigint;
  v_status text;
begin
  select dr.id, dr.status
  into v_run_id, v_status
  from public.demo_run_accounts dra
  join public.demo_runs dr on dr.id = dra.run_id
  where dra.account_id = p_account_id
    and dr.status in ('seeding', 'active', 'clearing', 'failed')
  order by dr.id desc
  limit 1;

  if not found then
    return;
  end if;

  if v_status not in ('seeding', 'active')
     or p_user_id is null
     or not exists (
       select 1
       from public.demo_run_users dru
       where dru.run_id = v_run_id and dru.user_id = p_user_id
     ) then
    raise exception 'demo boundary violation: % requires a registered synthetic actor',
      coalesce(p_action, 'operation')
      using errcode = 'check_violation';
  end if;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.demo_assert_same_active_run(p_account_ids bigint[], p_action text DEFAULT 'operation'::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_requested_count integer;
  v_mapped_count integer;
  v_run_count integer;
  v_all_active boolean;
  v_has_unfinished boolean;
begin
  with requested as (
    select distinct account_id
    from unnest(coalesce(p_account_ids, array[]::bigint[])) as ids(account_id)
    where account_id is not null
  )
  select count(*) into v_requested_count from requested;

  if v_requested_count = 0 then
    return;
  end if;

  select exists (
    select 1
    from public.demo_run_accounts dra
    join public.demo_runs dr on dr.id = dra.run_id
    where dra.account_id = any(p_account_ids)
      and dr.status in ('seeding', 'active', 'clearing', 'failed')
  ) into v_has_unfinished;

  -- A production-only operation is not on the demo boundary at all.
  if not v_has_unfinished then
    return;
  end if;

  with requested as (
    select distinct account_id
    from unnest(coalesce(p_account_ids, array[]::bigint[])) as ids(account_id)
    where account_id is not null
  ), mapped as (
    select r.account_id, latest.run_id, latest.status
    from requested r
    left join lateral (
      select dr.id as run_id, dr.status
      from public.demo_run_accounts dra
      join public.demo_runs dr on dr.id = dra.run_id
      where dra.account_id = r.account_id
        and dr.status in ('seeding', 'active', 'clearing', 'failed')
      order by dr.id desc
      limit 1
    ) latest on true
  )
  select
    count(*) filter (where run_id is not null),
    count(distinct run_id),
    coalesce(bool_and(
      status = 'active'
      or (
        status = 'seeding'
        and exists (
          select 1
          from public.demo_run_users dru
          where dru.run_id = mapped.run_id
            and dru.user_id = auth.uid()
        )
      )
    ), false)
  into v_mapped_count, v_run_count, v_all_active
  from mapped;

  if v_mapped_count <> v_requested_count
     or v_run_count <> 1
     or not v_all_active then
    raise exception 'demo boundary violation: % requires one active run for every endpoint',
      coalesce(p_action, 'operation')
      using errcode = 'check_violation';
  end if;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.demo_register_seed_resource(p_resource_type text, p_resource_id bigint, p_account_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_run_id bigint;
begin
  select dr.id into v_run_id
  from public.demo_runs dr
  join public.demo_run_accounts dra on dra.run_id = dr.id
  join public.demo_run_users dru on dru.run_id = dr.id
  where dr.status = 'seeding'
    and dra.account_id = p_account_id
    and dru.user_id = auth.uid()
  order by dr.id desc
  limit 1;

  if v_run_id is null then
    return;
  end if;

  insert into public.demo_run_resources (run_id, resource_type, resource_id)
  values (v_run_id, p_resource_type, p_resource_id)
  on conflict (run_id, resource_type, resource_id) do nothing;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.demo_run_lease_is_current(p_run_id bigint, p_lease_token text, p_operation text DEFAULT NULL::text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select exists (
    select 1 from public.demo_runs
    where id = p_run_id
      and lease_token = p_lease_token
      and (p_operation is null or operation = p_operation)
      and status in ('seeding', 'clearing')
      and lease_expires_at > now()
  );
$function$
;

CREATE OR REPLACE FUNCTION public.fail_demo_run(p_run_id bigint, p_lease_token text, p_operation text)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
  update public.demo_runs
  set status = 'failed', operation = null, lease_token = null,
      lease_expires_at = null, updated_at = now()
  where id = p_run_id
    and lease_token = p_lease_token
    and operation = p_operation
    and status in ('seeding', 'clearing')
  returning true;
$function$
;

CREATE OR REPLACE FUNCTION public.finalize_demo_clear(p_run_id bigint, p_lease_token text, p_release_demo boolean DEFAULT false, p_release_persona boolean DEFAULT false, p_actor_user_id uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_run public.demo_runs;
  v_active_members integer;
  v_completed_at timestamp with time zone := now();
begin
  select * into v_run from public.demo_runs where id = p_run_id for update;
  if not found or v_run.status <> 'clearing'
     or v_run.operation <> 'clear'
     or v_run.lease_token is distinct from p_lease_token
     or v_run.lease_expires_at is null
     or v_run.lease_expires_at <= now() then
    raise exception 'demo run % clear lease is stale or fenced', p_run_id
      using errcode = 'serialization_failure';
  end if;

  insert into public.member_state (user_id, active_account_id, updated_at)
  select user_id, original_active_account_id,
         coalesce(original_updated_at, now())
  from public.demo_run_member_state
  where run_id = p_run_id
  on conflict (user_id) do update
    set active_account_id = excluded.active_account_id,
        updated_at = excluded.updated_at;

  update public.accounts
  set name = coalesce(v_run.original_root_name, name),
      demo = case when p_release_demo then false else demo end
  where id = v_run.root_account_id;

  if p_release_persona and p_actor_user_id is not null then
    select count(*) into v_active_members
    from public.account_members
    where account_id = v_run.root_account_id and status = 'active';
    if v_active_members = 1 then
      update public.account_members
      set status = 'archived'
      where account_id = v_run.root_account_id
        and user_id = p_actor_user_id
        and role = 'parent_admin'
        and status = 'active';
    end if;
  end if;

  delete from public.demo_runs where id = p_run_id;
  return jsonb_build_object(
    'outcome', 'finalized',
    'run_id', p_run_id,
    'completed_at', v_completed_at
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.heartbeat_demo_run(p_run_id bigint, p_lease_token text, p_operation text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_run public.demo_runs;
begin
  update public.demo_runs
  set updated_at = now(), lease_expires_at = now() + interval '15 minutes'
  where id = p_run_id
    and lease_token = p_lease_token
    and operation = p_operation
    and status in ('seeding', 'clearing')
    and lease_expires_at > now()
  returning * into v_run;

  if not found then
    raise exception 'demo run % lease is stale or fenced', p_run_id
      using errcode = 'serialization_failure';
  end if;

  return jsonb_build_object(
    'run_id', v_run.id,
    'lease_epoch', v_run.lease_epoch,
    'lease_expires_at', v_run.lease_expires_at
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.reconcile_demo_actor(p_run_id bigint, p_lease_token text, p_actor_key text, p_user_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_intent public.demo_run_actor_intents;
begin
  if not public.demo_run_lease_is_current(p_run_id, p_lease_token, 'seed') then
    raise exception 'demo run % lease is stale or fenced', p_run_id
      using errcode = 'serialization_failure';
  end if;

  select * into v_intent
  from public.demo_run_actor_intents
  where run_id = p_run_id and actor_key = p_actor_key
  for update;
  if not found then
    raise exception 'demo actor intent % not found', p_actor_key
      using errcode = 'foreign_key_violation';
  end if;

  if v_intent.auth_user_id is not null
     and v_intent.auth_user_id is distinct from p_user_id then
    raise exception 'demo actor intent % already reconciled', p_actor_key
      using errcode = 'unique_violation';
  end if;

  update public.demo_run_actor_intents
  set auth_user_id = p_user_id, state = 'reconciled', updated_at = now()
  where id = v_intent.id;

  insert into public.demo_run_users (run_id, user_id, actor_key)
  values (p_run_id, p_user_id, p_actor_key)
  on conflict (run_id, actor_key) do update set user_id = excluded.user_id;

  return jsonb_build_object(
    'run_id', p_run_id,
    'actor_key', p_actor_key,
    'user_id', p_user_id
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.register_demo_resource(p_run_id bigint, p_lease_token text, p_resource_type text, p_resource_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if not public.demo_run_lease_is_current(p_run_id, p_lease_token, 'seed') then
    raise exception 'demo run % lease is stale or fenced', p_run_id
      using errcode = 'serialization_failure';
  end if;

  if p_resource_type not in (
    'invite', 'connection_invite', 'child_grant', 'connection',
    'thread', 'message', 'listing', 'share_link', 'task',
    'share_access_log', 'inbox_item', 'analytics_event',
    'message_notification', 'task_notification'
  ) then
    raise exception 'invalid demo resource type %', p_resource_type
      using errcode = 'check_violation';
  end if;

  insert into public.demo_run_resources (run_id, resource_type, resource_id)
  values (p_run_id, p_resource_type, p_resource_id)
  on conflict (run_id, resource_type, resource_id) do nothing;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.register_demo_storage(p_run_id bigint, p_lease_token text, p_account_id bigint, p_bucket text, p_storage_path text, p_resource_key text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_run public.demo_runs;
begin
  select * into v_run
  from public.demo_runs
  where id = p_run_id
  for update;

  if not found
     or v_run.lease_token is distinct from p_lease_token
     or v_run.operation <> 'seed'
     or v_run.status <> 'seeding'
     or v_run.lease_expires_at is null
     or v_run.lease_expires_at <= now() then
    raise exception 'demo run % lease is stale or fenced', p_run_id
      using errcode = 'serialization_failure';
  end if;

  if p_bucket not in ('documents', 'entity-files', 'attachments') then
    raise exception 'invalid demo storage bucket %', p_bucket
      using errcode = 'check_violation';
  end if;
  if p_resource_key not in ('resume', 'photo', 'entity-file', 'inbox-attachment') then
    raise exception 'invalid demo storage resource %', p_resource_key
      using errcode = 'check_violation';
  end if;
  if p_storage_path is null
     or p_storage_path not like p_account_id::text || '/%'
     or p_storage_path ~ '(^|/)\.\.(/|$)' then
    raise exception 'demo storage path is outside manifest account %', p_account_id
      using errcode = 'check_violation';
  end if;
  if not exists (
    select 1
    from public.demo_run_accounts
    where run_id = p_run_id and account_id = p_account_id
  ) then
    raise exception 'demo storage account % is not in run %', p_account_id, p_run_id
      using errcode = 'foreign_key_violation';
  end if;

  insert into public.demo_run_storage (run_id, bucket, storage_path, resource_key)
  values (p_run_id, p_bucket, p_storage_path, p_resource_key)
  on conflict (bucket, storage_path) do nothing;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.restore_demo_member_state(p_run_id bigint, p_lease_token text, p_operation text DEFAULT 'clear'::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_run public.demo_runs;
begin
  select * into v_run
  from public.demo_runs
  where id = p_run_id
  for update;

  if not found
     or p_operation not in ('seed', 'clear')
     or v_run.lease_token is distinct from p_lease_token
     or v_run.operation is distinct from p_operation
     or v_run.status <> case when p_operation = 'seed' then 'seeding' else 'clearing' end
     or v_run.lease_expires_at is null
     or v_run.lease_expires_at <= now() then
    raise exception 'demo run % lease is stale or fenced', p_run_id
      using errcode = 'serialization_failure';
  end if;

  insert into public.member_state (user_id, active_account_id, updated_at)
  select user_id, original_active_account_id,
         coalesce(original_updated_at, now())
  from public.demo_run_member_state
  where run_id = p_run_id
  on conflict (user_id) do update
    set active_account_id = excluded.active_account_id,
        updated_at = excluded.updated_at;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.accept_child_grant(p_token text)
 RETURNS public.child_grants
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_grant public.child_grants;
  v_grantee_account_id bigint := public.current_context_id();
  v_target_account_id bigint;
  v_grantee_kind text;
  v_member_role text;
begin
  select * into v_grant
  from public.child_grants
  where token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
  for update;

  if not found or v_grant.status <> 'pending' or v_grant.expires_at <= now() then
    raise exception 'This child grant is invalid, expired, or has already been used.'
      using errcode = 'check_violation';
  end if;

  if v_grantee_account_id is null or not exists (
    select 1 from public.account_members am
    where am.account_id = v_grantee_account_id
      and am.user_id = auth.uid()
      and am.status = 'active'
  ) then
    raise exception 'accept_child_grant requires an active membership of the current context'
      using errcode = 'insufficient_privilege';
  end if;

  select kind into v_grantee_kind from public.accounts where id = v_grantee_account_id;
  if v_grantee_kind not in ('household', 'shadchanus') then
    raise exception 'a child grant can only be accepted by a household or shadchanus context'
      using errcode = 'check_violation';
  end if;

  select account_id into v_target_account_id
  from public.singles
  where id = v_grant.target_single_id;

  perform public.demo_assert_same_active_run(
    array[v_grant.proposer_account_id, v_target_account_id, v_grantee_account_id],
    'child grant acceptance'
  );

  -- The recipient may be a household owner, helper, or standalone shadchan.
  -- The grant remains scoped to the one target child in every read/write
  -- policy after acceptance.
  select role into v_member_role
  from public.account_members
  where account_id = v_grantee_account_id and user_id = auth.uid() and status = 'active';

  if v_member_role not in ('parent_admin', 'self_manager', 'helper', 'shadchan') then
    raise exception 'only an authorized household member or shadchan may accept a child grant'
      using errcode = 'insufficient_privilege';
  end if;

  update public.child_grants
  set status = 'accepted', grantee_account_id = v_grantee_account_id, accepted_at = now()
  where id = v_grant.id
  returning * into v_grant;

  return v_grant;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.accept_connection_invite(p_token text)
 RETURNS public.connections
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_invite public.connection_invites;
  v_acceptor_account_id bigint := public.current_context_id();
  v_acceptor_kind text;
  v_household_account_id bigint;
  v_shadchanus_account_id bigint;
  v_shadchanus_name text;
  v_connection public.connections;
begin
  select * into v_invite
  from public.connection_invites
  where token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
  for update;

  if not found or v_invite.status <> 'pending' or v_invite.expires_at <= now() then
    raise exception 'This connection invite is invalid, expired, or has already been used.'
      using errcode = 'check_violation';
  end if;

  if v_acceptor_account_id is null or not exists (
    select 1 from public.account_members am
    where am.account_id = v_acceptor_account_id and am.user_id = auth.uid() and am.status = 'active'
  ) then
    raise exception 'accept_connection_invite requires an active membership of the current context'
      using errcode = 'insufficient_privilege';
  end if;

  select kind into v_acceptor_kind from public.accounts where id = v_acceptor_account_id;

  perform public.demo_assert_same_active_run(
    array[v_invite.inviter_account_id, v_acceptor_account_id],
    'connection invite acceptance'
  );

  if v_acceptor_kind = v_invite.inviter_kind then
    raise exception 'a connection links a household and a shadchanus context, not two of the same kind'
      using errcode = 'check_violation';
  end if;

  if v_acceptor_kind = 'household' then
    v_household_account_id := v_acceptor_account_id;
    v_shadchanus_account_id := v_invite.inviter_account_id;
  else
    v_household_account_id := v_invite.inviter_account_id;
    v_shadchanus_account_id := v_acceptor_account_id;
  end if;

  select name into v_shadchanus_name from public.accounts where id = v_shadchanus_account_id;

  -- Story 8.5 (AC-2): the mirror-image snapshot of v_shadchanus_name above —
  -- taken at the same moment, for the same reason (the household caller's
  -- own RLS never lets a shadchanus caller read `accounts` back the other
  -- way). See household_account_name's own comment in 01_tables.sql.
  insert into public.connections (
    household_account_id, shadchanus_account_id, status,
    proposed_by_account_id, accepted_at, household_account_name
  ) values (
    v_household_account_id, v_shadchanus_account_id, 'accepted',
    v_invite.inviter_account_id, now(),
    (select name from public.accounts where id = v_household_account_id)
  )
  returning * into v_connection;

  perform public.demo_register_seed_resource(
    'connection', v_connection.id, v_acceptor_account_id
  );

  insert into public.shadchanim (account_id, name, connection_id)
  values (v_household_account_id, v_shadchanus_name, v_connection.id);

  update public.connection_invites
  set status = 'accepted', accepted_by_account_id = v_acceptor_account_id, accepted_at = now()
  where id = v_invite.id;

  return v_connection;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.accept_invite(p_token uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_user_id uuid := auth.uid();
  v_email text;
  v_invite public.invites;
  v_membership_id bigint;
begin
  if v_user_id is null then
    raise exception 'accept_invite requires an authenticated caller'
      using errcode = 'insufficient_privilege';
  end if;

  select email into v_email from auth.users where id = v_user_id;

  select i.* into v_invite
  from public.invites i
  where i.token = p_token
    and lower(i.email) = lower(coalesce(v_email, ''));

  if not found then
    raise exception 'This invite is invalid, expired, or has already been used.'
      using errcode = 'check_violation';
  end if;

  if v_invite.status = 'accepted' and exists (
    select 1 from public.account_members
    where account_id = v_invite.account_id and user_id = v_user_id
  ) then
    return;
  end if;

  if v_invite.expires_at <= now() then
    raise exception 'This invite is invalid, expired, or has already been used.'
      using errcode = 'check_violation';
  end if;

  -- Story 6.1 review fix (BLOCKER #2): a `role = 'single'` invite that
  -- predates this story's `target_single_id` column (Epic 2 shipped
  -- `single` as an ordinary invitable household role two epics earlier) can
  -- have no target. `invites_role_target_check` (01_tables.sql) is
  -- deliberately NOT VALID forever rather than backfilled or deleted (the
  -- migration-data-safety guard forbids both for a pre-existing row), which
  -- means the UPDATE just below WOULD still raise for such a row — but as a
  -- raw constraint-violation error, not this function's own vocabulary.
  -- Catching it here first turns it into the exact same friendly message
  -- every other unhonourable invite gets: it can never be linked under the
  -- invariant this story establishes, so it is refused the same way an
  -- expired or already-used one is, never a leaked implementation detail.
  if v_invite.role = 'single' and v_invite.target_single_id is null then
    raise exception 'This invite is invalid, expired, or has already been used.'
      using errcode = 'check_violation';
  end if;

  perform public.demo_assert_same_active_run(
    array[v_invite.account_id],
    'membership invite acceptance'
  );
  perform public.demo_assert_registered_actor(
    v_invite.account_id,
    v_user_id,
    'membership invite acceptance'
  );

  -- Review finding #4 (2.8): claim the invite atomically BEFORE inserting
  -- the membership, re-checking `status = 'pending'` in the UPDATE's WHERE
  -- clause rather than relying on the plain SELECT read above (which a
  -- concurrent revoke_invite() could invalidate between this function's
  -- read and its write). See revoke_invite()'s matching comment for why the
  -- WHERE-clause re-check — not an explicit lock — is what makes the two
  -- functions mutually exclusive on the same row: whichever commits first
  -- wins, the other's UPDATE affects zero rows and raises here instead of
  -- creating a membership for an invite the admin just revoked.
  update public.invites
  set status = 'accepted', accepted_at = now()
  where id = v_invite.id and status = 'pending';

  if not found then
    raise exception 'This invite is invalid, expired, or has already been used.'
      using errcode = 'check_violation';
  end if;

  insert into public.account_members (account_id, user_id, role, invited_by, status)
  values (v_invite.account_id, v_user_id, v_invite.role, v_invite.invited_by, 'active')
  returning id into v_membership_id;

  -- Story 6.1 (AC-3/AC-4): a `role = 'single'` invite always carries a
  -- target (the table's check constraint), so this branch is the ONLY place
  -- `singles.member_id` is ever set from an invite. Fails closed even if the
  -- target became linked in the window between invite and acceptance (e.g.
  -- via add_persona('single')) — never silently reassigned.
  if v_invite.target_single_id is not null then
    update public.singles
    set member_id = v_membership_id
    where id = v_invite.target_single_id
      and account_id = v_invite.account_id
      and member_id is null;

    if not found then
      raise exception 'single % is already linked to a login, or does not belong to this household', v_invite.target_single_id
        using errcode = 'check_violation';
    end if;
  end if;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.can_moderate_note(p_actor_member_id bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$
  select exists (
      -- the caller wrote it: compare the AUTHOR's membership row on user_id,
      -- never on account_members.id (see Dev Notes "Why authorship joins on user_id")
      select 1
      from public.account_members am
      where am.id = p_actor_member_id
        and am.user_id = auth.uid()
    ) or exists (
      -- or the caller holds an owning role in the context they are active in
      select 1
      from public.account_members am
      where am.user_id = auth.uid()
        and am.account_id = public.current_context_id()
        and am.status = 'active'
        and public.is_owning_membership_role(am.role)
    );
$function$
;

CREATE OR REPLACE FUNCTION public.catch_shidduch(p_shidduchim_id bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint;
  v_s public.shidduchim;
  v_suggestions jsonb;
  v_dates jsonb;
  v_name_en_norm text;
  v_name_he_norm text;
  v_name_en_key text;
  v_name_he_key text;
  v_parents_norm text;
  v_seminary_norm text;
  v_location_norm text;
begin
  v_account_id := public.current_context_id();
  if v_account_id is null then
    return jsonb_build_object('has_catch', false, 'suggestions', '[]'::jsonb, 'dates', '[]'::jsonb);
  end if;

  -- shidduch_row() rather than `select * from public.shidduchim`: the same
  -- RLS-filtered row (that function is SECURITY INVOKER), reached without the
  -- SELECT-on-every-column that `select *` demands and `authenticated` no
  -- longer has for close_reason. Nothing below reads v_s.close_reason.
  select * into v_s
  from public.shidduch_row(p_shidduchim_id) s
  where s.account_id = v_account_id;

  if not found then
    raise exception 'shidduch % not found in current account', p_shidduchim_id;
  end if;

  -- Prior suggestions: the shared matcher, excluding this very row. Each
  -- candidate is joined back to its single/shadchan so the panel renders the
  -- prior context ("suggested for {single}, via {shadchan}, {state}") in one hop.
  select coalesce(
    jsonb_agg(to_jsonb(cand) order by cand.confidence desc, cand.prior_shidduchim_id asc),
    '[]'::jsonb
  )
  into v_suggestions
  from (
    select
      m.target_id as prior_shidduchim_id,
      m.confidence,
      m.deciding_facts,
      ps.name_en,
      ps.name_he,
      ps.age,
      ps.pipeline_state,
      ps.first_suggested_at,
      ps.redt_date,
      ps.single_id,
      c.first_name_en as single_first_name_en,
      c.first_name_he as single_first_name_he,
      sh.name as shadchan_name
    from public.match_identity(
      'shidduch',
      v_s.name_en,
      v_s.name_he,
      null,
      nullif(trim(
        coalesce(v_s.father_en, v_s.father_he, '') || ' ' ||
        coalesce(v_s.mother_en, v_s.mother_he, '')
      ), ''),
      coalesce(v_s.seminary_en, v_s.seminary_he),
      coalesce(v_s.shul_en, v_s.shul_he),
      coalesce(v_s.location_en, v_s.location_he),
      p_shidduchim_id
    ) m
      join public.shidduchim ps on ps.id = m.target_id
      left join public.singles c on c.id = ps.single_id
      left join public.shadchanim sh on sh.id = ps.shadchan_id
    where not coalesce(public.shidduch_has_known_halachic_conflict(
      ps.single_id,
      ps.person_gender,
      ps.kohen_status,
      ps.marital_status
    ), false)
  ) cand;

  -- Prior dating (honest, corroborated, never fabricated). date_records is not in
  -- identity_signals, so it is compared directly with the shared normalizers.
  v_name_en_norm := public.normalize_identity_text(v_s.name_en);
  v_name_he_norm := public.normalize_identity_text(v_s.name_he);
  v_name_en_key := public.identity_name_key(v_s.name_en);
  v_name_he_key := public.identity_name_key(v_s.name_he);
  v_parents_norm := public.normalize_identity_text(nullif(trim(
    coalesce(v_s.father_en, v_s.father_he, '') || ' ' ||
    coalesce(v_s.mother_en, v_s.mother_he, '')
  ), ''));
  v_seminary_norm := public.normalize_identity_text(coalesce(v_s.seminary_en, v_s.seminary_he));
  v_location_norm := public.normalize_identity_text(coalesce(v_s.location_en, v_s.location_he));

  select coalesce(
    jsonb_agg(to_jsonb(d) order by d.date_on desc nulls last, d.date_record_id desc),
    '[]'::jsonb
  )
  into v_dates
  from (
    select
      dr.id as date_record_id,
      dr.person_name_en,
      dr.person_name_he,
      dr.date_on,
      dr.outcome,
      dr.single_id,
      c.first_name_en as single_first_name_en
    from public.date_records dr
      left join public.singles c on c.id = dr.single_id
    where dr.account_id = v_account_id
      and (
        (v_name_en_norm is not null and public.normalize_identity_text(dr.person_name_en) = v_name_en_norm)
        or (v_name_he_norm is not null and public.normalize_identity_text(dr.person_name_he) = v_name_he_norm)
        or (v_name_en_key is not null and public.identity_name_key(dr.person_name_en) = v_name_en_key)
        or (v_name_he_key is not null and public.identity_name_key(dr.person_name_he) = v_name_he_key)
      )
      and (
        (v_parents_norm is not null and public.normalize_identity_text(dr.person_parents) = v_parents_norm)
        or (v_seminary_norm is not null and public.normalize_identity_text(dr.person_seminary) = v_seminary_norm)
        or (v_location_norm is not null and public.normalize_identity_text(dr.person_location) = v_location_norm)
      )
  ) d;

  return jsonb_build_object(
    'has_catch', (jsonb_array_length(v_suggestions) > 0 or jsonb_array_length(v_dates) > 0),
    'suggestions', v_suggestions,
    'dates', v_dates
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.claim_due_task_notifications(p_limit integer)
 RETURNS TABLE(id bigint, task_id bigint, account_id bigint, recipient_email text, task_text text, due_date timestamp with time zone, target_type text, target_id bigint, attempts integer, claimed_at timestamp with time zone, simulated boolean)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  perform public.enqueue_due_task_notifications();

  return query
  with claimed as (
    update public.task_notifications tn
    set status = 'sending', attempts = tn.attempts + 1, claimed_at = now()
    where tn.id in (
      select tn2.id from public.task_notifications tn2
      where (
        (
          tn2.status = 'pending'
          and (tn2.next_attempt_at is null or tn2.next_attempt_at <= now())
        ) or (
          tn2.status = 'sending'
          and tn2.claimed_at < now() - interval '10 minutes'
        )
      )
        and tn2.simulated is not true
      order by tn2.created_at
      limit p_limit
      for update skip locked
    )
    returning tn.*
  )
  select
    claimed.id,
    claimed.task_id,
    claimed.account_id,
    claimed.recipient_email,
    t.text,
    claimed.due_date,
    t.target_type,
    t.target_id,
    claimed.attempts,
    claimed.claimed_at,
    claimed.simulated
  from claimed
  join public.tasks t on t.id = claimed.task_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.claim_message_notifications(p_limit integer)
 RETURNS TABLE(id bigint, channel text, recipient_member_id bigint, recipient_email text, thread_id bigint, message_body text, subject_type text, subject_id bigint, push_subscriptions jsonb, simulated boolean)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  -- Every OUT column above (id, channel, ...) is an implicitly declared
  -- plpgsql variable in scope for the whole function body, so a BARE `id`
  -- inside the query below is ambiguous with the OUT parameter of the same
  -- name — table aliases on every reference (mn/mn2), not just on the final
  -- projection, are required here, not stylistic.
  return query
  with claimed as (
    update public.message_notifications mn
    set status = 'sending', attempts = attempts + 1
    where mn.id in (
      select mn2.id from public.message_notifications mn2
      where mn2.status = 'pending'
        and mn2.simulated is not true
      order by mn2.created_at
      limit p_limit
      for update skip locked
    )
    returning mn.*
  )
  select
    claimed.id,
    claimed.channel,
    claimed.recipient_member_id,
    claimed.recipient_email,
    m.thread_id,
    m.body,
    t.subject_type,
    t.subject_id,
    case when claimed.channel = 'push' then (
      select jsonb_agg(jsonb_build_object('endpoint', ps.endpoint, 'p256dh', ps.p256dh, 'auth', ps.auth))
      from public.push_subscriptions ps
      where ps.member_id = claimed.recipient_member_id
    ) else null end,
    claimed.simulated
  from claimed
  join public.messages m on m.id = claimed.message_id
  join public.threads t on t.id = m.thread_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.create_child_grant(p_target_single_id bigint, p_grantee_email text, p_access_level text DEFAULT 'read'::text)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_proposer_account_id bigint := public.current_context_id();
  v_proposer_kind text;
  v_token text;
  v_single public.singles;
  v_member_role text;
begin
  -- Validated early, ahead of the authorization checks below: a malformed
  -- access_level is a caller bug, not an authorization question, and the
  -- CHECK constraint on child_grants would otherwise report it as an opaque
  -- constraint-violation instead of this clear message.
  if p_access_level not in ('read', 'comment', 'edit') then
    raise exception 'access_level must be one of read, comment, edit (got %)', p_access_level
      using errcode = 'check_violation';
  end if;

  -- Caller must be an active member of the current context with owning role
  if v_proposer_account_id is null or not exists (
    select 1 from public.account_members am
    where am.account_id = v_proposer_account_id
      and am.user_id = auth.uid()
      and am.status = 'active'
      and am.role in ('parent_admin', 'self_manager')
  ) then
    raise exception 'create_child_grant requires an active parent_admin or self_manager membership of the current context'
      using errcode = 'insufficient_privilege';
  end if;

  -- Current context must be a household (grants are household-to-household)
  select kind into v_proposer_kind from public.accounts where id = v_proposer_account_id;
  if v_proposer_kind <> 'household' then
    raise exception 'grants can only be proposed from a household context'
      using errcode = 'check_violation';
  end if;

  -- Target single must exist and belong to the proposer's account
  select * into v_single
  from public.singles
  where id = p_target_single_id
    and account_id = v_proposer_account_id;

  if not found then
    raise exception 'single % not found in this household', p_target_single_id
      using errcode = 'check_violation';
  end if;

  -- Generate token and store hash
  v_token := encode(extensions.gen_random_bytes(32), 'hex');

  insert into public.child_grants (
    proposer_account_id, target_single_id, token_hash, expires_at, access_level
  ) values (
    v_proposer_account_id, p_target_single_id,
    encode(extensions.digest(v_token, 'sha256'), 'hex'),
    now() + interval '7 days',
    p_access_level
  );

  perform public.demo_register_seed_resource(
    'child_grant',
    (select id from public.child_grants
     where token_hash = encode(extensions.digest(v_token, 'sha256'), 'hex')),
    v_proposer_account_id
  );

  return v_token;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.create_connection_invite()
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint := public.current_context_id();
  v_kind text;
  v_token text;
  v_invite_id bigint;
begin
  if v_account_id is null or not exists (
    select 1 from public.account_members am
    where am.account_id = v_account_id and am.user_id = auth.uid() and am.status = 'active'
  ) then
    raise exception 'create_connection_invite requires an active membership of the current context'
      using errcode = 'insufficient_privilege';
  end if;

  select kind into v_kind from public.accounts where id = v_account_id;
  v_token := encode(extensions.gen_random_bytes(32), 'hex');

  insert into public.connection_invites (
    inviter_account_id, inviter_kind, token_hash, expires_at
  ) values (
    v_account_id, v_kind,
    encode(extensions.digest(v_token, 'sha256'), 'hex'),
    now() + interval '7 days'
  ) returning id into v_invite_id;

  perform public.demo_register_seed_resource(
    'connection_invite', v_invite_id, v_account_id
  );

  return v_token;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.create_invite(p_email text, p_role text, p_target_single_id bigint DEFAULT NULL::bigint)
 RETURNS public.invites
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint;
  v_membership_id bigint;
  v_caller_role text;
  v_account_kind text;
  v_invite public.invites;
begin
  v_account_id := public.current_context_id();

  select am.id, am.role into v_membership_id, v_caller_role
  from public.account_members am
  where am.account_id = v_account_id
    and am.user_id = auth.uid()
    and am.status = 'active';

  if v_membership_id is null then
    raise exception 'no active membership of the current context'
      using errcode = 'insufficient_privilege';
  end if;

  if not public.is_invite_capable_role(v_caller_role) then
    raise exception 'role % may not send invites', v_caller_role
      using errcode = 'insufficient_privilege';
  end if;

  if public.role_authority(p_role) > public.role_authority(v_caller_role) then
    raise exception 'cannot invite role % above your own authority', p_role
      using errcode = 'insufficient_privilege';
  end if;

  select kind into v_account_kind from public.accounts where id = v_account_id;

  if v_account_kind = 'household' and p_role not in ('parent_admin', 'helper', 'single') then
    raise exception 'role % is not invitable into a household-kind account', p_role
      using errcode = 'check_violation';
  end if;

  if v_account_kind = 'shadchanus' and p_role <> 'shadchan' then
    raise exception 'role % is not invitable into a shadchanus-kind account', p_role
      using errcode = 'check_violation';
  end if;

  -- Story 6.1 (AC-2, AC-4): a single-role invite always names a target — the
  -- check constraint would catch a null one too, but this is a clearer
  -- client message than a bare constraint violation.
  if p_role = 'single' and p_target_single_id is null then
    raise exception 'a single-role invite requires a target single'
      using errcode = 'check_violation';
  end if;

  -- Story 6.1 (AC-4): refuses an already-linked target at creation time
  -- (UX only — accept_invite() fails closed independently if the target
  -- becomes linked in the window between invite and acceptance).
  if p_target_single_id is not null and not exists (
    select 1 from public.singles s
    where s.id = p_target_single_id
      and s.account_id = v_account_id
      and s.member_id is null
  ) then
    raise exception 'single % not found in current account', p_target_single_id
      using errcode = 'check_violation';
  end if;

  insert into public.invites (email, account_id, role, invited_by, target_single_id)
  values (p_email, v_account_id, p_role, v_membership_id, p_target_single_id)
  returning * into v_invite;

  perform public.demo_register_seed_resource(
    'invite', v_invite.id, v_account_id
  );

  return v_invite;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.demo_account_is_previewable(p_account_id bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  -- Preview is intentionally narrower than the broader manifest helpers:
  -- seeding/clearing/failed runs remain mapped for compensating cleanup and
  -- simulated dispatch, but browser listing preview is active-only. Requiring
  -- both the caller's active context and the requested target account to be
  -- members of the same active run closes cross-bundle and stale-run access.
  select exists (
    select 1
    from public.demo_run_accounts caller_scope
    join public.demo_runs dr on dr.id = caller_scope.run_id
    join public.demo_run_accounts target_scope
      on target_scope.run_id = dr.id
     and target_scope.account_id = p_account_id
    where caller_scope.account_id = public.current_context_id()
      and dr.status = 'active'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.demo_delivery_history()
 RETURNS TABLE(event_type text, status text, simulated boolean, occurred_at timestamp with time zone, resource text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  with current_run as (
    select dr.id as run_id
    from public.demo_run_accounts caller_scope
    join public.demo_runs dr on dr.id = caller_scope.run_id
    where caller_scope.account_id = public.current_context_id()
      and dr.status = 'active'
    order by dr.id desc
    limit 1
  )
  select 'message'::text, mn.status, mn.simulated,
    coalesce(mn.sent_at, mn.created_at) as occurred_at, 'message'::text
  from public.message_notifications mn
  cross join current_run cr
  left join public.connections c on c.id = mn.connection_id
  where cr.run_id is not null
    and mn.simulated is true
    and (mn.account_id is not null or mn.connection_id is not null)
    and (
      mn.account_id is null
      or exists (
        select 1
        from public.demo_run_accounts dra
        where dra.run_id = cr.run_id and dra.account_id = mn.account_id
      )
    )
    and (
      mn.connection_id is null
      or (
        c.id is not null
        and exists (
          select 1
          from public.demo_run_accounts dra
          where dra.run_id = cr.run_id and dra.account_id = c.household_account_id
        )
        and exists (
          select 1
          from public.demo_run_accounts dra
          where dra.run_id = cr.run_id and dra.account_id = c.shadchanus_account_id
        )
      )
    )
  union all
  select 'reminder'::text, tn.status, tn.simulated,
    coalesce(tn.sent_at, tn.created_at), 'task'::text
  from public.task_notifications tn
  cross join current_run cr
  where cr.run_id is not null
    and tn.simulated is true
    and exists (
      select 1 from public.demo_run_accounts dra
      where dra.run_id = cr.run_id and dra.account_id = tn.account_id
    )
  union all
  select 'share'::text, 'accessed'::text, sal.simulated, sal.accessed_at, sal.resource
  from public.share_access_log sal
  join public.share_links sl on sl.id = sal.share_link_id
  cross join current_run cr
  where cr.run_id is not null
    and sal.simulated is true
    and exists (
      select 1 from public.demo_run_accounts dra
      where dra.run_id = cr.run_id and dra.account_id = sl.account_id
    )
  order by occurred_at desc;
$function$
;

CREATE OR REPLACE FUNCTION public.demo_scope_is_simulated(p_account_id bigint DEFAULT NULL::bigint, p_connection_id bigint DEFAULT NULL::bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  -- If both axes are supplied they must belong to the SAME active run. The
  -- old OR-shaped predicate could mark a production account as simulated
  -- merely because its connection happened to touch a different bundle.
  select case
    when p_account_id is null and p_connection_id is null then false
    else exists (
      select 1
      from public.demo_runs dr
      where dr.status in ('seeding', 'active', 'clearing', 'failed')
        and (
          p_account_id is null
          or exists (
            select 1
            from public.demo_run_accounts dra
            where dra.run_id = dr.id and dra.account_id = p_account_id
          )
        )
        and (
          p_connection_id is null
          or exists (
            select 1
            from public.connections c
            where c.id = p_connection_id
              and exists (
                select 1
                from public.demo_run_accounts dra
                where dra.run_id = dr.id
                  and dra.account_id = c.household_account_id
              )
              and exists (
                select 1
                from public.demo_run_accounts dra
                where dra.run_id = dr.id
                  and dra.account_id = c.shadchanus_account_id
              )
          )
        )
    )
  end;
$function$
;

CREATE OR REPLACE FUNCTION public.enqueue_due_task_notifications(p_now timestamp with time zone DEFAULT now())
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_count integer;
begin
  with candidates as (
    select
      t.id as task_id,
      t.account_id,
      t.due_date,
      m.email::text as recipient_email,
      public.demo_scope_is_simulated(t.account_id, null) as simulated,
      case
        when t.member_id is null then 'skipped'
        when m.email is null then 'failed'
        else 'pending'
      end as status,
      case
        when t.member_id is null then 'unassigned — no member_id set (deliberate, not a delivery failure)'
        when m.email is null then 'member_id names no live or no enabled member of this task''s own account'
        else null
      end as error
    from public.tasks t
    left join public.members m
      on m.id = t.member_id and public.is_deliverable_member(m.id, t.account_id)
    where t.done_date is null
      and t.due_date is not null
      and t.due_date <= p_now
      and 'email' = any (t.delivery_channels)
  ),
  inserted as (
    insert into public.task_notifications (account_id, task_id, channel, due_date, status, recipient_email, error, simulated, sent_at)
    select candidates.account_id, candidates.task_id, 'email', candidates.due_date,
      case when candidates.simulated then 'sent' else candidates.status end,
      candidates.recipient_email,
      case when candidates.simulated then 'simulated demo delivery' else candidates.error end,
      candidates.simulated,
      case when candidates.simulated then now() else null end
    from candidates
    on conflict (task_id, channel, due_date) do nothing
    returning 1
  )
  select count(*) into v_count from inserted;

  return v_count;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.export_account_data()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint := public.current_context_id();
  v_result jsonb := '{}'::jsonb;
begin
  -- Verify authenticated caller (not service_role)
  if current_user = 'postgres' then
    raise exception 'export_account_data: must be called by authenticated user'
      using errcode = 'insufficient_privilege';
  end if;

  perform public.demo_assert_same_active_run(array[v_account_id], 'account export');

  -- Explicitly list each table to avoid dynamic SQL issues
  -- This is maintainable because schema changes require migrations anyway
  SELECT jsonb_set(v_result, '{accounts}', coalesce(jsonb_agg(to_jsonb(acc)), '[]'))
  FROM public.accounts acc WHERE acc.id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{singles}', coalesce(jsonb_agg(to_jsonb(s)), '[]'))
  FROM public.singles s WHERE s.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{resumes}', coalesce(jsonb_agg(to_jsonb(r)), '[]'))
  FROM public.resumes r WHERE r.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{shidduchim}', coalesce(jsonb_agg(to_jsonb(sh)), '[]'))
  FROM public.shidduchim sh WHERE sh.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{messages}', coalesce(jsonb_agg(to_jsonb(m)), '[]'))
  FROM public.messages m WHERE m.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{references}', coalesce(jsonb_agg(to_jsonb(ref)), '[]'))
  FROM public.references ref WHERE ref.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{tasks}', coalesce(jsonb_agg(to_jsonb(t)), '[]'))
  FROM public.tasks t WHERE t.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{notes}', coalesce(jsonb_agg(to_jsonb(n)), '[]'))
  FROM public.notes n WHERE n.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{events}', coalesce(jsonb_agg(to_jsonb(e)), '[]'))
  FROM public.events e WHERE e.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{medical_notes}', coalesce(jsonb_agg(to_jsonb(mn)), '[]'))
  FROM public.medical_notes mn WHERE mn.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{connections}', coalesce(jsonb_agg(to_jsonb(c)), '[]'))
  FROM public.connections c WHERE c.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{connection_invites}', coalesce(jsonb_agg(to_jsonb(ci)), '[]'))
  FROM public.connection_invites ci WHERE ci.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{child_grants}', coalesce(jsonb_agg(to_jsonb(cg)), '[]'))
  FROM public.child_grants cg WHERE cg.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{share_links}', coalesce(jsonb_agg(to_jsonb(sl)), '[]'))
  FROM public.share_links sl WHERE sl.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{account_members}', coalesce(jsonb_agg(to_jsonb(am)), '[]'))
  FROM public.account_members am WHERE am.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{purge_requests}', coalesce(jsonb_agg(to_jsonb(pr)), '[]'))
  FROM public.purge_requests pr WHERE pr.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{deletion_requests}', coalesce(jsonb_agg(to_jsonb(dr)), '[]'))
  FROM public.deletion_requests dr WHERE dr.account_id = v_account_id
  INTO v_result;

  -- Add remaining tables with account_id column
  SELECT jsonb_set(v_result, '{entity_files}', coalesce(jsonb_agg(to_jsonb(ef)), '[]'))
  FROM public.entity_files ef WHERE ef.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{configuration}', coalesce(jsonb_agg(to_jsonb(c)), '[]'))
  FROM public.configuration c WHERE c.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{ai_usage}', coalesce(jsonb_agg(to_jsonb(au)), '[]'))
  FROM public.ai_usage au WHERE au.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{stripe_events}', coalesce(jsonb_agg(to_jsonb(se)), '[]'))
  FROM public.stripe_events se WHERE se.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{ai_parse_attempts}', coalesce(jsonb_agg(to_jsonb(apa)), '[]'))
  FROM public.ai_parse_attempts apa WHERE apa.account_id = v_account_id
  INTO v_result;

  SELECT jsonb_set(v_result, '{cron_heartbeat}', coalesce(jsonb_agg(to_jsonb(ch)), '[]'))
  FROM public.cron_heartbeat ch WHERE ch.account_id = v_account_id
  INTO v_result;

  RETURN v_result;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.export_account_files()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint := public.current_context_id();
  v_result jsonb := '{}'::jsonb;
  v_rows jsonb;
begin
  -- Verify authenticated caller
  if current_user = 'postgres' then
    raise exception 'export_account_files: must be called by authenticated user'
      using errcode = 'insufficient_privilege';
  end if;

  perform public.demo_assert_same_active_run(
    array[public.current_context_id()],
    'file export'
  );

  -- Resume photos (have file_bytes in DB)
  select coalesce(jsonb_agg(to_jsonb(t)), '[]'::jsonb) into v_rows
  from (
    select
      rp.id,
      rp.file_name as filename,
      encode(rp.file_bytes, 'base64') as content_base64,
      rp.content_type,
      null as storage_path
    from public.resume_photos rp
    join public.resumes r on r.id = rp.resume_id
    where r.account_id = v_account_id
  ) t;
  v_result := jsonb_set(v_result, array['resume_photos'], v_rows);

  -- Entity files (attachments) - stored in Supabase Storage, export metadata + storage_path
  select coalesce(jsonb_agg(to_jsonb(t)), '[]'::jsonb) into v_rows
  from (
    select
      ef.id,
      ef.file_name as filename,
      null as content_base64,
      ef.mime_type as content_type,
      ef.storage_path
    from public.entity_files ef
    where ef.account_id = v_account_id
  ) t;
  v_result := jsonb_set(v_result, array['entity_files'], v_rows);

  return v_result;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.export_full_account_bundle()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_data jsonb;
  v_files jsonb;
  v_bundle jsonb;
begin
  perform public.demo_assert_same_active_run(
    array[public.current_context_id()],
    'full account export'
  );
  v_data := public.export_account_data();
  v_files := public.export_account_files();
  v_bundle := jsonb_build_object(
    'exported_at', now(),
    'account_id', public.current_context_id(),
    'data', v_data,
    'files', v_files
  );
  return v_bundle;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.match_identity(p_target_type text, p_name_en text DEFAULT NULL::text, p_name_he text DEFAULT NULL::text, p_phone text DEFAULT NULL::text, p_parents text DEFAULT NULL::text, p_seminary text DEFAULT NULL::text, p_shul text DEFAULT NULL::text, p_location text DEFAULT NULL::text, p_exclude_target_id bigint DEFAULT NULL::bigint)
 RETURNS TABLE(target_id bigint, confidence numeric, deciding_facts jsonb)
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint;
  v_name_en_norm text;
  v_name_he_norm text;
  v_name_en_key text;
  v_name_he_key text;
  v_phone_norm text;
  v_parents_norm text;
  v_seminary_norm text;
  v_shul_norm text;
  v_location_norm text;
begin
  if p_target_type not in ('reference', 'shidduch', 'date_record') then
    raise exception 'unknown identity target_type: %', p_target_type
      using errcode = 'check_violation';
  end if;

  v_account_id := public.current_context_id();
  if v_account_id is null then
    return;
  end if;

  v_name_en_norm := public.normalize_identity_text(p_name_en);
  v_name_he_norm := public.normalize_identity_text(p_name_he);
  v_name_en_key := public.identity_name_key(p_name_en);
  v_name_he_key := public.identity_name_key(p_name_he);
  v_phone_norm := public.normalize_phone(p_phone);
  v_parents_norm := public.normalize_identity_text(p_parents);
  v_seminary_norm := public.normalize_identity_text(p_seminary);
  v_shul_norm := public.normalize_identity_text(p_shul);
  v_location_norm := public.normalize_identity_text(p_location);

  -- Nothing identifying was supplied: no candidates, no guessing.
  if v_phone_norm is null and v_name_en_norm is null and v_name_he_norm is null then
    return;
  end if;

  return query
  with scored as (
    select
      s.target_id as sig_target_id,
      (v_phone_norm is not null and s.phone_norm = v_phone_norm) as phone_hit,
      (
        (v_name_en_norm is not null and s.name_en_norm = v_name_en_norm)
        or (v_name_he_norm is not null and s.name_he_norm = v_name_he_norm)
      ) as name_exact,
      (
        (v_name_en_key is not null and s.name_en_key = v_name_en_key)
        or (v_name_he_key is not null and s.name_he_key = v_name_he_key)
      ) as name_variant,
      (v_parents_norm is not null and s.parents_norm = v_parents_norm) as parents_hit,
      (v_seminary_norm is not null and s.seminary_norm = v_seminary_norm) as seminary_hit,
      (v_shul_norm is not null and s.shul_norm = v_shul_norm) as shul_hit,
      (v_location_norm is not null and s.location_norm = v_location_norm) as location_hit
    from public.identity_signals s
    left join public.shidduchim candidate
      on p_target_type = 'shidduch'
     and candidate.id = s.target_id
    where s.account_id = v_account_id
      and s.target_type = p_target_type
      and (p_exclude_target_id is null or s.target_id <> p_exclude_target_id)
      and (
        p_target_type <> 'shidduch'
        or (
          candidate.id is not null
          and not coalesce(public.shidduch_has_known_halachic_conflict(
            candidate.single_id,
            candidate.person_gender,
            candidate.kohen_status,
            candidate.marital_status
          ), false)
        )
      )
  ),
  weighted as (
    select
      sc.*,
      (sc.parents_hit::int + sc.seminary_hit::int + sc.shul_hit::int + sc.location_hit::int) as corroborators
    from scored sc
  )
  select
    w.sig_target_id,
    case
      when w.phone_hit and (w.name_exact or w.name_variant) then 0.98
      when w.phone_hit then 0.90
      when w.name_exact and w.corroborators >= 2 then 0.85
      when w.name_exact and w.corroborators = 1 then 0.75
      when w.name_variant and w.corroborators >= 2 then 0.70
      when w.name_variant and w.corroborators = 1 then 0.60
    end::numeric,
    (
      select coalesce(jsonb_agg(f.fact), '[]'::jsonb)
      from (
        select jsonb_build_object('signal', 'phone', 'detail', 'phone number matches exactly') as fact
          where w.phone_hit
        union all
        select jsonb_build_object('signal', 'name', 'detail', 'name matches exactly')
          where w.name_exact
        union all
        select jsonb_build_object('signal', 'name', 'detail', 'name matches as a Hebrew/English spelling variant')
          where w.name_variant and not w.name_exact
        union all
        select jsonb_build_object('signal', 'parents', 'detail', 'same parents')
          where w.parents_hit
        union all
        select jsonb_build_object('signal', 'school', 'detail', 'same school or seminary')
          where w.seminary_hit
        union all
        select jsonb_build_object('signal', 'shul', 'detail', 'same shul')
          where w.shul_hit
        union all
        select jsonb_build_object('signal', 'location', 'detail', 'same location')
          where w.location_hit
      ) f
    )
  from weighted w
  where w.phone_hit
     or ((w.name_exact or w.name_variant) and w.corroborators >= 1)
  order by 2 desc, 1 asc
  limit 10;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.validate_shidduch_halachic_eligibility()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  -- Serialize candidate writes with edits to the target single's recorded
  -- facts. The lock is transaction-scoped; the following SELECT therefore
  -- observes the committed facts after a concurrent writer releases it.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('myshadchan.halachic.single:' || new.single_id::text, 0)
  );

  if coalesce(public.shidduch_has_known_halachic_conflict(
    new.single_id,
    new.person_gender,
    new.kohen_status,
    new.marital_status
  ), false) then
    raise exception 'This suggestion conflicts with a recorded detail.'
      using errcode = 'check_violation';
  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.validate_single_halachic_eligibility()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('myshadchan.halachic.single:' || new.id::text, 0)
  );

  if exists (
    select 1
    from public.shidduchim s
    where s.single_id = new.id
      and public.has_known_halachic_conflict(
        new.gender,
        new.kohen_status,
        new.marital_status,
        s.person_gender,
        s.kohen_status,
        s.marital_status
      )
  ) then
    raise exception 'This change conflicts with a recorded detail.'
      using errcode = 'check_violation';
  end if;

  return new;
end;
$function$
;

revoke all on table public.demo_run_actor_intents from anon, authenticated;
revoke all on table public.demo_run_member_state from anon, authenticated;
revoke all on table public.demo_run_resources from anon, authenticated;

grant delete on table "public"."demo_run_actor_intents" to "service_role";

grant insert on table "public"."demo_run_actor_intents" to "service_role";

grant references on table "public"."demo_run_actor_intents" to "service_role";

grant select on table "public"."demo_run_actor_intents" to "service_role";

grant trigger on table "public"."demo_run_actor_intents" to "service_role";

grant truncate on table "public"."demo_run_actor_intents" to "service_role";

grant update on table "public"."demo_run_actor_intents" to "service_role";

grant delete on table "public"."demo_run_member_state" to "service_role";

grant insert on table "public"."demo_run_member_state" to "service_role";

grant references on table "public"."demo_run_member_state" to "service_role";

grant select on table "public"."demo_run_member_state" to "service_role";

grant trigger on table "public"."demo_run_member_state" to "service_role";

grant truncate on table "public"."demo_run_member_state" to "service_role";

grant update on table "public"."demo_run_member_state" to "service_role";

grant delete on table "public"."demo_run_resources" to "service_role";

grant insert on table "public"."demo_run_resources" to "service_role";

grant references on table "public"."demo_run_resources" to "service_role";

grant select on table "public"."demo_run_resources" to "service_role";

grant trigger on table "public"."demo_run_resources" to "service_role";

grant truncate on table "public"."demo_run_resources" to "service_role";

grant update on table "public"."demo_run_resources" to "service_role";

grant all on sequence public.demo_run_actor_intents_id_seq to service_role;
grant all on sequence public.demo_run_member_state_id_seq to service_role;
grant all on sequence public.demo_run_resources_id_seq to service_role;

-- Keep the declarative browser/server boundary explicit. New functions
-- otherwise inherit PostgreSQL's EXECUTE-to-PUBLIC default, and replacing an
-- existing body does not repair a stale grant on that function.
revoke all on function public.current_account_demo_previewable() from public, anon;
grant execute on function public.current_account_demo_previewable() to authenticated, service_role;
revoke all on function public.current_demo_preview_accounts() from public, anon;
grant execute on function public.current_demo_preview_accounts() to authenticated, service_role;

revoke all on function public.demo_run_for_account(bigint) from public, anon, authenticated;
grant execute on function public.demo_run_for_account(bigint) to service_role;
revoke all on function public.demo_assert_same_active_run(bigint[], text) from public, anon, authenticated;
grant execute on function public.demo_assert_same_active_run(bigint[], text) to service_role;
revoke all on function public.demo_assert_registered_actor(bigint, uuid, text) from public, anon, authenticated;
grant execute on function public.demo_assert_registered_actor(bigint, uuid, text) to service_role;
revoke all on function public.demo_register_seed_resource(text, bigint, bigint) from public, anon, authenticated;
grant execute on function public.demo_register_seed_resource(text, bigint, bigint) to service_role;
revoke all on function public.demo_root_account_for(bigint) from public, anon, authenticated;
grant execute on function public.demo_root_account_for(bigint) to service_role;
revoke all on function public.demo_bundle_contains_account(bigint, bigint) from public, anon, authenticated;
grant execute on function public.demo_bundle_contains_account(bigint, bigint) to service_role;
revoke all on function public.demo_account_is_previewable(bigint) from public, anon;
grant execute on function public.demo_account_is_previewable(bigint) to authenticated, service_role;
revoke all on function public.demo_account_in_active_run(bigint) from public;
grant execute on function public.demo_account_in_active_run(bigint) to anon, authenticated, service_role;
revoke all on function public.demo_scope_is_simulated(bigint, bigint) from public, anon, authenticated;
grant execute on function public.demo_scope_is_simulated(bigint, bigint) to service_role;
revoke all on function public.demo_delivery_history() from public, anon;
grant execute on function public.demo_delivery_history() to authenticated, service_role;

revoke all on function public.demo_assert_empty_account(bigint) from public, anon, authenticated;
grant execute on function public.demo_assert_empty_account(bigint) to service_role;
revoke all on function public.begin_demo_seed(bigint, text) from public, anon, authenticated;
grant execute on function public.begin_demo_seed(bigint, text) to service_role;
revoke all on function public.demo_run_lease_is_current(bigint, text, text) from public, anon, authenticated;
grant execute on function public.demo_run_lease_is_current(bigint, text, text) to service_role;
revoke all on function public.heartbeat_demo_run(bigint, text, text) from public, anon, authenticated;
grant execute on function public.heartbeat_demo_run(bigint, text, text) to service_role;
revoke all on function public.create_demo_companion_context(bigint, text, text, text, text) from public, anon, authenticated;
grant execute on function public.create_demo_companion_context(bigint, text, text, text, text) to service_role;
revoke all on function public.create_demo_actor_intent(bigint, text, text, text) from public, anon, authenticated;
grant execute on function public.create_demo_actor_intent(bigint, text, text, text) to service_role;
revoke all on function public.reconcile_demo_actor(bigint, text, text, uuid) from public, anon, authenticated;
grant execute on function public.reconcile_demo_actor(bigint, text, text, uuid) to service_role;
revoke all on function public.register_demo_resource(bigint, text, text, bigint) from public, anon, authenticated;
grant execute on function public.register_demo_resource(bigint, text, text, bigint) to service_role;
revoke all on function public.register_demo_storage(bigint, text, bigint, text, text, text) from public, anon, authenticated;
grant execute on function public.register_demo_storage(bigint, text, bigint, text, text, text) to service_role;
revoke all on function public.restore_demo_member_state(bigint, text, text) from public, anon, authenticated;
grant execute on function public.restore_demo_member_state(bigint, text, text) to service_role;
revoke all on function public.activate_demo_run(bigint, text, text) from public, anon, authenticated;
grant execute on function public.activate_demo_run(bigint, text, text) to service_role;
revoke all on function public.claim_demo_clear(bigint, text) from public, anon, authenticated;
grant execute on function public.claim_demo_clear(bigint, text) to service_role;
revoke all on function public.fail_demo_run(bigint, text, text) from public, anon, authenticated;
grant execute on function public.fail_demo_run(bigint, text, text) to service_role;
revoke all on function public.finalize_demo_clear(bigint, text, boolean, boolean, uuid) from public, anon, authenticated;
grant execute on function public.finalize_demo_clear(bigint, text, boolean, boolean, uuid) to service_role;


  create policy "Listings readable by owner"
  on "public"."listings"
  as permissive
  for select
  to authenticated
using (((account_id = public.current_context_id()) AND ((NOT public.demo_account_in_active_run(account_id)) OR public.demo_account_is_previewable(account_id))));



  create policy "Listings readable via accepted grant"
  on "public"."listings"
  as permissive
  for select
  to authenticated
using (((EXISTS ( SELECT 1
   FROM public.child_grants g
  WHERE ((g.status = 'accepted'::text) AND (g.grantee_account_id = public.current_context_id()) AND (g.target_single_id = listings.single_id)))) AND (public.current_member_role() <> 'single'::text) AND ((NOT public.demo_account_in_active_run(account_id)) OR public.demo_account_is_previewable(account_id))));
