-- Story 5.4: resume_photos (the Photo tab's per-photo table, AC 2/3/4/6),
-- add_resume_photo()/hide_resume_photo() (the sole write paths), and the
-- `documents` bucket's photos/-scoped storage policies.
--
-- MANUAL ADJUSTMENTS (see AGENTS.md; entity_files precedent, migration
-- 20260729070301):
-- 1. The raw diff re-emitted the unrelated `reference_links_summary`,
--    `shadchan_stats`, `shidduchim_summary` and `singles_summary` views
--    (drop + recreate, with `security_invoker` stripped, this repo's known
--    `db diff`-and-views quirk). This story does not touch any of those
--    four views or their base tables, so that pair of statements was
--    removed rather than carried — recreating them here would be a no-op
--    at best and, since `db diff` never re-emits `security_invoker`, an RLS
--    regression at worst if that half were forgotten.
-- 2. `db diff` did not account for this database's pre-existing `alter
--    default privileges ... grant all on tables to authenticated` firing
--    the moment `create table` below ran, and emitted no ACL statement at
--    all for the two new functions. Verified live before the hand-added
--    block below: `authenticated` held TRUNCATE (bypasses RLS) and
--    TRIGGER/REFERENCES on resume_photos, the identity sequence had no
--    grant for `authenticated`/`service_role` at all (blocking every
--    INSERT), and `anon` could EXECUTE both new functions. Copied verbatim
--    from supabase/schemas/06_grants.sql so the applied database matches
--    the declared schema exactly.
-- 3. `db diff` does not emit `COMMENT ON` statements (same class of gap as
--    security_invoker/GRANT lines, migration 20260727233610) — added by
--    hand, verbatim from 01_tables.sql:379.

  create table "public"."resume_photos" (
    "id" bigint generated by default as identity not null,
    "account_id" bigint not null,
    "resume_id" bigint not null,
    "path" text not null,
    "uploaded_at" timestamp with time zone not null default now(),
    "visibility" text not null default 'shared'::text,
    "hidden_at" timestamp with time zone
      );


alter table "public"."resume_photos" enable row level security;

alter table "public"."resumes" drop column "photos";

CREATE INDEX resume_photos_account_id_idx ON public.resume_photos USING btree (account_id);

CREATE UNIQUE INDEX resume_photos_pkey ON public.resume_photos USING btree (id);

alter table "public"."resume_photos" add constraint "resume_photos_pkey" PRIMARY KEY using index "resume_photos_pkey";

alter table "public"."resume_photos" add constraint "resume_photos_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."resume_photos" validate constraint "resume_photos_account_id_fkey";

alter table "public"."resume_photos" add constraint "resume_photos_resume_id_fkey" FOREIGN KEY (account_id, resume_id) REFERENCES public.resumes(account_id, id) ON DELETE CASCADE not valid;

alter table "public"."resume_photos" validate constraint "resume_photos_resume_id_fkey";

alter table "public"."resume_photos" add constraint "resume_photos_storage_path_scope_check" CHECK ((path ~~ ((account_id)::text || '/%'::text))) not valid;

alter table "public"."resume_photos" validate constraint "resume_photos_storage_path_scope_check";

alter table "public"."resume_photos" add constraint "resume_photos_visibility_check" CHECK ((visibility = ANY (ARRAY['shared'::text, 'private_parent'::text]))) not valid;

alter table "public"."resume_photos" validate constraint "resume_photos_visibility_check";

-- MANUAL ADJUSTMENT 3, see the file header.
comment on table public.resume_photos is 'Deliberately not in account_has_domain_data()''s table list: it FKs to resumes, which that function already checks, so a photo cannot exist without a resumes row and the predicate is already true.';

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.add_resume_photo(p_shidduchim_id bigint, p_path text, p_visibility text DEFAULT 'shared'::text)
 RETURNS SETOF public.resume_photos
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint;
  v_resume_id bigint;
begin
  v_account_id := public.current_context_id();

  if not exists (
    select 1 from public.shidduchim s
    where s.id = p_shidduchim_id and s.account_id = v_account_id
  ) then
    raise exception 'shidduch % not found in current account', p_shidduchim_id;
  end if;

  insert into public.resumes (account_id, shidduchim_id)
  values (v_account_id, p_shidduchim_id)
  on conflict (shidduchim_id) do update set shidduchim_id = excluded.shidduchim_id
  returning id into v_resume_id;

  return query
  insert into public.resume_photos (account_id, resume_id, path, visibility)
  values (v_account_id, v_resume_id, p_path, coalesce(p_visibility, 'shared'))
  returning *;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.hide_resume_photo(p_photo_id bigint)
 RETURNS SETOF public.resume_photos
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v_account_id bigint;
begin
  v_account_id := public.current_context_id();

  if not exists (
    select 1 from public.resume_photos p
    where p.id = p_photo_id and p.account_id = v_account_id
  ) then
    raise exception 'photo % not found in current account', p_photo_id;
  end if;

  return query
  update public.resume_photos
  set hidden_at = now()
  where id = p_photo_id and account_id = v_account_id
  returning *;
end;
$function$
;

grant delete on table "public"."resume_photos" to "authenticated";

grant insert on table "public"."resume_photos" to "authenticated";

grant select on table "public"."resume_photos" to "authenticated";

grant update on table "public"."resume_photos" to "authenticated";

grant delete on table "public"."resume_photos" to "service_role";

grant insert on table "public"."resume_photos" to "service_role";

grant references on table "public"."resume_photos" to "service_role";

grant select on table "public"."resume_photos" to "service_role";

grant trigger on table "public"."resume_photos" to "service_role";

grant truncate on table "public"."resume_photos" to "service_role";

grant update on table "public"."resume_photos" to "service_role";

-- MANUAL ADJUSTMENT 2, see the file header.
revoke all on table public.resume_photos from anon, authenticated;
grant select, insert, update, delete on table public.resume_photos to authenticated;
grant all on table public.resume_photos to service_role;

revoke all on sequence public.resume_photos_id_seq from anon;
grant all on sequence public.resume_photos_id_seq to authenticated;
grant all on sequence public.resume_photos_id_seq to service_role;

revoke all on function public.add_resume_photo(bigint, text, text) from public, anon;
grant execute on function public.add_resume_photo(bigint, text, text) to authenticated;
grant execute on function public.add_resume_photo(bigint, text, text) to service_role;

revoke all on function public.hide_resume_photo(bigint) from public, anon;
grant execute on function public.hide_resume_photo(bigint) to authenticated;
grant execute on function public.hide_resume_photo(bigint) to service_role;


  create policy "Resume photos scoped to account, single sees only shared"
  on "public"."resume_photos"
  as permissive
  for all
  to authenticated
using (((account_id = public.current_context_id()) AND ((visibility = 'shared'::text) OR (EXISTS ( SELECT 1
   FROM public.account_members am
  WHERE ((am.id = public.current_member_id()) AND (am.role <> 'single'::text)))))))
with check (((account_id = public.current_context_id()) AND ((visibility = 'shared'::text) OR (EXISTS ( SELECT 1
   FROM public.account_members am
  WHERE ((am.id = public.current_member_id()) AND (am.role <> 'single'::text)))))));


CREATE TRIGGER set_resume_photos_account_id BEFORE INSERT ON public.resume_photos FOR EACH ROW EXECUTE FUNCTION public.set_account_id_default();

CREATE TRIGGER validate_resume_photos_household_scope BEFORE INSERT OR UPDATE OF account_id ON public.resume_photos FOR EACH ROW EXECUTE FUNCTION public.enforce_household_scope();


  create policy "Documents photos deletable within account"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'documents'::text) AND ((storage.foldername(name))[1] = (public.current_context_id())::text) AND ((storage.foldername(name))[2] = 'photos'::text) AND ((storage.foldername(name))[3] = ANY (ARRAY['shared'::text, 'private_parent'::text]))));



  create policy "Documents photos readable within account"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'documents'::text) AND ((storage.foldername(name))[1] = (public.current_context_id())::text) AND ((storage.foldername(name))[2] = 'photos'::text) AND (((storage.foldername(name))[3] = 'shared'::text) OR (EXISTS ( SELECT 1
   FROM public.account_members am
  WHERE ((am.id = public.current_member_id()) AND (am.role <> 'single'::text)))))));



  create policy "Documents photos writable within account"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'documents'::text) AND ((storage.foldername(name))[1] = (public.current_context_id())::text) AND ((storage.foldername(name))[2] = 'photos'::text) AND ((storage.foldername(name))[3] = ANY (ARRAY['shared'::text, 'private_parent'::text]))));



