create table "public"."single_notes" (
    "id" bigint generated by default as identity not null,
    "account_id" bigint not null,
    "single_id" bigint not null,
    "body" text not null,
    "visible_to_manager" boolean not null default false,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."single_notes" enable row level security;
alter table "public"."single_notes" force row level security;

CREATE INDEX single_notes_account_id_idx ON public.single_notes USING btree (account_id);

CREATE UNIQUE INDEX single_notes_pkey ON public.single_notes USING btree (id);

CREATE INDEX single_notes_single_id_idx ON public.single_notes USING btree (single_id);

alter table "public"."single_notes" add constraint "single_notes_pkey" PRIMARY KEY using index "single_notes_pkey";

alter table "public"."single_notes" add constraint "single_notes_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."single_notes" validate constraint "single_notes_account_id_fkey";

alter table "public"."single_notes" add constraint "single_notes_single_id_fkey" FOREIGN KEY (account_id, single_id) REFERENCES public.singles(account_id, id) ON DELETE CASCADE not valid;

alter table "public"."single_notes" validate constraint "single_notes_single_id_fkey";

revoke all on table "public"."single_notes" from anon, authenticated;
grant select, insert, update, delete on table "public"."single_notes" to authenticated;
grant all on table "public"."single_notes" to service_role;

revoke all on sequence "public"."single_notes_id_seq" from anon;
grant all on sequence "public"."single_notes_id_seq" to authenticated;
grant all on sequence "public"."single_notes_id_seq" to service_role;

  create policy "Single notes owned by single"
  on "public"."single_notes"
  as permissive
  for all
  to authenticated
using (((account_id = public.current_context_id()) AND (EXISTS ( SELECT 1
   FROM public.singles s
  WHERE ((s.id = single_notes.single_id) AND (s.account_id = public.current_context_id()) AND (s.member_id = public.current_member_id()))))))
with check (((account_id = public.current_context_id()) AND (EXISTS ( SELECT 1
   FROM public.singles s
  WHERE ((s.id = single_notes.single_id) AND (s.account_id = public.current_context_id()) AND (s.member_id = public.current_member_id()))))));



  create policy "Single notes readable by manager when shared"
  on "public"."single_notes"
  as permissive
  for select
  to authenticated
using (((account_id = public.current_context_id()) AND (visible_to_manager = true) AND (public.current_member_role() = ANY (ARRAY['parent_admin'::text, 'self_manager'::text]))));


CREATE TRIGGER set_single_notes_account_id BEFORE INSERT ON public.single_notes FOR EACH ROW EXECUTE FUNCTION public.set_account_id_default();