
  create table "public"."cron_heartbeat" (
    "worker" text not null,
    "last_run_at" timestamp with time zone not null default now(),
    "last_ok_at" timestamp with time zone,
    "last_error" text
      );


alter table "public"."cron_heartbeat" enable row level security;


  create table "public"."task_notifications" (
    "id" bigint generated by default as identity not null,
    "account_id" bigint not null,
    "task_id" bigint not null,
    "channel" text not null,
    "due_date" timestamp with time zone not null,
    "status" text not null default 'pending'::text,
    "recipient_email" text,
    "attempts" integer not null default 0,
    "sent_at" timestamp with time zone,
    "error" text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."task_notifications" enable row level security;

-- Hand-added: `db diff` does not re-emit FORCE ROW LEVEL SECURITY on a table
-- created within the same diff pass (the same gap message_notifications'
-- own migration documents — see 20260802051941_message_notifications.sql
-- and 05_policies.sql's Story 12.2 comment on this table).
alter table "public"."task_notifications" force row level security;

CREATE UNIQUE INDEX cron_heartbeat_pkey ON public.cron_heartbeat USING btree (worker);

CREATE INDEX task_notifications_pending_idx ON public.task_notifications USING btree (status, created_at);

CREATE UNIQUE INDEX task_notifications_pkey ON public.task_notifications USING btree (id);

CREATE UNIQUE INDEX task_notifications_task_id_channel_due_date_key ON public.task_notifications USING btree (task_id, channel, due_date);

alter table "public"."cron_heartbeat" add constraint "cron_heartbeat_pkey" PRIMARY KEY using index "cron_heartbeat_pkey";

alter table "public"."task_notifications" add constraint "task_notifications_pkey" PRIMARY KEY using index "task_notifications_pkey";

alter table "public"."task_notifications" add constraint "task_notifications_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."task_notifications" validate constraint "task_notifications_account_id_fkey";

alter table "public"."task_notifications" add constraint "task_notifications_channel_check" CHECK ((channel = 'email'::text)) not valid;

alter table "public"."task_notifications" validate constraint "task_notifications_channel_check";

alter table "public"."task_notifications" add constraint "task_notifications_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'sending'::text, 'sent'::text, 'failed'::text, 'skipped'::text]))) not valid;

alter table "public"."task_notifications" validate constraint "task_notifications_status_check";

alter table "public"."task_notifications" add constraint "task_notifications_task_id_channel_due_date_key" UNIQUE using index "task_notifications_task_id_channel_due_date_key";

alter table "public"."task_notifications" add constraint "task_notifications_task_id_fkey" FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE not valid;

alter table "public"."task_notifications" validate constraint "task_notifications_task_id_fkey";

-- Hand-added (AC-4): `db diff` never emits data, only DDL, so this backfill
-- cannot come from the generator — it must ship in THIS migration, not a
-- follow-up one or a script (the member_state lesson: a fail-closed
-- mechanism that ships without backfilling the rows already in the table).
-- Without it, the first sweep tick after deploy would enqueue and email
-- every reminder that is already overdue at deploy time — including any
-- overdue by weeks — all at once. Suppresses the pre-existing backlog by
-- pre-occupying the (task_id, channel, due_date) unique key each one would
-- otherwise enqueue under, so enqueue_due_task_notifications()'s own
-- `on conflict do nothing` (02_functions.sql) suppresses it forever after —
-- unless the task is later snoozed, which advances due_date and so
-- legitimately re-arms delivery at the new due moment (AC-2).
insert into public.task_notifications
  (account_id, task_id, channel, due_date, status, error)
select t.account_id, t.id, 'email', t.due_date, 'skipped',
       'pre-delivery backlog suppressed by the migration that introduced this table'
from public.tasks t
where t.done_date is null
  and t.due_date is not null
  and t.due_date <= now()
  and 'email' = any (t.delivery_channels)
on conflict do nothing;

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.claim_due_task_notifications(p_limit integer)
 RETURNS TABLE(id bigint, task_id bigint, account_id bigint, recipient_email text, task_text text, due_date timestamp with time zone, target_type text, target_id bigint)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  perform public.enqueue_due_task_notifications();

  return query
  with claimed as (
    update public.task_notifications tn
    set status = 'sending', attempts = tn.attempts + 1
    where tn.id in (
      select tn2.id from public.task_notifications tn2
      where tn2.status = 'pending'
      order by tn2.created_at
      limit p_limit
      for update skip locked
    )
    returning tn.*
  )
  select
    claimed.id,
    claimed.task_id,
    claimed.account_id,
    claimed.recipient_email,
    t.text,
    claimed.due_date,
    t.target_type,
    t.target_id
  from claimed
  join public.tasks t on t.id = claimed.task_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.enqueue_due_task_notifications(p_now timestamp with time zone DEFAULT now())
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_count integer;
begin
  with candidates as (
    select
      t.id as task_id,
      t.account_id,
      t.due_date,
      m.email::text as recipient_email,
      case
        when t.member_id is null then 'skipped'
        when m.email is null then 'failed'
        else 'pending'
      end as status,
      case
        when t.member_id is null then 'unassigned — no member_id set (deliberate, not a delivery failure)'
        when m.email is null then 'member_id names no live or no enabled member'
        else null
      end as error
    from public.tasks t
    left join public.members m on m.id = t.member_id and m.disabled = false
    where t.done_date is null
      and t.due_date is not null
      and t.due_date <= p_now
      and 'email' = any (t.delivery_channels)
  ),
  inserted as (
    insert into public.task_notifications (account_id, task_id, channel, due_date, status, recipient_email, error)
    select candidates.account_id, candidates.task_id, 'email', candidates.due_date, candidates.status, candidates.recipient_email, candidates.error
    from candidates
    on conflict (task_id, channel, due_date) do nothing
    returning 1
  )
  select count(*) into v_count from inserted;

  return v_count;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.record_cron_heartbeat(p_worker text, p_error text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if p_error is not null and p_error not in ('rpc_failed', 'transport_failed', 'unknown') then
    raise exception 'invalid cron_heartbeat error code: %', p_error
      using errcode = 'invalid_parameter_value';
  end if;

  insert into public.cron_heartbeat (worker, last_run_at, last_ok_at, last_error)
  values (p_worker, now(), case when p_error is null then now() else null end, p_error)
  on conflict (worker) do update
    set last_run_at = now(),
        last_ok_at = case when p_error is null then now() else public.cron_heartbeat.last_ok_at end,
        last_error = p_error;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.settle_task_notification(p_id bigint, p_status text, p_error text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if p_status not in ('sent', 'failed') then
    raise exception 'invalid task_notification status: %', p_status
      using errcode = 'invalid_parameter_value';
  end if;

  update public.task_notifications
  set status = p_status,
      error = p_error,
      sent_at = case when p_status = 'sent' then now() else sent_at end
  where id = p_id
    and status = 'sending';
end;
$function$
;

-- Hand-added: `db diff` under-emitted every one of these four function
-- grants entirely — a newly created function defaults to EXECUTE granted to
-- PUBLIC, and 06_grants.sql's revokes/grants against that default never
-- appeared in the plain generated diff (the same class of gap
-- message_notifications' own migration documents — see
-- 20260802051941_message_notifications.sql). Without this block every one
-- of these four SECURITY DEFINER functions would still be callable by
-- `authenticated` through inherited PUBLIC execute, which AC-6/AC-7/AC-8/
-- AC-9 all forbid.
revoke all on function public.enqueue_due_task_notifications(timestamp with time zone) from public, anon, authenticated;
grant execute on function public.enqueue_due_task_notifications(timestamp with time zone) to service_role;

revoke all on function public.claim_due_task_notifications(integer) from public, anon, authenticated;
grant execute on function public.claim_due_task_notifications(integer) to service_role;

revoke all on function public.settle_task_notification(bigint, text, text) from public, anon, authenticated;
grant execute on function public.settle_task_notification(bigint, text, text) to service_role;

revoke all on function public.record_cron_heartbeat(text, text) from public, anon, authenticated;
grant execute on function public.record_cron_heartbeat(text, text) to service_role;

-- Hand-added: `db diff` under-emits here exactly like its documented blind
-- spot for view security_invoker/grants — it emitted the explicit GRANTs
-- below but not the REVOKEs needed to strip the TRUNCATE/REFERENCES/TRIGGER
-- privilege Postgres's default privileges hand `authenticated` on every new
-- table `postgres` creates (06_grants.sql's own comment documents this fact;
-- message_notifications' own migration hit the identical gap). TRUNCATE
-- bypasses RLS entirely — force or no force — so leaving it granted on
-- either of these two tables is not cosmetic: task_notifications carries
-- recipient email addresses across every tenant (AC-8), and TRUNCATE would
-- let `authenticated` destroy cron_heartbeat's own liveness signal (AC-9).
revoke references on table "public"."cron_heartbeat" from "authenticated";
revoke trigger on table "public"."cron_heartbeat" from "authenticated";
revoke truncate on table "public"."cron_heartbeat" from "authenticated";

revoke references on table "public"."task_notifications" from "authenticated";
revoke trigger on table "public"."task_notifications" from "authenticated";
revoke truncate on table "public"."task_notifications" from "authenticated";

grant select on table "public"."cron_heartbeat" to "authenticated";

grant delete on table "public"."cron_heartbeat" to "service_role";

grant insert on table "public"."cron_heartbeat" to "service_role";

grant references on table "public"."cron_heartbeat" to "service_role";

grant select on table "public"."cron_heartbeat" to "service_role";

grant trigger on table "public"."cron_heartbeat" to "service_role";

grant truncate on table "public"."cron_heartbeat" to "service_role";

grant update on table "public"."cron_heartbeat" to "service_role";

grant delete on table "public"."task_notifications" to "service_role";

grant insert on table "public"."task_notifications" to "service_role";

grant references on table "public"."task_notifications" to "service_role";

grant select on table "public"."task_notifications" to "service_role";

grant trigger on table "public"."task_notifications" to "service_role";

grant truncate on table "public"."task_notifications" to "service_role";

grant update on table "public"."task_notifications" to "service_role";

-- Hand-added: `db diff` never re-emits sequence grants either (the same
-- class of blind spot as the default-privilege REVOKEs above) — mirrors
-- message_notifications' own precedent
-- (20260802051941_message_notifications.sql) and 7.1's before that
-- (threads_id_seq/connections_id_seq, 20260731181450_thread_model.sql).
-- cron_heartbeat has no sequence: its primary key is `worker text`, not an
-- identity column.
revoke all on sequence "public"."task_notifications_id_seq" from "anon", "authenticated";
grant all on sequence "public"."task_notifications_id_seq" to "service_role";

  create policy "Cron heartbeat readable by any signed-in member"
  on "public"."cron_heartbeat"
  as permissive
  for select
  to authenticated
using (true);



