-- Official onboarding demo bundle containment.
-- This migration is intentionally additive: existing tenant rows and delivery
-- history remain valid, while every new bundle resource is manifest-owned.

alter table public.task_notifications
    add column simulated boolean not null default false;
alter table public.message_notifications
    add column simulated boolean not null default false;
alter table public.share_access_log
    add column simulated boolean not null default false;

create table public.demo_runs (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    root_account_id bigint not null references public.accounts(id) on delete cascade,
    status text not null default 'active',
    seed_version text not null default 'official-onboarding-v1',
    cleanup_started_at timestamptz,
    completed_at timestamptz,
    constraint demo_runs_status_check check (status in ('seeding', 'active', 'clearing', 'cleared', 'failed'))
);

create table public.demo_run_accounts (
    id bigint generated by default as identity primary key,
    run_id bigint not null references public.demo_runs(id) on delete cascade,
    account_id bigint not null references public.accounts(id) on delete cascade,
    context_key text not null,
    context_kind text not null,
    is_root boolean not null default false,
    created_at timestamptz not null default now(),
    constraint demo_run_accounts_kind_check check (context_kind in ('household', 'shadchanus')),
    constraint demo_run_accounts_root_check check ((is_root and context_key = 'primary-household') or not is_root),
    constraint demo_run_accounts_run_account_key unique (run_id, account_id),
    constraint demo_run_accounts_run_context_key unique (run_id, context_key)
);

create table public.demo_run_users (
    id bigint generated by default as identity primary key,
    run_id bigint not null references public.demo_runs(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    actor_key text not null,
    email_domain text not null default 'invalid',
    created_at timestamptz not null default now(),
    constraint demo_run_users_actor_key unique (run_id, actor_key),
    constraint demo_run_users_user_key unique (run_id, user_id),
    constraint demo_run_users_invalid_domain check (email_domain = 'invalid')
);

create table public.demo_run_storage (
    id bigint generated by default as identity primary key,
    run_id bigint not null references public.demo_runs(id) on delete cascade,
    bucket text not null,
    storage_path text not null,
    resource_key text not null,
    created_at timestamptz not null default now(),
    constraint demo_run_storage_path_key unique (bucket, storage_path)
);

create table public.demo_share_snapshots (
    id bigint generated by default as identity primary key,
    run_id bigint not null references public.demo_runs(id) on delete cascade,
    share_link_id bigint not null references public.share_links(id) on delete cascade,
    token_hash text not null,
    snapshot jsonb not null,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null,
    revoked_at timestamptz,
    constraint demo_share_snapshots_link_key unique (share_link_id),
    constraint demo_share_snapshots_token_key unique (token_hash),
    constraint demo_share_snapshots_immutable_check check (jsonb_typeof(snapshot) = 'object')
);

create index demo_runs_root_account_idx on public.demo_runs (root_account_id);
create unique index demo_runs_active_root_idx on public.demo_runs (root_account_id)
    where status in ('seeding', 'active', 'clearing', 'failed');
create index demo_run_accounts_account_idx on public.demo_run_accounts (account_id);
create index demo_run_users_user_idx on public.demo_run_users (user_id);
create index demo_run_storage_run_idx on public.demo_run_storage (run_id);
create index demo_share_snapshots_run_idx on public.demo_share_snapshots (run_id);

-- These return shapes are consumed by Workers; dropping is required because
-- PostgreSQL cannot replace a function while changing OUT parameters.
drop function if exists public.claim_due_task_notifications(integer);
create function public.claim_due_task_notifications(p_limit integer)
returns table(id bigint, task_id bigint, account_id bigint, recipient_email text,
  task_text text, due_date timestamptz, target_type text, target_id bigint,
  attempts integer, claimed_at timestamptz, simulated boolean)
language plpgsql security definer set search_path = '' as $$
begin
  perform public.enqueue_due_task_notifications();
  return query
  with claimed as (
    update public.task_notifications tn
    set status = 'sending', attempts = tn.attempts + 1, claimed_at = now()
    where tn.id in (
      select tn2.id from public.task_notifications tn2
      where (
        (tn2.status = 'pending' and (tn2.next_attempt_at is null or tn2.next_attempt_at <= now()))
        or (tn2.status = 'sending' and tn2.claimed_at < now() - interval '10 minutes')
      )
        and tn2.simulated is not true
      order by tn2.created_at limit p_limit for update skip locked
    )
    returning tn.*
  )
  select claimed.id, claimed.task_id, claimed.account_id, claimed.recipient_email,
    t.text, claimed.due_date, t.target_type, t.target_id, claimed.attempts,
    claimed.claimed_at, claimed.simulated
  from claimed join public.tasks t on t.id = claimed.task_id;
end;
$$;

drop function if exists public.claim_message_notifications(integer);
create function public.claim_message_notifications(p_limit integer)
returns table(id bigint, channel text, recipient_member_id bigint, recipient_email text,
  thread_id bigint, message_body text, subject_type text, subject_id bigint,
  push_subscriptions jsonb, simulated boolean)
language plpgsql security definer set search_path = '' as $$
begin
  return query
  with claimed as (
    update public.message_notifications mn
    set status = 'sending', attempts = attempts + 1
    where mn.id in (
      select mn2.id from public.message_notifications mn2
      where mn2.status = 'pending'
        and mn2.simulated is not true
      order by mn2.created_at limit p_limit for update skip locked
    )
    returning mn.*
  )
  select claimed.id, claimed.channel, claimed.recipient_member_id,
    claimed.recipient_email, m.thread_id, m.body, t.subject_type, t.subject_id,
    case when claimed.channel = 'push' then (
      select jsonb_agg(jsonb_build_object('endpoint', ps.endpoint, 'p256dh', ps.p256dh, 'auth', ps.auth))
      from public.push_subscriptions ps where ps.member_id = claimed.recipient_member_id
    ) else null end,
    claimed.simulated
  from claimed
  join public.messages m on m.id = claimed.message_id
  join public.threads t on t.id = m.thread_id;
end;
$$;

-- Keep the declarative trigger/function source and the deploy artifact in lockstep:
-- demo-scoped notifications must be marked at enqueue time, not inferred by a
-- worker after a real delivery has already been attempted.
create or replace function public.enqueue_due_task_notifications(p_now timestamptz default now())
returns integer
language plpgsql security definer set search_path = '' as $$
declare
  v_count integer;
begin
  with candidates as (
    select
      t.id as task_id,
      t.account_id,
      t.due_date,
      m.email::text as recipient_email,
      public.demo_scope_is_simulated(t.account_id, null) as simulated,
      case
        when t.member_id is null then 'skipped'
        when m.email is null then 'failed'
        else 'pending'
      end as status,
      case
        when t.member_id is null then 'unassigned — no member_id set (deliberate, not a delivery failure)'
        when m.email is null then 'member_id names no live or no enabled member of this task''s own account'
        else null
      end as error
    from public.tasks t
    left join public.members m
      on m.id = t.member_id and public.is_deliverable_member(m.id, t.account_id)
    where t.done_date is null
      and t.due_date is not null
      and t.due_date <= p_now
      and 'email' = any (t.delivery_channels)
  ),
  inserted as (
    insert into public.task_notifications (
      account_id, task_id, channel, due_date, status, recipient_email, error, simulated, sent_at
    )
    select
      candidates.account_id, candidates.task_id, 'email', candidates.due_date,
      case when candidates.simulated then 'sent' else candidates.status end,
      candidates.recipient_email,
      case when candidates.simulated then 'simulated demo delivery' else candidates.error end,
      candidates.simulated,
      case when candidates.simulated then now() else null end
    from candidates
    on conflict (task_id, channel, due_date) do nothing
    returning 1
  )
  select count(*) into v_count from inserted;

  return v_count;
end;
$$;

create or replace function public.fan_out_message_notifications()
returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  v_participant record;
  v_user_id uuid;
  v_email text;
  v_disabled boolean;
  v_simulated boolean;
begin
  v_simulated := public.demo_scope_is_simulated(new.account_id, new.connection_id);
  for v_participant in
    select tp.member_id
    from public.thread_participants tp
    where tp.thread_id = new.thread_id
      and tp.member_id is distinct from new.sender_member_id
  loop
    select am.user_id into v_user_id
    from public.account_members am
    where am.id = v_participant.member_id;

    if v_user_id is null then
      insert into public.message_notifications (
        account_id, connection_id, message_id, recipient_member_id, channel, status, error, simulated, sent_at
      )
      values (
        new.account_id, new.connection_id, new.id, v_participant.member_id, 'email',
        case when v_simulated then 'sent' else 'skipped' end,
        case when v_simulated then 'simulated demo delivery'
          else 'recipient membership has no accepted login (account_members.user_id is null)' end,
        v_simulated,
        case when v_simulated then now() else null end
      )
      on conflict (message_id, recipient_member_id, channel) do nothing;
    else
      select m.email::text, m.disabled into v_email, v_disabled
      from public.members m
      where m.user_id = v_user_id;

      if v_email is null or v_disabled then
        insert into public.message_notifications (
          account_id, connection_id, message_id, recipient_member_id, channel, status, error, simulated, sent_at
        )
        values (
          new.account_id, new.connection_id, new.id, v_participant.member_id, 'email',
          case when v_simulated then 'sent' else 'failed' end,
          case when v_simulated then 'simulated demo delivery'
            else case
              when v_email is null then 'no public.members row for this login'
              else 'recipient member is disabled'
            end
          end,
          v_simulated,
          case when v_simulated then now() else null end
        )
        on conflict (message_id, recipient_member_id, channel) do nothing;
      else
        insert into public.message_notifications (
          account_id, connection_id, message_id, recipient_member_id, channel, status, recipient_email, simulated, sent_at
        )
        values (
          new.account_id, new.connection_id, new.id, v_participant.member_id, 'email',
          case when v_simulated then 'sent' else 'pending' end,
          v_email,
          v_simulated,
          case when v_simulated then now() else null end
        )
        on conflict (message_id, recipient_member_id, channel) do nothing;
      end if;
    end if;

    if exists (
      select 1 from public.push_subscriptions ps
      where ps.member_id = v_participant.member_id
    ) then
      insert into public.message_notifications (
        account_id, connection_id, message_id, recipient_member_id, channel, status, simulated, sent_at
      )
      values (
        new.account_id, new.connection_id, new.id, v_participant.member_id, 'push',
        case when v_simulated then 'sent' else 'pending' end,
        v_simulated,
        case when v_simulated then now() else null end
      )
      on conflict (message_id, recipient_member_id, channel) do nothing;
    end if;
  end loop;

  return new;
end;
$$;

create or replace function public.demo_run_for_account(p_account_id bigint default null)
returns bigint language sql stable security definer set search_path = '' as $$
  select dra.run_id
  from public.demo_run_accounts dra join public.demo_runs dr on dr.id = dra.run_id
  where dra.account_id = coalesce(p_account_id, public.current_context_id())
    and dr.status in ('seeding', 'active', 'clearing', 'failed')
  order by dr.id desc limit 1;
$$;

create or replace function public.demo_root_account_for(p_account_id bigint)
returns bigint language sql stable security definer set search_path = '' as $$
  select dr.root_account_id
  from public.demo_run_accounts dra join public.demo_runs dr on dr.id = dra.run_id
  where dra.account_id = p_account_id
    and dr.status in ('seeding', 'active', 'clearing', 'failed')
  order by dr.id desc limit 1;
$$;

create or replace function public.demo_bundle_contains_account(p_run_id bigint, p_account_id bigint)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.demo_run_accounts dra join public.demo_runs dr on dr.id = dra.run_id
    where dra.run_id = p_run_id and dra.account_id = p_account_id
      and dr.status in ('seeding', 'active', 'clearing', 'failed')
  );
$$;

create or replace function public.demo_account_is_previewable(p_account_id bigint)
returns boolean language sql stable security definer set search_path = '' as $$
  select public.demo_bundle_contains_account(public.demo_run_for_account(), p_account_id);
$$;

create or replace function public.demo_account_in_active_run(p_account_id bigint)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1
    from public.demo_run_accounts dra
    join public.demo_runs dr on dr.id = dra.run_id
    where dra.account_id = p_account_id
      and dr.status in ('seeding', 'active', 'clearing', 'failed')
  );
$$;

create or replace function public.demo_scope_is_simulated(p_account_id bigint default null, p_connection_id bigint default null)
returns boolean language sql stable security definer set search_path = '' as $$
  select case
    when p_account_id is null and p_connection_id is null then false
    else exists (
      select 1
      from public.demo_runs dr
      where dr.status in ('seeding', 'active', 'clearing', 'failed')
        and (
          p_account_id is null
          or exists (
            select 1 from public.demo_run_accounts dra
            where dra.run_id = dr.id and dra.account_id = p_account_id
          )
        )
        and (
          p_connection_id is null
          or exists (
            select 1
            from public.connections c
            join public.demo_run_accounts dra
              on dra.run_id = dr.id
             and dra.account_id in (c.household_account_id, c.shadchanus_account_id)
            where c.id = p_connection_id
          )
        )
    )
  end;
$$;

create or replace function public.demo_delivery_history()
returns table(event_type text, status text, simulated boolean, occurred_at timestamptz, resource text)
language sql stable security definer set search_path = '' as $$
  with current_run as (select public.demo_run_for_account() as run_id)
  select 'message'::text, mn.status, mn.simulated,
    coalesce(mn.sent_at, mn.created_at) as occurred_at, 'message'::text
  from public.message_notifications mn
  cross join current_run cr
  left join public.connections c on c.id = mn.connection_id
  where cr.run_id is not null
    and exists (
      select 1 from public.demo_run_accounts dra
      where dra.run_id = cr.run_id
        and dra.account_id in (mn.account_id, c.household_account_id, c.shadchanus_account_id)
    )
  union all
  select 'reminder'::text, tn.status, tn.simulated, coalesce(tn.sent_at, tn.created_at), 'task'::text
  from public.task_notifications tn cross join current_run cr
  where cr.run_id is not null
    and exists (
      select 1 from public.demo_run_accounts dra
      where dra.run_id = cr.run_id and dra.account_id = tn.account_id
    )
  union all
  select 'share'::text, 'accessed'::text, sal.simulated, sal.accessed_at, sal.resource
  from public.share_access_log sal join public.share_links sl on sl.id = sal.share_link_id
  cross join current_run cr
  where cr.run_id is not null
    and exists (
      select 1 from public.demo_run_accounts dra
      where dra.run_id = cr.run_id and dra.account_id = sl.account_id
    )
  order by occurred_at desc;
$$;

drop function if exists public.my_contexts();
create function public.my_contexts()
returns table(account_id bigint, kind text, name text, role text, is_active boolean, is_demo boolean)
language sql stable set search_path = '' as $$
  select
    am.account_id,
    a.kind,
    a.name,
    am.role,
    coalesce(am.account_id = public.current_context_id(), false) as is_active,
    public.demo_account_is_previewable(am.account_id) as is_demo
  from public.account_members am
  join public.accounts a on a.id = am.account_id
  where am.user_id = auth.uid() and am.status = 'active';
$$;

-- The root is the only account carrying accounts.demo=true. The active
-- companion contexts must still show the simulation banner, so the UI's
-- existing current_account_demo() contract follows the manifest resolver.
create or replace function public.current_account_demo()
returns boolean
language sql stable security definer set search_path = '' as $$
  select coalesce(
    (select a.demo from public.accounts a where a.id = public.current_context_id()),
    false
  ) or public.demo_account_is_previewable(public.current_context_id());
$$;

-- Preserve real public marketplace behavior while hiding bundle listings from
-- ordinary anonymous search. Authenticated bundle members get preview access.
drop policy if exists "Listings readable by anon" on public.listings;
create policy "Listings readable by anon" on public.listings
  for select to anon using (not public.demo_account_in_active_run(account_id));
drop policy if exists "Demo listings readable in bundle preview" on public.listings;
create policy "Demo listings readable in bundle preview" on public.listings
  for select to authenticated using (public.demo_account_is_previewable(account_id));

alter table public.demo_runs enable row level security;
alter table public.demo_runs force row level security;
alter table public.demo_run_accounts enable row level security;
alter table public.demo_run_accounts force row level security;
alter table public.demo_run_users enable row level security;
alter table public.demo_run_users force row level security;
alter table public.demo_run_storage enable row level security;
alter table public.demo_run_storage force row level security;
alter table public.demo_share_snapshots enable row level security;
alter table public.demo_share_snapshots force row level security;

revoke all on table public.demo_runs, public.demo_run_accounts, public.demo_run_users,
  public.demo_run_storage, public.demo_share_snapshots from anon, authenticated;
grant all on table public.demo_runs, public.demo_run_accounts, public.demo_run_users,
  public.demo_run_storage, public.demo_share_snapshots to service_role;
grant all on sequence public.demo_runs_id_seq, public.demo_run_accounts_id_seq,
  public.demo_run_users_id_seq, public.demo_run_storage_id_seq,
  public.demo_share_snapshots_id_seq to service_role;

revoke all on function public.demo_run_for_account(bigint), public.demo_root_account_for(bigint),
  public.demo_bundle_contains_account(bigint, bigint), public.demo_account_is_previewable(bigint),
  public.demo_scope_is_simulated(bigint, bigint), public.demo_delivery_history() from public, anon, authenticated;
revoke all on function public.demo_account_in_active_run(bigint) from public;
grant execute on function public.demo_account_in_active_run(bigint) to anon;
grant execute on function public.demo_run_for_account(bigint), public.demo_root_account_for(bigint),
  public.demo_bundle_contains_account(bigint, bigint) to service_role;
grant execute on function public.demo_account_is_previewable(bigint),
  public.demo_delivery_history() to authenticated, service_role;
grant execute on function public.demo_scope_is_simulated(bigint, bigint) to service_role;

revoke all on function public.claim_due_task_notifications(integer) from public, anon, authenticated;
grant execute on function public.claim_due_task_notifications(integer) to service_role;
revoke all on function public.claim_message_notifications(integer) from public, anon, authenticated;
grant execute on function public.claim_message_notifications(integer) to service_role;
revoke all on function public.enqueue_due_task_notifications(timestamptz) from public, anon, authenticated;
grant execute on function public.enqueue_due_task_notifications(timestamptz) to service_role;
grant execute on function public.fan_out_message_notifications() to service_role;
revoke all on function public.my_contexts() from public, anon;
grant execute on function public.my_contexts() to authenticated, service_role;
grant execute on function public.current_account_demo() to authenticated, service_role;
