--
-- MyShadchan — redt history: a shidduch can be redt (proposed) multiple times,
-- by the same shadchan or different ones, on different dates. Stored + visible;
-- shidduchim.redt_date always reflects the LAST redt.
--
-- Follow-up to 20260722120000_shidduchim_pipeline.sql (both hand-authored; local
-- apply was blocked on Docker). Mirrors the declarative additions in
-- supabase/schemas/{01_tables,02_functions,03_views,04_triggers,05_policies,06_grants}.sql.
--

-- ---------------------------------------------------------------------------
-- Table + FKs + indexes
-- ---------------------------------------------------------------------------
create table public.redts (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    created_at timestamp with time zone not null default now(),
    shidduchim_id bigint not null,
    shadchan_id bigint,
    redt_date date not null default current_date,
    note text
);

alter table public.redts
    add constraint redts_account_id_fkey foreign key (account_id) references public.accounts(id) on delete cascade;
alter table public.redts
    add constraint redts_shidduchim_id_fkey foreign key (shidduchim_id) references public.shidduchim(id) on delete cascade;
alter table public.redts
    add constraint redts_shadchan_id_fkey foreign key (shadchan_id) references public.shadchanim(id) on delete set null;

create index redts_account_id_idx on public.redts using btree (account_id);
create index redts_shidduchim_id_idx on public.redts using btree (shidduchim_id);

-- ---------------------------------------------------------------------------
-- Functions
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."refresh_shidduch_redt_summary"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  v_shidduch_id bigint;
  v_last_shadchan bigint;
  v_last_date date;
  v_first_shadchan bigint;
  v_first_date date;
begin
  v_shidduch_id := coalesce(new.shidduchim_id, old.shidduchim_id);

  select r.shadchan_id, r.redt_date into v_last_shadchan, v_last_date
  from public.redts r
  where r.shidduchim_id = v_shidduch_id
  order by r.redt_date desc, r.id desc
  limit 1;

  if not found then
    -- No redts remain (e.g. the last one was deleted); leave the summary as-is.
    return null;
  end if;

  select r.shadchan_id, r.redt_date into v_first_shadchan, v_first_date
  from public.redts r
  where r.shidduchim_id = v_shidduch_id
  order by r.redt_date asc, r.id asc
  limit 1;

  update public.shidduchim s
  set redt_date = v_last_date,
      shadchan_id = v_last_shadchan,
      first_suggested_by = v_first_shadchan,
      first_suggested_at = v_first_date
  where s.id = v_shidduch_id;

  return null;
end;
$$;

CREATE OR REPLACE FUNCTION "public"."add_redt"(
    "p_shidduchim_id" bigint,
    "p_shadchan_id" bigint DEFAULT NULL,
    "p_redt_date" date DEFAULT NULL,
    "p_note" text DEFAULT NULL
) RETURNS SETOF public.shidduchim
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  v_account_id bigint;
begin
  v_account_id := public.current_account_id();

  if not exists (
    select 1 from public.shidduchim s
    where s.id = p_shidduchim_id and s.account_id = v_account_id
  ) then
    raise exception 'shidduch % not found in current account', p_shidduchim_id;
  end if;

  if p_shadchan_id is not null and not exists (
    select 1 from public.shadchanim s
    where s.id = p_shadchan_id and s.account_id = v_account_id
  ) then
    raise exception 'shadchan % not found in current account', p_shadchan_id;
  end if;

  insert into public.redts (account_id, shidduchim_id, shadchan_id, redt_date, note)
  values (v_account_id, p_shidduchim_id, p_shadchan_id, coalesce(p_redt_date, current_date), p_note);

  return query select * from public.shidduchim where id = p_shidduchim_id;
end;
$$;

-- create_shidduch now records the first redt event and returns the refreshed row.
CREATE OR REPLACE FUNCTION "public"."create_shidduch"(
    "p_child_id" bigint,
    "p_shadchan_id" bigint DEFAULT NULL,
    "p_name_en" text DEFAULT NULL,
    "p_name_he" text DEFAULT NULL,
    "p_parents_en" text DEFAULT NULL,
    "p_parents_he" text DEFAULT NULL,
    "p_seminary_en" text DEFAULT NULL,
    "p_seminary_he" text DEFAULT NULL,
    "p_shul_en" text DEFAULT NULL,
    "p_shul_he" text DEFAULT NULL,
    "p_location_en" text DEFAULT NULL,
    "p_location_he" text DEFAULT NULL,
    "p_age" integer DEFAULT NULL,
    "p_height" text DEFAULT NULL,
    "p_origin" text DEFAULT 'manual',
    "p_initial_state" public.pipeline_state DEFAULT 'new',
    "p_visibility" text DEFAULT 'shared',
    "p_redt_date" date DEFAULT NULL
) RETURNS SETOF public.shidduchim
    LANGUAGE "plpgsql"
    SET "search_path" TO ''
    AS $$
declare
  v_account_id bigint;
  v_owner_member_id bigint;
  v_id bigint;
  v_redt_date date;
begin
  v_account_id := public.current_account_id();
  if v_account_id is null then
    raise exception 'no account context for create_shidduch (no account exists)';
  end if;

  if p_initial_state not in ('new', 'look_into', 'not_sure', 'for_sure_not') then
    raise exception 'invalid initial pipeline_state: % (decision states are reachable only from look_into)', p_initial_state
      using errcode = 'check_violation';
  end if;

  if not exists (
    select 1 from public.children c
    where c.id = p_child_id and c.account_id = v_account_id
  ) then
    raise exception 'child % not found in current account', p_child_id;
  end if;

  if p_shadchan_id is not null and not exists (
    select 1 from public.shadchanim s
    where s.id = p_shadchan_id and s.account_id = v_account_id
  ) then
    raise exception 'shadchan % not found in current account', p_shadchan_id;
  end if;

  select am.id into v_owner_member_id
  from public.account_members am
  where am.user_id = auth.uid() and am.account_id = v_account_id
  order by am.id
  limit 1;

  v_redt_date := coalesce(p_redt_date, current_date);

  insert into public.shidduchim (
    account_id, child_id, shadchan_id,
    name_en, name_he,
    parents_en, parents_he, seminary_en, seminary_he,
    shul_en, shul_he, location_en, location_he,
    age, height,
    pipeline_state, first_suggested_by, first_suggested_at, redt_date,
    origin, owner_member_id, visibility
  ) values (
    v_account_id, p_child_id, p_shadchan_id,
    p_name_en, p_name_he,
    p_parents_en, p_parents_he, p_seminary_en, p_seminary_he,
    p_shul_en, p_shul_he, p_location_en, p_location_he,
    p_age, p_height,
    p_initial_state, p_shadchan_id, v_redt_date, v_redt_date,
    p_origin, v_owner_member_id, p_visibility
  )
  returning id into v_id;

  insert into public.redts (account_id, shidduchim_id, shadchan_id, redt_date)
  values (v_account_id, v_id, p_shadchan_id, v_redt_date);

  return query select * from public.shidduchim where id = v_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- View: add nb_redts (redt count) to the board read path
-- ---------------------------------------------------------------------------
create or replace view public.shidduchim_summary with (security_invoker = on) as
select
    s.id,
    s.account_id,
    s.created_at,
    s.child_id,
    s.shadchan_id,
    s.name_en,
    s.name_he,
    s.parents_en,
    s.parents_he,
    s.seminary_en,
    s.seminary_he,
    s.shul_en,
    s.shul_he,
    s.location_en,
    s.location_he,
    s.age,
    s.height,
    s.pipeline_state,
    s.first_suggested_by,
    s.first_suggested_at,
    s.redt_date,
    s.close_reason,
    s.origin,
    s.owner_member_id,
    s.visibility,
    s.index,
    sh.name as shadchan_name,
    sh.name_he as shadchan_name_he,
    c.first_name_en as child_first_name_en,
    c.first_name_he as child_first_name_he,
    c.last_name_en as child_last_name_en,
    c.last_name_he as child_last_name_he,
    count(distinct rl.id) as nb_references,
    count(distinct r.id) as nb_redts
from public.shidduchim s
    left join public.shadchanim sh on sh.id = s.shadchan_id
    left join public.children c on c.id = s.child_id
    left join public.reference_links rl on rl.shidduchim_id = s.id
    left join public.redts r on r.shidduchim_id = s.id
group by s.id, sh.name, sh.name_he, c.first_name_en, c.first_name_he, c.last_name_en, c.last_name_he;

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------
create or replace trigger set_redts_account_id
    before insert on public.redts
    for each row execute function public.set_account_id_default();

create or replace trigger refresh_shidduch_redts
    after insert or update or delete on public.redts
    for each row execute function public.refresh_shidduch_redt_summary();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.redts enable row level security;

create policy "Redts scoped to account" on public.redts
    for all to authenticated
    using (account_id = public.current_account_id())
    with check (account_id = public.current_account_id());

-- ---------------------------------------------------------------------------
-- Grants (revoke anon)
-- ---------------------------------------------------------------------------
revoke all on table public.redts from anon;
grant all on table public.redts to authenticated;
grant all on table public.redts to service_role;

revoke all on sequence public.redts_id_seq from anon;
grant all on sequence public.redts_id_seq to authenticated;
grant all on sequence public.redts_id_seq to service_role;

revoke all on function public.refresh_shidduch_redt_summary() from public, anon;
grant execute on function public.refresh_shidduch_redt_summary() to authenticated;
grant execute on function public.refresh_shidduch_redt_summary() to service_role;

revoke all on function public.add_redt(bigint, bigint, date, text) from public, anon;
grant execute on function public.add_redt(bigint, bigint, date, text) to authenticated;
grant execute on function public.add_redt(bigint, bigint, date, text) to service_role;
