create table "public"."medical_notes" (
    "id" bigint generated by default as identity not null,
    "account_id" bigint not null,
    "shidduchim_id" bigint not null,
    "author_member_id" bigint,
    "body" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."medical_notes" enable row level security;

CREATE INDEX medical_notes_account_id_idx ON public.medical_notes USING btree (account_id);

CREATE UNIQUE INDEX medical_notes_pkey ON public.medical_notes USING btree (id);

alter table "public"."medical_notes" add constraint "medical_notes_pkey" PRIMARY KEY using index "medical_notes_pkey";

alter table "public"."medical_notes" add constraint "medical_notes_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE not valid;

alter table "public"."medical_notes" validate constraint "medical_notes_account_id_fkey";

alter table "public"."medical_notes" add constraint "medical_notes_author_member_id_fkey" FOREIGN KEY (author_member_id) REFERENCES public.account_members(id) ON DELETE SET NULL not valid;

alter table "public"."medical_notes" validate constraint "medical_notes_author_member_id_fkey";

alter table "public"."medical_notes" add constraint "medical_notes_shidduchim_id_fkey" FOREIGN KEY (account_id, shidduchim_id) REFERENCES public.shidduchim(account_id, id) ON DELETE CASCADE not valid;

alter table "public"."medical_notes" validate constraint "medical_notes_shidduchim_id_fkey";

-- MANUAL ADJUSTMENT: `db diff` drops this REVOKE (AGENTS.md) — starting from
-- "table does not exist", migra's diff never has to strip the privileges
-- `alter default privileges ... grant all on tables to authenticated`
-- (06_grants.sql) auto-grants the moment CREATE TABLE runs above, so without
-- this statement `authenticated` would keep TRIGGER/REFERENCES/TRUNCATE on
-- top of the four grants below, diverging from a from-schema-files build.
revoke all on table "public"."medical_notes" from "anon", "authenticated";

grant delete on table "public"."medical_notes" to "authenticated";

grant insert on table "public"."medical_notes" to "authenticated";

grant select on table "public"."medical_notes" to "authenticated";

grant update on table "public"."medical_notes" to "authenticated";

grant delete on table "public"."medical_notes" to "service_role";

grant insert on table "public"."medical_notes" to "service_role";

grant references on table "public"."medical_notes" to "service_role";

grant select on table "public"."medical_notes" to "service_role";

grant trigger on table "public"."medical_notes" to "service_role";

grant truncate on table "public"."medical_notes" to "service_role";

grant update on table "public"."medical_notes" to "service_role";


  create policy "Medical notes scoped to account, parent_admin/self_manager only"
  on "public"."medical_notes"
  as permissive
  for all
  to authenticated
using (((account_id = public.current_context_id()) AND (EXISTS ( SELECT 1
   FROM public.account_members am
  WHERE ((am.id = public.current_member_id()) AND (am.role = ANY (ARRAY['parent_admin'::text, 'self_manager'::text])))))))
with check (((account_id = public.current_context_id()) AND (EXISTS ( SELECT 1
   FROM public.account_members am
  WHERE ((am.id = public.current_member_id()) AND (am.role = ANY (ARRAY['parent_admin'::text, 'self_manager'::text])))))));


CREATE TRIGGER set_medical_notes_account_id BEFORE INSERT ON public.medical_notes FOR EACH ROW EXECUTE FUNCTION public.set_account_id_default();

CREATE TRIGGER validate_medical_notes_household_scope BEFORE INSERT OR UPDATE OF account_id ON public.medical_notes FOR EACH ROW EXECUTE FUNCTION public.enforce_household_scope();
