-- Official onboarding demo lifecycle review hardening.
-- Declarative source: supabase/schemas/01_tables.sql, 02_functions.sql,
-- 06_grants.sql. This migration intentionally preserves Auth actor identity
-- after deletion and keeps companion accounts until finalization.

alter table public.demo_run_users
  drop constraint if exists demo_run_users_user_id_fkey;
alter table public.demo_run_actor_intents
  drop constraint if exists demo_run_actor_intents_user_id_fkey;

alter table public.demo_run_resources
  drop constraint if exists demo_run_resources_type_check;
alter table public.demo_run_resources
  add constraint demo_run_resources_type_check check (
    resource_type in (
      'invite', 'connection_invite', 'child_grant', 'connection',
      'thread', 'message', 'listing', 'share_link', 'task',
      'share_access_log', 'inbox_item', 'analytics_event',
      'message_notification', 'task_notification', 'trusted_sender'
    )
  ) not valid;
alter table public.demo_run_resources
  validate constraint demo_run_resources_type_check;

create table public.demo_run_auth_cleanup (
  id bigint generated by default as identity primary key,
  run_id bigint not null,
  actor_key text not null,
  resolved_user_id uuid not null,
  expected_email extensions.citext not null,
  state text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint demo_run_auth_cleanup_state_check check (state in ('pending', 'deleting', 'deleted')),
  constraint demo_run_auth_cleanup_actor_key unique (run_id, actor_key),
  constraint demo_run_auth_cleanup_user_key unique (run_id, resolved_user_id),
  constraint demo_run_auth_cleanup_run_id_fkey foreign key (run_id)
    references public.demo_runs(id) on delete cascade
);
create index demo_run_auth_cleanup_run_idx on public.demo_run_auth_cleanup(run_id);

create table public.demo_onboarding_intents (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  account_id bigint,
  state text not null default 'pending',
  demo_run_id bigint,
  attempts integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint demo_onboarding_intents_state_check check (state in ('pending', 'failed', 'completed')),
  constraint demo_onboarding_intents_user_key unique (user_id),
  constraint demo_onboarding_intents_user_id_fkey foreign key (user_id)
    references auth.users(id) on delete cascade,
  constraint demo_onboarding_intents_account_id_fkey foreign key (account_id)
    references public.accounts(id) on delete cascade,
  constraint demo_onboarding_intents_run_id_fkey foreign key (demo_run_id)
    references public.demo_runs(id) on delete set null
);
create index demo_onboarding_intents_account_idx on public.demo_onboarding_intents(account_id);

alter table public.demo_run_auth_cleanup enable row level security;
alter table public.demo_run_auth_cleanup force row level security;
alter table public.demo_onboarding_intents enable row level security;
alter table public.demo_onboarding_intents force row level security;

revoke all on table public.demo_run_auth_cleanup from anon, authenticated;
revoke all on table public.demo_onboarding_intents from anon, authenticated;
grant all on table public.demo_run_auth_cleanup to service_role;
grant all on table public.demo_onboarding_intents to service_role;
grant all on sequence public.demo_run_auth_cleanup_id_seq to service_role;
grant all on sequence public.demo_onboarding_intents_id_seq to service_role;
alter table "public"."demo_run_actor_intents" add constraint "demo_run_actor_intents_user_id_identity_check" CHECK (((auth_user_id IS NULL) OR ((auth_user_id)::text <> '00000000-0000-0000-0000-000000000000'::text))) not valid;

alter table "public"."demo_run_actor_intents" validate constraint "demo_run_actor_intents_user_id_identity_check";

alter table "public"."demo_run_users" add constraint "demo_run_users_user_id_identity_check" CHECK ((user_id IS NOT NULL)) not valid;

alter table "public"."demo_run_users" validate constraint "demo_run_users_user_id_identity_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.cancel_demo_onboarding()
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
  delete from public.demo_onboarding_intents
  where user_id = auth.uid() and state in ('pending', 'failed');
$function$
;

CREATE OR REPLACE FUNCTION public.delete_demo_companion_contexts(p_run_id bigint, p_lease_token text, p_operation text DEFAULT 'seed'::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_run public.demo_runs;
begin
  select * into v_run from public.demo_runs where id = p_run_id for update;
  if not found or p_operation not in ('seed', 'clear')
     or v_run.lease_token is distinct from p_lease_token
     or v_run.operation is distinct from p_operation
     or v_run.status <> case when p_operation = 'seed' then 'seeding' else 'clearing' end
     or v_run.lease_expires_at is null or v_run.lease_expires_at <= now() then
    raise exception 'demo run % lease is stale or fenced', p_run_id
      using errcode = 'serialization_failure';
  end if;

  delete from public.account_members am
  where am.account_id in (
    select dra.account_id from public.demo_run_accounts dra
    where dra.run_id = p_run_id and not dra.is_root
  );
  delete from public.accounts a
  where a.id in (
    select dra.account_id from public.demo_run_accounts dra
    where dra.run_id = p_run_id and not dra.is_root
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.fail_demo_onboarding_seed(p_run_id bigint, p_lease_token text, p_error text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_root_account_id bigint;
begin
  select root_account_id into v_root_account_id
  from public.demo_runs
  where id = p_run_id;
  if not found or not public.demo_run_lease_is_current(p_run_id, p_lease_token, 'seed') then
    return;
  end if;
  update public.demo_onboarding_intents
  set state = 'failed', demo_run_id = p_run_id,
      last_error = left(coalesce(p_error, 'demo seed failed'), 500),
      updated_at = now()
  where account_id = v_root_account_id and state <> 'completed';
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_demo_onboarding_state()
 RETURNS TABLE(state text, account_id bigint, attempts integer)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select state, account_id, attempts
  from public.demo_onboarding_intents
  where user_id = auth.uid()
  limit 1;
$function$
;

CREATE OR REPLACE FUNCTION public.link_demo_onboarding_intent(p_user_id uuid, p_account_id bigint, p_allow_new_account boolean DEFAULT false)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_intent public.demo_onboarding_intents;
begin
  if p_user_id is distinct from auth.uid() then
    raise exception 'demo onboarding intent caller mismatch'
      using errcode = 'insufficient_privilege';
  end if;

  select * into v_intent
  from public.demo_onboarding_intents
  where user_id = p_user_id
  for update;
  if not found then
    return;
  end if;

  if v_intent.account_id is null then
    if not p_allow_new_account then
      raise exception 'demo onboarding intent must link only to a fresh household'
        using errcode = 'check_violation';
    end if;
    update public.demo_onboarding_intents
    set account_id = p_account_id, updated_at = now()
    where user_id = p_user_id;
  elsif v_intent.account_id <> p_account_id then
    raise exception 'demo onboarding intent account mismatch'
      using errcode = 'unique_violation';
  end if;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.mark_demo_auth_deleted(p_run_id bigint, p_lease_token text, p_actor_key text, p_resolved_user_id uuid, p_operation text DEFAULT 'clear'::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if not public.demo_run_lease_is_current(p_run_id, p_lease_token, p_operation) then
    raise exception 'demo run % lease is stale or fenced', p_run_id
      using errcode = 'serialization_failure';
  end if;
  update public.demo_run_auth_cleanup
  set state = 'deleted', deleted_at = coalesce(deleted_at, now()), updated_at = now()
  where run_id = p_run_id and actor_key = p_actor_key
    and resolved_user_id = p_resolved_user_id;
  if not found then
    raise exception 'demo auth cleanup tombstone % is not registered', p_actor_key
      using errcode = 'foreign_key_violation';
  end if;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.prepare_demo_onboarding()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_user_id uuid := auth.uid();
  v_intent public.demo_onboarding_intents;
begin
  if v_user_id is null then
    raise exception 'prepare_demo_onboarding requires an authenticated caller'
      using errcode = 'insufficient_privilege';
  end if;

  select * into v_intent
  from public.demo_onboarding_intents
  where user_id = v_user_id
  for update;
  if found then
    return jsonb_build_object(
      'state', v_intent.state,
      'account_id', v_intent.account_id,
      'attempts', v_intent.attempts
    );
  end if;

  -- A caller with any live context/persona is an established customer unless
  -- this exact durable intent already exists. Never manufacture a seed intent
  -- for an established account merely because its tables happen to be empty.
  if exists (
    select 1 from public.account_members
    where user_id = v_user_id and status = 'active'
  ) or exists (
    select 1
    from public.singles s
    join public.account_members am on am.id = s.member_id
    where am.user_id = v_user_id and am.status = 'active' and s.status = 'active'
  ) then
    raise exception 'demo onboarding is only available to a first-run login'
      using errcode = 'check_violation';
  end if;

  insert into public.demo_onboarding_intents (user_id, state, attempts)
  values (v_user_id, 'pending', 1)
  returning * into v_intent;

  return jsonb_build_object(
    'state', v_intent.state,
    'account_id', v_intent.account_id,
    'attempts', v_intent.attempts
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.register_demo_auth_cleanup(p_run_id bigint, p_lease_token text, p_actor_key text, p_resolved_user_id uuid, p_expected_email text, p_operation text DEFAULT 'clear'::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_run public.demo_runs;
  v_expected_email extensions.citext;
begin
  select * into v_run from public.demo_runs where id = p_run_id for update;
  if not found
     or p_operation not in ('seed', 'clear')
     or v_run.lease_token is distinct from p_lease_token
     or v_run.operation is distinct from p_operation
     or v_run.status <> case when p_operation = 'seed' then 'seeding' else 'clearing' end
     or v_run.lease_expires_at is null or v_run.lease_expires_at <= now() then
    raise exception 'demo run % lease is stale or fenced', p_run_id
      using errcode = 'serialization_failure';
  end if;

  select expected_email into v_expected_email
  from public.demo_run_actor_intents
  where run_id = p_run_id and actor_key = p_actor_key;
  if not found or lower(v_expected_email::text) <> lower(p_expected_email)
     or not exists (
       select 1 from public.demo_run_users
       where run_id = p_run_id and actor_key = p_actor_key
         and user_id = p_resolved_user_id
     ) and not exists (
       select 1 from public.demo_run_actor_intents
       where run_id = p_run_id and actor_key = p_actor_key
         and auth_user_id = p_resolved_user_id
     ) then
    raise exception 'demo auth cleanup identity is not exactly registered'
      using errcode = 'foreign_key_violation';
  end if;

  insert into public.demo_run_auth_cleanup (
    run_id, actor_key, resolved_user_id, expected_email, state
  ) values (
    p_run_id, p_actor_key, p_resolved_user_id, p_expected_email, 'deleting'
  )
  on conflict (run_id, actor_key) do update
    set resolved_user_id = excluded.resolved_user_id,
        expected_email = excluded.expected_email,
        state = case when public.demo_run_auth_cleanup.state = 'deleted'
          then 'deleted' else 'deleting' end,
        updated_at = now();
end;
$function$
;

CREATE OR REPLACE FUNCTION public.activate_demo_run(p_run_id bigint, p_lease_token text, p_active_root_name text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_run public.demo_runs;
begin
  select * into v_run from public.demo_runs where id = p_run_id for update;
  if not found or v_run.lease_token is distinct from p_lease_token
     or v_run.operation <> 'seed' or v_run.status <> 'seeding'
     or v_run.lease_expires_at <= now() then
    raise exception 'demo run % lease is stale or fenced', p_run_id
      using errcode = 'serialization_failure';
  end if;

  update public.accounts
  set name = p_active_root_name, demo = true
  where id = v_run.root_account_id;

  update public.demo_runs
  set status = 'active', operation = null, lease_token = null,
      lease_expires_at = null, updated_at = now()
  where id = p_run_id;

  update public.demo_onboarding_intents
  set state = 'completed', demo_run_id = p_run_id, last_error = null,
      updated_at = now()
  where account_id = v_run.root_account_id;

  return jsonb_build_object('run_id', p_run_id, 'status', 'active');
end;
$function$
;

CREATE OR REPLACE FUNCTION public.add_persona(p_persona text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_user_id uuid := auth.uid();
  v_first_name text;
  v_account_id bigint;
  v_membership_id bigint;
  v_created_household boolean := false;
begin
  -- Review finding #2: fail closed on an unauthenticated caller. Without
  -- this, service_role (which holds EXECUTE for legitimate server-side
  -- callers, e.g. a future edge function) calling add_persona() with no
  -- user JWT would silently insert an accounts/account_members row with
  -- user_id NULL — an orphan tenant nothing can ever reach, not a
  -- cross-tenant leak, but a violation of the fail-closed convention
  -- current_context_id()/set_active_context() already establish.
  if v_user_id is null then
    raise exception 'add_persona requires an authenticated caller'
      using errcode = 'insufficient_privilege';
  end if;

  if p_persona not in ('single', 'parent', 'shadchan') then
    raise exception 'unknown persona: %', p_persona
      using errcode = 'invalid_parameter_value';
  end if;

  select m.first_name into v_first_name
  from public.members m
  where m.user_id = v_user_id;

  if p_persona = 'parent' then
    -- No-op: an active parent_admin membership already exists.
    if exists (
      select 1 from public.account_members
      where user_id = v_user_id and status = 'active' and role = 'parent_admin'
    ) then
      select account_id into v_account_id
      from public.account_members
      where user_id = v_user_id and status = 'active' and role = 'parent_admin'
      order by id limit 1;
      perform public.link_demo_onboarding_intent(v_user_id, v_account_id, false);
      return;
    end if;

    -- Promote an existing self_manager membership in place (never rewrite
    -- account_id — that would trip enforce_household_scope() for no reason,
    -- the household is already valid).
    update public.account_members
      set role = 'parent_admin'
    where id = (
      select id from public.account_members
      where user_id = v_user_id and status = 'active' and role = 'self_manager'
      order by id
      limit 1
    );

    if found then
      select account_id into v_account_id
      from public.account_members
      where user_id = v_user_id and status = 'active' and role = 'parent_admin'
      order by id limit 1;
      perform public.link_demo_onboarding_intent(v_user_id, v_account_id, false);
      return;
    end if;

    -- Otherwise (no memberships at all, or only non-owning ones elsewhere —
    -- e.g. a helper in someone else's household): a fresh household. A
    -- non-owning membership is never promoted — that would hand the caller
    -- admin of a household that is not theirs.
    --
    -- Review finding #4: nullif(v_first_name, 'Pending') closes a dead
    -- fallback. public.members.first_name is NOT NULL DEFAULT 'Pending' and
    -- handle_new_user() always creates the row (01_tables.sql, 02_functions.sql),
    -- so plain `coalesce(v_first_name || '''s Family', 'My Account')` could
    -- never reach its own 'My Account' arm — a signup with no first/given
    -- name in their OAuth metadata got a household literally named
    -- "Pending's Family" instead of the intended placeholder.
    insert into public.accounts (name, kind)
    values (coalesce(nullif(v_first_name, 'Pending') || '''s Family', 'My Account'), 'household')
    returning id into v_account_id;
    v_created_household := true;

    insert into public.account_members (account_id, user_id, role, status)
    values (v_account_id, v_user_id, 'parent_admin', 'active');

    perform public.link_demo_onboarding_intent(v_user_id, v_account_id, v_created_household);

    return;
  end if;

  if p_persona = 'single' then
    -- No-op: a singles row already points at one of the caller's own active
    -- memberships (the invited single, or re-ticking a box already held).
    -- This predicate must match my_personas()'s single-detection exactly.
    -- Story 2.5: `s.status = 'active'` is load-bearing, not decorative —
    -- without it, re-ticking `single` after remove_persona() archived the
    -- caller's own singles row would silently no-op forever (the archived
    -- row still satisfies `s.member_id = am.id`), the exact "add a persona
    -- back" round trip the epic's own example requires.
    if exists (
      select 1
      from public.singles s
      join public.account_members am on am.id = s.member_id
      where am.user_id = v_user_id
        and am.status = 'active'
        and s.status = 'active'
        and (am.role = 'single' or public.is_owning_membership_role(am.role))
    ) then
      return;
    end if;

    -- Attach to an existing OWNING membership if the caller has one (never a
    -- helper's household — see the Dev Notes on why `single` never attaches
    -- to a helper's household).
    select am.id, am.account_id into v_membership_id, v_account_id
    from public.account_members am
    where am.user_id = v_user_id
      and am.status = 'active'
      and public.is_owning_membership_role(am.role)
    order by am.id
    limit 1;

    -- A 2-parent household can never also have a self-managed shidduch
    -- profile: `self_manager` exists specifically for a SINGLE-parent
    -- household where that one parent IS the shidduch candidate. Without
    -- this check, a parent_admin in an existing 2-parent household (reached
    -- via create_invite('parent_admin')/accept_invite() — a real path, not a
    -- hypothetical) could attach their own self-managed singles row here.
    -- Only checked when attaching to an EXISTING owning membership — the
    -- fresh-household branch below is guaranteed exactly one parent by
    -- construction and can never trip this.
    if v_membership_id is not null and (
      select count(*) from public.account_members am2
      where am2.account_id = v_account_id
        and am2.status = 'active'
        and public.is_owning_membership_role(am2.role)
    ) >= 2 then
      raise exception 'a 2-parent household cannot also have a self-managed shidduch profile'
        using errcode = 'check_violation';
    end if;

    if v_membership_id is null then
      insert into public.accounts (name, kind)
      values (coalesce(nullif(v_first_name, 'Pending') || '''s Family', 'My Account'), 'household')
      returning id into v_account_id;

      insert into public.account_members (account_id, user_id, role, status)
      values (v_account_id, v_user_id, 'self_manager', 'active')
      returning id into v_membership_id;
    end if;

    insert into public.singles (account_id, member_id)
    values (v_account_id, v_membership_id);

    return;
  end if;

  if p_persona = 'shadchan' then
    -- No-op: an active shadchan-role membership already exists.
    if exists (
      select 1 from public.account_members
      where user_id = v_user_id and status = 'active' and role = 'shadchan'
    ) then
      return;
    end if;

    insert into public.accounts (kind)
    values ('shadchanus')
    returning id into v_account_id;

    insert into public.account_members (account_id, user_id, role, status)
    values (v_account_id, v_user_id, 'shadchan', 'active');

    return;
  end if;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.demo_assert_empty_account(p_account_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if not exists (
    select 1 from public.accounts
    where id = p_account_id and kind = 'household'
  ) then
    raise exception 'demo root account % must be a household context', p_account_id
      using errcode = 'check_violation';
  end if;

  if exists (select 1 from public.singles where account_id = p_account_id)
     or exists (select 1 from public.shadchanim where account_id = p_account_id)
     or exists (select 1 from public.references where account_id = p_account_id)
     or exists (select 1 from public.shidduchim where account_id = p_account_id)
     or exists (select 1 from public.inbox_items where account_id = p_account_id)
     or exists (select 1 from public.message_notifications where account_id = p_account_id)
     or exists (select 1 from public.task_notifications where account_id = p_account_id)
     or exists (select 1 from public.messages where account_id = p_account_id)
     or exists (select 1 from public.threads where account_id = p_account_id)
     or exists (select 1 from public.thread_participants where account_id = p_account_id)
     or exists (select 1 from public.tasks where account_id = p_account_id)
     or exists (select 1 from public.reference_links where account_id = p_account_id)
     or exists (select 1 from public.redts where account_id = p_account_id)
     or exists (select 1 from public.shidduch_education where account_id = p_account_id)
     or exists (select 1 from public.resume_photos where account_id = p_account_id)
     or exists (select 1 from public.resumes where account_id = p_account_id)
     or exists (select 1 from public.entity_files where account_id = p_account_id)
     or exists (select 1 from public.medical_notes where account_id = p_account_id)
     or exists (select 1 from public.shidduchim_external_links where account_id = p_account_id)
     or exists (select 1 from public.date_records where account_id = p_account_id)
     or exists (select 1 from public.listing_withdrawal_locks where account_id = p_account_id)
     or exists (select 1 from public.listings where account_id = p_account_id)
     or exists (select 1 from public.invites where account_id = p_account_id)
     or exists (select 1 from public.analytics_events where account_id = p_account_id)
     or exists (select 1 from public.trusted_senders where account_id = p_account_id)
     or exists (select 1 from public.share_links where account_id = p_account_id)
     or exists (
       select 1 from public.connections
       where household_account_id = p_account_id
          or shadchanus_account_id = p_account_id
     )
     or exists (
       select 1 from public.connection_invites
       where inviter_account_id = p_account_id
          or accepted_by_account_id = p_account_id
     )
     or exists (
       select 1 from public.child_grants
       where proposer_account_id = p_account_id
          or grantee_account_id = p_account_id
     )
     or exists (
       select 1
       from public.messages m
       join public.connections c on c.id = m.connection_id
       where c.household_account_id = p_account_id
          or c.shadchanus_account_id = p_account_id
     )
     or exists (
       select 1
       from public.threads t
       join public.connections c on c.id = t.connection_id
       where c.household_account_id = p_account_id
          or c.shadchanus_account_id = p_account_id
     )
     or exists (
       select 1
       from public.thread_participants tp
       join public.connections c on c.id = tp.connection_id
       where c.household_account_id = p_account_id
          or c.shadchanus_account_id = p_account_id
     )
     or exists (
       select 1
       from public.message_notifications mn
       join public.connections c on c.id = mn.connection_id
       where c.household_account_id = p_account_id
          or c.shadchanus_account_id = p_account_id
     )
     or exists (
       select 1
       from storage.objects
       where bucket_id in ('documents', 'entity-files', 'attachments')
         and (name = p_account_id::text or name like p_account_id::text || '/%')
     ) then
    raise exception 'demo root account % is not empty', p_account_id
      using errcode = 'check_violation';
  end if;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.finalize_demo_clear(p_run_id bigint, p_lease_token text, p_release_demo boolean DEFAULT false, p_release_persona boolean DEFAULT false, p_actor_user_id uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_run public.demo_runs;
  v_active_members integer;
  v_completed_at timestamp with time zone := now();
begin
  select * into v_run from public.demo_runs where id = p_run_id for update;
  if not found or v_run.status <> 'clearing'
     or v_run.operation <> 'clear'
     or v_run.lease_token is distinct from p_lease_token
     or v_run.lease_expires_at is null
     or v_run.lease_expires_at <= now() then
    raise exception 'demo run % clear lease is stale or fenced', p_run_id
      using errcode = 'serialization_failure';
  end if;

  if p_release_persona and p_actor_user_id is not null then
    select count(*) into v_active_members
    from public.account_members
    where account_id = v_run.root_account_id and status = 'active';
    if v_active_members = 1 then
      update public.account_members
      set status = 'archived'
      where account_id = v_run.root_account_id
        and user_id = p_actor_user_id
        and role = 'parent_admin'
        and status = 'active';
    end if;
  end if;

  if exists (
    select 1
    from public.demo_run_users dru
    where dru.run_id = p_run_id
      and not exists (
        select 1 from public.demo_run_auth_cleanup dac
        where dac.run_id = dru.run_id
          and dac.actor_key = dru.actor_key
          and dac.resolved_user_id = dru.user_id
          and dac.state = 'deleted'
      )
  ) then
    raise exception 'demo clear cannot finalize before every exact Auth actor is deleted'
      using errcode = 'check_violation';
  end if;

  -- Companion accounts stay present until this transaction. That keeps a
  -- failed clear's manifest strictly valid after every external/Auth step and
  -- makes account removal atomic with finalization.
  delete from public.account_members am
  where am.account_id in (
    select dra.account_id
    from public.demo_run_accounts dra
    where dra.run_id = p_run_id and not dra.is_root
  );
  delete from public.accounts a
  where a.id in (
    select dra.account_id
    from public.demo_run_accounts dra
    where dra.run_id = p_run_id and not dra.is_root
  );

  -- Restore only a live membership. In particular, when release_persona
  -- archived the sole bootstrap membership above, active_account_id becomes
  -- NULL rather than pointing at that archived row.
  insert into public.member_state (user_id, active_account_id, updated_at)
  select s.user_id,
         case
           when s.original_active_account_id is null then null
           when exists (
             select 1 from public.account_members am
             where am.user_id = s.user_id
               and am.account_id = s.original_active_account_id
               and am.status = 'active'
           ) then s.original_active_account_id
           else null
         end,
         coalesce(s.original_updated_at, now())
  from public.demo_run_member_state s
  where s.run_id = p_run_id
  on conflict (user_id) do update
    set active_account_id = excluded.active_account_id,
        updated_at = excluded.updated_at;

  update public.accounts
  set name = coalesce(v_run.original_root_name, name),
      demo = case when p_release_demo then false else demo end
  where id = v_run.root_account_id;

  if (p_release_persona or p_release_demo) and p_actor_user_id is not null then
    delete from public.demo_onboarding_intents
    where user_id = p_actor_user_id
      and account_id = v_run.root_account_id;
  end if;

  delete from public.demo_runs where id = p_run_id;
  return jsonb_build_object(
    'outcome', 'finalized',
    'run_id', p_run_id,
    'completed_at', v_completed_at
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.register_demo_resource(p_run_id bigint, p_lease_token text, p_resource_type text, p_resource_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if not public.demo_run_lease_is_current(p_run_id, p_lease_token, 'seed') then
    raise exception 'demo run % lease is stale or fenced', p_run_id
      using errcode = 'serialization_failure';
  end if;

  if p_resource_type not in (
    'invite', 'connection_invite', 'child_grant', 'connection',
    'thread', 'message', 'listing', 'share_link', 'task',
    'share_access_log', 'inbox_item', 'analytics_event',
    'message_notification', 'task_notification', 'trusted_sender'
  ) then
    raise exception 'invalid demo resource type %', p_resource_type
      using errcode = 'check_violation';
  end if;

  insert into public.demo_run_resources (run_id, resource_type, resource_id)
  values (p_run_id, p_resource_type, p_resource_id)
  on conflict (run_id, resource_type, resource_id) do nothing;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.restore_demo_member_state(p_run_id bigint, p_lease_token text, p_operation text DEFAULT 'clear'::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_run public.demo_runs;
begin
  select * into v_run
  from public.demo_runs
  where id = p_run_id
  for update;

  if not found
     or p_operation not in ('seed', 'clear')
     or v_run.lease_token is distinct from p_lease_token
     or v_run.operation is distinct from p_operation
     or v_run.status <> case when p_operation = 'seed' then 'seeding' else 'clearing' end
     or v_run.lease_expires_at is null
     or v_run.lease_expires_at <= now() then
    raise exception 'demo run % lease is stale or fenced', p_run_id
      using errcode = 'serialization_failure';
  end if;

  insert into public.member_state (user_id, active_account_id, updated_at)
  select s.user_id,
         case
           when s.original_active_account_id is null then null
           when exists (
             select 1 from public.account_members am
             where am.user_id = s.user_id
               and am.account_id = s.original_active_account_id
               and am.status = 'active'
           ) then s.original_active_account_id
           else null
         end,
         coalesce(original_updated_at, now())
  from public.demo_run_member_state s
  where s.run_id = p_run_id
  on conflict (user_id) do update
    set active_account_id = excluded.active_account_id,
        updated_at = excluded.updated_at;
end;
$function$
;

revoke all on function public.prepare_demo_onboarding() from public, anon;
grant execute on function public.prepare_demo_onboarding() to authenticated, service_role;
revoke all on function public.link_demo_onboarding_intent(uuid, bigint, boolean) from public, anon, authenticated;
grant execute on function public.link_demo_onboarding_intent(uuid, bigint, boolean) to service_role;
revoke all on function public.cancel_demo_onboarding() from public, anon;
grant execute on function public.cancel_demo_onboarding() to authenticated, service_role;
revoke all on function public.get_demo_onboarding_state() from public, anon;
grant execute on function public.get_demo_onboarding_state() to authenticated, service_role;
revoke all on function public.register_demo_auth_cleanup(bigint, text, text, uuid, text, text) from public, anon, authenticated;
grant execute on function public.register_demo_auth_cleanup(bigint, text, text, uuid, text, text) to service_role;
revoke all on function public.mark_demo_auth_deleted(bigint, text, text, uuid, text) from public, anon, authenticated;
grant execute on function public.mark_demo_auth_deleted(bigint, text, text, uuid, text) to service_role;
revoke all on function public.fail_demo_onboarding_seed(bigint, text, text) from public, anon, authenticated;
grant execute on function public.fail_demo_onboarding_seed(bigint, text, text) to service_role;
revoke all on function public.delete_demo_companion_contexts(bigint, text, text) from public, anon, authenticated;
grant execute on function public.delete_demo_companion_contexts(bigint, text, text) to service_role;
