-- The demo is one family.
--
-- It used to seed three contexts: the customer's household plus a shadchanus
-- office and a second household, so the connection, cross-household child
-- grant and two-party discussion scenarios had a real counterparty. That also
-- put a context switcher in the app bar for every demo user, because
-- ContextSwitcher renders for any login holding two or more contexts — a
-- person trying the product is one family, and being asked to pick between
-- three of them is the wrong first impression.
--
-- So the companions are gone rather than hidden, and this gate now asserts
-- that: exactly one account (the root household), and the six cross-account
-- resource types asserted ABSENT rather than merely uncounted, so a
-- reintroduced companion fails activation loudly instead of seeding a demo
-- nobody designed.
--
-- The inventory drops 29 -> 19: connection (1), connection_invite (2),
-- child_grant (2), thread (1), message (2) and message_notification (2) all
-- required a second account. Everything else is unchanged, including storage
-- (50 objects), because every file already belonged to this family.
--
-- Two counts stay at 1 by a change of subject rather than by luck: the live
-- listing used to be the shadchanus office's, and the withdrawal tombstone
-- came from withdrawing the family's own. Now the family publishes for both
-- children and withdraws the son's, so `listing` = the daughter's live one and
-- `listing_withdrawal` = the son's tombstone. withdraw_demo_listing() deletes
-- the `listing` registration as it inserts the `listing_withdrawal`, so the
-- pair nets out the same.

CREATE OR REPLACE FUNCTION public.assert_official_demo_inventory(p_run_id bigint, p_require_active boolean DEFAULT false)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare v_status text; v_operation text; v_cleanup_started_at timestamptz; v_root bigint; v_resource record;
begin
  select status, operation, cleanup_started_at, root_account_id into v_status, v_operation, v_cleanup_started_at, v_root from public.demo_runs where id = p_run_id;
  if not found or (p_require_active and (v_status not in ('active','clearing') or (v_status = 'clearing' and (v_operation <> 'clear' or v_cleanup_started_at is null)))) or (not p_require_active and v_status <> 'seeding') then raise exception 'official demo run % is not in the expected inventory phase', p_run_id using errcode = 'check_violation'; end if;
  if (select count(*) from public.demo_run_accounts where run_id = p_run_id) <> 1 or not exists (select 1 from public.demo_run_accounts where run_id = p_run_id and context_key = 'primary-household' and context_kind = 'household' and is_root) or (select count(*) from public.demo_run_accounts where run_id = p_run_id and is_root) <> 1 or not exists (select 1 from public.demo_run_accounts where run_id = p_run_id and account_id = v_root and is_root) then raise exception 'official demo run % has an incomplete context graph', p_run_id using errcode = 'check_violation'; end if;
  if (select count(*) from public.demo_run_actor_intents where run_id = p_run_id) <> 2 or exists (select 1 from public.demo_run_actor_intents where run_id = p_run_id and state <> 'reconciled') or (select count(*) from public.demo_run_users where run_id = p_run_id) <> 2 or not exists (select 1 from public.demo_run_users where run_id = p_run_id and actor_key = 'dovid-klein') or not exists (select 1 from public.demo_run_users where run_id = p_run_id and actor_key = 'sarah-klein') or exists (select 1 from public.demo_run_actor_intents dai where dai.run_id = p_run_id and not exists (select 1 from public.demo_run_users dru where dru.run_id = dai.run_id and dru.actor_key = dai.actor_key and dru.user_id = dai.auth_user_id)) then raise exception 'official demo run % has an incomplete synthetic actor graph', p_run_id using errcode = 'check_violation'; end if;
  if not p_require_active then
    if (select count(*) from public.demo_run_resources where run_id = p_run_id) <> 19 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'invite') <> 3 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'listing') <> 1 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'listing_withdrawal') <> 1 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'share_link') <> 1 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'task') <> 1 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'share_access_log') <> 1 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'inbox_item') <> 1 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'analytics_event') <> 3 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'task_notification') <> 1 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'trusted_sender') <> 2 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'single_preference') <> 2 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'single_note') <> 2 or exists (select 1 from public.demo_run_resources where run_id = p_run_id and resource_type = 'connection') or exists (select 1 from public.demo_run_resources where run_id = p_run_id and resource_type = 'connection_invite') or exists (select 1 from public.demo_run_resources where run_id = p_run_id and resource_type = 'child_grant') or exists (select 1 from public.demo_run_resources where run_id = p_run_id and resource_type = 'thread') or exists (select 1 from public.demo_run_resources where run_id = p_run_id and resource_type = 'message') or exists (select 1 from public.demo_run_resources where run_id = p_run_id and resource_type = 'message_notification') or (select count(*) from public.demo_run_storage where run_id = p_run_id) <> 50 or (select count(*) from public.demo_run_storage where run_id = p_run_id and bucket = 'documents') <> 47 or (select count(*) from public.demo_run_storage where run_id = p_run_id and bucket = 'entity-files') <> 3 or exists (select 1 from public.demo_run_storage where run_id = p_run_id and bucket not in ('documents','entity-files')) then raise exception 'official demo run % is missing its exact baseline inventory', p_run_id using errcode = 'check_violation'; end if;
  else
    if (select count(*) from public.demo_run_resources where run_id = p_run_id) < 19 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'invite') < 3 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'listing') < 1 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'listing_withdrawal') < 1 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'share_link') < 1 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'task') < 1 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'share_access_log') < 1 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'inbox_item') < 1 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'analytics_event') < 3 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'task_notification') < 1 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'trusted_sender') < 2 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'single_preference') < 2 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'single_note') < 2 or (select count(*) from public.demo_run_storage where run_id = p_run_id) < 50 or (select count(*) from public.demo_run_storage where run_id = p_run_id and bucket = 'documents') < 47 or (select count(*) from public.demo_run_storage where run_id = p_run_id and bucket = 'entity-files') < 3 or exists (select 1 from public.demo_run_storage where run_id = p_run_id and bucket not in ('documents','entity-files')) then raise exception 'official demo run % is missing a baseline resource or storage receipt', p_run_id using errcode = 'check_violation'; end if;
  end if;
  if not p_require_active and ((select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'task_notification') <> 1 or (select count(*) from public.demo_run_resources where run_id = p_run_id and resource_type = 'share_access_log') <> 1 or not exists (select 1 from public.singles where account_id = v_root) or (select count(*) from public.single_preferences where account_id = v_root) <> 2 or (select count(*) from public.single_notes where account_id = v_root) <> 2 or not exists (select 1 from public.shidduchim where account_id = v_root) or not exists (select 1 from public.task_notifications tn join public.demo_run_resources drr on drr.resource_type = 'task_notification' and drr.resource_id = tn.id and drr.run_id = p_run_id where tn.simulated and tn.status = 'sent') or not exists (select 1 from public.share_access_log sal join public.demo_run_resources drr on drr.resource_type = 'share_access_log' and drr.resource_id = sal.id and drr.run_id = p_run_id where sal.simulated) or exists (select 1 from public.demo_run_resources drr join public.task_notifications tn on tn.id = drr.resource_id where drr.run_id = p_run_id and drr.resource_type = 'task_notification' and (tn.simulated is not true or tn.status <> 'sent')) ) then raise exception 'official demo run % is missing a simulated outcome', p_run_id using errcode = 'check_violation'; end if;
  for v_resource in select resource_type, resource_id from public.demo_run_resources where run_id = p_run_id loop perform public.assert_demo_resource_ownership(p_run_id, v_resource.resource_type, v_resource.resource_id, not p_require_active); end loop;
end;
$function$;
